### ISSUE TITLE
[BUG] No preview available for Python files updated through git

### ISSUE THREAD

**Issue by xpple** [overleaf/overleaf#1003]
## Steps to Reproduce

1. Create a Python file on Overleaf
2. Observe that the file can be previewed/edited
3. Make a change to the file remotely and push the changes to Overleaf through Git
4. Observe that the file can no longer be previewed/edited

## Expected Behaviour

The file should still be previewable/editable.

## Observed Behaviour

The file is no longer previewable/editable (error: `Sorry, no preview is available.`).

## Context

I am using the git integration provided by Overleaf.

## Technical Info

Locally (on my laptop) I am running Git version `2.24.1.windows.2`. The file was edited with PyCharm.

* URL: N/A
* Browser Name and version: N/A
* Operating System and version (desktop or mobile): Windows 21H2
* Signed in as: N/A
* Project and/or file: N/A

**Comment by asifgit** [comment]
I am facing the same problem. Has it been resolved yet or just closed only. 
I can't view python files and another friend of mine is able to preview and edit the same exported project in overleaf.

**Comment by gozzarda** [comment]
I have also encountered this.

More specifically, I can confirm that any python files created externally and brought in through git (including GitHub sync) have no preview, but if you create the file in Overleaf and then modify it through git it remains visible.

Would definitely like to see this fixed.
