### ISSUE TITLE
Cannot compile bigger projects

### ISSUE THREAD

**Issue by chschenk** [overleaf/overleaf#1006]
## Steps to Reproduce
1. Try to compile a really big project

## Expected Behaviour
Compiling bigger projects should work flawlessly

## Observed Behaviour
Compile request times out and Server Error Message is show

## Context
I cannot compile bigger projects.

## Technical Info
The latexmk process blocks while writing to stderr

**Comment by jdleesmiller** [comment]
#1007 should be automatically merged tonight --- no action required. Thanks again for the fix.
