### ISSUE TITLE
tlmgr: Local TeX Live (2021) is older than remote repository (2022).

### ISSUE THREAD

**Issue by zwxlyy1995** [overleaf/overleaf#1009]
Run the installation script in the Overleaf container with the following command:
```
$ docker exec sharelatex tlmgr install scheme-full
```

I got following error:
```
tlmgr: Local TeX Live (2021) is older than remote repository (2022).
Cross release updates are only supported with
  update-tlmgr-latest(.sh/.exe) --update
See https://tug.org/texlive/upgrade.html for details.
```
I don't know how to solve this.

**Comment by bowenEI** [comment]
I got the same problem with you as well. According to the information, I just try to run:

```bash
docker exec sharelatex wget "https://mirror.ctan.org/systems/texlive/tlnet/update-tlmgr-latest.sh"
docker exec sharelatex sh update-tlmgr-latest.sh
```

And then:

```bash
docker exec sharelatex tlmgr install scheme-full
```

It takes a long time to install. Maybe it will work. Hope it can help you.

**Comment by zwxlyy1995** [comment]
Hey,@bowenEI, thank u very much, it works for me. Best regrads.

**Comment by deewong7** [comment]
> I got the same problem with you as well. According to the information, I just try to run:
> 
> ```shell
> docker exec sharelatex wget "https://mirror.ctan.org/systems/texlive/tlnet/update-tlmgr-latest.sh"
> docker exec sharelatex sh update-tlmgr-latest.sh
> ```
> 
> And then:
> 
> ```shell
> docker exec sharelatex tlmgr install scheme-full
> ```
> 
> It takes a long time to install. Maybe it will work. Hope it can help you.

Well done. It worked for me.
It took around 2h30min to complete the whole installation, after which, it works well.
Thank you very much.

**Comment by GuillaumeNadal13** [comment]
Hi,

This no longer work for 2024 to 2025. I have the exact same error and I installed : 
`docker exec sharelatex wget "https://mirror.ctan.org/systems/texlive/tlnet/update-tlmgr-latest.sh"`
`docker exec sharelatex sh update-tlmgr-latest.sh`
every thing install on 2024 folder and I have the same issue again
Do you know how to create a new version and how overleaf can use it ?

Thanks
