### ISSUE TITLE
Rename Project

### ISSUE THREAD

**Issue by fcarlier** [overleaf/overleaf#101]
Can you add a rename function for Project ?

C-U

**Comment by PrieureDeSion** [comment]
For shared projects, maybe there can be a rename function for local copies? People have different ways to name/organize their files and only having the project owner set the name for everyone has been limiting. Would be very helpful! :D

**Comment by travisdesell** [comment]
Would like to also request being able to rename projects shared with you. I end up having many projects shared with me with names that are completely disorganized with no way to sort or change names.

**Comment by philipptempel** [comment]
How is this still not an implemented feature? I agree with previous commenters that not being able to rename shared projects is a pain.
Only when I have a local copy can I rename the project, but that unlinks it from changes in upstream.
Yes, I can use folders to organize my projects, but that’s still no solution to the problem as it just wraps the problem inside folders/tags.
