### ISSUE TITLE
leftovers in container after project deleted

### ISSUE THREAD

**Issue by ichangzhi** [overleaf/overleaf#1010]
## Steps to Reproduce

* delete one project completely

## Expected Behaviour

* files belong to the deleted project should also being deleted

## Observed Behaviour

* the files not being cleaned

**Comment by jesperschlegel** [comment]
+1

**Comment by mserranom** [comment]
As @jesperschlegel states, full project deletion only happens after expiration. Intermediate files produced during compilation are also eventually cleared from the filesystem.
