### ISSUE TITLE
Cannot browse files in history panel 

### ISSUE THREAD

**Issue by salleman33** [overleaf/overleaf#1011]
## Steps to Reproduce

1. create a new latex project
2. make some changes in multiples files
3. go to history panel and try to browse differentes files in history 
4. when you click on an other file, you are redirect to editor panel and quit history panel

## Expected Behaviour

we can browse the differents files in history panel

## Observed Behaviour

when you click on an other file in history panel, you are redirect to editor panel and quit history panel. 

## Context
history panel is buggy

## Technical Info

I use local instance after building sharelatex-base image and sharelatex image with docker (make build-base and make build-community). I run shalatex with docker-compose

* URL: localhost 
* Browser Name and version: firefox 98 or google chrome 100
* Operating System and version (desktop or mobile): Ubuntu 20.04

## Analysis

I use the last version (commit b99f4b0f19bb95eb4d7ec5a978b19e9b92283959).
I have try with a version of end 2021 (commit 847795e10fdd69c2668b81a47d429d53d5d8cb9c) and history panel works as expected !

**Comment by mserranom** [comment]
This is fixed in the latest release, Overleaf Community Edition 3.1.0.
