### ISSUE TITLE
Updating dependent jquery to a newer version ?

### ISSUE THREAD

**Issue by byujiang** [overleaf/overleaf#1012]
## Default jquery is kind of old
Jquery that overleaf uses now is 2.x, which is affected by some vulnerabilities.  Is it possible for overleaf to update jquery to a newer version like 3.6?

**Comment by das7pad** [comment]
Hello,

It took a while as we removed AngularJS from our frontend. I'm happy to let you that we've completed that work and upgraded jquery to 3.7 recently.

Greetings,
Jakob
