### ISSUE TITLE
Project title escaped incorrectly in change owner modal

### ISSUE THREAD

**Issue by natestemen** [overleaf/overleaf#1015]
👋🏻 

## Steps to Reproduce

1. Create a project and share it with a collaborator
2. Have the collaborator accept the invitation
3. Transfer ownership to said collaborator

## Expected Behavior

**Assistantship (U Hawai'i)** printed in modal

## Observed Behavior

<img width="681" alt="Screen Shot 2022-05-02 at 10 16 59 PM" src="https://user-images.githubusercontent.com/12703123/166407534-4f2164a4-4088-4e45-b5be-211d1f81a017.png">

**Comment by cmcisaac6** [comment]
Thanks for the report! This behaviour has now been resolved.

![image](https://user-images.githubusercontent.com/81039188/185380711-7b4458a1-288b-40c0-b951-909e03a97f34.png)
