### ISSUE TITLE
How to run web locally in dev environment without docker?

### ISSUE THREAD

**Issue by hykilpikonna** [overleaf/overleaf#1018]
I'm trying to run overleaf/services/web locally for development. I tried many methods with no success. Is there a step-by-step guide?

## Steps to Reproduce

1. Clone the repository (and cd into it)
2. `npm i`
3. `cd services/web`
4. Bind ports "6379:6379" for redis and "27017:27017" for mongo in `docker-compose.yml`
5. `docker-compose up redis mongo -d`
6. Set environment variables (listed below)
7. `sudo yarn global add bunyan`
8. `npm run start | bunyan`

Environment Variables:

```sh
#!/bin/bash
export WEB_API_USER=me@example.com
export WEB_API_PASSWORD=qwq
export REDIS_HOST=localhost
export QUEUES_REDIS_HOST=localhost
export ANALYTICS_QUEUES_REDIS_HOST=localhost
export MONGO_URL=mongodb://localhost/sharelatex
export SHARELATEX_ALLOW_PUBLIC_ACCESS=true
npm run start | bunyan
```

## Expected Behaviour

The web server runs successfully.

## Observed Behaviour

The web server did start successfully, but when I access `localhost:3000`, the following error were given (screenshot attached):

![image](https://user-images.githubusercontent.com/22280294/167180546-6212967d-6831-47d2-9b51-ad8bd8cb2e9c.png)

It might be due to CSS compilation problem? I tried running `npm run webpack` and `npm run webpack:production`, which neither of them fixed the problem.

## Technical Info

* URL: `http://localhost:3000/login`
* Browser Name and version: Chrome `100.0.4896.127`
* Operating System and version (desktop or mobile): Arch Linux `5.17.5-arch1-1`

**Comment by mserranom** [comment]
We have launched a new development environment for Overleaf CE, please check it out. Any feedback is appreaciated!

https://github.com/overleaf/overleaf/tree/main/develop

**Comment by alaimodiloro** [comment]
the development environment doesnt ssem to work anymore, the webpack, web and realtime containers fail to run. 
web and realtime containers complain about missing Session Keys, I was not able to find anything useful on this. the webpack caintainers logs say something about missing permissions with mkdir instructions.

Has anyone have this working in 2024?

**Comment by hykilpikonna** [comment]
> the development environment doesnt ssem to work anymore, the webpack, web and realtime containers fail to run. web and realtime containers complain about missing Session Keys, I was not able to find anything useful on this. the webpack caintainers logs say something about missing permissions with mkdir instructions.
> 
> Has anyone have this working in 2024?

I switched to typst (maybe you should try typst too :)

**Comment by alaimodiloro** [comment]
I want to fork overleaf and do some customizations for our company. From what I read typst especially the webapp is not open source. But thanks for the suggestion.

**Comment by kxxt** [comment]
> I want to fork overleaf and do some customizations for our company.  From what I read typst especially the webapp is not open source.

I am making typst work in overleaf. It is working now(without syntax highlighting and auto-completion though): https://github.com/kxxt/overleaf/tree/typst

<img width="2559" height="1461" alt="Image" src="https://github.com/user-attachments/assets/ca9ee34e-56b0-4ed5-87fb-925a9d182dd7" />

**Comment by hykilpikonna** [comment]
> > I want to fork overleaf and do some customizations for our company.  From what I read typst especially the webapp is not open source.
> 
> I am making typst work in overleaf. It is working now(without syntax highlighting and auto-completion though): https://github.com/kxxt/overleaf/tree/typst

lmao rip latex

great work btw!

**Comment by mderycke22** [comment]
In case this is still relevant for someone, here is a procedure to run Overleaf locally (tested on this version from March 2025: https://github.com/overleaf/overleaf/tree/c4e6dfbbbd69ef58435abe969b2218d6696a138c)

## Requirements

- **Node**: v18.20.7
- **Docker**: v27.4.0 (for MongoDB and Redis databases)
- **TeXLive** installed locally

## Procedure:

1. Run ``npm install`` in the project root folder.
2. The databases are still running inside Docker containers. You can use this ``docker-compose.yml``file and run the ``docker compose up``command in order to set them up.
```yml
services:
    mongo:
        restart: always
        image: mongo:6.0
        container_name: mongo
        command: '--replSet overleaf'
        ports:
            - "27017:27017"
        volumes:
            - ~/mongo_data:/data/db
        environment:
          MONGO_INITDB_DATABASE: sharelatex
        healthcheck:
            test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'overleaf',members:[{_id:0,host:'mongo:27017'}]}) }" | mongosh --port 27017 --quiet
            interval: 10s
            timeout: 60s
            retries: 5

    redis:
        restart: always
        image: redis:6.2
        container_name: redis
        ports:
            - "6379:6379"
        volumes:
            - ~/redis_data:/data
```

3. If you don't need to use S3 and to avoid errors when creating a new project on your Overleaf instance, you can use the filesystem to store the projects chunks. In ``services/history-v1/config/default.json``, change the ``persistor.backend`` value from ``s3`` to ``fs``.

4. To run Webpack in development mode, you can use a mix of the ``services/web/webpack.config.dev.js`` and ``develop/webpack.config.dev-env.js`` inside the ``services/web/webpack.config.dev.js``:

```js
const webpack = require('webpack')
const { merge } = require('webpack-merge')
const MiniCssExtractPlugin = require('mini-css-extract-plugin')
const ReactRefreshWebpackPlugin = require('@pmmmwh/react-refresh-webpack-plugin')

const base = require('./webpack.config')

// if WEBPACK_ENTRYPOINTS is defined, remove any entrypoints that aren't included
if (process.env.WEBPACK_ENTRYPOINTS) {
  const entrypoints = new Set(process.env.WEBPACK_ENTRYPOINTS.split(/\s*,\s*/))
  console.log(`Building entrypoints ${[...entrypoints].join(',')}`)
  for (const entrypoint in base.entry) {
    if (!entrypoints.has(entrypoint)) {
      delete base.entry[entrypoint]
    }
  }
}

module.exports = merge(base, {
  mode: 'development',

  // Enable accurate source maps for dev
  devtool:
    process.env.CSP_ENABLED === 'true' ? 'source-map' : 'eval-source-map',

  // Load entrypoints without contenthash in filename
  output: {
    filename: 'js/[name].js',
  },

  // Load assets without contenthash in filename
  module: {
    rules: [
      {
        test: /\.(woff|woff2)$/,
        type: 'asset/resource',
        generator: {
          filename: 'fonts/[name][ext]',
        },
      },
      {
        test: /\.(svg|gif|png|jpg|pdf)$/,
        type: 'asset/resource',
        generator: {
          filename: 'images/[name][ext]',
        },
      },
    ],
  },

  plugins: [
    // Extract CSS to a separate file (rather than inlining to a <style> tag)
    new MiniCssExtractPlugin({
      // Output to public/stylesheets directory
      filename: 'stylesheets/[name].css',
    }),

    process.env.REACT_REFRESH_ENABLED === 'true' &&
      new ReactRefreshWebpackPlugin({
        exclude: [
          /node_modules/, // default
          /source-editor/, // avoid crashing the source editor
        ],
        overlay: false,
      }),

    // Disable React DevTools if DISABLE_REACT_DEVTOOLS is set to "true"
    process.env.DISABLE_REACT_DEVTOOLS === 'true' &&
      new webpack.DefinePlugin({
        __REACT_DEVTOOLS_GLOBAL_HOOK__: '({ isDisabled: true })',
      }),
  ].filter(Boolean),

  devServer: {
    // Expose dev server at www.dev-overleaf.com
    host: '0.0.0.0',
    port: 3808,
    client: {
      webSocketURL: 'auto://0.0.0.0:0/ws',
      overlay: process.env.DISABLE_WEBPACK_OVERLAY !== 'true',
    },
    hot: true,
    proxy: [
      {
        context: '/socket.io/**',
        target: 'http://127.0.0.1:3026',
        ws: true,
      },
      {
        context: ['!**/*.js', '!**/*.css', '!**/*.json'],
        target: 'http://127.0.0.1:3000',
      },
    ],
    allowedHosts: 'auto',
    setupMiddlewares(middlewares, devServer) {
      devServer.app.get('/status', (req, res) => res.send('webpack is up'))
      return middlewares
    },
  },

  // Customise output to the (node) console
  stats: {
    preset: 'minimal',
    colors: true,
  },
})

```

5. Run the services
    - **chat**: ``MONGO_CONNECTION_STRING="mongodb://localhost:27017/sharelatex?directConnection=true" npm run start``
    - **contacts**:  ``MONGO_CONNECTION_STRING="mongodb://localhost:27017/sharelatex?directConnection=true" npm run start``
    - **clsi**: create the folders ``cache``, ``compiles``, ``output`` and ``db`` in the service root folder, then ``npm run start``
    - **docstore**: ``MONGO_CONNECTION_STRING="mongodb://localhost:27017/sharelatex?directConnection=true" npm run start``
    - **document-updater**: ``MONGO_CONNECTION_STRING="mongodb://localhost:27017/sharelatex?directConnection=true" npm run start``
    - **filestore**: ``npm run start``
    - **notifications**: ``MONGO_CONNECTION_STRING="mongodb://localhost:27017/sharelatex?directConnection=true" npm run start``
    - **project-history**: ``MONGO_CONNECTION_STRING="mongodb://localhost:27017/sharelatex?directConnection=true" npm run start``
    - **history-v1**: ``MONGO_CONNECTION_STRING="mongodb://localhost:27017/sharelatex?directConnection=true" npm run start``
    - **real-time**: ``SESSION_SECRET="foo" npm run start`` (you can use any value for the variable)
    - **web**:
        - Start in "production" mode: ``npm run webpack:production`` and ``SESSION_SECRET="foo" WEB_API_USER="overleaf" WEB_API_PASSWORD="password" MONGO_CONNECTION_STRING="mongodb://localhost:27017/sharelatex?directConnection=true" EMAIL_CONFIRMATION_DISABLED=true OVERLEAF_ALLOW_PUBLIC_ACCESS=true NODE_ENV=production npm run start`` to start the web service
        - Start in "development" mode: ``npm run webpack`` to start Webpack, and ``SESSION_SECRET="foo" WEB_API_USER="overleaf" WEB_API_PASSWORD="password" MONGO_CONNECTION_STRING="mongodb://localhost:27017/sharelatex?directConnection=true" EMAIL_CONFIRMATION_DISABLED=true OVERLEAF_ALLOW_PUBLIC_ACCESS=true NODE_ENV=development npm run start`` to start the web service
    - **git-bridge** is written in Java, so it is not detailed here


> [!NOTE]
> You can use any other value for the "SESSION_SECRET", "WEB_API_USER" and "WEB_API_PASSWORD" environment variables.

> [!NOTE]
> As the default values in the configuration file are sometimes mentioning the default host name (inside the Docker network) or ``127.0.0.1`` (without the port), providing the MONGO_CONNECTION_STRING or MONGO_HOST environment variable may be required. Here is an example from ``services/contact/config/settings.defaults.js``:

```js
mongo: {
    url:
        process.env.MONGO_CONNECTION_STRING ||
        `mongodb://${process.env.MONGO_HOST || '127.0.0.1'}/sharelatex`,
    options: {
        monitorCommands: true,
    },
}
```

6. Open http://localhost:3808
