### ISSUE TITLE
Recovering /overleaf

### ISSUE THREAD

**Issue by ImVictorCheng** [overleaf/overleaf#1025]
Hi, the server I ran the instance on accidentally deleted /overleaf. I never manually set up any backup mechanism. Is there any way to recover my files? Either from the server, or maybe from the browser cache? Thank you!

## Steps to Reproduce

1.
2.
3.

## Technical Info

* URL:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Signed in as:
* Project and/or file:

**Comment by andrewfowlie** [comment]
(not in any way affiliated with overleaf)

I believe in the default compose file, user data is mounted on a docker volume, such that it sits outside your container. It sounds like it could be tricky. Following could be relevant. What exactly was deleted? Inside the container or outside? and is the container still running?
