### ISSUE TITLE
webpack-cli not found after install dependencies in docker image

### ISSUE THREAD

**Issue by sparkcyf** [overleaf/overleaf#1027]
## Steps to Reproduce

1.  `docker run --rm -it --entrypoint bash sharelatex/sharelatex:3.1`
2.  `cd /overleaf`
3. `node genScript install | bash` (install dependencies command from Dockerfile)
4. `node genScript compile | bash` or `cd /overleaf/services/web && npm run webpack:production`

## Expected Behaviour

The webpack could succefully run.

## Observed Behaviour

npm will promote me to install webpack-cli:

```
+ pushd services/web
/overleaf/services/web /overleaf
+ npm run webpack:production

> webpack:production
> webpack --config webpack.config.prod.js

CLI for webpack must be installed.
  webpack-cli (https://github.com/webpack/webpack-cli)

We will use "npm" to install the CLI via "npm install -D webpack-cli".
Do you want to install 'webpack-cli' (yes/no): rm -rf node_modules/.cache
You need to install 'webpack-cli' to use webpack via CLI.
You can also install the CLI manually.
root@bcb8ff0321d1:/overleaf# node genScript compile | bash
+ pushd services/web
/overleaf/services/web /overleaf
+ npm run webpack:production

> webpack:production
> webpack --config webpack.config.prod.js

CLI for webpack must be installed.
  webpack-cli (https://github.com/webpack/webpack-cli)

We will use "npm" to install the CLI via "npm install -D webpack-cli".
Do you want to install 'webpack-cli' (yes/no): rm -rf node_modules/.cache
You need to install 'webpack-cli' to use webpack via CLI.
You can also install the CLI manually.

```

(try install webpack-cli inside `/overleaf/services/web` will get this error:)
<img width="1194" alt="image" src="https://user-images.githubusercontent.com/14960340/173006201-e9169555-6541-47d8-b3f7-831c22ebcc93.png">

However, even if I installed webpack-cli by`npm install -D webpack-cli` in `/overleaf` or `/overleaf/services/web`, the same promote will occur again and again, which is quite like this problem (https://stackoverflow.com/questions/48991706/webpack-after-installing-webpack-and-webpack-cli-still-getting-error-when-runni).

## Context

Could not build the fronted after add something in `router.js`.

## Technical Info

- sharelatex image version: 3.1
- npm version: 7.24.2 (same as Dockerfile)

* URL:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Signed in as:
* Project and/or file:

## Analysis

There seems to be a `package-lock.json` inside the `/overleaf/services/web` directory. However, some commit remove that, which I guess may be the root of the problem as npm could find the right dependencies without that file.

**Comment by aeaton-overleaf** [comment]
Because [the Dockerfile](https://github.com/overleaf/overleaf/blob/main/server-ce/Dockerfile) sets `NODE_ENV=production`, you need to run `export NODE_ENV=development` before running `node genScript install | bash` manually, so the development dependencies (including webpack) are installed.

**Comment by Musicminion** [comment]
> Because [the Dockerfile](https://github.com/overleaf/overleaf/blob/main/server-ce/Dockerfile) sets `NODE_ENV=production`, you need to run `export NODE_ENV=development` before running `node genScript install | bash` manually, so the development dependencies (including webpack) are installed.

Btw, sorry to interrupt. It seems that currently the [package-lock.json](https://github.com/overleaf/overleaf/blob/main/package-lock.json) file is in the root of the repo. So what if I modify the `service/web/package.json` (maybe run `npm install xxx`), **how to regenerate the `package-lock.json` in the root of this repo**?

It seems `package-lock.json` also contains the dependence of server pro, overleaf saas, so maybe regenerate this file `package-lock.json`  can also save some space?
