### ISSUE TITLE
Compile Error and PDF Download Notifications

### ISSUE THREAD

**Issue by cmprmsd** [overleaf/overleaf#1031]
The editor's latest version of Overleaf should look like this AFAIK:
![image](https://user-images.githubusercontent.com/73472903/175925874-f2fa9b36-b7ab-4e08-bbbd-2d6c70c38c8f.png)

However, I'm still stuck with the old layout where `Download PDF` and errors are not prominently visible.

This is the old layout:
![image](https://user-images.githubusercontent.com/73472903/175926184-f5c6b217-7a86-4a5d-be21-f0ff9760684c.png)

Also I see a lot of work going to migrate from ACE to CodeMirror 6. 
Will the updates be available to the community edition of Overleaf as well or do you plan phasing out your efforts on the community edition?

If there is any beta available for the community edition, how would I get it? Currently I use you docker-compose file and a dedicated nginx instance on the server.

Thanks in advance!

**Comment by jdleesmiller** [comment]
> the old layout

That layout is still the current one on overleaf.com, for the moment.

> migrate from ACE to CodeMirror 6

Yes, the CM6 work will be coming to CE soon.

> any beta available for the community edition

We don't have an official beta release at this time, no.

**Comment by cmprmsd** [comment]
Thanks for the quick response! Looking forward to see the updates being published 👍

**Comment by mserranom** [comment]
Hi! The new notification should be available in the latest version of Overleaf CE and Server Pro.
