### ISSUE TITLE
Broken link created by enabling link exchange

### ISSUE THREAD

**Issue by am0ral93** [overleaf/overleaf#1034]
Hello community! Shared link not working, works - read-only! Last version Overleaf. 
The problem is only in one project!
![photo_2022-07-08_11-50-45](https://user-images.githubusercontent.com/53824714/177956768-84fb62ce-2384-476e-a3e8-8b671a243f84.jpg)
![photo_2022-07-08_11-47-26](https://user-images.githubusercontent.com/53824714/177956679-07c06022-b8a1-472a-a390-1cbd194fde45.jpg)

**Comment by mserranom** [comment]
Hi! Would you mind sharing more information?

* URL:
* Browser Name and version:
* Operating System and version (desktop or mobile):
