### ISSUE TITLE
History diff no longer works in editor with sharelatex 3.1.0 docker image

### ISSUE THREAD

**Issue by raptor** [overleaf/overleaf#1035]
## Steps to Reproduce

1. Update to latest docker image (3.1.0)
2. Open an existing project
3. Click 'History'
4. Select radial buttons between two revisions

## Expected Behaviour

History revisions are selected, and API call is made, and the editor updates with the changes.

## Observed Behaviour

Radio buttons disappear. No API call is made. And thus the editor is not updated.

## Context

Seeing history of more than one revision has been super important for collaborative projects. I was hoping to have a few bugs fixed with the update but I may have to roll back as this bug is more impactful.

## Technical Info

* URL:  **self-hosted**
* Browser Name and version:  **any**
* Operating System and version (desktop or mobile):  **any**
* Signed in as: **any user**
* Project and/or file:  **any**

## Analysis

I tried to make a direct API call with something like:

`https://<server>/project/abcdef/doc/abcde01/diff?from=24&to=590`

where I manually modified the request parameters `from` and `to`. The resulting JSON *does* have the changes so the API call works. But something must be wrong with the radio buttons and maybe the editor. This appears to be client-side only.

Thanks!

**Comment by abhpc** [comment]
The same question. Radio button disappear when I click it.

**Comment by mserranom** [comment]
This should be fixed in the latest release (3.1.1)

**Comment by abhpc** [comment]
> 

Yes, this issue is fixed in 3.1.1. I have update my docker image, and it works now.

**Comment by raptor** [comment]
Confirmed. Thanks!
