### ISSUE TITLE
Track changes and comments in ShareLaTeX not available in self-hosted overleaf

### ISSUE THREAD

**Issue by SimonBard** [overleaf/overleaf#1036]
## Steps to Reproduce
 

1. Run docker container for sharelatex, 
2. then exec to have full scheme as described here in the docu
3. login to an account.

## Expected Behaviour

See the possibilty to track changes and to comment as shown here:
![grafik](https://user-images.githubusercontent.com/63670466/179020091-832455e0-0981-43a8-bcec-0088759afc91.png)

## Observed Behaviour

![grafik](https://user-images.githubusercontent.com/63670466/179020702-780cd6ad-00f7-4dcf-b846-08f04ff26d4d.png)

## Technical Info

* URL: self hosted
* Browser Name and version: Firefox 101
* Operating System and version (desktop or mobile): ubuntu
* Signed in as: admin
* Project and/or file:

**Comment by jdleesmiller** [comment]
Thanks for your ticket.

Tracked changes and comments are currently available only in the Server Pro edition (https://www.overleaf.com/for/enterprises).

Please see also https://github.com/overleaf/overleaf/issues/666 / https://github.com/overleaf/overleaf/issues/884 .

**Comment by SimonBard** [comment]
Its a bit misleading to show a screenshot of the Pro version here in github.

**Comment by Truejunjun** [comment]
Hi, so if i want to "Add a comment" in self-hosted overleaf, i need to buy Server Pro edition?

**Comment by mserranom** [comment]
> Its a bit misleading to show a screenshot of the Pro version here in github.

Should be fixed now

> Hi, so if i want to "Add a comment" in self-hosted overleaf, i need to buy Server Pro edition?

I'm afraid that's the case.

**Comment by Ezimkin** [comment]
I am also curious to hear an updated statement on this issue if possible. There are several reasons why many of us may need self-hosted and if [this documentation](https://www.overleaf.com/learn/how-to/How_to_make_comments_in_an_Overleaf_LaTeX_project) is correct than it seems to currently imply that there is a feature discrepancy. @jdleesmiller
