### ISSUE TITLE
Potential Documentation inconsistency: Deleting Users

### ISSUE THREAD

**Issue by MaKla89** [overleaf/overleaf#1039]
According to the documentation, running `"cd /var/www/sharelatex; grunt user:delete --email=joe@example.com"` should be used in order to delete the user with said mail adress. The folder /var/www/sharelatex does not exist though (using the docker installation). Am I doing this wrong or is the path in the documentation outdated?

**Comment by aeaton-overleaf** [comment]
Thank you for pointing out that `cd /var/www/sharelatex` isn't needed any more - I've updated [the documentation](https://github.com/overleaf/overleaf/wiki/Creating-and-managing-users) for Overleaf Toolkit users.
