### ISSUE TITLE
Overleaf 3.2 failes to generate output.bbl with biber backend

### ISSUE THREAD

**Issue by LinusCDE** [overleaf/overleaf#1042]
## Steps to Reproduce

Watchtower auto-updated the `sharelatex/sharelatex:latest` image to the same as tag `3.2` at at 2022-08-17 at 09:45 CEST. Today (18th at aprox 12:00 CEST) a change in `literatur.bib` (specified bibliography file) caused the need to regenerate `output.bbl`.

## Expected Behaviour

It should have regenerated `output.bbl` just fine, but failed at it. There is no clear reason to be found in the (raw) logs other than it wanted to rerun biber.

## Observed Behaviour

No `output.bbl` was generated, thus no citations were found and no bibliography pages could be populated.

## Technical Info

The document is a almost finished work of a good friend. So I can't paste the entire document. I'm also not sure how to best reproduce it in a minimal fashion as I'm not deep into latex internals (styling, settings, ...). We both use a similar template provided by out school. However the friend adjusted a lot and seemingly also changed the backend to `biber`. Below are the source lines regarding bib generation (commented out lines were likely the old versions).

```
% ...
%Literatur
%\usepackage[round,authoryear]{natbib} % Natbib für DINAT
%\setcitestyle{authoryear,open={(},close={)}}

\usepackage[backend=biber,style=numeric,natbib=true,defernumbers=true]{biblatex}
\addbibresource{literatur.bib}

% ...
\begin{document}
  % ...

  % Literature table
    \newpage 
    \pagenumbering{Roman}
    \setcounter{page}{11}
    %natbib
    %\bibliographystyle{dinat} 
    %\bibliography{literatur}

    %biblatex
    \printbibliography[keyword={lit}]
    \fancyfoot{}
    \fancyfoot[C] {\thepage}

    % Image sources
    \printbibliography[
    keyword={image},
    heading=bibintoc,
    title={Image Sources}
    ]
    \adjustmtc % minitoc fix

    % ...
\end{document}
```

## Analysis

The current fix was to change the used docker image back to `sharelatex/sharelatex:3.1`. I backed up the mongo-db beforhand, but the downgrade didn't seem to break anything, so I assumed it is fine for now.

Since the friend needs to finish up and hand in his work tomorrow, I can't do any experiments on the server rn to try figure out more. I don't seem to have an failing output.log anymore, but remember this warning showing up:

```
Package biblatex Warning: Please (re)run Biber on the file
```

Maybe there is some problem where overleaf fails to detect and run biber properly? Was the [execution flow](https://www.overleaf.com/learn/how-to/How_to_find_and_fix_errors_reported_in_generated_files) changed between 3.1 and 3.2?

Also tried to remove the `backend=biber` option. But since the document was probably updated to accommodate it a while ago, that produced errors for me I couldn't solve (the old version used dinat and/or natbib afaik).

**While it likely seems to be because of using biber, it could be something else.**

**Comment by LinusCDE** [comment]
I found some opened old `output.log` which had the issues. I included all lines containing `bib` since many entries contain file names and other information which I'm not sure whether I'm allowed to post them.

https://haste.cosmos-ink.net/doqomujuju.txt

Note: In the original post, replaced the keyword `bild` with `image`, since image is the english translation for the german word "bild". The sources use the keywords `lit` and `bild` to allow generation of to bibliographies for literature and images respectively.

All entries in `literatur.bib` have either `keywords="lit"` or `keywords="bild"` included.

I also checked the syntax for any missing or duplicated commas earlier and found no issue there.

**Comment by tim-rohrer** [comment]
This seems to be similar to #1030.

**Comment by LinusCDE** [comment]
Seems so. I'll do a re-test, once mentioned issue is fixed.

**Comment by mserranom** [comment]
Would you mind trying with the latest release, 3.2.2? We fixed a problem installing certain packages.

**Comment by LinusCDE** [comment]
Just tried and it is fixed now! Huge thanks!!!

**Comment by tim-rohrer** [comment]
This is not working for me. I continue to be unable to generate a bibliography.

BTW, does the `latex discussion` label mean the maintainers are discussing this behind the scenes?

**Comment by catmoez** [comment]
Overleaf is not outputting a .bbl when submitting to Arxiv currently, even when the .bib file name matches the main .tex file name.

**Comment by MeesMeijer** [comment]
Also see [this issue fix](https://github.com/overleaf/toolkit/issues/325)
