### ISSUE TITLE
Unable to compile XeLaTeX example

### ISSUE THREAD

**Issue by Seraphli** [overleaf/overleaf#1046]
## Steps to Reproduce

1. Install overleaf toolkit and docker. Install full texlive and commit changes by following https://github.com/overleaf/overleaf/wiki/Quick-Start-Guide#latex-environment
2. Try to run this example https://www.overleaf.com/learn/latex/Chinese
3. Compile the tex and get this result
![image](https://user-images.githubusercontent.com/1586755/189907480-fa6c0939-192a-4cd0-a34c-9e58830fea7f.png)

## Expected Behaviour

The same source file can be compiled on overleaf.com
![image](https://user-images.githubusercontent.com/1586755/189907818-f9e3179b-665b-49d3-8c3a-80b82a00efca.png)

## Observed Behaviour

As above. No PDF is produced.

## Technical Info

====== Overleaf Doctor ======
- Host Information
    - Not Linux !
    - lsb_release not found !
- Dependencies
    - bash
        - status: present
        - version info: 3.2.57(1)-release
    - docker
        - status: present
        - version info: Docker version 20.10.17, build 100c701
    - docker-compose
        - status: present
        - version info: docker-compose version 1.29.2, build 5becea4c
    - realpath
        - status: present
        - version info: /Users/chaoranli/Workspace/Github/Others/overleaf-toolkit/--version
        - WARNING: Could not find 'realpath' binary, falling back to custom function
    - perl
        - status: present
        - version info: 5.030003
    - awk
        - status: present
        - version info: awk version 20200816
    - openssl
        - status: present
        - version info: LibreSSL 2.8.3
- Docker Daemon
    - status: up
====== Configuration ======
- config/version
    - status: present
    - version: 3.2.0
- config/overleaf.rc
    - status: present
    - values
        - SHARELATEX_DATA_PATH: data/sharelatex
        - SERVER_PRO: false
        - SHARELATEX_LISTEN_IP: 127.0.0.1
        - SHARELATEX_PORT: 80
        - MONGO_ENABLED: true
        - MONGO_IMAGE: mongo:4.4
        - MONGO_DATA_PATH: data/mongo
        - REDIS_ENABLED: true
        - REDIS_DATA_PATH: data/redis
        - NGINX_ENABLED: false
        - NGINX_CONFIG_PATH: config/nginx/nginx.conf
        - TLS_PRIVATE_KEY_PATH: config/nginx/certs/overleaf_key.pem
        - TLS_CERTIFICATE_PATH: config/nginx/certs/overleaf_certificate.pem
        - NGINX_HTTP_LISTEN_IP: 127.0.1.1
        - NGINX_HTTP_PORT: 80
        - NGINX_TLS_LISTEN_IP: 127.0.1.1
        - TLS_PORT: 443
- config/variables.env
    - status: present
====== Warnings ======
! This system seems to not be Linux
! Could not find 'realpath' binary, falling back to custom function
====== End ======

* URL:
* Browser Name and version:
* Operating System and version (desktop or mobile): macOS Monterey 12.5.1
* Signed in as:
* Project and/or file:

**Comment by Sped0n** [comment]
Here is a temporary workaround.
https://github.com/overleaf/overleaf/issues/1044#issuecomment-1239009945

**Comment by Seraphli** [comment]
Thanks. It works.

**Comment by mserranom** [comment]
This should be fixed in the latest release, would you mind checking in `3.2.2`/`3.2`/`3`/`latest`?

**Comment by Seraphli** [comment]
@mserranom Hi mserranom, I saw you push a new docker image. But when I try to use `bin/upgrade` to upgrade, it shows `No change to docker image version`. Should I manually pull the new image?

**Comment by Sped0n** [comment]
> This should be fixed in the latest release, would you mind checking in `3.2.2`/`3.2`/`3`/`latest`?

latest version works fine now, thx

**Comment by Seraphli** [comment]
@mserranom Upgrade manually and it works

**Comment by WendaLi-cnyj** [comment]
> @mserranom Upgrade manually and it works

how to manually upgrade, I also have this problem.

**Comment by Sped0n** [comment]
> > @mserranom Upgrade manually and it works
> 
> how to manually upgrade, I also have this problem.

@WendaLi-cnyj if you deploy sharelatex service with docker compose, you can enter the code below

**backup your data first If you haven't map the data directory to the host**

```bash
docker stop sharelatex
docker rm sharelatex
docker image rm sharelatex/sharelatex
docker pull sharelatex/sharelatex:latest
# and then go to where your docker-compose .yml file lie
docker-compose up -d
```

中文版本参见[这里](https://blog.sped0nwen.com/dev/notageek/docker_sharelatex/#升级sharelatex)

**Comment by Seraphli** [comment]
> > @mserranom Upgrade manually and it works
> 
> how to manually upgrade, I also have this problem.

An easy way to upgrade if you are using toolkit is changing the version to `3.2.2` in `lib/config-seed/version` and then running `bin/upgrade`.

**Comment by note286** [comment]
```shell
bin/shell
tlmgr option repository https://mirrors.cloud.tencent.com/CTAN/systems/texlive/tlnet/
tlmgr install scheme-full
tlmgr path add
```

Run `tlmgr path add` is important. It is mentioned in [Quick Start Guide · overleaf/overleaf Wiki](https://github.com/overleaf/overleaf/wiki/Quick-Start-Guide#latex-environment)

> Important: From `3.3.0` release onwards running `tlmgr path add` is required again after every use of `tlmgr install`, in order to correctly symlink all the binaries into the system path.

@1205129045x @Viking-1
