### ISSUE TITLE
Tikz isn't installed and won't install.

### ISSUE THREAD

**Issue by tim-rohrer** [overleaf/overleaf#1049]
## Steps to Reproduce

1. Add `\usepackage{tikz}` to the project and get error `LaTeX Error: File `tikz.sty' not found.`
2. Run `docker exec -it overleaf tlmgr install tikz`

## Expected Behaviour

The package `tikz` is installed so it can be used.

## Observed Behaviour

```
tlmgr: package repository https://mirror.ox.ac.uk/sites/ctan.org/systems/texlive/tlnet (verified)
tlmgr install: package tikz not present in repository.
tlmgr: action install returned an error; continuing.
tlmgr: An error has occurred. See above messages. Exiting.
```

## Context

I can't generate graphs using `tikz`.

## Technical Info

* URL:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Signed in as:
* Project and/or file:

**Comment by Blameying** [comment]
@tim-rohrer Hi, I met the same problem as yours, and when I searched the package Tikz at https://www.ctan.org/pkg, I found that Tikz's package name is **pgf**. The commands below work for me, I hope it is helpful for this issue:
```shell
tlmgr repository add http://pgf-tikz.github.io/pgf/tlnet pgf-development
tlmgr pinning add pgf-development "*"
tlmgr update --self --all
tlmgr install pgf --reinstall
tlmgr install xcolor --reinstall
```

**Comment by das7pad** [comment]
Hello,

I'm afraid we cannot offer LaTeX help for specific templates or packages in Overleaf Community Edition. Our Server Pro offering provides you with access to the same optimized LaTeX environment as used for overleaf.com. We run [extensive tests with the overleaf.com gallery templates](https://www.overleaf.com/learn/latex/Overleaf_and_TeX_Live) when preparing new TeXLive releases and generally make sure that templates either compile with the new version or leave them at their previous TeXLive release. Server Pro customers get access to our historic TeXLive releases as well to ensure older projects continue to work.
You can find more information on Server Pro here: https://www.overleaf.com/for/enterprises

Greetings,
Jakob
