### ISSUE TITLE
PDF Rendering Error

### ISSUE THREAD

**Issue by kitware-sysadmin** [overleaf/overleaf#1050]
Multiple users - using Chrome and Firefox browsers.
We periodically get the following error when trying to compile in overleaf:
 
PDF Rendering Error Something went wrong while rendering this PDF.
 
Typically it occurs when recompiling often (e.g., trying to adjust some formatting-relate change). However, then we can't recompile for an undetermined amount of time

We've tried the initial troubleshooting:  These did not resolve the issue.

- •	Refresh your browser page.
- •	Clear your browser’s cookies and cache (especially the cookies).
- •	Use the Incognito/Private mode of your browser.
- •	Temporarily disable any browser extensions/plugins especially ad-blockers, download managers or firewalls/proxies that you may be running.
- •	Make sure your browser is up-to-date, and is a supported version.

Related error when recompiling pdf:
We see "Rate limit reached, please try again later". Is there a configurable rate limit with a timeout period on the server that we reduce?
Once you hit the limit, it seems to lock us out for a while.

* URL:  https://ecoverleaf.kitware.com
* Chrome: Version 104.0.5112.101 (Official Build) (64-bit)
* Firefox: 104.0 (64-bit) for Ubuntu
* Issue seen on Windows 10 and Ubuntu 18.04.6
* Signed in as:  matt.brown@kitware.com

-Thanks

**Comment by nobodyinperson** [comment]
Running into this as well. Really weird, I tried all buttons in the admin panel and restarting the Docker containers, nothing helps, just waiting. I also didn't find any rate-limiting configuration in the docker setup files. But it surely is possible to deactivate rate-limiting completely for the self-hosted variant, right? It's not a paid feature? 😉

**Comment by mserranom** [comment]
Hi! We've published a new version of Overleaf CE and Server Pro, which includes some rate-limiting improvements. Please check it out: https://github.com/overleaf/overleaf/wiki/Release-Notes-3.x.x#server-pro-34
