### ISSUE TITLE
The PDF viewer mixes up colors when compiling with LaTeX

### ISSUE THREAD

**Issue by bensmrs** [overleaf/overleaf#1060]
## Steps to Reproduce
1. Create a new project with the “LaTeX” compiler
2. Use the following code
```latex
\documentclass{standalone}
\usepackage{color}
\begin{document}
\def\r{\rule{1ex}{10ex}}%
\def\s{\hskip1ex}%
\color{black}\r\s{\color{blue}\r}\s\r
\end{document}
```
3. Compile

## Expected Behaviour
![image](https://user-images.githubusercontent.com/25688414/200596828-9ff74935-9e3a-45e1-a904-d26ef175140e.png)

## Observed Behaviour
![image](https://user-images.githubusercontent.com/25688414/200596902-7aa2e94f-eaa4-4a4f-914a-0af0cb4cd130.png)

## Context
N/A

## Technical Info
N/A

## Analysis
The problem disappears when using the pdfLaTeX, XeLaTeX or LuaLaTeX compilers and the visual glitch is not reproductible using another PDF viewer.

**Comment by aeaton-overleaf** [comment]
To help with reproducing this issue, would you mind confirming a few things?

* Which TeX Live version is in use (`2022` is currently the default version for new projects).
* Which PDF viewer is in use ("Overleaf" or "Brower"), and perhaps the name of the PDF viewer which you've found to render the PDF without the same issue.
* Whether this issue also appears on overleaf.com, or just in the Community Edition.
* Which operating system and browser are being used.

**Comment by bensmrs** [comment]
Hmmm silly me, I didn’t bother checking on other browsers. The problem appears on the “Overleaf” viewer, for all (rough guess, I checked the last four) versions of LaTeX, on both overleaf.com and the CE version, but only on macOS, using Safari. I really should have mentioned that!

**Comment by bensmrs** [comment]
I’m using Safari 16.1. Yes, same problem using Mozilla’s viewer. Should I rather open an issue on their repository and close this one?

**Comment by aeaton-overleaf** [comment]
> Should I rather open an issue on their repository and close this one?

Potentially yes, except I haven't been able to reproduce the issue yet, even using Safari 16.1. Would you mind attaching an example PDF here, to make sure everyone's testing with the same file?

**Comment by bensmrs** [comment]
Sure thing!

[latex_bug.pdf](https://github.com/overleaf/overleaf/files/10104304/latex_bug.pdf)

**Comment by aeaton-overleaf** [comment]
> Should I rather open an issue on their repository and close this one?

I've reproduced the issue in Safari now, after making sure to compile the PDF using the `latex` compiler (and confirming it using your attached PDF, thank you). 

If you'd like to report the issue upstream in the pdf.js repository, I agree that would be best.

**Comment by bensmrs** [comment]
> I've reproduced the issue in Safari now, after making sure to compile the PDF using the `latex` compiler

Yeah, it appears that the problem is **very** specific

> If you'd like to report the issue upstream in the pdf.js repository, I agree that would be best.

Will do, thanks a lot for your time!
