### ISSUE TITLE
Forward and Reverse Search

### ISSUE THREAD

**Issue by GongSiqiu** [overleaf/overleaf#1061]
## Steps to Reproduce

Can community version Forward and Reverse Search?

## Expected Behaviour

![image](https://user-images.githubusercontent.com/40697840/201385787-52b2ec4d-20fb-47b8-8b48-577e85d0e4d3.png)

## Observed Behaviour

These two buttons don't exist in my server.
![image](https://user-images.githubusercontent.com/40697840/201385560-351b5083-24bd-4b97-ad3e-dcf535a5451d.png)

* Browser Name and version:  firefox 107.0
* Operating System and version (desktop or mobile): desktop

**Comment by aeaton-overleaf** [comment]
The two buttons shown in the screenshot above are the "Go to code location in PDF" and "Go to PDF location in code" buttons, which are available when using Overleaf's PDF viewer, but not when using the browser's native PDF viewer.

If you open the settings menu and change the "PDF viewer" setting from "Browser" to "Overleaf", the buttons should become visible.
