### ISSUE TITLE
File outline contains preamble paragraphs

### ISSUE THREAD

**Issue by promasu** [overleaf/overleaf#1062]
## Steps to Reproduce

1. Create a file
2. Use a sectioning command inside a command definition e.g.: `\newcommand{\myparagraph}[1]{\paragraph{#1}\mbox{}}`

## Expected Behaviour
Every usage of sectioning commands before the beginning of the document should be omited and not displayed.

## Observed Behaviour
Element ''1'' appears inside the file outline screen.

## Context

The displayed file outline is wrong and confusing by this.

**Comment by aeaton-overleaf** [comment]
Thank you for creating an issue to report this problem. 

After some investigation, given that `\newcommand` is allowed to appear inside the main document environment, it seems that a more comprehensive solution would be to ignore sectioning commands that appear inside command definitions.

**Comment by promasu** [comment]
Sure that is better then. I did not consider the possibility for `\newcommand` to appear inside the main document.
Thanks for the response.

**Comment by hrjakobsen** [comment]
This issue should be fixed now so I'll close the issue. Feel free to re-open it if you are still seeing the problem.
