### ISSUE TITLE
[Feature Request] Auto-suggest collaborator mail-addresses

### ISSUE THREAD

**Issue by ciscam** [overleaf/overleaf#1063]
Hello,

when sharing a document with another user on the same instance, there is no way to find out their mail addresses in the web interface. Neither as user, nor as admin. You have to correctly and manually enter the mail address of another account.

It would be indescribably convenient to have Overleaf auto-suggest/-complete mail addresses based on registered users. If there are people who don't want that we don't even need fine-grained permission control. A simple disable toggle should do the trick and make everyone happier.
![image](https://user-images.githubusercontent.com/13006585/204033886-b19cf7b6-3ab6-4f25-813e-922983136925.png)

**Comment by das7pad** [comment]
Hello,

Overleaf remembers who you shared projects with previously and also who invited you to a project before. These collaborator emails will be available as suggestions after accepting invitations. So you only need to type an email correct once and can use the autocomplete suggestions afterwards.

Greetings,
Jakob
