### ISSUE TITLE
Shared author cannot access the project

### ISSUE THREAD

**Issue by iszhi** [overleaf/overleaf#1070]
I just installed the community version, and created two authors to test the server. However, when I creased a test project and shared it with my second author, the second author still cannot find the shared project in the second user profile.

**Comment by das7pad** [comment]
Hello,

Collaborators need to accept an invitation before they can access a project or see it in the project dashboard `/project`.

With email sending configured, they should have received an inviation by email. The project dashboard will also show a notification at the top.

Greetings,
Jakob
