### ISSUE TITLE
Why isn't there still one-button recompile action? 

### ISSUE THREAD

**Issue by brunolnetto** [overleaf/overleaf#1071]
Why isn't there still single keyboard-button recompile action?

**Comment by das7pad** [comment]
Hello,

You can find the list of keyboard shortcuts for the Overleaf editor in the side-menu under "Help" -> "Show shortcuts". The full set of shortcuts in also listed in [this template](https://www.overleaf.com/latex/templates/overleaf-keyboard-shortcuts/pphdnzrwmttk) and the "View PDF" button will enlarge the preview.

Here is the relevant entry:

![image](https://github.com/user-attachments/assets/21a389d1-6a23-4ced-a477-3241c62b0d0e)

Greetings,
Jakob
