### ISSUE TITLE
Embed VS Code as the editor of Overleaf.

### ISSUE THREAD

**Issue by Adam-Antios** [overleaf/overleaf#1073]
This is not a bug report, but merely a suggestion. It would be a good idea to use VS Code as the underlying editor of Overleaf, or at least provide this option. Given how powerful VS Code is, and how easy it seems to be embedded into web applications (see vscode.dev or GitHub's Codespaces), it would make sense.

**Comment by Musicminion** [comment]
What you said seems reasonable, but you might as well build a cloud vscode plus textlive environment. Now cloud vscode can be said to be very easy to build, or if you have used Aliyun's workbench, you will find that they are actually similar.



It is very expensive to rewrite the overlay front-end using the vscode interface. If you have carefully studied the overlay code, you will find that it is not an obvious application with front and back ends separated. The code modification is actually very complex. Once modified, it will involve a lot of logic changes.



So I suggest that if you prefer the style of vscode, you can use your own cloud vscode or local vscode.

**Comment by Musicminion** [comment]
maybe you can adjust editor theme to what you like
<img width="786" alt="截屏2023-01-23 15 43 37" src="https://user-images.githubusercontent.com/84625273/213988235-335bc545-878b-4cab-a1f5-c0975fd16f74.png">

**Comment by Adam-Antios** [comment]
Thank you for your thorough answer! I was suggesting this mainly for the functionality (settings, extensions etc.) rather than the theme, but taking into account your explanation I understand what you mean. I don't know if you want this issue open for the future, if not, feel free to close it.

**Comment by SethFalco** [comment]
Just want to note that putting that typically one of the following would be used as opposed to Visual Studio Code itself.

* [Eclipse Theia](https://theia-ide.org/) - An IDE platform based on Visual Studio Code that can be white labeled and designed to work in the web. GitPod uses this to manage workspaced.
* [Monaco Editor](https://github.com/microsoft/monaco-editor/) - By Microsoft, pulls out source from Visual Studio Code and makes it am embeddable package for the web. Grafana uses this for the query editor.

While one can use Visual Studio Code as-is afaik, it probably wouldn't make for the experience Overleaf would want to offer users.

**Comment by Adam-Antios** [comment]
No objection to that. My main suggestion is to, at least, use the Monaco editor.

**Comment by iamhyc** [comment]
Hi, I am working on the vscode extension, [Overleaf-Workshop](https://marketplace.visualstudio.com/items?itemName=iamhyc.overleaf-workshop), to integrate overleaf with vscode.

I am seeking for possible audience and glad to know we have open issue discussions here.

We currently achieve almost 80% features of overleaf webpage frontend (though with defects), but you can actually enjoy copilot together with latex coding!

If you think vscode is a better editor, please give it a try :smiley: 

P.S. the extension now cannot run on web like `vscode.dev` due to failure of packing the old `socket.io-client`.

**Comment by das7pad** [comment]
Hello,

Thanks for the suggestion. We've build the new Overleaf Source and Visual editor using CodeMirror 6 and you can read more about it [on our blog](https://www.overleaf.com/blog/towards-the-future-a-new-source-editor). A large number of features were unlocked by this migration and there are no plans to start another editor migration :wink: 

Greetings,
Jakob
