### ISSUE TITLE
Message box can break UI

### ISSUE THREAD

**Issue by mbiesiad** [overleaf/overleaf#1074]
Hi, 

not a big deal but:

## Steps to Reproduce
I.
1. Go to: https://www.overleaf.com/
2. Click Help -> Select Contact Us
3. Expand Message box to the right

II.
The same with:
1. Go to: https://www.overleaf.com/for/contact-sales
2. Expand Message box to the right

## Expected Behaviour
Related parts still looks fine after user actions with mentioned element.

## Observed Behaviour
User can break UI just expanding Msg box.

## Context
NA

## Technical Info
Browser: Chromium based

## Additional information
Screenshots:

![image](https://user-images.githubusercontent.com/18367606/209462696-592b7bb1-3ea1-4558-89ae-9070a5c2aaa6.png)

![image](https://user-images.githubusercontent.com/18367606/209462682-f1619fa5-8a7c-45ff-ae11-be6341df5f4c.png)

Best wishes,
Michal

**Comment by ArunBohra12** [comment]
Hi, can I work on fixing this issue?
