### ISSUE TITLE
Pressing "$" does not exit math mode when using dollar signs.

### ISSUE THREAD

**Issue by NoahPrentice** [overleaf/overleaf#1078]
## Steps to Reproduce

1. I entered math mode by pressing the "$" key. This caused two dollar signs to be written, with the typing cursor placed in-between them.
2. I typed an equation, such as "2 + 2 = 4". So the resulting writing was "$2 + 2 = 4$" with the typing cursor placed before the final dollar sign.
3. I attempted to leave math math mode by pressing the "$" key again, but, instead of leaving math mode, this simply wrote another dollar sign within the math mode environment, resulting in the total equation of "$2 + 2 = 4$$" with the typing cursor placed in-between the final two dollar signs.

## Expected Behaviour

As in past versions, the expected behavior is that, while in math mode with the typing cursor placed right before the final dollar sign, pressing "$" again will move the cursor outside of math mode, instead of writing another dollar sign within the math mode environment.

## Observed Behaviour

As mentioned before, pressing "$" again wrote another dollar sign within the math mode environment.

## Context

It is simply slightly bothersome as muscle memory build up over time using overleaf.com now makes writing using overleaf more time-consuming and less conducive to "flow state."

## Technical Info

* URL: N/A
* Browser Name and version: Chrome 108.0.5359.124
* Operating System and version (desktop or mobile): Desktop
* Signed in as: N/A
* Project and/or file: N/A

**Comment by aeaton-overleaf** [comment]
@NoahPrentice Thank you for the detailed bug report - this behaviour should be working as expected now.

**Comment by NoahPrentice** [comment]
@aeaton-overleaf Fix works great. Thanks so much!
