### ISSUE TITLE
Can't create document in dev mod(both arm64 and x86-64)

### ISSUE THREAD

**Issue by Musicminion** [overleaf/overleaf#1082]
## Steps to Reproduce

1. clone this repository and cd to develop folder
2. run `bin/dev` and wait for all containers were launched
3. open browser and input localhost/launchpad, input admin email and password
4. login with username and pwd just registered successfully
5. I can't find the item of topbar admin, which shows in procution env
6. I try to new one latex document, but I can't create any document, it tells me 500 server internal error

I am not sure whether there is any limitation in dev mod? Why can't I create document? I have tested both on mac m1 and x86-64 aliyun server, it proves out it's not the problem of arch.

![image](https://user-images.githubusercontent.com/84625273/213928156-d0fdf59b-b29b-4049-a78f-45736fe45127.png)

<img width="1313" alt="截屏2023-01-23 00 52 59" src="https://user-images.githubusercontent.com/84625273/213928174-36fe6bb9-6bd7-47cd-af34-f84ad1460578.png">

## Expected Behaviour

1. I can see admin button from topbar after I login successfully
2. I can create document in dev mod?

## Observed Behaviour

1. server inner error 500, can't create

## Comment About test
- server with x86 is testing dev mod now.(test finish and result appear above)
- server with arm64 is testing production image(build from server-se folder)(test finish and everthiings goes well!)

## Technical Info

* URL:
* Browser Name and version: edge and safari, I use overleaf newest version, which id is ddf14b0cdd363cb96e9851cff20c425955afb90b
* Operating System and version (desktop or mobile): macOS 13.1 desktop
* Signed in as: admin 
* Project and/or file:

**Comment by Musicminion** [comment]
log info
```
develop-web-1               | {"name":"web","hostname":"db52be9a2cb6","pid":32,"level":50,"err":{"message":"Cannot read 
properties of undefined (reading 'displayHistoryForNewProjects')","name":"TypeError","stack":"TypeError: Cannot read 
properties of undefined (reading 'displayHistoryForNewProjects')\n    at _createBlankProject 
(/overleaf/services/web/app/src/Features/Project/ProjectCreationHandler.js:174:35)\n    at processTicksAndRejections 
(node:internal/process/task_queues:96:5)\n    at async Object.createExampleProject 
(/overleaf/services/web/app/src/Features/Project/ProjectCreationHandler.js:97:19)","info":
{}},"url":"/project/new","method":"POST","user":
{"id":"63ce02d861629c2a736b7a79","email":"zhangziqian@sjtu.edu.cn"},"msg":"error passed to top level next 
middleware","time":"2023-01-23T04:14:04.709Z","v":0}

develop-web-1               | {"name":"web","hostname":"db52be9a2cb6","pid":32,"level":20,"responseTimeMs":27,"req":
{"method":"POST","url":"/project/new","remoteAddress":"172.19.0.11","headers":{"referer":"http://localhost/project","user-
agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 
Safari/537.36 Edg/109.0.1518.61","content-length":"93"}},"res":{"statusCode":500,"headers":{"content-
length":"770"}},"msg":"POST /project/new","time":"2023-01-23T04:14:04.729Z","v":0}
```

**Comment by Musicminion** [comment]
One possible solution: services/web/app/src/Features/Project/ProjectCreationHandler.js Line 174
```
  // only display full project history when the project has the overleaf history id attribute
  // (to allow scripted creation of projects without full project history)
  const historyId = project.overleaf.history.id
  if (
    Settings.apis.project_history.displayHistoryForNewProjects &&
    historyId != null
  ) {
    project.overleaf.history.display = true
  }
```
just delete displayHistoryForNewProjects, though it's not an good soluton
```
  // only display full project history when the project has the overleaf history id attribute
  // (to allow scripted creation of projects without full project history)
  const historyId = project.overleaf.history.id
  if (
    Settings.apis.project_history &&
    historyId != null
  ) {
    project.overleaf.history.display = true
  }
```

**Comment by aeaton-overleaf** [comment]
Thank you for reporting this issue - we have a fix that should be ready soon.

**Comment by neerdoc** [comment]
Any progress on this? I have the exact same problem.

**Comment by neerdoc** [comment]
I can confirm that the temporary solution above works. Deleting `displayHistoryForNewProjects` works.

**Comment by maestro1315** [comment]
I have this same issue. I deployed using the toolkit.

**Comment by DinhNghiaVo** [comment]
for mac chip ": https://gitlab.com/DinhNghia_Vo/overleaf_toolkit
