### ISSUE TITLE
Nomenclature does not work in Overleaf CE

### ISSUE THREAD

**Issue by fram1984** [overleaf/overleaf#1083]
## Steps to Reproduce

1. Install Overleaf CE with TexLive full
2. Create new project with example tex file
```
\documentclass{article}
\usepackage{nomencl}
\makenomenclature

\begin{document}
Here is an example:
\nomenclature{\(c\)}{Speed of light in a vacuum}
\nomenclature{\(h\)}{Planck constant}

\printnomenclature
\end{document}
```
3. Compile

## Expected Behaviour
To see nomenclature in PDF file
## Observed Behaviour
No nomenclature in PDF file

## Context
Nomenclature works in overleaf.com
<img width="1269" alt="nom_erroe" src="https://user-images.githubusercontent.com/121512639/213971171-03a51a61-fd22-41f6-9f8d-1e923519b877.png">

**Comment by Musicminion** [comment]
enter docker container and get full texlive packege, xelatex may be better for problems like this.
if you just follow the official instruciton, sharelatex container only obtain basic texlive package.

**Comment by Musicminion** [comment]
refer to this: https://github.com/overleaf/overleaf/issues/1055

**Comment by fram1984** [comment]
> enter docker container and get full texlive packege, xelatex may be better for problems like this. if you just follow the official instruciton, sharelatex container only obtain basic texlive package.

TexLive full is instaled according the instructions. I launched `tlmgr path add` command and XeLatex is now works but the PDF file is the same with no nomenclature.

**Comment by fram1984** [comment]
It appears that if I manually create the file called .latexmkrc in the project with the following content, it fixes nomenclature 
```
# Provide support for Nomencl
################################################################################
add_cus_dep('nlo', 'nls', 0, 'run_makenomencl');
push @generated_exts, 'nlo', 'nls';

sub run_makenomencl {
    if ( $silent ) {
        system "makeindex -q '$_[0].nlo' -s nomencl.ist -o '$_[0].nls'";
    }
    else {
        system "makeindex '$_[0].nlo' -s nomencl.ist -o '$_[0].nls'";
    };
}
```

**Comment by Musicminion** [comment]
yes, I encounter this recently, it require `.latexmkrc` file. As for overleaf, since it have it's own compile chain, so you can see it compile successfully.

**Comment by das7pad** [comment]
Hello,

I'm afraid we cannot offer LaTeX help for specific templates or packages in Overleaf Community Edition. Our Server Pro offering provides you with access to the same optimized LaTeX environment as used for overleaf.com. We run [extensive tests with the overleaf.com gallery templates](https://www.overleaf.com/learn/latex/Overleaf_and_TeX_Live#About_Overleaf%E2%80%99s_upgrade_process) when preparing new TeXLive releases and generally make sure that templates either compile with the new version or leave them at their previous TeXLive release. Server Pro customers get access to our historic TeXLive releases as well to ensure older projects continue to work.
You can find more information on Server Pro here: https://www.overleaf.com/for/enterprises

Greetings,
Jakob
