### ISSUE TITLE
User's email addresses can be enumerated through the 'Password Reset' page

### ISSUE THREAD

**Issue by stefanvi** [overleaf/overleaf#1086]
## Observed Behaviour
The page to reset a password leaks whether the user's account exists, or not:
![image](https://user-images.githubusercontent.com/60365750/216088748-a396ceed-729c-4535-9792-e59f72bf8c87.png)

Versus an existing account:
![image](https://user-images.githubusercontent.com/60365750/216089432-48f39345-edfc-42f7-9b5a-1fa5a4bf417c.png)

This can leak the email addresses of many users. An attacker can try to guess the email naming scheme used by a company and can thus learn potentially many email addresses.

## Expected Behaviour
Many websites solve this problem by showing a the same message in both cases. Something along the lines of

"If this is a known account, we will send you an email with instructions to reset your password".

* URL: {overleaf_instance}/user/password/reset
* Browser Name and version: Firefox 109.0
* Operating System and version (desktop or mobile): Linux 6.1.0-3-amd64

**Comment by jdleesmiller** [comment]
Thank you for your report. We would prefer that you disclose potential security issues to security@overleaf.com as per our [policy](https://github.com/overleaf/overleaf/blob/b10b7b1f915f005733075165c10ea2ee2b96204c/CONTRIBUTING.md#security). We have now tried to make that policy more easily findable [here](https://github.com/overleaf/overleaf/security/policy). If you would like to continue this discussion, please email.
