### ISSUE TITLE
Wiki: Creating and managing users: Add how to list users

### ISSUE THREAD

**Issue by paulmenzel** [overleaf/overleaf#1089]
Is there a way to list all users on the command line? The Wiki only lists how to add and delete users.

**Comment by mserranom** [comment]
You can query the DB. Using the toolkit run `bin/mongo` and then:

```
db.users.find({}, { email : 1 })
```

**Comment by paulmenzel** [comment]
Thank you. Manually:

    $ docker exec -ti mongo mongo
    > show dbs
    […]
    > use sharelatex
    switched to db sharelatex
    > db.users.find({}, { email : 1 })
    […]
    > exit
