### ISSUE TITLE
Publish project as template

### ISSUE THREAD

**Issue by JohnRobson** [overleaf/overleaf#109]
Hello everyone,

Publish project as template
"There is a problem with our publishing service, please try again in a few minutes."

What I need to do to enable this feature?

Thank you,
John

**Comment by cmprmsd** [comment]
Hi all,
I'm currently trying to add a template to the community edition of Overleaf.
I am fine with having to change some values in the mongodb, but I'm struggling to find the correct way of adding a template without the Pro version.
I can define my user as template-user with `SHARELATEX_TEMPLATES_USER_ID` but the button does not appear. 

How could I do this manually as I see the folder `/var/www/sharelatex/web/app/templates/` and am able to add a template folder with `SHARELATEX_NEW_PROJECT_TEMPLATE_LINKS` in the OSS version.

Thanks in advance for any hints! :+1:
