### ISSUE TITLE
Create tag for release 3.5.0

### ISSUE THREAD

**Issue by JulienMalka** [overleaf/overleaf#1094]
Hello,
It is difficult (maybe impossible) to know what commit of the ``main`` branch corresponds to a given release (I've read that the latest release version of overleaf CE is 3.5.0. Would it be possible to point me towards the right commit (I am building from source) or tag the appropriate commit ?
Thanks.

**Comment by mserranom** [comment]
Hey @JulienMalka, inside the docker container you can check `/var/www/revisions.txt`, which contains the commit ID at which the revision was produced.

https://github.com/overleaf/overleaf/blob/cfadebabc2e1e38fa079a8079fa8346619b88c14/server-ce/Dockerfile#L21

**Comment by JulienMalka** [comment]
That will work for me, thanks :)
