### ISSUE TITLE
XXX is too large, maximum file size is 52.4MB.

### ISSUE THREAD

**Issue by nico-zck** [overleaf/overleaf#1099]
How can I change the size limit of upload files?

I tried to change of nginx config `client_max_body_size 50m;` to a large size, but it not works.

PS:
The warning shows as js alert, I think it not related to the nginx config. 
I found it may caused by the code from [fineuploader-5.15.4.js](https://github.com/overleaf/overleaf/blob/main/services/web/frontend/js/vendor/libs/fineuploader-5.15.4.js#L2379), but I don't know how to change the limit config in this file.
Can anybody help me with this problem?

**Comment by nico-zck** [comment]
I solved this problem by the follow 2 steps:

1. change nginx limit in config file (common path is `/etc/nginx/nginx.conf`), for docker users may need to change config template to prevent automatic overwrite after restart (`/etc/nginx/templates/nginx.conf.template`). 
```nginx
client_max_body_size [N]m;
```    
2. change the config of overleaf service, `**/services/web/config/settings.defaults.js` (see [github](https://github.com/overleaf/overleaf/blob/38973fb971063686e824a98adc2e1ec134d1d3d0/services/web/config/settings.defaults.js#L274))
```javascript
maxUploadSize: [N] * 1024 * 1024, // 50 MB
```
Remember to reload config or restart service to apply new config. 
Done.

And I also recommend developers to add an environment variable to control this limit.

**Comment by nico-zck** [comment]
I solved this problem by the follow 2 steps:

1. change nginx limit in config file (common path is `/etc/nginx/nginx.conf`), for docker users may need to change config template to prevent automatic overwrite after restart (`/etc/nginx/templates/nginx.conf.template`). 
```nginx
client_max_body_size [N]m;
```    
2. change the config of overleaf service, `**/services/web/config/settings.defaults.js` (see [github](https://github.com/overleaf/overleaf/blob/38973fb971063686e824a98adc2e1ec134d1d3d0/services/web/config/settings.defaults.js#L274))
```javascript
maxUploadSize: [N] * 1024 * 1024, // 50 MB
```
Remember to reload config or restart service to apply new config. 
Done.

And I also recommend developers to add an environment variable to control this limit.

**Comment by Musicminion** [comment]
much thanks!

To allow larger project upload, there are 2 things to do 
- modify nginx config, it is here: https://github.com/overleaf/overleaf/blob/92f8e445d355bcd0004b362c7496fcc22872828f/server-ce/nginx/nginx.conf.template#L49
- The second one is this https://github.com/overleaf/overleaf/blob/38973fb971063686e824a98adc2e1ec134d1d3d0/services/web/config/settings.defaults.js#L274


<img width="542" alt="截屏2024-01-07 16 40 10" src="https://github.com/overleaf/overleaf/assets/84625273/c32a71a0-d8f5-44f7-b59b-8889d3211010">

**Comment by das7pad** [comment]
Hello,

Changing the maximum file size is not officially supported in Overleaf Community Edition and [Server Pro](https://www.overleaf.com/for/enterprises). I'm sorry for this limitation.
The limit is enforced in different parts of the application and changing it in one place (e.g. nginx or web) may still break other features down the line, like the project history.

Greetings,
Jakob

**Comment by maxin-cn** [comment]
Hi @Musicminion @nico-zck, how do I get around this limitation if I use the overleaf [toolkit](https://github.com/[overleaf/toolkit](https://github.com/overleaf/toolkit)) to build overleaf myself. Many thanks.
