### ISSUE TITLE
Project list empty and js error

### ISSUE THREAD

**Issue by andylee830914** [overleaf/overleaf#1100]
## Steps to Reproduce
1. Clone overleaf/overleaf
2. make build-base && make build-community
3. Switch to overleaf/toolkit
4. docker tag sharelatex/sharelatex sharelatex/sharelatex:3.5.2
5. bin/up

## Expected Behaviour
It should show the project list or "create project"

## Observed Behaviour
The screen becomes empty and the js "project-list" show errors

* URL:
* Browser Name and version: Safari and Edge
* Operating System and version (desktop or mobile): both amd64 and arm64
* Signed in as:
* Project and/or file:

<img width="626" alt="截圖 2023-03-10 上午10 16 56" src="https://user-images.githubusercontent.com/7420328/224208839-63f05e87-af1a-4312-a4c6-b12bf080f46d.png">
<img width="1220" alt="截圖 2023-03-10 上午10 16 45" src="https://user-images.githubusercontent.com/7420328/224208845-266bc137-652f-44e0-b670-16fd97804cf7.png">

**Comment by mserranom** [comment]
Would you mind confirming full information, including versioning for 
- Browser Name and version
- Operating System and version (desktop or mobile)

**Comment by andylee830914** [comment]
> Would you mind confirming full information, including versioning for
> 
> * Browser Name and version
> * Operating System and version (desktop or mobile)

I tested on macOS 13.2.1 with Safari 16.3 and Edge 110.0.1587.69.

Server are hosted on Ubuntu 20.04 x86_64/arm64 Server Edition.

**Comment by mserranom** [comment]
Thanks for the report, I was able to reproduce the problem, we're working on a fix.
