### ISSUE TITLE
There is a rollback of db for half a year, after changes in the docker file

### ISSUE THREAD

**Issue by am0ral93** [overleaf/overleaf#1111]
Hi all! My database is rollback near for about six months I try to update the data in the dockerfile. For example, I need to change my smtp account. Previously, there were no such problems, on an older version of Sharelatex (before that on the back). Now there is a rollback. However, no changes are made to mongo and redis. But I noticed that the last change in sharelatex_data db.sqlite was half a year ago. What needs to be done to update Sharelatex (changes in dockerfile) so that the data stays the same?

I use docker-compose -d up

Sorry for the template. I can’t give a public link and my English is bad. Thanks for the help!

![2023-04-18 174947](https://user-images.githubusercontent.com/53824714/232815558-551e3a7c-323a-48a6-b6b6-36788bd2de3d.png)

--------------
dockerfile:

version: '2'
services:
    sharelatex:
        restart: always
        image: sharelatex/sharelatex:with-texlive-full
        container_name: sharelatex
        depends_on:
            - mongo
            - redis
        privileged: true
        ports:
            - 80:80
        links:
            - mongo
            - redis
        volumes:
            - ~/sharelatex_data:/var/lib/sharelatex
            - /var/run/docker.sock:/var/run/docker.sock
            #- /var/clsi/compiles:/var/www/sharelatex/clsi/compiles
        environment:
            SHARELATEX_MONGO_URL: mongodb://mongo/sharelatex
            SHARELATEX_REDIS_HOST: redis
            SHARELATEX_APP_NAME: Our ShareLaTeX
            SHARELATEX_SITE_URL: "https://domain.com:8000"
            SHARELATEX_NAV_TITLE: ShareLaTeX Instance
            SHARELATEX_ADMIN_EMAIL: "administrator@mail.com"
            SHARELATEX_EMAIL_FROM_ADDRESS: "sharelatex@mail.com"
            SHARELATEX_EMAIL_SMTP_HOST: "smtp.mail.com"
            SHARELATEX_EMAIL_SMTP_PORT: "465"
            SHARELATEX_EMAIL_SMTP_SECURE: "true"
            SHARELATEX_EMAIL_SMTP_USER: "sharelatex@mail.com"
            SHARELATEX_EMAIL_SMTP_PASS: "pass"

    mongo:
        restart: always
        image: mongo
        container_name: mongo
        expose:
            - 27017
        volumes:
            - ~/mongo_data:/data/db

    redis:
        restart: always
        image: redis
        container_name: redis
        expose:
            - 6379
        volumes:
            - ~/redis_data:/data

**Comment by am0ral93** [comment]
Maybe I got excited the wrong way. I don't have the option to update more dockerfile. Any changes and there is a rollback for six months. If you do not touch it, the data continues to work at the original level

**Comment by senyai** [comment]
This issue can be closed. Invalid `SHARELATEX_MONGO_URL` was specified.

**Comment by das7pad** [comment]
`db.sqlite` was used by the compile service for keeping track of on-disk state. It is not used by recent versions of Server Pro/Community edition anymore. You can delete `db.sqlite`.
