### ISSUE TITLE
When will overleaf upgrade to TexLive 2023?

### ISSUE THREAD

**Issue by jjyyxx** [overleaf/overleaf#1113]
TexLive 2023 is released, and many CTAN mirrors do not preserve archive versions of TexLive, making building a docker image with full TexLive 2022 difficult.

**Comment by SimonUzL** [comment]
I simply installed TexLive 2023 in the container. This works at least as long as there is no other solution.

**Comment by jjyyxx** [comment]
@SimonUzL Thanks for your suggestion. Does it work by simply following the error report's instruction
```
tlmgr: Local TeX Live (2022) is older than remote repository (2023).
Cross release updates are only supported with
  update-tlmgr-latest(.sh/.exe) --update
See https://tug.org/texlive/upgrade.html for details.
```
then continue `tlmgr install scheme-full`?

**Comment by SimonUzL** [comment]
I can't guarantee this is the correct solution, but here's what worked for me each time a new texlive release came out (I would recommend to make a full backup of everything at beforehand):

I did the following **inside** the docker container sharelatex/sharelatex:3.5.5:
````
wget -O - -- http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz | tar xzf - --strip-components=1
apt install tex-common texinfo equivs perl-tk perl-doc 
./install-tl
````
Then `O` for options, then `L` for create symlinks in standard directories and confirm everything. Back with `R`. Finally `I` for installing it. Finally I am able to upgrade my installation with:
````
tlmgr update --self --all
````
or install full texlive with:
````
tlmgr install scheme-full
````

Source (German): https://wiki.ubuntuusers.de/TeX_Live/

**Comment by ehfd** [comment]
https://github.com/overleaf/overleaf/issues/873#issuecomment-1498442727
