### ISSUE TITLE
Cannot completely remove project

### ISSUE THREAD

**Issue by VPaulV** [overleaf/overleaf#1115]
## Steps to Reproduce
1.  Install overlief using docker toolkits 
2. Setup reverse proxy with apache2. Here is my config:
```
<VirtualHost *:80>
        ServerName domain.com
        ServerAlias domain.com
        ServerAdmin paul@domain.com
        ErrorLog ${APACHE_LOG_DIR}/domain-error.log
        CustomLog ${APACHE_LOG_DIR}/domain-access.log combined

        ProxyRequests Off
        <Proxy *>
          Order deny,allow
          Allow from all
        </Proxy>

        ProxyPreserveHost On
        ProxyPass / http://127.0.0.1:4480/
        ProxyPassReverse / http://127.0.0.1:4480/
        RewriteEngine on
        RewriteCond %{HTTP:Upgrade} websocket [NC]
        RewriteCond %{HTTP:Connection} upgrade [NC]
        RewriteRule ^/?(.*) "ws://127.0.0.1:4480/$1" [P,L]
       RewriteCond %{SERVER_NAME} =domain.com
       RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]

        <Location />
          Order allow,deny
          Allow from all
        </Location>
</VirtualHost>
```
3. Create test project and delete it 
4. Go to "trashed projects" and press delete 
5. Project will be not be removed and "login" page will open instead

## Expected Behaviour
Project will be completely deleted

## Observed Behaviour
Project  is not deleted and I am redirected to the login page

## Context
Hi guys, I am trying to setup self hosted overleaf with apache2 as a reverse proxy. Everything seems to work great, except I cannot remove projects completely. Probably I did a mistake during setup? I would really appreciate if you could help with this issue. Let me know if you need any logs or would like to have access to the server to try yourself

**Comment by das7pad** [comment]
Hello,

Can you expand on what you mean with
> Project is not deleted and I am redirected to the login page

Are you seeing the editor page after logging in `/project/<id>`?

By default, all endpoints are behind the user login, only after logging in we will check whether a given project still exists in the database and whether the logged-in user has access to it.

Greetings,
Jakob
