### ISSUE TITLE
How can I use the CLSI API

### ISSUE THREAD

**Issue by Konafets** [overleaf/overleaf#1117]
Hi, sorry to misuse the issue tracker for a question, but I did not found another way to ask.

I found the archived repo https://github.com/overleaf/clsi and read that it was migrated into the mono repo. However, I do not find any documentation about that API. Is it still usable in the CE edition?

Thanks in advance!

**Comment by bela127** [comment]
Similar question here, I would like to develop an extension for Overleaf, and the API would be really helpful.

Also, I have a question about the build nr., which is currently randomly generated, i.e., it would be nice to have it not randomly generated (for example, use the git commit UID) or to have another interface that enables one to get access to it.

**Comment by Musicminion** [comment]
Clsi Related Service is now in this: https://github.com/overleaf/overleaf/tree/main/services/clsi

It seems the only solution now is to read related code in that repo.

**Comment by das7pad** [comment]
Hello,

Thanks for raising this issue. As @Musicminion pointed out, the source is now at [`services/clsi`](https://github.com/overleaf/overleaf/tree/main/services/clsi) inside this monorepo. The service is include in Overleaf Community Edition and [Server Pro](https://www.overleaf.com/for/enterprises), where it resides in `/overleaf/services/clsi` and listens on `127.0.0.1:3013`.

Greetings,
Jakob
