### ISSUE TITLE
Add TTL for git to documentation

### ISSUE THREAD

**Issue by heidi-holappa** [overleaf/overleaf#1118]
Dear Overleaf staff, 

please consider adding TTL (time-to-live) value for git authentication to the Overleaf documentation. This would help to optimize the automated workflows to keep the credentials valid for a longer work session with scheduled pulls. Optimization would reduce network traffic, which possibly is preferred for all parties involved. 

Also note that in time a more optimal solution is preferred (support for SSH keys, etc.) , but this would be helpful in the mean time and a very small update to do on your end.

**Comment by das7pad** [comment]
Hello,

Thank you for raising this issue. We've recently completed the migration to personal accesstokens for interfacing with the Git-Integration. Password authentication has been deprecated and fully removed now.

Greetings,
Jakob
