### ISSUE TITLE
[Question] menu-clicked-login event

### ISSUE THREAD

**Issue by scmanjarrez** [overleaf/overleaf#1122]
Hi,
I've noticed that if you click the top-right login button, you're redirected
to `/event/menu-clicked-login` with a 404 error right after successful login

![image](https://github.com/overleaf/overleaf/assets/9284124/86f38eb0-aa3b-4dd8-bd57-e182bec622d3)

Is that supposed to happen? Or is it a remnant of overleaf enterprise edition (related to users stats tracking or similar)? 

## Steps to Reproduce

1. Start overleaf-ce containers
2. Click login button
3. Then use your credentials

## Technical Info

* URL: self-hosted
* Overleaf version: dockerhub, tag 4.0.2
* Operating System and version (desktop or mobile): Linux, Firefox 114
* Signed in as: user
* Project and/or file: right after login

**Comment by scmanjarrez** [comment]
Applying this patch fixes the problem
```patch
--- navbar-marketing.pug.bk
+++ navbar-marketing.pug
@@ -138,7 +138,6 @@
 						li
 							a(
 								href="/login"
-								event-tracking="menu-clicked-login"
 								event-tracking-action="clicked"
 								event-tracking-trigger="click"
 								event-tracking-mb="true"

```

**Comment by das7pad** [comment]
Hello,

Thanks for raising this ticket. We've fix the post-login redirect after clicking the "Login" button in the navbar with the release of Overleaf Community Editition 5.1 and [Server Pro](https://www.overleaf.com/for/enterprises) 5.1.

> https://github.com/overleaf/overleaf/wiki/Release-Notes-5.x.x#bugfixes-1
> > Fixed post-login redirection when login after clicking the "Log in" button in the header.

Greetings,
Jakob
