### ISSUE TITLE
error: "dependency failed to start: container mongo is unhealthy"

### ISSUE THREAD

**Issue by yzakzero** [overleaf/overleaf#1124]
I had followed https://github.com/overleaf/overleaf/blob/main/docker-compose.yml,
but it does not work.
error: "dependency failed to start: container mongo is unhealthy".
The system I used is windows10, and running in the docker.

sharelatex logs showing "Killing all processes".

**Comment by yzakzero** [comment]
谢谢，收到！

**Comment by das7pad** [comment]
Hello,

Thanks for raising this ticket. I'm afraid we do not support running Overleaf Community Edition or [Server Pro](https://www.overleaf.com/for/enterprises) on Windows. We recommend running it on Ubuntu or another Debian based operating system. I'm sorry for this limitation.

Greetings,
Jakob

**Comment by yzakzero** [comment]
谢谢，收到！
