### ISSUE TITLE
Found conflicts or bad filenames in filetree

### ISSUE THREAD

**Issue by senyai** [overleaf/overleaf#1127]
Hello!

I'm doing [Full-Project-History-Migration](https://github.com/overleaf/overleaf/wiki/Full-Project-History-Migration) and I see 12 (out of ~1600) projects failing at 'at Object.initializeProject (/overleaf/services/web/app/src/Features/History/HistoryManager.js:25:11)'.

Looking at /var/log/sharelatex/web.log:
```
Set UV_THREADPOOL_SIZE=16
ENABLE_TRACE_AGENT set to undefined
ENABLE_DEBUG_AGENT set to undefined
ENABLE_PROFILE_AGENT set to undefined
Using default settings from /overleaf/services/web/config/settings.defaults.js
Using settings from /etc/sharelatex/settings.js
{"name":"web","hostname":"2fdb3c6ed074","pid":163,"level":40,"projectId":"5783aa6a7385395200c17213","renames":[{"oldPath":"/images/illustration.eps","newPath":"/images/illustration.eps (1)"},{"oldPath":"/images/illustrationPairs.eps","newPath":"/images/illustrationPairs.eps (1)"}],"msg":"found conflicts or bad filenames in filetree","time":"2023-06-26T15:06:05.021Z","v":0}
{"name":"web","hostname":"2fdb3c6ed074","pid":163,"level":40,"projectId":"593163f3cd65816300120b90","renames":[{"oldPath":"/prototype","newPath":"/@prototype"}],"msg":"found conflicts or bad filenames in filetree","time":"2023-06-26T15:10:22.551Z","v":0}
```
After this migration I can't start server as it error on seeing any migration failure.
It is fine to purge these projects history, but I don't see a way to do it. Any help is very much appreciated.

**Comment by briangough** [comment]
Hello.  Thanks for the bug report. The log lines above are warnings that a filename is being fixed automatically and on their own they shouldn't cause the migration to fail - there is probably another error happening somewhere else.  

Could you send us  migration script log output and the other log files mentioned in https://github.com/overleaf/overleaf/wiki/Full-Project-History-Migration#troubleshooting for these 12 failing projects.  You can run the script for the remaining failing projects with `migrate_history.js --force-clean`.  Thank you.

**Comment by senyai** [comment]
Thanks a lot for your response!
All logs (history-v1.log, project-history.log, track-changes.log) are empty.

There's `overleaf/services/web/history-migration-2023-06-28T08_
09_41_416Z.log` that has 12 lines with this error:
```
{
    "project_id": "62b301cd05998e007f653fc9",
    "result": {
        "error": {
            "_oErrorTags": [
                {
                    "name": "TaggedError",
                    "message": "Something went wrong flushing and resyncing project; clearing full project history for project",
                    "info": {
                        "projectId": "62b301cd05998e007f653fc9"
                    }
                }
            ]
        },
        "historyType": "NoneWithConversion"
    },
    // resofratted for readability
    "stack": "Error: invalid character in content" + // one project with (Invalid path in history migration)
        "at sanitise (/overleaf/services/web/modules/history-migration/app/src/ProjectHistoryController.js:1068:13)" +
        "at validateUpdates (/overleaf/services/web/modules/history-migration/app/src/ProjectHistoryController.js:1100:25)" +
        "at Object.migrateProjectHistory (/overleaf/services/web/modules/history-migration/app/src/ProjectHistoryController.js:1209:9)" +
        "at async doUpgradeForNoneWithConversion (/overleaf/services/web/modules/history-migration/app/src/HistoryUpgradeHelper.js:262:5)" +
        "at async upgradeProject (/overleaf/services/web/modules/history-migration/app/src/HistoryUpgradeHelper.js:124:18)" +
        "at async _migrateProject (/overleaf/services/web/scripts/history/migrate_history.js:190:22)",
    "startTime": "2023-06-28T08:09:43.098Z",
    "endTime": "2023-06-28T08:09:43.176Z"
}```

Right now I'm looking at /overleaf/services/web/app/src/Features/History/HistoryMa
nager.js:16 `fetch(`${settings.apis.project_history.url}/project`, ...)` and this fetch returns error 500 (body: { message: 'an internal error occurred' }) that causes clearing to fail. I will try to investigate it further, but don't know where to start yet.

**Comment by mserranom** [comment]
Hi Senyai,

This might be fixable, would you mind trying the script again adding the `--fix-invalid-characters` option?

```
migrate_history.js --force-clean --fix-invalid-characters
```

**Comment by senyai** [comment]
@mserranom I don't know how, but it helped with 11 out of 12 projects. That's so good! Now I have one remaining with 'Invalid path in history migration'.

**Comment by senyai** [comment]
definitely invalid `[ 'file:5bccf61082e64800754d249a path:/F*.png' ]` [(/overleaf/services/web/modules/history-migration/app/src/ProjectHistoryController.js:635)](https://github.com/overleaf/overleaf/blob/37f01dfe1e7df25625b53769ce7db1f7c239420b/services/web/modules/history-migration/app/src/ProjectHistoryController.js#L635)

**Comment by mserranom** [comment]
Hi Senyai, the recommendation at this point is to run the script with `--archive-on-failure`. This will initialise Full Project History in the remaining project, and a machine-readable backup of the history will be added to the project as a zipfile. 

After that, you should be able to upgrade to version `4.0.2`.

**Comment by senyai** [comment]
Unfortunately `--archive-on-failure` doesn't do anything and I get the same error. I tried `--force-clean --archive-on-failure` too.

**Comment by senyai** [comment]
Everything is fine now! I looked at the code: `archive-on-failure` is really a no-op. The option is called `import-broken-history-as-zip` and the full command for those who need it is `scripts/history/migrate_history.js --import-broken-history-as-zip --force-clean`. You can close the issue now, or maybe after mentioning these command lines in the docs. @mserranom thank you 👍

**Comment by mserranom** [comment]
That's right, this is leftover from a separate migration system. The correct option is `--import-broken-history-as-zip`. Thanks for confirming!
