### ISSUE TITLE
[BUG] New source editor always adds a space to valid ISBNs, when switching to the bibliography file

### ISSUE THREAD

**Issue by bertramrichter** [overleaf/overleaf#1129]
The new source editor always adds a space in .bib file in the after the number in ISBN fields containing a valid ISBN, when switched to the file.
This seems to only happen, when the ISBN is a valid one. It does not matter, whether the ISBN is hyphenated or not.

## Steps to Reproduce
1. Create a project with:
    - a `.tex` file,
    - a `.bib` file, containing at least a single entry like `@book1{test, isbn= {978-3-658-13611-6},}`
or `@book2{test,isbn={9783658136116 },}`
2. Select the new editor
3.  Switch back and forth between .tex and .bib and observe the new space for each switching to the new `.bib` file:
## Expected Behaviour
The `.bib` should stay unchanged

## Observed Behaviour
For each switch to the `.bib` file, a new space is added:
1. `@book{test, isbn= {978-3-658-13611-6 },}`
2. `@book{test, isbn= {978-3-658-13611-6  },}`
3. `@book{test, isbn= {978-3-658-13611-6   },}`
4. ...

## Context
This is annoying, when working on the bibliography.

## Technical Info

* URL: N/A
* Browser Name and version: Firefox 102.8.0esr
* Operating System and version (desktop or mobile): Windows 10
* Signed in as: N/A
* Project and/or file: N/A

## Analysis

This seems to only happen, when the ISBN is a valid one. It does not matter, whether the ISBN is hyphenated or not.
If the ISBN is invalid ( e.g., changing the checksum, nothing happens (as expected).

**Comment by jdleesmiller** [comment]
Thanks, that is an interesting one, but I cannot reproduce this. Do you have any browser extensions active? Maybe try again after disabling all of those.

**Comment by bertramrichter** [comment]
Thanks you for the reply and the tip with the addons.
Yes indeed, I had the Citavi Picker active.
With Citavi Picker disabled, the problematic unexpected behavior is not observed anymore.
Furthermore, this is not restricted to `.bib` files, but only surfaced there.
So here is the updated steps to reproduce:

1.  Install and activate Citavi Picker
2. Create a project with two files, one of them containing a valid ISBN e.g., `978-3-658-13611-6` or `9783658136116 `
3. Select the new editor
3.  Switch back and forth between the two files and observe the new space after the ISBN for each switching to the file containting it.

## Expected Behaviour
The file content should stay unchanged

## Observed Behaviour
For each switch to the file with the ISBN, a new space is added:
1. `@book{test, isbn= {978-3-658-13611-6 },}`
2. `@book{test, isbn= {978-3-658-13611-6  },}`
3. `@book{test, isbn= {978-3-658-13611-6   },}`
5. ...

## Technical Info


* URL: N/A
* Browser Name and version: Firefox 102.8.0esr
* Operating System and version (desktop or mobile): Windows 10
* Citavi Picker Version: 2021.4.8.5
* Signed in as: N/A
* Project and/or file: N/A

## Analysis
Citavi Picker scans the content and tries to inject its logo with a link offering to add this refernce to the data base, when it thinks, it found a literature reference.
This is triggered, when a valid ISBN is found.
I assume, the editor allows plain text only, so the link is not created, but the space is input by Citavi Picker.

Could the reason why this is observed with the new editor only be, that Citavi Picker can analyze the content in the new editor, but not in the old editor?

I will forward this to Citavi.

Should the issue title be edited accordingly?

**Comment by jdleesmiller** [comment]
Thanks for confirming. I think the advice for Citavi would be to avoid injecting their widget into elements with `contenteditable` set. That should avoid breakage with CodeMirror 6 and many other editor surfaces. Since this isn't an Overleaf issue, I'll close the ticket. Thanks again for the report.
