### ISSUE TITLE
Could not connect to websocket server :(

### ISSUE THREAD

**Issue by zeakey** [overleaf/overleaf#1130]
I'm trying to setup overleaf services locally with native local environment without docker containers.

After days of struggling I eventually setup the services and I'm able to create admin account and create projects in my browser.

However, when opening a project, the webpage gives me an error: 

> Could not connect to websocket server :(

and the browser console hints that the `real-time` service is not running.

![Screenshot from 2023-06-29 18-38-14](https://github.com/overleaf/overleaf/assets/6763078/edcb7c51-508d-4ac8-b557-e8e9d8628595)

However, the `real-time` service is actually running in my terminal and I don't see any anomaly about the service:
![Screenshot from 2023-06-29 18-43-49](https://github.com/overleaf/overleaf/assets/6763078/e0f9172f-58eb-4431-b767-4c72183e970b)

**Comment by zeakey** [comment]
Seems like `socket.io/socket.io.js` is served by `services/real-time`, not `services/web`.

I can visit `socket.io/socket.io.js` through `localhost:3026/socket.io/socket.io.js`, which means  `services/real-time` is actively running.

But I cannot access `localhost:3000/socket.io/socket.io.js` (`services/web` is running on port 3000). There seems to be a 'proxy' that forward all requests to `localhost:3000/socket.io/*` to `localhost:3026/socket.io/*`. But I did not find relavent codes.

**Comment by mserranom** [comment]
Hi @zeakey, this is the socket.io configuration in the reverse proxy:

https://github.com/overleaf/overleaf/blob/37f01dfe1e7df25625b53769ce7db1f7c239420b/server-ce/nginx/sharelatex.conf#L19-L30

**Comment by zeakey** [comment]
@mserranom I see. Now I've successfully setup everything. Great thanks.
