### ISSUE TITLE
Issues accessing Overleaf outside of Azure VM

### ISSUE THREAD

**Issue by EXiSJH** [overleaf/overleaf#1131]
Hi Everyone,

I am trying to configure overleaf community edition running on an Azure VM with an internal IP address of 10.0.0.19. I can confirm firewall and NSG's look good and I can ssh and ping the server by IP just fine. When I do a curl http://localhost/launchpad from within the VM it works fine but I cannot access port 80 outside of the VM at all. I've tried modifying my config file but no luck. Any help would be appreciated. Here is the config file:

```
#### Overleaf RC ####

PROJECT_NAME=overleaf

# Sharelatex container
# Uncomment the SHARELATEX_IMAGE_NAME variable to use a user-defined image.
# SHARELATEX_IMAGE_NAME=sharelatex/sharelatex
SHARELATEX_DATA_PATH=data/sharelatex
SERVER_PRO=false
SHARELATEX_LISTEN_IP=10.0.0.19
SHARELATEX_PORT=80

# Sibling Containers
SIBLING_CONTAINERS_ENABLED=false
DOCKER_SOCKET_PATH=/var/run/docker.sock

# Mongo configuration
MONGO_ENABLED=true
MONGO_DATA_PATH=data/mongo
MONGO_IMAGE=mongo:4.4

# Redis configuration
REDIS_ENABLED=true
                           
```

**Comment by lirm-math** [comment]
I am having the same trouble

**Comment by das7pad** [comment]
Hello,

Thanks for raising this ticket. I'm afraid configuring Azures firewall is not something we can provide support for. You could try reaching out to Azure support.

Greetings,
Jakob
