### ISSUE TITLE
Unable to create new project

### ISSUE THREAD

**Issue by matmat59** [overleaf/overleaf#1132]
Hello,

On a VM based on Debian 12 I try to install Overleaf using the toolkit
The installation is quite easy.

I can connect to overleaf and create the first user. No error is reported on the launchpad page.
I can go to page project.

## Observed Behaviour

When I want to create a project, I receive an error message :  Something went wrong. Please try again.

![Capture d’écran du 2023-07-19 11-44-09](https://github.com/overleaf/overleaf/assets/139964576/fdf7a2ba-5002-4eb8-89ba-879028cbeb73)

Using the command /bin/logs web I catch this error:
{"name":"web","hostname":"b3f885bbfc3f","pid":169,"level":50,"err":{"message":"failed to initialize project history","name":"OError","stack":"OError: failed to initialize project history\n    at Object.initializeProject (/overleaf/services/web/app/src/Features/History/HistoryManager.js:25:11)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async _createBlankProject (/overleaf/services/web/app/src/Features/Project/ProjectCreationHandler.js:164:23)\n    at async Object.createBasicProject (/overleaf/services/web/app/src/Features/Project/ProjectCreationHandler.js:84:19)","info":{"statusCode":500}},"url":"/project/new","method":"POST","user":{"id":"64b7a81751e4d5f6a88f3980","email":"xxx@yyy.fr"},"msg":"error passed to top level next middleware","time":"2023-07-19T09:43:39.853Z","v":0}

Complete logs are here:
[logs.txt](https://github.com/overleaf/overleaf/files/12093595/logs.txt)

doctor tool output:
[doctor.txt](https://github.com/overleaf/overleaf/files/12093462/doctor.txt)

project-history.log :
[project-history.log](https://github.com/overleaf/overleaf/files/12094149/project-history.log)

## Technical Info
I'm using the last sharelatex docker image : sharelatex/sharelatex:4.0.4 
Doing the same on a Ubuntu 22.04.2 LTS works perfectly ...
I try the anwer 
The debian 12 is up to date
Same error using other web browser 
Same error without using the nginx proxy
I try the fix presented in https://github.com/overleaf/overleaf/issues/1082  but without success ...

Thank you

**Comment by rizlas** [comment]
Go inside container

-  `cd /var/log/sharelatex` 
-  `tail -f *`

Check logs when you click create project. 

For me the problem was S3 env variable.

**Comment by matmat59** [comment]
thank you for your answer,

here are the logs I obtained in the VM when I create a blank project:

==> project-history.log <==
{"name":"project-history","hostname":"b3f885bbfc3f","pid":135,"level":40,"err":{"message":"history store a non-success status code: 503","name":"OError","stack":"OError: history store a non-success status code: 503\n    at Request._callback (file:///overleaf/services/project-history/app/js/HistoryStoreManager.js:436:15)\n    at Request.self.callback (/overleaf/node_modules/request/request.js:185:22)\n    at Request.emit (node:events:513:28)\n    at Request.<anonymous> (/overleaf/node_modules/request/request.js:1154:10)\n    at Request.emit (node:events:513:28)\n    at IncomingMessage.<anonymous> (/overleaf/node_modules/request/request.js:1076:12)\n    at Object.onceWrapper (node:events:627:28)\n    at IncomingMessage.emit (node:events:525:35)\n    at endReadableNT (node:internal/streams/readable:1358:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","info":{}},"msg":"history store a non-success status code: 503","time":"2023-08-25T07:38:02.528Z","v":0}
{"name":"project-history","hostname":"b3f885bbfc3f","pid":135,"level":50,"err":{"message":"history store a non-success status code: 503","name":"OError","stack":"OError: history store a non-success status code: 503\n    at Request._callback (file:///overleaf/services/project-history/app/js/HistoryStoreManager.js:436:15)\n    at Request.self.callback (/overleaf/node_modules/request/request.js:185:22)\n    at Request.emit (node:events:513:28)\n    at Request.<anonymous> (/overleaf/node_modules/request/request.js:1154:10)\n    at Request.emit (node:events:513:28)\n    at IncomingMessage.<anonymous> (/overleaf/node_modules/request/request.js:1076:12)\n    at Object.onceWrapper (node:events:627:28)\n    at IncomingMessage.emit (node:events:525:35)\n    at endReadableNT (node:internal/streams/readable:1358:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)\nTaggedError\n    at file:///overleaf/services/project-history/app/js/HistoryStoreManager.js:346:32\n    at Request._callback (file:///overleaf/services/project-history/app/js/HistoryStoreManager.js:442:7)\n    at Request.self.callback (/overleaf/node_modules/request/request.js:185:22)\n    at Request.emit (node:events:513:28)\n    at Request.<anonymous> (/overleaf/node_modules/request/request.js:1154:10)\n    at Request.emit (node:events:513:28)\n    at IncomingMessage.<anonymous> (/overleaf/node_modules/request/request.js:1076:12)\n    at Object.onceWrapper (node:events:627:28)\n    at IncomingMessage.emit (node:events:525:35)\n    at endReadableNT (node:internal/streams/readable:1358:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)\nTaggedError\n    at file:///overleaf/services/project-history/app/js/HttpController.js:42:26\n    at file:///overleaf/services/project-history/app/js/HistoryStoreManager.js:346:16\n    at Request._callback (file:///overleaf/services/project-history/app/js/HistoryStoreManager.js:442:7)\n    at Request.self.callback (/overleaf/node_modules/request/request.js:185:22)\n    at Request.emit (node:events:513:28)\n    at Request.<anonymous> (/overleaf/node_modules/request/request.js:1154:10)\n    at Request.emit (node:events:513:28)\n    at IncomingMessage.<anonymous> (/overleaf/node_modules/request/request.js:1076:12)\n    at Object.onceWrapper (node:events:627:28)\n    at IncomingMessage.emit (node:events:525:35)\n    at endReadableNT (node:internal/streams/readable:1358:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","info":{}},"req":{"method":"POST","url":"/project","remoteAddress":"127.0.0.1","headers":{"user-agent":"node-fetch/1.0 (+https://github.com/bitinn/node-fetch)","content-length":"40"}},"msg":"history store a non-success status code: 503","time":"2023-08-25T07:38:02.528Z","v":0}

==> web.log <==
{"name":"web","hostname":"b3f885bbfc3f","pid":133,"level":50,"err":{"message":"failed to initialize project history","name":"OError","stack":"OError: failed to initialize project history\n    at Object.initializeProject (/overleaf/services/web/app/src/Features/History/HistoryManager.js:25:11)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async _createBlankProject (/overleaf/services/web/app/src/Features/Project/ProjectCreationHandler.js:164:23)\n    at async Object.createBasicProject (/overleaf/services/web/app/src/Features/Project/ProjectCreationHandler.js:84:19)","info":{"statusCode":500}},"url":"/project/new","method":"POST","user":{"id":"64b7a81751e4d5f6a88f3980","email":"mathieu.rossi@univ-artois.fr"},"msg":"error passed to top level next middleware","time":"2023-08-25T07:38:02.530Z","v":0}

**Comment by senyai** [comment]
Are you migrating to 4.0.4 or is this a new installation? I had similar errors, when not all of my projects migrated successfully. Just guessing.

**Comment by matmat59** [comment]
It's a new installation.

**Comment by CZtheHusky** [comment]
I have the same problem. I clone the toolkit repo and try to start it with a wsl2 in Windows 10 with docker, and i encounter the same error as you. 

Then I remove all containers, images and volumes in docker and again it fails. The logs of mine seems to be similar as yours.

**Comment by CZtheHusky** [comment]
Update:

I solve the error by enabling the hyper-v functionality of Windows 10.

**Comment by mscadela** [comment]
Hello,
I have the same problem on a VM based on Ubuntu 22.04.
Do you found a solution?
Thanks.

**Comment by vectorsss** [comment]
Hello! I also meet the same problem on QNAP NAS (CPU J4125 no avx support). 
I try to replace mongoDB without AVX, everything works fine on my macbook pro (M1).
But when I move the docker to NAS, I meet such kind of problem.
I guess maybe the reason is because of the CPU?

**Comment by shoeychi** [comment]
i have the same problem as you on both tencent cloud (ubuntu 20.04) and  synology nas.
at the same time, fail to upload file,  
<img width="953" alt="Screenshot 2024-06-29 at 21 50 11" src="https://github.com/overleaf/overleaf/assets/6987233/23399d30-d0e4-44eb-a035-64e9537ec0b6">

**Comment by shoeychi** [comment]
i fix the bug:

change `OVERLEAF_MONGO_URL ` inot `SHARELATEX_MONGO_URL`

**Comment by aruznieto** [comment]
> SHARELATEX_MONGO_URL

 Please either replace them with the "OVERLEAF_" prefix,
   e.g. SHARELATEX_MONGO_URL -> OVERLEAF_MONGO_URL, or
   remove old entries from your configuration.

**Comment by Cufoon** [comment]
The same logs and error. I do not know why they make their special and nice work opensource, but keep them errored.

**Comment by das7pad** [comment]
Hello,

Thanks for raising this. Are you still having issues with creating projects using a fresh checkout of the Overleaf Toolkit? If so, please open a new ticket.

Greetings,
Jakob
