### ISSUE TITLE
Numbers in project name download as underscores

### ISSUE THREAD

**Issue by ben-rampartcommuncations** [overleaf/overleaf#1133]
## Steps to Reproduce

1. Start a new project, give it a name that includes numbers (e.g. 01_Test_Project)
2. Compile your document
3. Download the PDF

## Expected Behaviour

Document should download as 01_Test_Project.pdf

## Observed Behaviour

Document downloads as ___Test_Project.pdf

## Technical Info

* Using Overleaf Server Pro 4.0.3
* Browser Name and version: 
    * Chrome 114.0.5735.198
    * Firefox 115.0.2
* Operating System and version (desktop or mobile): 
    * Ubuntu 22.04.02 LTS
    * ChromeOS 114

**Comment by mserranom** [comment]
Thanks for the report, this has been fixed in Overleaf CE/Server Pro 4.0.5

https://github.com/overleaf/overleaf/wiki/Release-Notes--4.x.x#server-pro-405

**Comment by ben-rampartcommuncations** [comment]
@mserranom Thank you!
