### ISSUE TITLE
docker-compose up not running properly

### ISSUE THREAD

**Issue by erdiphd** [overleaf/overleaf#1137]
## Steps to Reproduce

1. In Ubuntu 20.04.6 LTS `git clone https://github.com/overleaf/overleaf.git` ,then `docker-compose up`
2.
3.

## Expected Behaviour

I would expected to access `http://localhost/`

## Observed Behaviour

![image](https://github.com/overleaf/overleaf/assets/81103451/d59abe5b-756b-4dcd-bc97-aff75a95286e)

## Technical Info

* URL:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Signed in as:
* Project and/or file:

**Comment by holema** [comment]
Hello, I have the same issue :)

**Comment by senyai** [comment]
Mongo should be executed with transactions enabled. Please check release notes [about running mongo as a replica set](https://github.com/overleaf/overleaf/wiki/Release-Notes--4.x.x#manually-setting-up-mongodb-as-a-replica-set)

**Comment by holema** [comment]
Hello @senyai,

this is working great. Thanks a lot for the fast help

**Comment by holema** [comment]
Now I have the Problem, that I get this error:

![image](https://github.com/overleaf/overleaf/assets/22790152/9ddd6f19-1ba9-46b2-bea5-3256d64cda09)

**Comment by senyai** [comment]
Looks like MongoDB didn't start. Can you check its logs?

**Comment by holema** [comment]
Hello @senyai,
after exectuing This command on the mongo db:
```
rs.initiate({ _id: "overleaf", members: [ { _id: 0, host: "mongo:27017" } ] })
```

**Comment by rikroe** [comment]
If you add an init container to your docker compose file, it should always work, see https://github.com/overleaf/overleaf/issues/1120#issuecomment-1623295314

**Comment by erdiphd** [comment]
Do you also know how can I integrate git ?
For exampl;e 
I can see my project file here
`sharelatex_data/data/compiles/64db80c90d7f204ff7aa0d60-64db808c0d7f204ff7aa0d32`

![image](https://github.com/overleaf/overleaf/assets/81103451/a34db6ef-3e8f-4cd3-8009-f058c95d7d51)


I want to edit files here and see the changes in the web browser. I also would like to use .git in this folder.

Unfortunately my changes are not reflected in the web browser. 

How can I make changes in my local folder and see them in browser ?
In addion to that, how can I use .git ?

Thanks

**Comment by das7pad** [comment]
Hello,

As noted in the [Toolkit Quick-Start guide](https://github.com/overleaf/toolkit/blob/master/doc/quick-start-guide.md), the steps for starting from scratch are `bin/init` followed by `bin/up`.
`bin/up` will create the Mongo replica set as needed.

Greetings,
Jakob
