### ISSUE TITLE
Bug: top menu on /admin/register not working

### ISSUE THREAD

**Issue by krtko1** [overleaf/overleaf#1144]
## Steps to Reproduce

1. open admin manage users
2. click on menu
3.

## Expected Behaviour

redirect to another site

## Observed Behaviour
nothing happends

* Operating System and version (desktop or mobile): tested on Chrome and Firefox on Android and Desktop

**Comment by das7pad** [comment]
Hello,

Thanks for the report. I just tried out the top menu navigation on `/admin/register` in the latest version of Overleaf Community Edition (5.1.1) and it's working for me. Let me know if you are still having issues after upgrading.

Greetings,
Jakob
