### ISSUE TITLE
The line for project quantity statistics is covered by the footer.

### ISSUE THREAD

**Issue by siaimes** [overleaf/overleaf#1152]
![image](https://github.com/overleaf/overleaf/assets/34199488/83787863-b9db-4a95-a362-7c67b318f3cd)

**Comment by das7pad** [comment]
Hello,

Thanks for the report. This has been fixed in the latest minor version of Overleaf Community Edition and [Server Pro](https://www.overleaf.com/for/enterprises) 5.1.x.

Greetings,
Jakob
