### ISSUE TITLE
docker container stopping too slow

### ISSUE THREAD

**Issue by UlyssesZh** [overleaf/overleaf#1156]
It takes 60s every time the sharelatex docker container stops. I believe it takes much longer if the stop grace time limit is set to higher values.

**Comment by Musicminion** [comment]
just stop with `-f` may be better.

**Comment by das7pad** [comment]
Hello,

Thanks for raising this ticket. We've improved the shutdown procedure in Overleaf Community Editition 5.1 and [Server Pro](https://www.overleaf.com/for/enterprises) 5.1.

> https://github.com/overleaf/overleaf/wiki/Release-Notes-5.x.x#other-changes-1
> > Stricter and faster graceful shutdown procedure for the Server Pro container

Greetings,
Jakob
