### ISSUE TITLE
i can't login with initial user | Not able to create password

### ISSUE THREAD

**Issue by wiebereu** [overleaf/overleaf#1159]
Used docker-compose.
Looks like this:

`version: '2'
services:
    sharelatex:
        restart: always
        image: sharelatex/sharelatex
        container_name: sharelatex
        depends_on:
            - mongo
            - redis
        privileged: true
        ports:
            - 80:80
        links:
            - mongo
            - redis
        volumes:
            - ~/sharelatex_data:/var/lib/sharelatex
            - /var/run/docker.sock:/var/run/docker.sock
        environment:

            SHARELATEX_APP_NAME: Overleaf Community Edition

            SHARELATEX_MONGO_URL: mongodb://mongo/sharelatex

            # Same property, unfortunately with different names in
            # different locations
            SHARELATEX_REDIS_HOST: redis
            REDIS_HOST: redis

            ENABLED_LINKED_FILE_TYPES: 'url,project_file'

    mongo:
        restart: always
        image: mongo
        container_name: mongo
        expose:
            - 27017
        volumes:
            - ~/mongo_data:/data/db

    redis:
        restart: always
        image: redis
        container_name: redis
        expose:
            - 6379
        volumes:
            - ~/redis_data:/data`

I manage to create an admin user and after creation it provided me with an URL to visit and create an password. However i don't know where to run this URL cause i create the admin user in de CLI of my docker server. 

I tried to change the localhost name provided in the url into the IP of the dockerserver but to no avail. 

If is want to register i get the following message: 
**Please contact placeholder@example.com to create an account.**

That isn't going to work. 
Beneath is the only thing i see but can't login

![afbeelding](https://github.com/overleaf/overleaf/assets/58167538/91747e93-5cb8-456d-b596-f8bc5f37348d)

**Comment by henryclw** [comment]
Maybe you could try deleting the whole docker compose (using `down` option), and then try to run the whole docker compose once again (using `up -d` option). And the try to create the first user using the `/launchpad` webpage according to [this wiki](https://github.com/overleaf/overleaf/wiki/Creating-and-managing-users) instead of creating user in the cli

**Comment by wiebereu** [comment]
> Maybe you could try deleting the whole docker compose (using `down` option), and then try to run the whole docker compose once again (using `up -d` option). And the try to create the first user using the `/launchpad` webpage according to [this wiki](https://github.com/overleaf/overleaf/wiki/Creating-and-managing-users) instead of creating user in the cli

I manage to fix it. It works now
