### ISSUE TITLE
Templates not available

### ISSUE THREAD

**Issue by wiebereu** [overleaf/overleaf#1161]
I am using the Docker version of Overleaf. In the online version i can just select templates and use one of the available templates. i tried to do the same in the  Docker version but when i  go the template selection, i notice that Template was grade out and the option All templates results in the following error:

![afbeelding](https://github.com/overleaf/overleaf/assets/58167538/fa3e8b8c-3638-4dd1-b2a7-e9e7e3178e10)

Is this normal behavior? Or maybe i missed something during installation. 

The docker compose file i used is this one: [docker compose](https://github.com/overleaf/overleaf/blob/main/docker-compose.yml)
I only changed the image, as i was advised to do, into  tuetenk0pp/sharelatex-full

**Comment by henryclw** [comment]
I'm not sure how this error occurs, but one way to work around this might be just downloading the template as zip file and then create a new project using the upload feature.

**Comment by wiebereu** [comment]
> I'm not sure how this error occurs, but one way to work around this might be just downloading the template as zip file and then create a new project using the upload feature.

Yes i know that it is possible, but i wanted to know if maybe i made some mistake during installation or that everybody who use this container have the same problem?

**Comment by henryclw** [comment]
![image](https://github.com/overleaf/overleaf/assets/97804910/d458d99a-fe54-41c7-8751-d92be55ee202)

This is what I've got when I create a whole new instance from scratch using docker compose. I think they might not implemented the `templates` and `learn` in our community docker version.

**Comment by Musicminion** [comment]
This is the feature of server Pro(

No templates or learning page is included in overleaf CE version

**Comment by das7pad** [comment]
Hello,

Indeed, the templates feature is not part of Overleaf Community Edition. Our [Server Pro offering](https://www.overleaf.com/for/enterprises) includes a template feature.

In the latest version of Overleaf Community Edition we've hidden the templates link from the project dashboard.

Greetings,
Jakob
