### ISSUE TITLE
could not use xelatex

### ISSUE THREAD

**Issue by blue-eyed-g** [overleaf/overleaf#1163]
i refer to the page https://github.com/overleaf/toolkit/blob/master/doc/quick-start-guide.md and https://github.com/overleaf/toolkit/blob/master/doc/ce-upgrading-texlive.md to install and run overleaf on docker. but i could not use xelatex.
here is the output from bin/docker:
====== Overleaf Doctor ======
- Host Information
    - Linux
    - lsb_release not found !
- Dependencies
    - bash
        - status: present
        - version info: 5.1.16(1)-release
    - docker
        - status: present
        - version info: Docker version 24.0.6, build ed223bc820
    - realpath
        - status: present
        - version info: realpath (GNU coreutils) 9.4
    - perl
        - status: present
        - version info: 5.038000
    - awk
        - status: present
        - version info: GNU Awk 5.2.2, API 3.2, PMA Avon 8-g1, (GNU MPFR 4.2.1, GNU MP 6.3.0)
    - openssl
        - status: present
        - version info: OpenSSL 3.1.4 24 Oct 2023 (Library: OpenSSL 3.1.4 24 Oct 2023)
    - docker compose
        - status: present
        - version info: Docker Compose version 2.22.0
- Docker Daemon
    - status: up
====== Configuration ======
- config/version
    - status: present
    - version: 4.1.4
- config/overleaf.rc
    - status: present
    - values
        - SHARELATEX_DATA_PATH: data/sharelatex
        - SERVER_PRO: false
        - SHARELATEX_LISTEN_IP: x.x.x.x
        - SHARELATEX_PORT: x
        - MONGO_ENABLED: true
        - MONGO_IMAGE: mongo:4.4
        - MONGO_DATA_PATH: data/mongo
        - REDIS_ENABLED: true
        - REDIS_IMAGE: redis:6.2
        - REDIS_DATA_PATH: data/redis
        - NGINX_ENABLED: false
        - NGINX_CONFIG_PATH: config/nginx/nginx.conf
        - TLS_PRIVATE_KEY_PATH: config/nginx/certs/overleaf_key.pem
        - TLS_CERTIFICATE_PATH: config/nginx/certs/overleaf_certificate.pem
        - NGINX_HTTP_LISTEN_IP: 127.0.1.1
        - NGINX_HTTP_PORT: 80
        - NGINX_TLS_LISTEN_IP: 127.0.1.1
        - TLS_PORT: 443
        - GIT_BRIDGE_ENABLED: false
- config/variables.env
    - status: present
    - values
        - SHARELATEX_FILESTORE_BACKEND: fs
        - SHARELATEX_HISTORY_BACKEND: fs
====== Warnings ======
- None, all good
====== End ======

**Comment by PillarsZhang** [comment]
For me, just running `tlmgr path add` sorted it out. (Might save time for anyone else who runs into this.)

**Comment by blue-eyed-g** [comment]
> For me, just running `tlmgr path add` sorted it out. (Might save time for anyone else who runs into this.)

thanks
