### ISSUE TITLE
koma-script scrreport not working

### ISSUE THREAD

**Issue by byebb** [overleaf/overleaf#1164]
In the normal Overleaf version, it is working, but in my own Overleaf instance running on my device it is not working:

![image](https://github.com/overleaf/overleaf/assets/4288893/670da13c-c264-438d-acee-5db7098d92a2)

any idea how i can use the [scrreprt.cls](https://ctan.org/pkg/scrreprt?lang=de)

Thank you!

**Comment by das7pad** [comment]
Hello,

I'm afraid we cannot offer LaTeX help for specific templates or packages in Overleaf Community Edition. Our Server Pro offering provides you with access to the same optimized LaTeX environment as used for overleaf.com. We run [extensive tests with the overleaf.com gallery templates](https://www.overleaf.com/learn/latex/Overleaf_and_TeX_Live) with new TeXLive releases and generally make sure that they compile with new versions or leave them at their previous TeXLive release. Server Pro customers get access to our historic TeXLive releases as well to ensure older projects continue to work.
You can find more information on Server Pro here: https://www.overleaf.com/for/enterprises

Greetings,
Jakob
