### ISSUE TITLE
mac M1, the hotkey command + space (Reference Autocomplete) not work

### ISSUE THREAD

**Issue by zmsn-2077** [overleaf/overleaf#1165]
I remove the hotkey: command+space for spotlight, but it still not work for overleaf hotkey: Reference Autocomplete

<img width="622" alt="image" src="https://github.com/overleaf/overleaf/assets/73586554/41d2a416-e465-40a0-b67c-79c4cd0a7df3">

**Comment by aeaton-overleaf** [comment]
The relevant hotkey is Control+Space (`⌃ Space`), not Command+Space (`⌘ Space`).

**Comment by Musicminion** [comment]
It seem that you should use <kbd>option</kbd> + <kbd>space</kbd> .

since Control+Space (⌃ Space) is used to change Input Method

**Comment by aeaton-overleaf** [comment]
Indeed, if you have input sources enabled then you'll need to use the alternative shortcut Option+Space (`⌥ Space`).
