### ISSUE TITLE
Compilation time out variable settings

### ISSUE THREAD

**Issue by jmchantrein** [overleaf/overleaf#1166]
## Expected Behaviour
Be able to set a compilation timeout variable environment via the variables.env file, for example.

## Observed Behaviour
I seem to have documents that apparently compile without a timeout. This is annoying because they use CPU resources without releasing them. I tried to change the timeout value for compilation, but I couldn't find where this default value was defined in the source code or how to change it.

## Analysis
Some things have been suggested here #805, but it seems outdated...

## Questions

1. Is there a default time-out setting for the compilation of documents ?
2. If such a setting exists, could you please guide me on how to modify it ?

Thank you.

**Comment by senyai** [comment]
I'd like to add my two cents here. Om my server some pdflatex projects get stuck forever (weeks!) eating 100% of the cpu. To overcome this I added this bash script to cron that kills latex processes running for more that 13 minutes.
```bash
#!/usr/bin/env bash
docker exec sharelatex bash -c "kill -9 \$(ps -eo etimes,pid,etime,args --sort -etimes | awk '\$4~/^(pdflatex|latex)/{if (\$1 > 13*60) print \$2 }')"
echo $(date) "exit code: $?"
```
So, what I'm saying is that if there's `COMPILE_TIMEOUT` somewhere it does nothing.

**Comment by Musicminion** [comment]
First of all, let me answer your question.

1. In overleaf CE, the default setting for compile is 180s(3 min).

https://github.com/overleaf/overleaf/blob/26ee64fe620a486eef8086884d616048b08fcf4e/server-ce/config/settings.js#L278C1-L287C5

2. if you already run your overleaf CE in production mode, first of all  you need to modify settting in the code above(or in env 
var setting), secondly, you need to update db of every user's compile time. since **Compile timeout is stored in the mongodb**. Check [this](https://github.com/overleaf/overleaf/pull/805)

> Run a script to update timeouts for existing users with db.users.updateMany({}, {'$set': {'features.compileTimeout': <value>}})

There are some important point you need to know(also write for those who want to Enlarge or Decrease the timeout limit)

1. Compile timeout is also limited by nginx conf, if you want to Increase the limit, don't forget to modify 
this https://github.com/overleaf/overleaf/blob/main/server-ce/nginx/sharelatex.conf and also you own nginx setting
2. Compile timeout is stored in the MongoDB, so if you are upgrading your instance, you need to modify data in the MongoDB
3. Don't modify code directly in the container, just build your own docker image

**Comment by das7pad** [comment]
Hello,

Thank you for getting in touch regarding compile timeouts. I'm afraid we do not enforce compile timeouts in Overleaf Community Edition. Compile timeouts can be enforced using our Sandboxed compiles mode as available in [our Server Pro offering](https://www.overleaf.com/for/enterprises). I'm sorry for this limitation.

Greetings,
Jakob

**Comment by TafkaMax** [comment]
> ps -eo etimes,pid,etime,args --sort -etimes | awk '\$4~/^(pdflatex|latex)/{if (\$1 > 13*60) print \$2 }'

Hmm I tried to use this script, but to no avail.

First of all it reported like this:

```
awk: 0: unexpected character '\'
awk: 1: unexpected character '\'
```

EDIT: I needed to add `(pdflatex|latex|xelatex)`

**Comment by senyai** [comment]
@TafkaMax I'm sorry, it's not easy to understand the trouble you're having. Maybe you tried to run `awk` locally instead of inside Docker?

**Comment by TafkaMax** [comment]
> [@TafkaMax](https://github.com/TafkaMax) I'm sorry, it's not easy to understand the trouble you're having. Maybe you tried to run `awk` locally instead of inside Docker?

I tried to run it inside the container, it didn't like the quotes. It does work though running through `docker exec`

But for me there was some perl xelatex process so I changed it to not look at exactly the $4 part.

```
#!/usr/bin/env bash
docker exec sharelatex bash -c "kill -9 \$(ps -eo etimes,pid,etime,args --sort -etimes | awk '/^(.*xelatex.*|.*latexmk.*)/{if (\$1 > 13*60) print \$2 }')" 
echo $(date) "exit code: $?" 
```

So skip the args part.

Interestingly this did not solve my issue yet. I had 100% CPU util and it bought down the utilization to about 50% and then climbed back up.

I had to restart the sharelatex container to fix it, but looking at it now it seems to have climbed back up.

<img width="1700" height="223" alt="Image" src="https://github.com/user-attachments/assets/a1f5184c-bdad-49c6-bf82-ccad204e7b1f" />

**Comment by senyai** [comment]
> <img alt="Image" width="1700" height="223" src="https://private-user-images.githubusercontent.com/46354923/569890416-a1f5184c-bdad-49c6-bf82-ccad204e7b1f.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzQ1NDM3MDksIm5iZiI6MTc3NDU0MzQwOSwicGF0aCI6Ii80NjM1NDkyMy81Njk4OTA0MTYtYTFmNTE4NGMtYmRhZC00OWM2LWJmODItY2NhZDIwNGU3YjFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMzI2VDE2NDMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmOTI3YTdiZGE2MDBlZDlkMmVkYWJjZTgzYzQ1YTc1YTc4Mzc0NzVjZTdlZTUxYjY2ZjNhOWQ5OTUyY2FkMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.boG_BOd7hkfYS2eTrc0IEOWdGguOfo6G6a5_p0w7ulg">

Looking at the graph, I suspect that the processes have been running for more than 13 minutes and these processes should've been terminated by a cron job.
Likely, you have processes other than xelatex or latexmk. Btw, the expression could be just `...awk '/(xelatex|latexmk)/{if...`
