### ISSUE TITLE
Make container names configurable

### ISSUE THREAD

**Issue by Scriptim** [overleaf/overleaf#1167]
I would like to configure the names of the ShareLaTeX, Redis and Mongo containers. I want to recognize at first glance which containers belong to ShareLaTeX/Overleaf when I run `docker ps` by naming them `sharelatex_redis`, for instance.

The `container_name` values [`sharelatex`](https://github.com/overleaf/toolkit/blob/36692fb2aa8c1fb6e746325e464f0b5362d6cfbb/lib/docker-compose.base.yml#L8), [`redis`](https://github.com/overleaf/toolkit/blob/36692fb2aa8c1fb6e746325e464f0b5362d6cfbb/lib/docker-compose.redis.yml#L10) and [`mongo`](https://github.com/overleaf/toolkit/blob/36692fb2aa8c1fb6e746325e464f0b5362d6cfbb/lib/docker-compose.mongo.yml#L9)  (also [`nginx`](https://github.com/overleaf/toolkit/blob/36692fb2aa8c1fb6e746325e464f0b5362d6cfbb/lib/docker-compose.nginx.yml#L15) and [`git-bridge`](https://github.com/overleaf/toolkit/blob/36692fb2aa8c1fb6e746325e464f0b5362d6cfbb/lib/docker-compose.git-bridge.yml#L10)) are currently hard-coded in the `docker-compose.yml` files.

My suggestion is adding configuration variables, e. g. `REDIS_CONTAINER_NAME` to `overleaf.rc`.

**Comment by das7pad** [comment]
Hello,

Thank you for the suggestion. Having consistent container names is very useful for sending docker commands to our [Server Pro](https://www.overleaf.com/for/enterprises) customers, especially `docker cp` commands. Having configurable container names would make these commands and instructions very complex. So I'm afraid we will still with hard-coded names for the time being.

Greetings,
Jakob
