### ISSUE TITLE
sharelatex 4,2 docker image launches but web UI not starting

### ISSUE THREAD

**Issue by jjyyxx** [overleaf/overleaf#1168]
## Steps to Reproduce

1. I was upgrading my own community instance from 4.1 (works normally) to 4.2. The `docker-compose.yml` is not changed. Only the `sharelatex/sharelatex` image is updated.
2. Mongo, Redis and Sharelatex container all launches normally.
3. Web UI not starting, not sure how to debug, possibly related to `This release separates the web service into an internal API service and a user facing service`
4. Currently revert to 4.1

## Expected Behaviour

Service Launches properly after upgrade.

## Observed Behaviour

Opened ports I could find are for API only, not for Web UI.

## Context

Upgrade from 4.1 to 4.2

**Comment by Doomsdayrs** [comment]
Did overleaf just not inform us of port changes??

**Comment by jjyyxx** [comment]
@Doomsdayrs That's my initial thought, but if I remembered correctly, I searched ports in two directions (pid -> port and port -> pid), but failed to find an eligible port. I might have something missing, but currently I am reverting to v4.1

**Comment by simono41** [comment]
I think it has to do with the fact that I used an ipv6 with the container.

According to the netstat command, the seever was only 
![IMG_0652](https://github.com/overleaf/overleaf/assets/21181514/c289f5c1-ef0d-4775-ba5a-1eb512b6d3b7)
released to the following port http:://[::1]:4000
