### ISSUE TITLE
Password is too long

### ISSUE THREAD

**Issue by mrgohin** [overleaf/overleaf#1171]
## Steps to Reproduce

1. Got to https://your-instance/launchpad
2. Enter an email and password
3. Make sure you have no idea what is the maximum length of the password field

## Expected Behaviour

Choose a password with maximum length of *X* and use only following character *Y*

## Observed Behaviour

![image](https://github.com/overleaf/overleaf/assets/38684218/bf5e64de-c960-402d-a558-f02739d14018)

## Context

Create an admin user
## Technical Info

* URL:
* Browser Name and version: unimportant
* Operating System and version (desktop or mobile): unimportant
* Signed in as: unimportant
* Project and/or file: unimportant

## Analysis

- Created an issue for improvement
- Probably the answer: https://github.com/overleaf/overleaf/blob/a722ca9483df10ca9e857ee14720c957cc174ed9/services/web/app/src/Features/Authentication/AuthenticationManager.js#L42-L51

**Comment by das7pad** [comment]
Hello,

Thank you for your feedback. We are using `bcrypt` for protecting user passwords. As you might have spotted in the code snippet, [`bcrypt` has a limit of 72 character for its input](https://en.wikipedia.org/wiki/Bcrypt#Description).
We have considered limiting the length of the HTML input field, but ultimately decided against it as the user feedback for entering too long values into fields in not very user friendly in all browsers. Notably, users (and password managers) may "think" that they submitted a very long password, but in fact only a prefix was accepted. The server-side check is a good compromise here.

Greetings,
Jakob
