### ISSUE TITLE
Where to set MONGO_IMAGE to upgrade using toolkit

### ISSUE THREAD

**Issue by michaelvanhorn** [overleaf/overleaf#1172]
According to

https://github.com/overleaf/overleaf/wiki/Updating-Mongo-version

in order to upgrade the mongo image using the toolkit, you 

"update MONGO_IMAGE, e.g. MONGO_IMAGE=mongo:4.4"

In which file do we make the change? I'm currently running mongo 4.0.27, and I need to first upgrade to 4.2, then to 4.4. So, I need to update the value of MONGO_IMAGE first to "mongo:4.2", and then once that works, change it again to "mongo:4.4" (since I'm using overleaf version 4.1.3, which is >=3.2.

But, where do I change the value of MONGO_IMAGE?

**Comment by mlevans0** [comment]
When using the toolkit, the `MONGO_IMAGE` environment variable is set in the **config/overleaf.rc** file. 

An example value would be `MONGO_IMAGE=mongo:5`.
