### ISSUE TITLE
Build fails with deprecated apt-key use

### ISSUE THREAD

**Issue by kaosmaja** [overleaf/overleaf#1173]
## Steps to Reproduce
1. have a clean project pulled from overleaf/overleaf
2. cd overleaf/develop
3. sh bin/build

## Expected Behaviour
Project builds successfully.

## Observed Behaviour
Build fails with exit code 2
```
 > [spelling base 4/5] RUN chmod 0755 ./install_deps.sh && ./install_deps.sh:
0.782 + echo 'APT::Default-Release "buster";'
0.801 + echo 'deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ focal main universe'
0.818 + echo 'deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ focal main universe'
0.850 + apt-key adv --no-tty --keyserver keyserver.ubuntu.com --recv-keys 3B4FE6ACC0B21F32
1.578 Warning: apt-key output should not be parsed (stdout is not a terminal)
1.703 Executing: /tmp/apt-key-gpghome.26je31k0bE/gpg.1.sh --no-tty --keyserver keyserver.ubuntu.com --recv-keys 3B4FE6ACC0B21F32
1.963 gpg: keyserver receive failed: No route to host
------
failed to solve: process "/bin/sh -c chmod 0755 ./install_deps.sh && ./install_deps.sh" did not complete successfully: exit code: 2
```

## Context
Build doesn't complete.

## Technical Info
The offending script is found here: overleaf/services/spelling/install_deps.sh

## Analysis
My guess is that the cause lies in the use of a static key in combination with the deprecated apt-key command.

**Comment by das7pad** [comment]
Hello,

It looks like you had troubles accessing the keyserver for the GPG key: `No route to host`. It might succeed after a few retries or checking the internet connection.

Greetings,
Jakob
