### ISSUE TITLE
ECCONREFUSED with latest version of ShareLatex

### ISSUE THREAD

**Issue by Doomsdayrs** [overleaf/overleaf#1176]
## Steps to Reproduce
1. Upgrade to ShareLatex 4.2.1
2. Open any project, new or old

## Expected Behaviour
Entering project like normal

## Observed Behaviour
Notice the view below repeating
![image](https://github.com/overleaf/overleaf/assets/38189170/54c13bbf-d843-4fdc-aa59-8b685559e9ec)

## Technical Info

The below is the specific issue
```
{
  "name": "real-time",
  "hostname": "overleaf",
  "pid": 173,
  "level": 50,
  "project_id": "657e6242e863e66861b05db1",
  "user_id": "65285bbda706d1bf35f52969",
  "client_id": "6McxkBLN14xejM31riB3",
  "err": {
    "message": "connect ECONNREFUSED ::1:3000",
    "name": "Error",
    "stack": "Error: connect ECONNREFUSED ::1:3000\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)\nTaggedError: join project request failed\n    at Request._callback (/overleaf/services/real-time/app/js/WebApiManager.js:36:18)\n    at self.callback (/overleaf/node_modules/request/request.js:185:22)\n    at Request.emit (node:events:517:28)\n    at Request.onRequestError (/overleaf/node_modules/request/request.js:877:8)\n    at ClientRequest.emit (node:events:517:28)\n    at Socket.socketErrorListener (node:_http_client:501:9)\n    at Socket.emit (node:events:517:28)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)",
    "info": {},
    "code": "ECONNREFUSED"
  },
  "method": "joinProject",
  "msg": "server side error in joinProject",
  "time": "2023-12-17T02:53:58.018Z",
  "v": 0
}
```

URL: latex.doomsdayrs.page
Browser Name and version: Firefox 120
Operating System: Fedora 39

## Analysis

This seems related possibly to the continued lack of ipv6 support, as the URL "::1:3000" seems to be an ipv6 URL. No errors are reported by mongoDB nor redis.

The problem is, this issue persists regardless if I have ipv6 enabled or not.

**Comment by Doomsdayrs** [comment]
https://github.com/overleaf/overleaf/pull/1175 Might help(?)

**Comment by Doomsdayrs** [comment]
https://github.com/overleaf/overleaf/issues/1168 is possibly related

**Comment by ehfd** [comment]
I reproduce this with an ipv6-enabled Kubernetes cluster in versions 4.1 and 4.2.

Staying with 3.5.13 for now.

**Comment by ehfd** [comment]
I reproduce this with an IPv6-enabled Kubernetes cluster in version 4.2.

This is a blocker for IPv6 infrastructure.

https://github.com/overleaf/overleaf/pull/1175 using `RUN sed -i 's/127.0.0.1/localhost/g' /etc/nginx/sites-enabled/sharelatex.conf` by @toastedcrumpets and @Wielewout did not fix the issue. When there was an NGINX 502 error, now it shows this error on the Web UI.

Staying with 3.5.13 for now.

**Comment by drescherflo** [comment]
I had the same issue since the latest docker-ce update.

First I got an NGINX 502 error like in #1146.
Running `sed -i 's/127.0.0.1/localhost/g' /etc/nginx/sites-enabled/sharelatex.conf` like suggested brought back the web ui, but led to the issue described here.

I'm working around the issue by completely disabling IPv6 for the sharelatex container.
For the overleaf-toolkit, I did this by creating a `docker-compose.override.yml` in `config/` with the content proposed by #1168.

```yaml
---
version: '2.2'
services:
  sharelatex:
    # ...
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
```

**Comment by toastedcrumpets** [comment]
> I'm working around the issue by completely disabling IPv6 for the sharelatex container. For the overleaf-toolkit, I did this by creating a `docker-compose.override.yml` in `config/` with the content proposed by #1168.
> 
> ```yaml
> ---
> version: '2.2'
> services:
>   sharelatex:
>     # ...
>     sysctls:
>       - net.ipv6.conf.all.disable_ipv6=1
> ```

This is a great solution @drescherflo, thank you for sharing. Its a good fix while we await overleaf to address IPv6 support.

**Comment by ehfd** [comment]
Unfortunately not possible in Kubernetes with ipv6.

**Comment by das7pad** [comment]
The latest releases 4.2.4 and 5.0.3 include changes for switching all internal traffic to IPv4 on the application level.
