### ISSUE TITLE
How to solve "Error rendering embedded code  Invalid PDF

### ISSUE THREAD

**Issue by limsungwoo** [overleaf/overleaf#1177]
<!-
I've been uploading a pdf file to the github repository and it went well. But suddenly uploading a new file
Error rendering embedded code

Invalid PDF
I see an error. Why is it popping up? What's the solution?
I tried removing Idm with YouTube Google Search, but it doesn't work.
-->

## Steps to Reproduce

![image](https://github.com/overleaf/overleaf/assets/103165459/2093e46b-8096-41fa-a0ce-b832b77a9a9a)

1.
2.
3.

## Technical Info

* URL:
* Browser Name and version: https://github.com/limsungwoo/3grade-higschool-math_korea/blob/main/studyfile/2024%20%23The27%20%EB%AA%A8%EC%9D%98%EA%B3%A0%EC%82%AC%20%EC%8B%9C%EC%A6%8C1%20%EC%A0%9C1%ED%9A%8C.pdf
* Operating System and version (desktop or mobile): desktop
* Signed in as:
* Project and/or file:

**Comment by das7pad** [comment]
Hello,

Your issue does not seem to be related to Overleaf Community Edition. Consider reaching out to GitHub support instead.

Greetings,
Jakob
