### ISSUE TITLE
Reference-Error when compiling kaobook-class in overleaf community edition

### ISSUE THREAD

**Issue by ljagg** [overleaf/overleaf#1178]
[raw.log](https://github.com/overleaf/overleaf/files/13813217/raw.log)

## Steps to Reproduce

1. Installing overleaf community edition using the toolkit and successfully pulling every Texlive package via `tlmgr install scheme-full`
2. Exporting the kaobook-Template from overleaf.com after importing it from [here](https://www.latextemplates.com/template/kaobook)
3. Compiling the files from scratch after clearing the cache

## Expected Behaviour

Successful compilation of a PDF file including correct references and bibliography
The same LaTex project compiles without major errors on overleaf.com

## Observed Behaviour

The references and the bibliography aren't generated properly
When compiling i get the following persistent errors: 
`Package hyperref Warning: bookmark level for unknown mtocsection defaults to 0.`
`Citation 'XXX' on page 1 undefined on input line X` ...for very citation
`Empty bibliography on input line 258.`
`Package biblatex Warning: Please (re)run Biber on the file: output and rerun LaTeX afterwards.`

I'll attach the raw log file.

Probably the community edition doesn't use or supporting the compileall.sh file of the package that specifies how to compile the document. I'll paste it here:

```
#!/bin/bash

# Compile document
pdflatex -interaction=nonstopmode main

# Compile nomenclature
makeindex main.nlo -s nomencl.ist -o main.nls

# Compile index
makeindex main

# Compile bibliography
biber main

# Compile document
pdflatex main

# Compile glossary
makeglossaries main

# Compile document
pdflatex main
```

## Technical Info
Beside this error the installation works well. The /bin/doctor script included in the toolkit doesn't show any errors

Thank you in advance for your help!

**Comment by Musicminion** [comment]
I can compile it on my self-hosted overleaf, maybe you need to update your texlive?

**Comment by das7pad** [comment]
Hello,

I'm afraid we cannot offer LaTeX help for specific templates or packages in Overleaf Community Edition. Our Server Pro offering provides you with access to the same optimized LaTeX environment as used for overleaf.com. We run [extensive tests with the overleaf.com gallery templates](https://www.overleaf.com/learn/latex/Overleaf_and_TeX_Live) with new TeXLive releases and generally make sure that they compile with new versions or leave them at their previous TeXLive release. Server Pro customers get access to our historic TeXLive releases as well to ensure older projects continue to work.
You can find more information on Server Pro here: https://www.overleaf.com/for/enterprises

Greetings,
Jakob
