### ISSUE TITLE
Ubuntu, postfix, mail dont work

### ISSUE THREAD

**Issue by mscadela** [overleaf/overleaf#1179]
Hello,
mail don't work:
###############
[2024-01-03 11:36:41] DEBUG Sending mail using SMTP/6.7.2[client:6.7.2]
[2024-01-03 11:36:41] DEBUG [agkXBePEfPg] Resolved localhost as 127.0.0.1 [cache miss]
[2024-01-03 11:36:41] ERROR [agkXBePEfPg] connect ECONNREFUSED 127.0.0.1:25
[2024-01-03 11:36:41] DEBUG [agkXBePEfPg] Closing connection to the server using "destroy"
[2024-01-03 11:36:41] ERROR Send Error: connect ECONNREFUSED 127.0.0.1:25
{"name":"web","hostname":"4b463be235a9","pid":175,"level":40,"err":{"message":"error sending message","name":"OError","stack":"OError: error sending message\n    at Object.sendEmail (/overleaf/services/web/app/src/Features/Email/EmailSender.js:99:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Object.sendEmail (/overleaf/services/web/app/src/Features/Email/EmailHandler.js:25:3)\ncaused by:\n    Error: connect ECONNREFUSED 127.0.0.1:25\n        at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)","info":{}},"msg":"failed to send activation email","time":"2024-01-03T11:36:41.450Z","v":0}
################
SHARELATEX_EMAIL_FROM_ADDRESS=team@example.com
SHARELATEX_EMAIL_SMTP_HOST=localhost
SHARELATEX_EMAIL_SMTP_PORT=25
SHARELATEX_EMAIL_SMTP_SECURE=true
SHARELATEX_EMAIL_SMTP_USER=overleaf
SHARELATEX_EMAIL_SMTP_PASS=password
SHARELATEX_EMAIL_SMTP_LOGGER=true
SHARELATEX_EMAIL_SMTP_TLS_REJECT_UNAUTH=false
 SHARELATEX_EMAIL_SMTP_IGNORE_TLS=false
#################
sending email from the server works, but in overleaf I receive a "ERROR Send Error: connect ECONNREFUSED 127.0.0.1:25"
Can anyone help?
Thank you so much and a Happy New Year!

**Comment by Darkdragon84** [comment]
Have you tried sending a test email from inside the sharelatex docker container, e.g. using telnet?
```
docker exec -it sharelatex bash
// now we are root inside the docker container
apt-get update
apt-get install telnet
telnet 127.0.0.1 25
// send email following steps from https://prox.dev/sending-emails-with-telnet/
```
My guess is that your smtp server is not reachable from inside the docker container. Have you made sure it is accessible from inside the container?

**Comment by das7pad** [comment]
Hello,

Thanks for getting in touch. It looks like you are trying to talk to postfix running on the Dockerhost. The `sharelatex` container has it's own network namespace and it's localhost is not the same as the Docker hosts localhost. You need to configure your system to accept traffic from the Docker network of the `sharelatex` container and then point the Overleaf CE container at the Docker host.
I'm afraid I cannot provide any detailed steps here. We offer email based support to [Server Pro](https://www.overleaf.com/for/enterprises) customers. I hope the above helps still.

Greetings,
Jakob
