### ISSUE TITLE
False positive of `_ must be inside math mode` in LaTeX linter

### ISSUE THREAD

**Issue by YDX-2147483647** [overleaf/overleaf#1185]
> [!NOTE]
>
> I met this problem on overleaf.com, but I guess this is a bug in Community Edition.

Underscores are valid as `\documentclass` options, but the LaTeX linter does not think so.

## Steps to Reproduce

1. Create `foo.cls`:

   ```latex
   \NeedsTeXFormat{LaTeX2e}
   \ProvidesClass{foo}
   
   \DeclareOption{under_score}{\newcommand{\foo}{Foo}}
   \ProcessOptions\relax
   \LoadClass{article}
   ```

2. Create `main.tex`:

   ```latex
   \documentclass[under_score]{foo}
   
   \begin{document}
   
   Document
   
   \foo
   
   \end{document}
   ```

3. Wait until Overleaf compiles successfully.

4. Locate the first line of `main.tex`:

   > _ must be inside math mode

![](https://github.com/overleaf/overleaf/assets/73375426/513f1f81-f859-4779-b0be-172381927999)

## Expected Behaviour

The linter should be happy.

## Observed Behaviour

- ❌Linter throws an error.
- ✅PDF is generated as expected.
- ✅The raw log has no relevant error.

## Context

[A thesis template](https://www.ctan.org/pkg/bithesis) needs the following option to work:

```latex
\documentclass[type=bachelor_translation]{bithesis}
```

## Technical Info

* URL: https://github.com/BITNP/BIThesis/tree/main/templates/paper-translation

  (This is the full project/scaffold, instead of MWE)

* Browser Name and version: Mozilla Firefox or MS Edge.

* Operating System and version (desktop or mobile): Desktop.

* Signed in as: (N/A)

* Project and/or file: https://www.overleaf.com/read/kjjdwmgcbwqb#299eb2

  (This is the full project/scaffold, instead of MWE)

## Analysis

Maybe we should add a new environment?

https://github.com/overleaf/overleaf/blob/fdf8ebe001ec91dc3ab5c23b47bbbb03dc03d1bb/services/web/frontend/js/features/source-editor/languages/latex/linter/latex-linter.worker.js#L1180-L1191

**Comment by Musicminion** [comment]
If you don;t want to see this warning, just close option: `code check`
<img width="307" alt="截屏2024-01-31 13 43 11" src="https://github.com/overleaf/overleaf/assets/84625273/7d1094c2-7e29-4d2e-87bb-39c8ffb209b0">

**Comment by tomh-overleaf** [comment]
Hi there, the syntax parser unfortunately will never be perfect, but the trick from https://www.overleaf.com/learn/how-to/Code_Check shall work:
```
%%begin novalidate
\documentclass[under_score]{foo}
%%end novalidate
```

Note that we in general do not provide support for the Overleaf Community Edition. For issues that are exhibiting themselves also on the SaaS version at www.overleaf.com, you can contact us at support@overleaf.com. I hope this helps.

**Comment by tomh-overleaf** [comment]
Hi there, the syntax parser unfortunately will never be perfect, but the trick from https://www.overleaf.com/learn/how-to/Code_Check shall work:
```
%%begin novalidate
\documentclass[under_score]{foo}
%%end novalidate
```

Note that we in general do not provide support for the Overleaf Community Edition. For issues that are exhibiting themselves also on the SaaS version at www.overleaf.com, you can contact us at support@overleaf.com. I hope this helps.
