### ISSUE TITLE
Oveleaf offline not generating complete images, but overleaf hosted at overleaf.com works fine

### ISSUE THREAD

**Issue by muralimanohar0212** [overleaf/overleaf#1186]
I currently have a latex template from this repository -> [TUD_Thesis_Template](https://github.com/TUDSSL/TUD_ENS_MSc_Thesis_Template) .  I am using the offline version of latex. In the offline version (running the latext version of tex live) when I compile the repository, the images do not get generated. I tried compiling the image tex file in the templates directory as well, and it still does not work. None of the images are generated. The document compiles as 

<img width="351" alt="image" src="https://github.com/overleaf/overleaf/assets/22497463/71fc1e2f-967e-4bd4-825a-83e6e0b98ec6">
 

However, when the same repository is uploaded to the overleaf hosted at overleaf.com and compiled, it generates the images rightly as below -

<img width="494" alt="image" src="https://github.com/overleaf/overleaf/assets/22497463/1e29ce11-2898-499d-aa6b-18d46b71b8f4">

I tried switching all the compilers. No success. 

Here is the error stack if it helps 

<img width="545" alt="image" src="https://github.com/overleaf/overleaf/assets/22497463/41760e7b-2a5b-45ab-9aa3-01d4fd4793f1">

Can you please help me with this issue?  You can just clone the latex template repository and upload it as it is and you can see the error. 

Here is the output of bin/doctor

====== Overleaf Doctor ======
- Host Information
    - Linux
    - Output of 'lsb_release -a':
            No LSB modules are available.
            Distributor ID:     Ubuntu
            Description:        Ubuntu 22.04.3 LTS
            Release:    22.04
            Codename:   jammy
- Dependencies
    - bash
        - status: present
        - version info: 5.1.16(1)-release
    - docker
        - status: present
        - version info: Docker version 24.0.6, build ed223bc
    - realpath
        - status: present
        - version info: realpath (GNU coreutils) 8.32
    - perl
        - status: present
        - version info: 5.034000
    - awk
        - status: present
        - version info: mawk 1.3.4 20200120
    - openssl
        - status: present
        - version info: OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)
    - docker compose
        - status: present
        - version info: Docker Compose version v2.21.0
- Docker Daemon
    - status: up
====== Configuration ======
- config/version
    - status: present
    - version: 4.2.0
- config/overleaf.rc
    - status: present
    - values
        - SHARELATEX_DATA_PATH: data/sharelatex
        - SERVER_PRO: false
        - SHARELATEX_LISTEN_IP: 127.0.0.1
        - SHARELATEX_PORT: 8888
        - MONGO_ENABLED: true
        - MONGO_IMAGE: mongo:5.0
        - MONGO_DATA_PATH: data/mongo
        - REDIS_ENABLED: true
        - REDIS_IMAGE: redis:6.2
        - REDIS_DATA_PATH: data/redis
        - NGINX_ENABLED: false
        - NGINX_CONFIG_PATH: config/nginx/nginx.conf
        - TLS_PRIVATE_KEY_PATH: config/nginx/certs/overleaf_key.pem
        - TLS_CERTIFICATE_PATH: config/nginx/certs/overleaf_certificate.pem
        - NGINX_HTTP_LISTEN_IP: 127.0.1.1
        - NGINX_HTTP_PORT: 80
        - NGINX_TLS_LISTEN_IP: 127.0.1.1
        - TLS_PORT: 443
        - GIT_BRIDGE_ENABLED: false
- config/variables.env
    - status: present
    - values
        - SHARELATEX_FILESTORE_BACKEND: fs
        - SHARELATEX_HISTORY_BACKEND: fs
====== Warnings ======
- None, all good
====== End ======

**Comment by Musicminion** [comment]
So, your issue is that you can't compile your project on `overleaf` or `your local overleaf` or `your local texlive`? 

I got confused about your problem. 

- The first picture you show: you may use draft mode to compile
- The second picture you show looks normal, anything wrong?

**Comment by muralimanohar0212** [comment]
Hello @Musicminion , 

The second picture is the one complied on the online paid version of overleaf. Maybe I should not have added it. Please ignore the second one. 

For the first picture, it is not in the the draft mode. It is in the normal Compile mode. 

Yes, it is a local deployed version of overleaf. The GitHub link has the access to the project. 

This is an issue with the local hosted version of overleaf, as with the exact same configuration, the online version of overleaf (2nd image) Compiles well. 

Please let me know if you need any information or logs to look into this, and I can provide them. 


Thanks!

**Comment by muralimanohar0212** [comment]
> So, your issue is that you can't compile your project on `overleaf` or `your local overleaf` or `your local texlive`?

And this issue is thar I am not able to compile it properly from the local overleaf .

**Comment by Musicminion** [comment]
I am testing this project now, please be patient.

**Comment by Musicminion** [comment]
@muralimanohar0212 

Run this command on your server to enter your container env:
```
docker exec -it sharelatex /bin/bash
```
Then:
```
apt-get update
apt-get install ghostscript 
```

This is not a bug of overleaf-ce, but a feature specific needed by your project. Overleaf Official Website's TeXLive images have been carefully adjusted to cater for most people's requirements.(This is a huge project, and it is accumulated by years of maintenance) However, related texlive image is closed source and provided for **only server-pro users**.

To be exact, your project use `\usepackage{epstopdf}`, and this package need `ghostscript `

If you are not that familar with texlive and docker, a good solution is to use overleaf Official Version, However, if you use your self-deployed version, maybe you need to figure out bugs by yourself.

Hopefully this can solve your trouble.

**Comment by Musicminion** [comment]
just similar to https://github.com/overleaf/overleaf/issues/411

**Comment by muralimanohar0212** [comment]
> @muralimanohar0212
> 
> Run this command on your server to enter your container env:
> 
> ```
> docker exec -it sharelatex /bin/bash
> ```
> 
> Then:
> 
> ```
> apt-get update
> apt-get install ghostscript 
> ```
> 
> This is not a bug of overleaf-ce, but a feature specific needed by your project. Overleaf Official Website's TeXLive images have been carefully adjusted to cater for most people's requirements.(This is a huge project, and it is accumulated by years of maintenance) However, related texlive image is closed source and provided for **only server-pro users**.
> 
> To be exact, your project use `\usepackage{epstopdf}`, and this package need `ghostscript `
> 
> If you are not that familar with texlive and docker, a good solution is to use overleaf Official Version, However, if you use your self-deployed version, maybe you need to figure out bugs by yourself.
> 
> Hopefully this can solve your trouble.

Thank you for the solution. I tried this, and it still does not work. 

ghostscript is already installed on my system. I had already restarted the server multiple times, and only then I raised this ticket.  

I will scout around a little more. Thanks!

**Comment by Musicminion** [comment]
I just tried this on my server, and it's ok.

Have you set `enable_escape = t` ?

**Comment by muralimanohar0212** [comment]
Hello @Musicminion ,

I have fixed the problem. It is also not with enable_escape = t. 
We need to install the texlive-font-utils package. 

The command for the same is below:
'apt-get install texlive-font-utils'


This fixes this issue. I think https://github.com/overleaf/overleaf/issues/411 will also be solved with this

Thank you very much for pointing me in the right direction!

**Comment by Musicminion** [comment]
Here is a list of overleaf official's websites installed packages. If you want more experiences like official web, you can install all of these.
[Display_Overleaf_Installed_Package.pdf](https://github.com/overleaf/overleaf/files/14235805/Display_Overleaf_Installed_Package.pdf)

**Comment by Karonolandiis** [comment]
please try
`\usepackage{graphicx}
\usepackage[outdir=./]{epstopdf}`
