### ISSUE TITLE
Limit registration

### ISSUE THREAD

**Issue by jsanpedro** [overleaf/overleaf#119]
Can't seem to find a way to limit the registration of new users. Anybody can click register and get an account in my privately hosted sharelatex service, without any approval from my side. Is there a way to control new user registration?

Thanks

**Comment by jpallen** [comment]
Basic user management is now available in ShareLaTeX 0.1.4. Public account registration is now disabled, and users must be added by admins.

**Comment by zeigerpuppy** [comment]
Thanks, that's really useful, time to upgrade!

**Comment by jlazerus** [comment]
Is there a way to easily turn public account registration back on for those who prefer that method?

**Comment by jowagner** [comment]
https://github.com/sharelatex/sharelatex/wiki/Creating-and-managing-users
