### ISSUE TITLE
non-ok response from filestore for upload: 500

### ISSUE THREAD

**Issue by wixaw** [overleaf/overleaf#1194]
Hello,

Since this weekend, my users are unable to copy a project or upload a .zip file. There have been no changes to the VM and no updates. There are no storage problems. However, we get an error 500 as soon as there is a resource. If we upload a zip file with only .tex files, it works. I have restarted the container and rebooted the VM, but nothing has changed. Do you have any idea what might be causing this issue?

Thank you in advance.

`{"name":"web","hostname":"06d440a0f424","pid":213,"level":50,"err":{"message":"non-ok response from filestore for upload: 500","name":"OError","stack":"OError: non-ok response from filestore for upload: 500\n    at Request.<anonymous> (/overleaf/services/web/app/src/Features/FileStore/FileStoreHandler.js:99:19)\n    at Request.emit (node:events:517:28)\n    at Request.emit (node:domain:489:12)\n    at Request.onRequestResponse (/overleaf/node_modules/request/request.js:1059:10)\n    at ClientRequest.emit (node:events:517:28)\n    at ClientRequest.emit (node:domain:489:12)\n    at HTTPParser.parserOnIncomingClient (node:_http_client:700:27)\n    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)\n    at Socket.socketOnData (node:_http_client:541:22)\n    at Socket.emit (node:events:517:28)\n    at Socket.emit (node:domain:489:12)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)\n    at Readable.push (node:internal/streams/readable:278:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)\nTaggedError: Error uploading file, retries failed\n    at /overleaf/services/web/app/src/Features/FileStore/FileStoreHandler.js:50:20\n    at /overleaf/node_modules/async/dist/async.js:4634:21\n    at /overleaf/node_modules/underscore/underscore-node-f.cjs:1213:19\n    at Request.<anonymous> (/overleaf/services/web/app/src/Features/FileStore/FileStoreHandler.js:103:20)\n    at Request.emit (node:events:517:28)\n    at Request.emit (node:domain:489:12)\n    at Request.onRequestResponse (/overleaf/node_modules/request/request.js:1059:10)\n    at ClientRequest.emit (node:events:517:28)\n    at ClientRequest.emit (node:domain:489:12)\n    at HTTPParser.parserOnIncomingClient (node:_http_client:700:27)\n    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)\n    at Socket.socketOnData (node:_http_client:541:22)\n    at Socket.emit (node:events:517:28)\n    at Socket.emit (node:domain:489:12)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)","info":{"statusCode":500,"projectId":"xxxx","fileArgs":{"name":"Chi-Square-table.png","linkedFileData":null}}},"projectId":"xxx","filePath":"/var/lib/sharelatex/tmp/uploads/9954bb09f868dbd4798803a3d335d097","fileName":"Chi-Square-table.png","folderId":"xxxx","msg":"error uploading file","time":"2024-03-18T10:18:43.635Z","v":0}`

**Comment by wixaw** [comment]
For example, I am getting EFBIG error in the filestore, but my file is only 110 KB in size...

```
{"name":"filestore","hostname":"06d440a0f424","pid":214,"level":40,"offset":297,"msg":"slow event loop","time":"2024-03-18T10:35:50.676Z","v":0}
{"name":"filestore","hostname":"06d440a0f424","pid":214,"level":50,"req":{"method":"POST","url":"/project/65f819050fd95cee54a17a6d/file/65f819050fd95cee54a17a71","remoteAddress":"127.0.0.1","headers":{}},"res":{"statusCode":500,"headers":{"content-length":"22"}},"responseTimeMs":955,"info":{"key":"65f819050fd95cee54a17a6d/65f819050fd95cee54a17a71","bucket":"/var/lib/sharelatex/data/user_files","error":{"name":"WriteError","info":{"location":"/var/lib/sharelatex/data/user_files","target":"65f819050fd95cee54a17a6d/65f819050fd95cee54a17a71"},"cause":{"errno":-27,"code":"EFBIG","syscall":"rename","path":"/var/lib/sharelatex/data/user_files/tmp-iS1gwp/uploaded-file","dest":"/var/lib/sharelatex/data/user_files/65f819050fd95cee54a17a6d_65f819050fd95cee54a17a71"}}},"msg":"inserting file","time":"2024-03-18T10:35:50.686Z","v":0}


{"name":"filestore","hostname":"06d440a0f424","pid":214,"level":50,"req":{"method":"POST","url":"/project/65f819050fd95cee54a17a6d/file/65f819060fd95cee54a17a73","remoteAddress":"127.0.0.1","headers":{}},"res":{"statusCode":500,"headers":{"content-length":"22"}},"responseTimeMs":765,"info":{"key":"65f819050fd95cee54a17a6d/65f819060fd95cee54a17a73","bucket":"/var/lib/sharelatex/data/user_files","error":{"name":"WriteError","info":{"location":"/var/lib/sharelatex/data/user_files","target":"65f819050fd95cee54a17a6d/65f819060fd95cee54a17a73"},"cause":{"errno":-27,"code":"EFBIG","syscall":"rename","path":"/var/lib/sharelatex/data/user_files/tmp-ElkxBo/uploaded-file","dest":"/var/lib/sharelatex/data/user_files/65f819050fd95cee54a17a6d_65f819060fd95cee54a17a73"}}},"msg":"inserting file","time":"2024-03-18T10:35:51.458Z","v":0}
{"name":"filestore","hostname":"06d440a0f424","pid":214,"level":50,"req":{"method":"POST","url":"/project/65f819050fd95cee54a17a6d/file/65f819070fd95cee54a17a74","remoteAddress":"127.0.0.1","headers":{}},"res":{"statusCode":500,"headers":{"content-length":"22"}},"responseTimeMs":758,"info":{"key":"65f819050fd95cee54a17a6d/65f819070fd95cee54a17a74","bucket":"/var/lib/sharelatex/data/user_files","error":{"name":"WriteError","info":{"location":"/var/lib/sharelatex/data/user_files","target":"65f819050fd95cee54a17a6d/65f819070fd95cee54a17a74"},"cause":{"errno":-27,"code":"EFBIG","syscall":"rename","path":"/var/lib/sharelatex/data/user_files/tmp-QxWzBo/uploaded-file","dest":"/var/lib/sharelatex/data/user_files/65f819050fd95cee54a17a6d_65f819070fd95cee54a17a74"}}},"msg":"inserting file","time":"2024-03-18T10:35:52.220Z","v":0}
```

**Comment by jdleesmiller** [comment]
I wonder if you have hit the maximum number of files in that folder. Could you see whether you can create a file in that directory, e.g. `touch /var/lib/sharelatex/data/user_files/test`?
