### ISSUE TITLE
Google Drive support

### ISSUE THREAD

**Issue by jpallen** [overleaf/overleaf#12]
Similar to Dropbox support except that it has a very different API.

**Comment by adv1112** [comment]
me too

**Comment by staslev** [comment]
+1 for sure.

**Comment by dibetao** [comment]
:+1:

**Comment by arnaudh** [comment]
+1

**Comment by SantiMunin** [comment]
+1000

Any status updates on this?

**Comment by henryoswald** [comment]
Sorry it is still on our to do list.

sent from my mobile.

**Comment by stuefi** [comment]
+1

**Comment by adv1112** [comment]
+1!

**Comment by homo-loquens** [comment]
+1 any news on this front?

**Comment by henryoswald** [comment]
no short term plans sorry.

On Mon, Mar 14, 2016 at 1:52 AM, homo-loquens <notifications@github.com>
wrote:

> +1 any news on this front?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sharelatex/sharelatex/issues/12#issuecomment-196103589>
> .
>



-- 
Henry Oswald
shareLaTeX.com co-founder

**Comment by whatthefunction** [comment]
+1 Would very much like this feature.

**Comment by tiagodanielff** [comment]
+1

**Comment by FXelix** [comment]
+1

Any news on Google Drive support? It would be really helpful, especially with the rise of upcoming chromebooks!

**Comment by maninalift** [comment]
There is a a [similar but less polished LaTeX editor](https://texviewer.herokuapp.com/)(uses CodeMirror, not ace) that is integrated with google drive. 

I expect the author would be happy to publish the source if it is not already public, but I haven't been able to track down either so far.

**Comment by Yharooer** [comment]
any updates on whether there are any plans for this?

**Comment by GenieTim** [comment]
May I ask where the relevant code is for Dropbox? I wanted to try to implement this myself to send a PR, but could not find the relevant Dropbox code to use as a guide...

**Comment by gh2k** [comment]
Closing this issue as the Dropbox code (and related parts) are not open-source, so this is being tracked elsewhere.
