### ISSUE TITLE
Container services over IPv4 IPv6

### ISSUE THREAD

**Issue by mateodurante** [overleaf/overleaf#1201]
## Steps to Reproduce

1. Create a container using Docker or Docker Compose that utilizes IPv6 (I used Kubernetes).
2. Attempt to access:
![image](https://github.com/overleaf/overleaf/assets/668847/da2b066b-4c95-4543-8fcf-17949a14c996)

## Expected Behavior

All internal services should be accessible over both IPv4 and IPv6 (`*:port`).

## Observed Behavior

The ShareLaTeX container ports are only listening over IPv6 (`[::]:port`).
![image](https://github.com/overleaf/overleaf/assets/668847/c5a5aca0-3e20-4191-8ba1-c6ef1fccf846)

## Context

I recently created a new environment using Kubernetes, and it doesn't seem to connect. When I recreated the same environment using Docker with IPv4, it functioned correctly:
![image](https://github.com/overleaf/overleaf/assets/668847/572ed024-8058-45ab-8ce7-0bc8120f3977)

## Technical Info

* URL: NA
* Browser Name and Version: NA
* Operating System and Version (Desktop or Mobile): Kubernetes cluster K3S
* Signed in as: NA
* Project and/or File: https://github.com/mateodurante/overleaf-docker

## Analysis

- Disabling IPv6 for the container/cluster is not an option in my infrastructure (like other comment issues suggest).
- I resolved the issue by configuring Nginx to listen on all ports for both IPv4 and IPv6 and proxying between them. See the configuration file: https://github.com/mateodurante/overleaf-docker/blob/main/sharelatex-nginx/sharelatex.conf

**Comment by mserranom** [comment]
This should be fixed in the latest release, `5.0.1`, would you mind giving it a try?

Check the release notes, as there are several breaking changes: https://github.com/overleaf/overleaf/wiki/Release-Notes-5.x.x
