### ISSUE TITLE
Does not recompile if code has errors

### ISSUE THREAD

**Issue by jn9702** [overleaf/overleaf#1209]
## Steps to Reproduce

If the code has errors (don't judge, intentionally), try to compile it twice without changing anything.

## Expected Behaviour

It should recompile as overleaf.com does.

## Observed Behaviour

Error code: 
> No PDF
> This compile didn’t produce a PDF. This can happen if:
> There is an unrecoverable LaTeX error. If there are LaTeX errors shown below or in the raw logs, please try to fix them and compile again.
> The document environment contains no content. If it’s empty, please add some content and compile again.
> This project contains a file called output.pdf. If that file exists, please rename it and compile again.

## Context

It affects when there is an intentional error and the compile button is clicked twice.

## Technical Info

Ubuntu 22.04 LTS + Overleaf toolkits (latest)

## Analysis

I know the following ways work:
1. Modify the document and recompile.
2. Clear cached files.
However, the behaviour is different from overleaf.com, that is what I am confused about.

**Comment by matejsmycka** [comment]
experience the same issue.

**Comment by TexnoMann** [comment]
I also have a similar problem. Why is this issue closed?

**Comment by jn9702** [comment]
> I also have a similar problem. Why is this issue closed?

They have fixed it in the latest version, please upgrade (backup forehead of course).
