### ISSUE TITLE
pull sharelatex\sharelatex:lastest not working

### ISSUE THREAD

**Issue by minnten** [overleaf/overleaf#1210]
## Steps to Reproduce

1. I tried to set up a new environment, but keep getting the following Error by trying to pull the sharelatex-image:

`admn@dockerhost:~# docker pull sharelatex/sharelatex:latest   
Error response from daemon: manifest for sharelatex/sharelatex:latest not found: manifest unknown: manifest unknown`

2. other pulls, like `docker pull sharelatex/sharelatex:5.0.2-RC4` work 

## Expected Behaviour
Get the latest docker-image

## Observed Behaviour
The error seen above

**Comment by Musicminion** [comment]
No latest tag it seems, and use overleaf/toolkit is best solution.

btw, sth is woring with toolkit now, so maybe wait for some time.

**Comment by minnten** [comment]
I will not use the overleaf toolkit, as this does not integrates in my environment. 

I deploy my own Instance since 2019, with almost issues over the docker-compose-file.

and there was an latest-tag till recently, because i have a running system which only uses sharelatex/sharelatex

`sudo docker pull sharelatex/sharelatex
Using default tag: latest
Error response from daemon: manifest for sharelatex/sharelatex:latest not found: manifest unknown: manifest unknown`

As docker uses default the tag latest, there should be one.

**Comment by damian-anlauf** [comment]
The latest-tag is now back. It seems the tag has been (accidentally?) removed, when they took the 5.0.2 version offline. 
As of writing it points to version 5.0.3.
