### ISSUE TITLE
Rebranding from ShareLaTeX to Overleaf

### ISSUE THREAD

**Issue by MrPandragon** [overleaf/overleaf#1212]
## Steps to Reproduce

1. I am trying to follow the Quick-Start Guide for the latest version installation.
2. Encountered a version conflict problem during Starting Up
![微信图片编辑_20240423145344](https://github.com/overleaf/overleaf/assets/55674206/13d5d804-2e4b-49c1-8dea-2605008c437c)
3. Trying to use the bin/upgrade function also gives the same error

## Expected Behaviour

Successfully installed the latest version of overleaf

## Observed Behaviour

Already mentioned in Steps to Reproduce. There was an issue with [docker-compose](https://github.com/overleaf/overleaf/blob/main/docker-compose.yml) and other file environments not being updated in a timely manner, which prevented the installation of the

## Technical Info

* Browser Name and version: 5.0.2
* Operating System and version (desktop or mobile):Ubuntu 22.04

## Analysis

Version 5.0.X seems break the overleaf toolkit to some extend - at least their compatibilitychecks. Need to update the relevant files to the latest version.Thank you.

**Comment by Musicminion** [comment]
So, are you installing in a brand new environment, or you are upgrading your instance from old one to newer?

Btw, sth is woring with overleaf toolkit currently, you need to modify https://github.com/overleaf/toolkit/blob/master/lib/config-seed/version to 5.x, so that it can work.

**Comment by MrPandragon** [comment]
> So, are you installing in a brand new environment, or you are upgrading your instance from old one to newer?
> 
> Btw, sth is woring with overleaf toolkit currently, you need to modify https://github.com/overleaf/toolkit/blob/master/lib/config-seed/version to 5.x, so that it can work.

Thank you. I was trying to install a completely new environment. Following your advice I can start it now.

**Comment by Musicminion** [comment]
> > So, are you installing in a brand new environment, or you are upgrading your instance from old one to newer?
> > Btw, sth is woring with overleaf toolkit currently, you need to modify https://github.com/overleaf/toolkit/blob/master/lib/config-seed/version to 5.x, so that it can work.
> 
> Thank you. I was trying to install a completely new environment. Following your advice I can start it now.

It seems that they have fixed now, the latest version is 5.0.3. Both 5.0.1 and 5.0.2 may have bugs, which results in the delayed update of overleaf/toolkit.

**Comment by das7pad** [comment]
Sorry for the hassle. We had to retract the 5.0.1/5.0.2 releases and missed to revert the `variables.env` file to the old branding. As @Musicminion pointed out, 5.0.3 has been release in the meantime.

Running `bin/upgrade` should get you back on track.
