### ISSUE TITLE
Upgrade to 5.0.3 CE - Installing scheme-full fails due to outdated texlive version (2023 instead of 2024)

### ISSUE THREAD

**Issue by jazzdd86** [overleaf/overleaf#1215]
## Steps to Reproduce
1. start overleaf with toolkit
2. Enter command as mentioned in the Quick Installation Guide to install texlive scheme-full: `docker exec sharelatex tlmgr install scheme-full`

## Expected Behaviour
Should install texlive scheme-full

## Observed Behaviour
Console output:
`tlmgr: Local TeX Live (2023) is older than remote repository (2024).
Cross release updates are only supported with
  update-tlmgr-latest(.sh/.exe) --update
See https://tug.org/texlive/upgrade.html for details.`

* Operating System and version (desktop or mobile): Server system, Arch Linux

**Comment by Musicminion** [comment]
```bash
wget http://mirror.ctan.org/systems/texlive/tlnet/update-tlmgr-latest.sh
chmod +x update-tlmgr-latest.sh
./update-tlmgr-latest.sh -- --update
```

**Comment by Ezimkin** [comment]
https://github.com/overleaf/overleaf/issues/873#issuecomment-1498442727

**Comment by MaveriQ** [comment]
> ```shell
> ./update-tlmgr-latest.sh -- --update
> ```

For noobs like me, first shell into sharelatex docker instance like so
`docker exec -it sharelatex bash`
and then run the commands given above.
Exit the docker instance and then install new packages.

**Comment by ziorufus** [comment]
Is it possible to get this update persistent?
If I reboot the container, I loose the packages and I need to run the whole process again.

**Comment by nssassassin** [comment]
> Is it possible to get this update persistent? If I reboot the container, I loose the packages and I need to run the whole process again.

docker commit sharelatex sharelatex/sharelatex:<commit-message>
then add to docker compose:
services:
    sharelatex:
        image: sharelatex/sharelatex:<commit-message>

**Comment by ziorufus** [comment]
> docker commit sharelatex sharelatex/sharelatex: then add to docker compose: services: sharelatex: image: sharelatex/sharelatex:

Thank you very much!
I've already found the same solution on the Wiki, but I forgot to update my Github comment. Sorry for that!

**Comment by das7pad** [comment]
Hello,

Installing `scheme-full` should be possible in the latest Server Pro 5.1 release again.

Greetings,
Jakob
