### ISSUE TITLE
history-v1 sent 404 to project-history

### ISSUE THREAD

**Issue by Ray-ZX** [overleaf/overleaf#1216]
## Steps to Reproduce
Encountered an issue when attempting to create a project while using the master version of the code, building the image with 'make build-community', and launching the program via the TLS Proxy method of the toolkit. WebSocket test succeeded, but failed when creating project.
Please give me some advice,Thanks.

1.Use the master version of the code.
2.Run 'make build-community' to build the image.
3.Launch the program using the TLS Proxy method of the toolkit.
4.Attempt to create a project.

## Expected Behaviour
Projects should be created successfully.

## Observed Behaviour
Browser received 500.Internal service 'history-v1' sent 404 to 'project-history' at 'setupErrorHandling'.
Can't find 'projectHistoryGlobalBlobs'  in mongoDB.

**Comment by ayaka-lab** [comment]
Are you using arm-based machine? Master code is in development status, the only solution is wait for some time before they can fix.

Or, you can checked the release of overleaf-docker-image, and go back to release version in the pase.

**Comment by Ray-ZX** [comment]
> Are you using arm-based machine? Master code is in development status, the only solution is wait for some time before they can fix.
> 
> Or, you can checked the release of overleaf-docker-image, and use git to go back to a released version in the past.

I am using the x86 architecture. 
Yes, I tried not to use 'make build-community', but instead used sharelatex5.0.3. I successfully avoided this issue temporarily. Thank you for your advice!
