### ISSUE TITLE
How to reduce compile time when using overleaf CE 5.0.3

### ISSUE THREAD

**Issue by UntaggedRui** [overleaf/overleaf#1219]
I have deployed overleaf 5.0.3 via [toolkit](https://github.com/overleaf/toolkit/blob/master/doc/configuration.md) in my own server. It run successfully. However, I find it a little slow when compiling my dissertation. My dissertation is a 120-page Chinese pdf containing some formulas and images, and it takes about 20 seconds to compile each time. I am using a multi-core physical server to deploy overleaf, how should I configure it so that it can use enough resources to speed up my compilation? My server configuration is as follows
```
server: DELL R740
cpu: Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (2*16*2=64cores)
memory: 128G
docker version: Docker version 26.0.0, build 2ae903e
os: Ubuntu 20.04.6 LTS
```

I've changed the following configuration in `variables.env`, but it doesn't seem to reduce my compile time
```
## Nginx
NGINX_WORKER_PROCESSES=40
NGINX_WORKER_CONNECTIONS=1768
```

**Comment by Musicminion** [comment]
既然你都说中文pdf了我就直接中文回复你了（

你说的这些nginx啊配置、版本啊都没有关系，跟编译速度无关。

说实话你要对编译速度感兴趣，可以把你的文档上传到overleaf官网试试，然后看看编译速度，我敢说大差不差也就是10s-20s甚至更久（哦，官网现在只能限时20s了）

Latex这个编译的东西很玄幻，不管你是20核心，32核心，甚至64核心，再或者是128GB内存甚至2TB内存，你用所谓的多核心的、高内存的服务器，只能增加你并发的数量。因为他本来就是考验的单核性能，根据我的测试，一个文档的编译，满载情况下差不多吃掉一个cpu+300MB的内存。

所以你要是追求所谓的速度，要目换高主频的CPU（这个是我知乎看texpage说的，也是一个做类似latex编译的服务），要目就是本地（理论来说本地编译应该还是要快一些的）

这种轻微的编译速度问题，基本忽略就好。如果你发现你在本地编译了20s，overleaf编译出现2分钟，这才是严重的bug。

**Comment by UntaggedRui** [comment]
> 既然你都说中文pdf了我就直接中文回复你了（
> 
> 你说的这些nginx啊配置、版本啊都没有关系，跟编译速度无关。
> 
> 说实话你要对编译速度感兴趣，可以把你的文档上传到overleaf官网试试，然后看看编译速度，我敢说大差不差也就是10s-20s甚至更久（哦，官网现在只能限时20s了）
> 
> Latex这个编译的东西很玄幻，不管你是20核心，32核心，甚至64核心，再或者是128GB内存甚至2TB内存，你用所谓的多核心的、高内存的服务器，只能增加你并发的数量。因为他本来就是考验的单核性能，根据我的测试，一个文档的编译，满载情况下差不多吃掉一个cpu+300MB的内存。
> 
> 所以你要是追求所谓的速度，要目换高主频的CPU（这个是我知乎看texpage说的，也是一个做类似latex编译的服务），要目就是本地（理论来说本地编译应该还是要快一些的）
> 
> 这种轻微的编译速度问题，基本忽略就好。如果你发现你在本地编译了20s，overleaf编译出现2分钟，这才是严重的bug。

感谢回复。我在overleaf会员账号上编译这个文档也差不多要这么久，顶多快一两秒。
这么看来并没有参数可以调节编译速度，那我就继续这样使用了。

**Comment by Musicminion** [comment]
> > 既然你都说中文pdf了我就直接中文回复你了（
> > 你说的这些nginx啊配置、版本啊都没有关系，跟编译速度无关。
> > 说实话你要对编译速度感兴趣，可以把你的文档上传到overleaf官网试试，然后看看编译速度，我敢说大差不差也就是10s-20s甚至更久（哦，官网现在只能限时20s了）
> > Latex这个编译的东西很玄幻，不管你是20核心，32核心，甚至64核心，再或者是128GB内存甚至2TB内存，你用所谓的多核心的、高内存的服务器，只能增加你并发的数量。因为他本来就是考验的单核性能，根据我的测试，一个文档的编译，满载情况下差不多吃掉一个cpu+300MB的内存。
> > 所以你要是追求所谓的速度，要目换高主频的CPU（这个是我知乎看texpage说的，也是一个做类似latex编译的服务），要目就是本地（理论来说本地编译应该还是要快一些的）
> > 这种轻微的编译速度问题，基本忽略就好。如果你发现你在本地编译了20s，overleaf编译出现2分钟，这才是严重的bug。
> 
> 感谢回复。我在overleaf会员账号上编译这个文档也差不多要这么久，顶多快一两秒。 这么看来并没有参数可以调节编译速度，那我就继续这样使用了。

诶嘿，看起来像是个MMD的爱好者，还买了overleaf会员嘛哈哈哈，羡慕了（

**Comment by UntaggedRui** [comment]
> > > 既然你都说中文pdf了我就直接中文回复你了（
> > > 你说的这些nginx啊配置、版本啊都没有关系，跟编译速度无关。
> > > 说实话你要对编译速度感兴趣，可以把你的文档上传到overleaf官网试试，然后看看编译速度，我敢说大差不差也就是10s-20s甚至更久（哦，官网现在只能限时20s了）
> > > Latex这个编译的东西很玄幻，不管你是20核心，32核心，甚至64核心，再或者是128GB内存甚至2TB内存，你用所谓的多核心的、高内存的服务器，只能增加你并发的数量。因为他本来就是考验的单核性能，根据我的测试，一个文档的编译，满载情况下差不多吃掉一个cpu+300MB的内存。
> > > 所以你要是追求所谓的速度，要目换高主频的CPU（这个是我知乎看texpage说的，也是一个做类似latex编译的服务），要目就是本地（理论来说本地编译应该还是要快一些的）
> > > 这种轻微的编译速度问题，基本忽略就好。如果你发现你在本地编译了20s，overleaf编译出现2分钟，这才是严重的bug。
> > 
> > 
> > 感谢回复。我在overleaf会员账号上编译这个文档也差不多要这么久，顶多快一两秒。 这么看来并没有参数可以调节编译速度，那我就继续这样使用了。
> 
> 诶嘿，看起来像是个MMD的爱好者，还买了overleaf会员嘛哈哈哈，羡慕了（
> 
> 补一嘴：overleaf官方编译的镜像是经过了调优的，所以有些东西社区版还不一定能编译好，但是官网可以，但是属实是用过就不想回来了。我之前也折腾过好久的overleaf搭建，后来还是选择用官网去了hhhh

朋友的会员账号，他帮忙测试的。 官网最近似乎对免费用户的限制增加，对于120页的中文毕业论文已经很难编译成功了，所有要么开会员要么自建了。

**Comment by Musicminion** [comment]
> > > > 既然你都说中文pdf了我就直接中文回复你了（
> > > > 你说的这些nginx啊配置、版本啊都没有关系，跟编译速度无关。
> > > > 说实话你要对编译速度感兴趣，可以把你的文档上传到overleaf官网试试，然后看看编译速度，我敢说大差不差也就是10s-20s甚至更久（哦，官网现在只能限时20s了）
> > > > Latex这个编译的东西很玄幻，不管你是20核心，32核心，甚至64核心，再或者是128GB内存甚至2TB内存，你用所谓的多核心的、高内存的服务器，只能增加你并发的数量。因为他本来就是考验的单核性能，根据我的测试，一个文档的编译，满载情况下差不多吃掉一个cpu+300MB的内存。
> > > > 所以你要是追求所谓的速度，要目换高主频的CPU（这个是我知乎看texpage说的，也是一个做类似latex编译的服务），要目就是本地（理论来说本地编译应该还是要快一些的）
> > > > 这种轻微的编译速度问题，基本忽略就好。如果你发现你在本地编译了20s，overleaf编译出现2分钟，这才是严重的bug。
> > > 
> > > 
> > > 感谢回复。我在overleaf会员账号上编译这个文档也差不多要这么久，顶多快一两秒。 这么看来并没有参数可以调节编译速度，那我就继续这样使用了。
> > 
> > 
> > 诶嘿，看起来像是个MMD的爱好者，还买了overleaf会员嘛哈哈哈，羡慕了（
> > 补一嘴：overleaf官方编译的镜像是经过了调优的，所以有些东西社区版还不一定能编译好，但是官网可以，但是属实是用过就不想回来了。我之前也折腾过好久的overleaf搭建，后来还是选择用官网去了hhhh
> 
> 朋友的会员账号，他帮忙测试的。 官网最近似乎对免费用户的限制增加，对于120页的中文毕业论文已经很难编译成功了，所有要么开会员要么自建了。

还是觉得overleaf的定价有点过高，9刀一个月 80多刀一年，已经超过国内大部分软件的订阅价格了，下次如果有机会给他们官方可以建议建议这个价格问题（

**Comment by UntaggedRui** [comment]
> > > > > 既然你都说中文pdf了我就直接中文回复你了（
> > > > > 你说的这些nginx啊配置、版本啊都没有关系，跟编译速度无关。
> > > > > 说实话你要对编译速度感兴趣，可以把你的文档上传到overleaf官网试试，然后看看编译速度，我敢说大差不差也就是10s-20s甚至更久（哦，官网现在只能限时20s了）
> > > > > Latex这个编译的东西很玄幻，不管你是20核心，32核心，甚至64核心，再或者是128GB内存甚至2TB内存，你用所谓的多核心的、高内存的服务器，只能增加你并发的数量。因为他本来就是考验的单核性能，根据我的测试，一个文档的编译，满载情况下差不多吃掉一个cpu+300MB的内存。
> > > > > 所以你要是追求所谓的速度，要目换高主频的CPU（这个是我知乎看texpage说的，也是一个做类似latex编译的服务），要目就是本地（理论来说本地编译应该还是要快一些的）
> > > > > 这种轻微的编译速度问题，基本忽略就好。如果你发现你在本地编译了20s，overleaf编译出现2分钟，这才是严重的bug。
> > > > 
> > > > 
> > > > 感谢回复。我在overleaf会员账号上编译这个文档也差不多要这么久，顶多快一两秒。 这么看来并没有参数可以调节编译速度，那我就继续这样使用了。
> > > 
> > > 
> > > 诶嘿，看起来像是个MMD的爱好者，还买了overleaf会员嘛哈哈哈，羡慕了（
> > > 补一嘴：overleaf官方编译的镜像是经过了调优的，所以有些东西社区版还不一定能编译好，但是官网可以，但是属实是用过就不想回来了。我之前也折腾过好久的overleaf搭建，后来还是选择用官网去了hhhh
> > 
> > 
> > 朋友的会员账号，他帮忙测试的。 官网最近似乎对免费用户的限制增加，对于120页的中文毕业论文已经很难编译成功了，所有要么开会员要么自建了。
> 
> 还是觉得overleaf的定价有点过高，9刀一个月 80多刀一年，已经超过国内大部分软件的订阅价格了，下次如果有机会给他们官方可以建议建议这个价格问题（

非常有用的建议。等你读研了读博了，你就知道overleaf对于你的重要性了哈哈。
