### ISSUE TITLE
How to Recover Files from a Local Deployment of Overleaf

### ISSUE THREAD

**Issue by codeor** [overleaf/overleaf#1221]
My local deployment of Overleaf has suddenly encountered a problem, specifically, my user information seems to have been lost, so I can't log in. Is there a way to directly copy the project out from the data directory of the docker container ? Thank you.

**Comment by mserranom** [comment]
If you've lost your admin credentials the best options for recovery is to create a new admin account following [these instructions](https://github.com/overleaf/overleaf/wiki/Creating-and-managing-users#creating-the-first-admin-user). Admins have access and can download any project in the instance.

**Comment by codeor** [comment]
Thank you.
