### ISSUE TITLE
Problems with config/variables.env when upgrading to 5.0.3CE

### ISSUE THREAD

**Issue by JayPi01** [overleaf/overleaf#1222]
## Steps to Reproduce

1. started overleaf via 'bin/start'
2. started upgrade process via 'bin/upgrade'
3. answered all questions with 'yes'
4. executed 'bin/rename-rc-vars'
5. answered 'yes' 
6. again 'bin/upgrade'
7. answered 'yes' to all questions
8. get error: `Rebranding from ShareLaTeX to Overleaf
  The 'TEXMFVAR' override is not needed since Server Pro/Overleaf CE version 3.2 (August 2022) and it conflicts with the rebranded paths.
  Please remove the following entry from your config/variables.env:
    TEXMFVAR=/var/lib/sharelatex/tmp/texmf-var`
9. executed 'bin/start' gives same error.
10. tried to run 'bin/up' with same error.

## Expected Behaviour

At least 'bin/up' should reread config/variables.env but it does not. Or am I wrong?

## Technical Info

* URL:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Signed in as:
* Project and/or file:

**Comment by das7pad** [comment]
As detailed in the error message, you need to edit your config and remove the conflicting entry manually, then use `bin/up` to bring up the instance again.

We do not want to delete entries from the users config in an automated fashion.

**Comment by JayPi01** [comment]
Sorry, forgot to mention that I edited and deleted the TEXMFVAR line. Step 8a. So bin/up ignores the deleted line.
