### ISSUE TITLE
error "/etc/my_init.d/500_check_db_access.sh failed with status 1"

### ISSUE THREAD

**Issue by lizhi10** [overleaf/overleaf#1224]
Hi!
I am trying to deploy Overleaf to my router which has an Intel N5105 processor installed OpenWRT.
Since N5105 does not support AVX which is necessary for Mongo 5.0, I modified lib/docker-compose.mongo.yml to use Mongo 4.4.
I also created config/docker-compose.override.yml file.

However, the deployment repeated  "/etc/my_init.d/500_check_db_access.sh failed with status 1" and failed.

The whole log is as follows. Any help will be appreciated.

Attaching to mongo, redis, sharelatex
redis       | 1:C 09 May 2024 16:19:04.438 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis       | 1:C 09 May 2024 16:19:04.438 # Redis version=6.2.14, bits=64, commit=00000000, modified=0, pid=1, just started
redis       | 1:C 09 May 2024 16:19:04.438 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis       | 1:M 09 May 2024 16:19:04.439 * monotonic clock: POSIX clock_gettime
redis       | 1:M 09 May 2024 16:19:04.439 * Running mode=standalone, port=6379.
redis       | 1:M 09 May 2024 16:19:04.439 # Server initialized
redis       | 1:M 09 May 2024 16:19:04.439 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis       | 1:M 09 May 2024 16:19:04.440 * Loading RDB produced by version 6.2.14
redis       | 1:M 09 May 2024 16:19:04.440 * RDB age 320 seconds
redis       | 1:M 09 May 2024 16:19:04.440 * RDB memory usage when created 0.77 Mb
redis       | 1:M 09 May 2024 16:19:04.440 # Done loading RDB, keys loaded: 0, keys expired: 0.
redis       | 1:M 09 May 2024 16:19:04.440 * DB loaded from disk: 0.000 seconds
redis       | 1:M 09 May 2024 16:19:04.440 * Ready to accept connections
mongo       | {"t":{"$date":"2024-05-09T16:19:12.746+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"127.0.0.1:58690","connectionId":11,"connectionCount":5}}
mongo       | {"t":{"$date":"2024-05-09T16:19:12.746+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn11","msg":"client metadata","attr":{"remote":"127.0.0.1:58690","client":"conn11","doc":{"application":{"name":"MongoDB Shell"},"driver":{"name":"MongoDB Internal Client","version":"4.4.29"},"os":{"type":"Linux","name":"Ubuntu","architecture":"x86_64","version":"20.04"}}}}
mongo       | {"t":{"$date":"2024-05-09T16:19:12.757+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn11","msg":"Connection ended","attr":{"remote":"127.0.0.1:58690","connectionId":11,"connectionCount":4}}
sharelatex  | *** Running /etc/my_init.d/000_check_for_old_bind_mounts_5.sh...
sharelatex  | *** Running /etc/my_init.d/000_check_for_old_env_vars_5.sh...
sharelatex  | *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
sharelatex  | *** Running /etc/my_init.d/100_generate_secrets.sh...
sharelatex  | generating random secrets
sharelatex  | *** Running /etc/my_init.d/100_make_overleaf_data_dirs.sh...
sharelatex  | *** Running /etc/my_init.d/100_restore_site_status.sh...
sharelatex  | *** Running /etc/my_init.d/100_set_docker_host_ipaddress.sh...
sharelatex  | *** Running /etc/my_init.d/10_syslog-ng.init...
sharelatex  | May  9 16:19:13 21c3951e6895 syslog-ng[80]: syslog-ng starting up; version='3.35.1'
sharelatex  | *** Running /etc/my_init.d/200_nginx_config_template.sh...
sharelatex  | Nginx: generating config file from template
sharelatex  | Checking Nginx config
sharelatex  | nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
sharelatex  | nginx: configuration file /etc/nginx/nginx.conf test is successful
sharelatex  | Nginx: reloading config
sharelatex  |  * Reloading nginx configuration nginx
sharelatex  |    ...done.
sharelatex  | *** Running /etc/my_init.d/300_delete_old_logs.sh...
sharelatex  | *** Running /etc/my_init.d/500_check_db_access.sh...
sharelatex  | Checking can connect to mongo and redis
sharelatex  | Using default settings from /overleaf/services/web/config/settings.defaults.js
sharelatex  | Using settings from /etc/overleaf/settings.js
sharelatex  | Set UV_THREADPOOL_SIZE=16
mongo       | {"t":{"$date":"2024-05-09T16:19:14.802+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.18.0.4:42362","connectionId":12,"connectionCount":5}}
mongo       | {"t":{"$date":"2024-05-09T16:19:14.807+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn12","msg":"client metadata","attr":{"remote":"172.18.0.4:42362","client":"conn12","doc":{"application":{"name":"web"},"driver":{"name":"nodejs|Mongoose","version":"4.17.1|6.12.0"},"platform":"Node.js v18.20.2, LE","os":{"name":"linux","architecture":"x64","version":"5.10.201","type":"Linux"}}}}
mongo       | {"t":{"$date":"2024-05-09T16:19:14.819+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.18.0.4:42374","connectionId":13,"connectionCount":6}}
mongo       | {"t":{"$date":"2024-05-09T16:19:14.820+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn13","msg":"client metadata","attr":{"remote":"172.18.0.4:42374","client":"conn13","doc":{"application":{"name":"web"},"driver":{"name":"nodejs|Mongoose","version":"4.17.1|6.12.0"},"platform":"Node.js v18.20.2, LE","os":{"name":"linux","architecture":"x64","version":"5.10.201","type":"Linux"}}}}
sharelatex  | The MongoDB server has version 4.4.29, but Overleaf requires at least version 5.0. Aborting.
mongo       | {"t":{"$date":"2024-05-09T16:19:14.833+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn13","msg":"Connection ended","attr":{"remote":"172.18.0.4:42374","connectionId":13,"connectionCount":5}}
mongo       | {"t":{"$date":"2024-05-09T16:19:14.833+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn12","msg":"Connection ended","attr":{"remote":"172.18.0.4:42362","connectionId":12,"connectionCount":4}}
sharelatex  | *** /etc/my_init.d/500_check_db_access.sh failed with status 1
sharelatex  | 
sharelatex  | *** Killing all processes...
sharelatex  | May  9 16:19:14 21c3951e6895 syslog-ng[80]: syslog-ng shutting down; version='3.35.1'
sharelatex exited with code 1

**Comment by andreas-schliebitz** [comment]
> The MongoDB server has version 4.4.29, but Overleaf requires at least version 5.0

Like myself, you first have to update to MongoDB Version 5.0. 

After doing so, I then had to force `mongod` to:

1. Bind to IPv6 localhost using `mongod --ipv6`
2. Enable support for transactions using a [single node replica set](https://www.mongodb.com/docs/manual/tutorial/convert-standalone-to-replica-set/) by also adding `--replSet rs0`.

I also made sure to explicitly set the `hostname` for my MongoDB container (in my case `overleaf_mongodb`). Finally I had to initiate the replica set by running:

```bash
docker compose exec -it overleaf_mongodb /bin/bash -c 'echo "rs.initiate()" | mongosh'
```

If you don't set the `hostname` the `rs.initiate()` will create a replica set using the container ID, which will change, if the container is removed and restarted.

**Comment by andreas-schliebitz** [comment]
Just noticed that you cannot run MongoDB 5.0.

I'll leave my comment as the error may be quite frequent for users migrating to Overleaf Version 5.

**Comment by lizhi10** [comment]
> Just noticed that you cannot run MongoDB 5.0.
> 
> I'll leave my comment as the error may be quite frequent for users migrating to Overleaf Version 5.

Thank you for you quick answer. Your comment lets me consider runing Overleaf 4.2 instead of trying to deploy Overleaf 5. However, I think it is better to run Overleaf on some low-energy-comsuption devices such as Rasberry Pi so that one can TeX any time, any device with a very low environmental burden.
