### ISSUE TITLE
Alternatives to MongoDB 5.0?

### ISSUE THREAD

**Issue by lizhi10** [overleaf/overleaf#1226]
Hi!
Overleaf is such a good tool to help me work. However, I am wondering if the developers could provide alternatives to MongoDB 5.0. As I have learned, MongoDB 5.0 requires AVX support (x86) or ARMv8.2-A (arm) cpu. This prevents me to deploy Overleaf on my devices like an NAS (I have a nas with Intel N5105), router (Intel J4125) or my little arm-based computer box (like Rasberry Pi4).
It is fun and useful to make Overleaf run on a local and low-engery-comsuption server. 
Thank you!

**Comment by Wurzelmann** [comment]
+1, postgres would be great for example.

**Comment by LECOQQ** [comment]
+1, been a while since i've wanted overleaf on my mariadb:). That would be a cool feature to be able to chose freely (even if we need to tweak some settings by ourselves)!

**Comment by das7pad** [comment]
Hello,

We are not considering moving away from MongoDB in the near future.
The source of Overleaf Community Edition is open. Feel free to take this on as an exercise for your next weekend(s) :wink: 

Greetings,
Jakob

**Comment by qiankemeng** [comment]
> Overleaf is such a good tool to help me work. However, I am wondering if the developers coul

same device
