### ISSUE TITLE
Recreating Sharelatex after Changing Settings

### ISSUE THREAD

**Issue by jn9702** [overleaf/overleaf#1227]
## Steps to Reproduce

1. Change some settings (like SMTP)
2. ./bin/docker-compose down
3. ./bin/up -d

## Expected Behaviour

If some settings are changed, the container should stay the same? Or not?

## Observed Behaviour

Container Sharelatex has been recreated and everything is refreshed to default (with TexLive 2023 + minimum packages).

## Context

So that I need to reinstall all the packages and update TexLive.

## Technical Info

Ubuntu 22.04 LTS + Toolbox 5.0.3

**Comment by das7pad** [comment]
Hi there,

The Overleaf application uses environment variables for configuration. Updating the environment variables of a Docker container requires recreating it. When recreating a Docker container, any changes to ephemeral mounts are discarded. You can take a look at [our documentation](https://github.com/overleaf/toolkit/blob/master/doc/ce-upgrading-texlive.md#saving-your-changes) for persisting the TeXLive changes into a new image.

Greeting,
Jakob
