### ISSUE TITLE
Patch files for 5.0.4 not available

### ISSUE THREAD

**Issue by MonsterDruide1** [overleaf/overleaf#1230]
## Steps to Reproduce

1. Check the current version in the [Changelog wiki](https://github.com/overleaf/overleaf/wiki/Release-Notes-5.x.x#server-pro-504) or Docker hub
2. Notice that it's version 5.0.4
3. Check the patch files that usually contain changes for the updates: [server-ce/hotfix](https://github.com/overleaf/overleaf/tree/d56f5a303087f0ad44f23870de4a5fb455997fdb/server-ce/hotfix)
4. Folder with `5.0.4` is missing.

According to the docker build logs, it should exist with at least four files though: [Image Layers](https://hub.docker.com/layers/sharelatex/sharelatex/5.0.4/images/sha256-429f6c4c02d5028172499aea347269220fb3505cbba2680f5c981057ffa59316)
=> `pr_18433.patch`, `pr_18393.patch`, `pr_18444.patch`, and a `Dockerfile` containing `npm install/uninstall/audit`

## Expected Behaviour
A folder named `5.0.4` with the expected files should be listed in this repo.

## Observed Behaviour
The folder and files are missing.

## Context
We run a custom version of Overleaf that requires manually patching in the hotfix changes, as we do not make use of the standard Docker build-chain. For this reason, we cannot use the Docker-Hub-Release(s), but need to build it directly from source.

## Technical Info
Looking at the [current commit history](https://github.com/overleaf/overleaf/commits/main/), the last commit was done 5 days ago. Given the previous commit intervals, which are more regularly without such large "gaps", I would assume that the [Copybot](https://github.com/google/copybara) is broken, and therefore missed copying the patch files that should've been added ... yesterday?

**Comment by mserranom** [comment]
Patch files are now in the master branch: https://github.com/overleaf/overleaf/tree/main/server-ce/hotfix/5.0.4
