### ISSUE TITLE
redis 5 → 6.2: Container fails to start with `Fatal: Can't initialize Background Jobs.`

### ISSUE THREAD

**Issue by paulmenzel** [overleaf/overleaf#1240]
From [*Release Notes 4.x.x*](https://github.com/overleaf/overleaf/wiki/Release-Notes--4.x.x#server-pro-401):

> We’ve also updated the version of Redis to 6.2. This change requires no action other than updating the image version.

Doing this, the Redis container failed to start with:

    1:C 13 Jun 2024 06:50:44.289 # Redis version=6.2.14, bits=64, commit=00000000, modified=0, pid=1, just started
    1:C 13 Jun 2024 06:50:44.289 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
    1:M 13 Jun 2024 06:50:44.290 * monotonic clock: POSIX clock_gettime
    1:M 13 Jun 2024 06:50:44.290 * Running mode=standalone, port=6379.
    1:M 13 Jun 2024 06:50:44.290 # Server initialized
    1:M 13 Jun 2024 06:50:44.290 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
    1:M 13 Jun 2024 06:50:44.290 # Fatal: Can't initialize Background Jobs.

It’d be great to mention the warning in the release notes – no idea, if present before. No idea, what is wrong with the background jobs.

**Comment by mlevans0** [comment]
This may be related to the version of Docker currently in use. Please see https://github.com/overleaf/overleaf/wiki/Troubleshooting#upgrading-to-redis-62-results-in-a-restart-loop

**Comment by paulmenzel** [comment]
Thank you for the confirmation. I should have added *overleaf* to the key words for the search engine.

Upgrading Docker in our Alpine virtual machine is not an easy task, so we are going to stay with Redis 6.2.11 for the moment. Maybe the troubleshooting guide could be referenced in the release notes, and the Redis upstream issue be mentioned in the troubleshooting guide.

**Comment by paulmenzel** [comment]
Thank you for your instance reaction.
