### ISSUE TITLE
Accessing the Javascript object of codemirror 

### ISSUE THREAD

**Issue by uneetsingh** [overleaf/overleaf#1241]
I had made a chrome plugin sometimes back that would access the codemirror's object using window._ide.$scope.editor.sharejs_doc.cm6.view. The code has been restructured it seems and I can't find where the cm6 object is. 

Can anyone help me find it?

**Comment by das7pad** [comment]
Hello,

You can access the CodeMirror `EditorView` via `window.overleaf.unstable.store.get('editor.view')`. Please note that this is not a stable API and we may change it in the future without notice.

May I ask what your browser plugin does?

Greetings,
Jakob
