### ISSUE TITLE
Fresh CE install, new user creation fails

### ISSUE THREAD

**Issue by d1nuc0m** [overleaf/overleaf#1244]
## Steps to Reproduce

1. Installed Overleaf CE using toolkit
2. Create admin account
3. Try to add a new user

## Expected Behaviour

* Registration email arrives
* The new user is able to set a password and login

## Observed Behaviour

* Registration email arrives
* Included link redirects to login, the new user is not able to register

## Context
I was trying to setup a local Overleaf CE instance to try simultaneous editing

## Technical Info
Using:

- nginx:1.19-alpine
- sharelatex/sharelatex:5.0.6 (modified with texlive-full as per docs)
- redis:6.2
- mongo:5.0

## Analysis
The link included in the email is broken, is like
https://overleaf.example.com//user/activate?token=(token)&user_id=(uid)

Note the double //

**Comment by rinkp** [comment]
Maybe you have already checked this, but are you sure your `OVERLEAF_SITE_URL` does not end with a `/`? If that is the case, you will see two slashes:

https://github.com/overleaf/overleaf/blob/7212c16dde66950b1a5456e98bba1effbe6aebf1/services/web/app/src/Features/User/UserRegistrationHandler.js#L114
