### ISSUE TITLE
\cite{} environment autocompletion does not work

### ISSUE THREAD

**Issue by giannibi** [overleaf/overleaf#1248]
Latest community edition installed via the toolkit.
Autocompletion works for all environments except \cite{}.
Relevant BibTeX files are free of syntax errors and duplicate keys. Even a one-entry .bib does not seem to work.
Same behaviour with either bibtex or biblatex.
The js script handling autocompletion is there (as shown by the browser inspector) but does not seem to get invoked. Reloading the page does not help.
Autocompletion on www.overleaf.com works just right on the same projects with a free account.

## Expected Behaviour

Inside a \cite{} environment, bib entries should be shown for autocompletion.

## Observed Behaviour

Inside a \cite{} environment, autocompletion is not triggered.

## Technical Info

* URL: https://overleaf.control.diism.unisi.it
* Browser Name and version: any
* Operating System and version (desktop or mobile): any
* Signed in as:
* Project and/or file:

**Comment by lukad01** [comment]
Is there an update on this problem?

**Comment by ilmatematico** [comment]
it seems this feature is not available in the community edition...

https://github.com/overleaf/overleaf/issues/646

**Comment by das7pad** [comment]
Hello,

Indeed, the reference search feature is not part of the Overleaf Community Edition. In case you are interested in using it on-premise, we include it in our [Server Pro offering](https://www.overleaf.com/for/enterprises).

Greetings,
Jakob

**Comment by nyomen** [comment]
Hey deciders to take out features for more profit:
Would you have than the decency to update your docu!?

https://de.overleaf.com/learn/how-to/How_to_search_for_references_in_an_Overleaf_project

Its pretty specific with a video showing that /cite was working on the community edition and you took it out.

![grafik](https://github.com/user-attachments/assets/9a8fb1e8-aba5-4a64-99d5-5247c6824486)

And only the "Advanced Reference Search" was a premium feature.

So maybe, spend less dev time on **** up your users by taking away features that alrdy existed and monetize them, and spend more dev time to implement actual new beneficial features that you can monetize.

Would be great if the your car is not getting an update and your steering wheel is patched out, right?
