### ISSUE TITLE
Does Overleaf not support using a remote mongodb instance?

### ISSUE THREAD

**Issue by scwang98** [overleaf/overleaf#1249]
## Steps to Reproduce

1. Specify MONGO_URL as a remote mongodb URL, such as mongodb://x.x.x.x:27017/sharelatex
2. Specify MONGO_ENABLED as false
3.

## Expected Behaviour

Overleaf CE should use remote mongodb directly.

## Observed Behaviour

Does Overleaf not support using a remote mongodb instance? It seems that Overleaf is still looking for the local mongo docker container.

sharelatex  | Cannot connect to mongodb
sharelatex  | MongooseServerSelectionError: getaddrinfo ENOTFOUND mongo
sharelatex  |     at Connection.openUri (/overleaf/node_modules/mongoose/lib/connection.js:825:32)
sharelatex  |     at /overleaf/node_modules/mongoose/lib/index.js:414:10
sharelatex  |     at /overleaf/node_modules/mongoose/lib/helpers/promiseOrCallback.js:41:5
sharelatex  |     at new Promise (<anonymous>)
sharelatex  |     at promiseOrCallback (/overleaf/node_modules/mongoose/lib/helpers/promiseOrCallback.js:40:10)
sharelatex  |     at Mongoose._promiseOrCallback (/overleaf/node_modules/mongoose/lib/index.js:1288:10)
sharelatex  |     at Mongoose.connect (/overleaf/node_modules/mongoose/lib/index.js:413:20)
sharelatex  |     at Object.<anonymous> (/overleaf/services/web/app/src/infrastructure/Mongoose.js:19:36)
sharelatex  |     at Module._compile (node:internal/modules/cjs/loader:1364:14)
sharelatex  |     at Module._extensions..js (node:internal/modules/cjs/loader:1422:10) {
sharelatex  |   reason: TopologyDescription {
sharelatex  |     type: 'ReplicaSetNoPrimary',
sharelatex  |     servers: Map(1) { 'mongo:27017' => [ServerDescription] },
sharelatex  |     stale: false,
sharelatex  |     compatible: true,
sharelatex  |     heartbeatFrequencyMS: 10000,
sharelatex  |     localThresholdMS: 15,
sharelatex  |     setName: 'overleaf',
sharelatex  |     maxElectionId: new ObjectId("7fffffff0000000000000001"),
sharelatex  |     maxSetVersion: 1,
sharelatex  |     commonWireVersion: 0,
sharelatex  |     logicalSessionTimeoutMinutes: null
sharelatex  |   },
sharelatex  |   code: undefined
sharelatex  | }
sharelatex  | *** /etc/my_init.d/500_check_db_access.sh failed with status 1

## Context

The data on the server where Overleaf is deployed is not safe and data may be lost. I hope the database can be directly deployed on another server with safe data, such as our NAS.

## Technical Info

* URL:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Signed in as:
* Project and/or file:

**Comment by scwang98** [comment]
Should I use MongoDB's Replica Set to back up my data?
Is there a better way?

**Comment by davrot** [comment]
In my installation ( https://github.com/davrot/overleaf )  I get MongoDB from a different independent container via IP. 

Important is that the database is initialized. I do this via a health check in the mongo container

      test: "mongosh --quiet --eval 'rs.hello().setName ? rs.hello().setName : rs.initiate({_id: \"overleaf\",members:[{_id: 0, host:\"overleafmongo:27017\"}]})'"
      
It is also important that the MongoDB has the 
command: "--replSet overleaf"
setting. 

For the overleaf container, I use:
      OVERLEAF_MONGO_URL: "mongodb://overleafmongo/sharelatex"
And I can ping the overleafmongo from inside the overleaf container.

And mind the involved firewalls. :-)
      
Does this help?

**Comment by scwang98** [comment]
> In my installation ( https://github.com/davrot/overleaf ) I get MongoDB from a different independent container via IP.
> 
> Important is that the database is initialized. I do this via a health check in the mongo container
> 
> ```
>   test: "mongosh --quiet --eval 'rs.hello().setName ? rs.hello().setName : rs.initiate({_id: \"overleaf\",members:[{_id: 0, host:\"overleafmongo:27017\"}]})'"
> ```
> 
> It is also important that the MongoDB has the command: "--replSet overleaf" setting.
> 
> For the overleaf container, I use: OVERLEAF_MONGO_URL: "mongodb://overleafmongo/sharelatex" And I can ping the overleafmongo from inside the overleaf container.
> 
> And mind the involved firewalls. :-)
> 
> Does this help?

@davrot Thanks! I tried your method but it doesn't work. The mongo and overleaf containers are still on the same host, but I want them to be on different hosts

**Comment by davrot** [comment]
Are you sure that you can reach the external mongodb from inside the overleaf container? (XXXXXXXXXXXX is the name of your external mongodb server, YYY.YYY.YYY.YYY is the ip of the external mongodb server)

On the docker host:
docker exec -it overleaf bash

Inside the container (since there is not ping):
ssh -p 27017 XXXXXXXXXXXX

If you get something like this, then it can reach the mongo db:
kex_exchange_identification: Connection closed by remote host
Connection closed by YYY.YYY.YYY.YYY port 27017


On the host for testing if the host can reach the external mongodb:
telnet YYY.YYY.YYY.YYY 27017

**Comment by scwang98** [comment]
> Are you sure that you can reach the external mongodb from inside the overleaf container? (XXXXXXXXXXXX is the name of your external mongodb server, YYY.YYY.YYY.YYY is the ip of the external mongodb server)
> 
> On the docker host: docker exec -it overleaf bash
> 
> Inside the container (since there is not ping): ssh -p 27017 XXXXXXXXXXXX
> 
> If you get something like this, then it can reach the mongo db: kex_exchange_identification: Connection closed by remote host Connection closed by YYY.YYY.YYY.YYY port 27017
> 
> On the host for testing if the host can reach the external mongodb: telnet YYY.YYY.YYY.YYY 27017

Yes, I got messages in the overleaf container as follows:

scwang@dell:~$ docker exec -it sharelatex /bin/bash
root@c878c9b06a5d:/overleaf# ssh -p 27017 scwang@10.102.104.7
kex_exchange_identification: Connection closed by remote host
Connection closed by 10.102.104.7 port 27017

**Comment by scwang98** [comment]
> Are you sure that you can reach the external mongodb from inside the overleaf container? (XXXXXXXXXXXX is the name of your external mongodb server, YYY.YYY.YYY.YYY is the ip of the external mongodb server)
> 
> On the docker host: docker exec -it overleaf bash
> 
> Inside the container (since there is not ping): ssh -p 27017 XXXXXXXXXXXX
> 
> If you get something like this, then it can reach the mongo db: kex_exchange_identification: Connection closed by remote host Connection closed by YYY.YYY.YYY.YYY port 27017
> 
> On the host for testing if the host can reach the external mongodb: telnet YYY.YYY.YYY.YYY 27017


Thank you very very very much for your reply!!

I found the solution!!!

It seems that this problem is related to the replica set. Just add the directConnection=true parameter to the mongodb URL, for example, mongodb://xxx:xxxx@x.x.x.x/sharelatex?directConnection=true

**Comment by scwang98** [comment]
This should be a very low-level question, but because I am not familiar enough with mongodb, it has troubled me for a whole day.
