### ISSUE TITLE
Toggle area of review panel and review comment overlap.

### ISSUE THREAD

**Issue by fbuetler** [overleaf/overleaf#1250]
## Steps to Reproduce

* Create a document and add a review comment.
* Open the "review comments panel" on the right.
* In the "review comment panel", change to the "Overview" (as opposed to "Current File")
* Try to collapse a review comment by clicking on the ">" symbol.

## Expected Behaviour

The review comment should be collapsed

## Observed Behaviour

The "review comment panel" is collapsed. The review comment can still be collapsed by moving the mouse more to the right.

## Technical Info

* Browser Name and version: Mozilla Firefox 128.0
* Operating System and version (desktop or mobile): Arch Linux 6.6.39-1-lts (desktop)

## Analysis

The clicking area of the "toggle review comment panel" and "toggle review comment" overlaps. See attached image.
![overleaf_overlap](https://github.com/user-attachments/assets/3887d3cf-43a9-465c-ab4f-9715fad52d50)

Probably need to move the ">" a bit more to the right.

Related code:
https://github.com/overleaf/overleaf/blob/523e340a0d644b471bbe7495f90d7aab767be289/services/web/frontend/js/features/source-editor/components/review-panel/overview-file.tsx#L43-L47
https://github.com/overleaf/overleaf/blob/523e340a0d644b471bbe7495f90d7aab767be289/services/web/frontend/stylesheets/app/editor/review-panel.less#L738

https://github.com/overleaf/overleaf/blob/523e340a0d644b471bbe7495f90d7aab767be289/services/web/frontend/stylesheets/app/editor/review-panel.less#L182
https://github.com/overleaf/overleaf/blob/523e340a0d644b471bbe7495f90d7aab767be289/services/web/frontend/js/features/source-editor/components/review-panel/toggler.tsx#L15-L21

**Comment by das7pad** [comment]
Hello @fbuetler,

Thank you for the detailed bug report and code suggestion. The Review feature is not available in Overleaf Community Edition. For overleaf.com questions or bug reports it's better to use the contact form: https://www.overleaf.com/contact.

With that said, we are aware of a few minor UI issues with the layering of the review panel and this ticket has been added to the list of bugs to fix in the future.

Thanks again for your time to report this issue.

Greetings,
Jakob
