### ISSUE TITLE
False positive linter when using `\path` (`url` package)

### ISSUE THREAD

**Issue by rinkp** [overleaf/overleaf#1260]
This bug is applicable to both overleaf.com and to the community edition. 

## Steps to Reproduce

Recreate the [following example](https://www.overleaf.com/read/vnrksjpxjzqh#af4168) that contains usage of the `path` command from the [`url` package](https://ctan.org/pkg/url):

```tex
\documentclass{article}
\usepackage{url}

\begin{document}

This is a valid path: \path{http://google.com/?$filter=}

In fact, this would not work: \path{http://google.com/?\$filter=}. That is the advantage of \texttt{path} over using \texttt{texttt}: \texttt{test\$f}.

\end{document}
```

## Expected Behaviour

I expect the overleaf linter to not show any errors since this is valid syntax according to [the documentation](https://ftp.snt.utwente.nl/pub/software/tex/macros/latex/contrib/url/url.pdf). 

The reason for this is that `\path` is a command which was defined by [`url.sty`](https://ftp.snt.utwente.nl/pub/software/tex/macros/latex/contrib/url/url.sty), line 204:

```tex
% picTeX defines \path, so declare it optionally:
\@ifundefined{path}{\DeclareUrlCommand\path{\urlstyle{tt}}}{}
```

With these commands, the restrictions below apply. Note that we have not violated the unbalanced braces provision; instead, we have an unbalanced number of $ signs, which is not banned and is correctly parsed by LaTeX, pdfLaTeX, XeLaTeX and LuaLaTeX. 

> The argument must not contain unbalanced braces. If used in the argument to another command, the \url argument cannot contain any “%”, “#”, or “^^”, or end with “\”.

## Observed Behaviour

The linter raises two errors: `unclosed $ found at close group }` and `unexpected close group } after $`. When compiling, no errors are created by pdfLaTeX.

## Context

The issue affects me in describing paths that contain arguments containing dollar signs such as `$filter`. Ideally, all commands that have been declared using `DeclareUrlCommand` accept an unbalanced number of $ signs as argument.

## Technical Info

* URL: [https://www.overleaf.com/read/vnrksjpxjzqh](https://www.overleaf.com/read/vnrksjpxjzqh)
* Browser Name and version: Firefox 115.13.0 ESR
* Operating System and version (desktop or mobile): N/A
* Signed in as: Overleaf premium, but also happens in community edition
* Project and/or file: `66a7d06bcb19f14b265bd573`

## Analysis

In the readme of the linter, I see that certain commands such as `url` have an exception for unbalanced arguments. `path` does not appear in this list.

https://github.com/overleaf/overleaf/blob/7212c16dde66950b1a5456e98bba1effbe6aebf1/services/web/frontend/js/features/source-editor/languages/latex/linter/README.md?plain=1#L90

The same issue actually appears when using the 1991 package `path`, which allows the syntax below. Therefore, I do not think a fix will impact users of `path`.

```latex
\path|http://google?$filter|
```

**Comment by dmackinnon1** [comment]
The Overleaf code check is not a full LaTeX parser, and will raise false positives for less-common syntax. There are a few different options for disabling the code check when it is raising misleading or distracting errors as described here: https://www.overleaf.com/learn/how-to/Code_Check.  The most localized option is to turn off the validation around the specific code chunk that is causing trouble.

```
%%begin novalidate
This part is not checked
%%end novalidate
```
