### ISSUE TITLE
texpage.com is misusing the opensource code and violating the license

### ISSUE THREAD

**Issue by NicolaDaj** [overleaf/overleaf#1261]
<https://texpage.com> is misusing the code in this repo and violating the license.

The product is based on the open-source code in this repo without respecting the license.

The founder is here: @PeterMu .

**Comment by VladimirLi683** [comment]
To be honest, providing feedback on this kind of issue requires the related code. 
If unable to provide it, the whole thing becomes meaningless.

**Comment by NicolaDaj** [comment]
> To be honest, providing feedback on this kind of issue requires the related code. If unable to provide it, the whole thing becomes meaningless.

I've let the overleaf legal team be aware of the issue.

Yes, of course, I have their code.

STOP the Chinese Plagiarist.

**Comment by jdleesmiller** [comment]
Thank you for raising this concern. Digital Science takes seriously the enforcement of its intellectual property rights. If you believe you have evidence of infringement, please contact [copyright@digital-science.com](mailto:copyright@digital-science.com).

**Comment by PeterMu** [comment]
Thanks for reviewing and marking this issue as resolved.

TeXPage has been built independently from scratch, and it does not include any code from Overleaf. We respect Overleaf and the open‑source community and always comply with software licenses.

If anyone still has questions, feel free to reach out to us at support@texpage.com.

— TeXPage Team
