### ISSUE TITLE
Unable to compile on overleaf

### ISSUE THREAD

**Issue by rahatzamancse** [overleaf/overleaf#1264]
## Steps to Reproduce

1. Start the overleaf docker server. 
2. Create an example project
3. Compile the example project

## Expected Behaviour

Compiles and shows the PDF

## Observed Behaviour

**Server Error**: Sorry, something went wrong and your project could not be compiled. Please try again in a few moments.

## Context

I used this docker-compose.yaml to boot up overleaf:

```yaml
services:
    sharelatex:
        restart: always
        image: sharelatex/sharelatex:5.1.1
        container_name: sharelatex
        ports:
            - 8055:80
        volumes:
            - /home/insane/overleaf-toolkit/data/overleaf:/var/lib/overleaf
            - /var/run/docker.sock:/var/run/docker.sock
        env_file: .env
        stop_grace_period: 60s
```

The .env file is below:

```bash
PROJECT_NAME=overleaf
OVERLEAF_APP_NAME="Our Overleaf Instance"
ENABLED_LINKED_FILE_TYPES=project_file,project_output_file

EXTERNAL_AUTH=none

# Sharelatex container
# Uncomment the OVERLEAF_IMAGE_NAME variable to use a user-defined image.
# OVERLEAF_IMAGE_NAME=sharelatex/sharelatex
OVERLEAF_DATA_PATH=/home/insane/overleaf-toolkit/data/overleaf
SERVER_PRO=false
OVERLEAF_LISTEN_IP=127.0.0.1
OVERLEAF_PORT=8055

# Sibling Containers
SIBLING_CONTAINERS_ENABLED=true
DOCKER_SOCKET_PATH=/var/run/docker.sock

# Mongo configuration
MONGO_ENABLED=false
MONGO_DATA_PATH=data/mongo
MONGO_IMAGE=mongo
MONGO_VERSION=6.0
MONGO_VERSION_MAJOR=6
MONGO_URL=mongodb://10.0.0.10/overleaf?directConnection=true
OVERLEAF_MONGO_URL=mongodb://10.0.0.10/overleaf?directConnection=true
MONGOSH=mongosh

# Redis configuration
REDIS_ENABLED=false
REDIS_DATA_PATH=data/redis
REDIS_IMAGE=redis:6.2
REDIS_AOF_PERSISTENCE=true
REDIS_HOST=10.0.0.10
REDIS_PORT=6379
OVERLEAF_REDIS_HOST=10.0.0.10

# Git-bridge configuration (Server Pro only)
GIT_BRIDGE_ENABLED=false
GIT_BRIDGE_DATA_PATH=data/git-bridge

# TLS proxy configuration (optional)
# See documentation in doc/tls-proxy.md
NGINX_ENABLED=false
NGINX_CONFIG_PATH=config/nginx/nginx.conf
NGINX_HTTP_PORT=80
# Replace these IP addresses with the external IP address of your host
NGINX_HTTP_LISTEN_IP=127.0.1.1
NGINX_TLS_LISTEN_IP=127.0.1.1
TLS_PRIVATE_KEY_PATH=config/nginx/certs/overleaf_key.pem
TLS_CERTIFICATE_PATH=config/nginx/certs/overleaf_certificate.pem
TLS_PORT=443


# Enables Thumbnail generation using ImageMagick
ENABLE_CONVERSIONS=true

# Disables email confirmation requirement
EMAIL_CONFIRMATION_DISABLED=true

V1_HISTORY_URL=http://10.0.0.10:3100/api

TZ=America/Devner
DOCKER_RUNNER='true'


SANDBOXED_COMPILES='true'
SANDBOXED_COMPILES_SIBLING_CONTAINERS='true'
SANDBOXED_COMPILES_HOST_DIR="${OVERLEAF_DATA_PATH}/data/compiles"
SYNCTEX_BIN_HOST_PATH="${OVERLEAF_DATA_PATH}/bin/synctex"
            


# Other variables might be needed for the configuration of the containers.
IMAGE=sharelatex/sharelatex:5.1.1
IMAGE_VERSION=5.1.1
IMAGE_VERSION_MAJOR=5
IMAGE_VERSION_MINOR=1
IMAGE_VERSION_PATCH=1


OVERLEAF_IN_CONTAINER_DATA_PATH=/var/lib/overleaf
RC_DEBUG=true

SCRIPT_DIR=/home/insane/overleaf-toolkit/bin
SCRIPT_PATH=/home/insane/overleaf-toolkit/bin/docker-compose
TOOLKIT_ROOT=/home/insane/overleaf-toolkit
```

MongoDB and Redis are running on a another local machine at local IP 10.0.0.10

## Technical Info

Hitting compile button sends a post request, and get "Our staff are probably looking into this, but if it continues, please check our status page at..." from the server.

* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): EndeavorOS

## Analysis

So I tried to run the overleaf using the Overleaf-toolkit with the remote MongoDB and redis servers. And it worked! It compiles just fine. Remember that I am still using the same MongoDB database and redis server. It's just that I am starting the overleaf container with `./bin/up`. I also modified the configs to disable MongoDB and Redis.

**Comment by das7pad** [comment]
Hello @rahatzamancse,

The Sandboxed Compiles feature is not available in Overleaf Community Edition. You seem to be using the Overleaf Toolkit rendering of it's docker-compose files with `SIBLING_CONTAINERS_ENABLED=true`, which will not work with Community Edition. I recommend going back to the stock Overleaf Toolkit docker-compose setup.
In case you are interested in using Sandboxed Compiles as available in Overleaf Server Pro, please reach out to our sales team at https://www.overleaf.com/for/contact-sales.

Greetings,
Jakob
