### ISSUE TITLE
Ignore Files from Overleaf Sync to GitHub

### ISSUE THREAD

**Issue by rafisics** [overleaf/overleaf#1266]
I like to collaborate on a GitHub project from Overleaf. Is it possible to ignore some specific files so that they don't get uploaded/synced from Overleaf to GitHub and vice versa?

For example, I have two files named `main.tex` and `test.tex` in my Overleaf project. I want to sync only the file `main.tex` to Github, not the file `test.tex`. I  tried using a `.gitignore` file to do it. But it seems `.gitignore` doesn't work in Overleaf!

What can be done in such a situation?

**Comment by das7pad** [comment]
Hello @rafisics,

The GitHub integration is not available in Overleaf Community Edition. For overleaf.com questions it's better to use the contact form: https://www.overleaf.com/contact.

Greetings,
Jakob
