### ISSUE TITLE
Can not start normally at all!

### ISSUE THREAD

**Issue by Cufoon** [overleaf/overleaf#1268]
Whether I use the compose.yaml file I wrote myself or the toolkit, I cannot start and use it normally. I have gone through all the issues in the two repositories and tried all the solutions, but all failed. Please tell me what I should do to get this project up and running?

https://github.com/overleaf/toolkit/issues/289

https://github.com/overleaf/overleaf/issues/1263

**Comment by das7pad** [comment]
Hello,

I've commented on https://github.com/overleaf/toolkit/issues/289. Please refrain from opening duplicate tickets. Also please note that Overleaf Community Edition is community supported. Our Server Pro offering comes with extra features and commercial email-based support. See https://www.overleaf.com/for/enterprises/features for more details about Server Pro and how to 
buy a license.

Greetings,
Jakob
