### ISSUE TITLE
PDF Rendering Error when compile mode is normal

### ISSUE THREAD

**Issue by MjdMahasneh** [overleaf/overleaf#1274]
**PDF Rendering Error with "Normal" Mode Compilation**

**PDF Rendering Error** 
I encounter the following error only when compiling my project in "Normal" mode:

PDF Rendering Error Something went wrong while rendering this PDF. Please try recompiling the project from scratch, and if that doesn’t help, follow our [troubleshooting guide](https://www.overleaf.com/learn/how-to/Resolving_access%2C_loading%2C_and_display_problems).

We’ve recently migrated PDF downloads to a new domain. Something might be blocking your browser from accessing that new domain, compiles.overleafusercontent.com. This could be caused by network blocking or a strict browser plugin rule. Please follow our [troubleshooting guide](https://www.overleaf.com/learn/how-to/Resolving_access%2C_loading%2C_and_display_problems).

Steps I’ve tried:
- Cleared cookies and cache
- Used different browsers
- Restarted browsers and PC
- Checked for plugin interference
- Compiled from scratch

This issue occurs with **all my projects**, not just one. All projects compiled without issues this morning, and nothing changed in the project before the error occurred.

**Comment by dmackinnon1** [comment]
If you are having trouble with your account on overleaf.com, please use the contact form https://www.overleaf.com/contact to get in touch with Overleaf support.  Issues in this repository are meant for reports with the open source project, not for support requests with overleaf.com.  Please [see here](https://www.overleaf.com/learn/how-to/User_Support_Policy) to learn more about the support we offer for the cloud service.

**Comment by MjdMahasneh** [comment]
> If you are having trouble with your account on overleaf.com, please use the contact form https://www.overleaf.com/contact to get in touch with Overleaf support. Issues in this repository are meant for reports with the open source project, not for support requests with overleaf.com. Please [see here](https://www.overleaf.com/learn/how-to/User_Support_Policy) to learn more about the support we offer for the cloud service.

Apologies, thanks for directing me.
