### ISSUE TITLE
Unhinted fonts on web front-end impacts legibility and readability

### ISSUE THREAD

**Issue by vitorsr** [overleaf/overleaf#1276]
Long-term Overleaf user. Usually I contact support about issues but this is somewhat technical and hard to communicate.

The fonts on the web front-end are almost all unhinted which hinders legibility and readability - mostly on Windows and some FreeType configurations.

The fix is easy - serve hinted fonts.

The Noto project releases hinted variations. Here is Noto Sans Regular:

<https://notofonts.github.io/#:~:text=NotoSans%2DRegular.ttf%20(621.5%20kB)>

To see if a font is hinted or not, perform QA on a Windows system with Scale set to 100% (96 dpi). Fonts should not be blurry.

Optionally, you can check if the following TrueType tables are present using [ttx](https://fonttools.readthedocs.io/en/latest/ttx.html#dump-options): **cvt**, **fpgm**, gasp, prep.

```
$ ttx -l NotoSans-Regular.ttf
Listing table info for "NotoSans-Regular.ttf":
    tag     checksum    length    offset
    ----  ----------  --------  --------
    GDEF  0xA931BCA7      1124       284
    GPOS  0x541B948F     86506      1408
    GSUB  0xA08C60BE     11960     87916
    OS/2  0x8E158609        96     99876
    cmap  0xBB2E67AF     12760     99972
    cvt   0x3E0E1B37       300    617348
    fpgm  0x622F0B83      3596    617648
    gasp  0x00000010         8    617340
    glyf  0x31A06A64    428798    112732
    head  0x2830BBE0        54    541532
    hhea  0x0CB31A9B        36    541588
    hmtx  0x6A198E4F     15536    541624
    loca  0x35B04012     15540    557160
    maxp  0x11FD1075        32    572700
    name  0xA9D4C8CE      1568    572732
    post  0xD2D96603     43040    574300
    prep  0x447EC6B9       261    621244
```

Needless to say this only applies to TrueType fonts. On Windows CFF fonts are rendered in grayscale antialiasing only.

If no hinted version is found, it is easy to generate hinting instructions using [ttfautohint](https://freetype.org/ttfautohint/index.html).

In addition, even better would be to query if the user has them before using the served asset. This gives the user some control by using local files they installed on their platform.

Here is how that looks for the Noto Sans stylesheet ([overleaf/services/web/frontend/fonts/noto-sans.css](https://github.com/overleaf/overleaf/blob/4c0c341fe124e648d14f30b203d809d28676754f/services/web/frontend/fonts/noto-sans.css)):

```diff
7c7,8
<   src: url('noto-sans/NotoSans-Regular.woff2') format('woff2');
---
>   src: local('Noto Sans Regular'), local('NotoSans-Regular'),
>     url('noto-sans/NotoSans-Regular.woff2') format('woff2');
15c16,17
<   src: url('noto-sans/NotoSans-Italic.woff2') format('woff2');
---
>   src: local('Noto Sans Italic'), local('NotoSans-Italic'),
>     url('noto-sans/NotoSans-Italic.woff2') format('woff2');
24c26,27
<   src: url('noto-sans/NotoSans-Medium.woff2') format('woff2');
---
>   src: local('Noto Sans Medium'), local('NotoSans-Medium'),
>     url('noto-sans/NotoSans-Medium.woff2') format('woff2');
32c35,36
<   src: url('noto-sans/NotoSans-MediumItalic.woff2') format('woff2');
---
>   src: local('Noto Sans Medium Italic'), local('NotoSans-MediumItalic'),
>     url('noto-sans/NotoSans-MediumItalic.woff2') format('woff2');
41c45,46
<   src: url('noto-sans/NotoSans-SemiBold.woff2') format('woff2');
---
>   src: local('Noto Sans SemiBold'), local('NotoSans-SemiBold'),
>     url('noto-sans/NotoSans-SemiBold.woff2') format('woff2');
49c54,55
<   src: url('noto-sans/NotoSans-SemiBoldItalic.woff2') format('woff2');
---
>   src: local('Noto Sans SemiBold Italic'), local('NotoSans-SemiBoldItalic'),
>     url('noto-sans/NotoSans-SemiBoldItalic.woff2') format('woff2');
```

**Comment by aeaton-overleaf** [comment]
@vitorsr The Noto Sans fonts should be hinted now, if you'd like to test on Windows.
