### ISSUE TITLE
Latest Sharelatex Docker Hub image broken: "Cannot generate subnet key as the ip address is not of the expected format."

### ISSUE THREAD

**Issue by KKraljic** [overleaf/overleaf#1281]
## Steps to Reproduce
1. Pull the latest sharelatex image ( sha256:a325560399c8baf706369ae99651774d6031dbac8607e723e95b6280fbb61e23 ) from Docker Hub
2. Start it (docker compose up -d)
3. Go to the Web UI
4, Log in

## Expected Behaviour
Login should succeed.

## Observed Behaviour
The web UI does not let one in, i.e., it throws the following error: "Something went wrong. Please try again."

## Technical Info
The Overleaf instance is running in two different networks:

- default:
    - mongo
    - redis
    - overleaf web app
- web
    - reverse proxy
    - overleaf web app

The default network is inteded to be used for local communication only, while the web network conects my reverse proxy (caddy) with my overleaf web app. In the past, the header have been correctly transmitted as it used to work.

## Analysis
I checked the logs, i.e., "/var/log/overleaf/web.log"  and found the following error message:

```
{"name":"web","hostname":"2fd1df794955","pid":175,"level":50,"err":{"message":"Cannot generate subnet key as the ip address is not of the expected format.","name":"OError","stack":"OError: Cannot generate subnet key as the ip address is not of the expected format.\n    at RateLimiter.getSubnetKeyFromIp (/overleaf/services/web/app/src/infrastructure/RateLimiter.js:107:13)\n    at RateLimiter.consume (/overleaf/services/web/app/src/infrastructure/RateLimiter.js:71:30)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","info":{"ip":"<REDACTED>"}},"responseTimeMs":6,"req":{"method":"POST","url":"/login","remoteAddress":"<REDACTED>","headers":{"referer":"<REDACTED>","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36","content-length":"112"}},"res":{"statusCode":500,"headers":{"content-length":"796"}},"msg":"POST /login","time":"2024-10-21T08:25:32.772Z","v":0}
```

Rolling back to image tag 5.1 (sha256:14fb13cd2a11c69f3fb968e0d075d385eee569aa9cdd3be94f8038d42574612f) works.

**Comment by KKraljic** [comment]
```
OVERLEAF_SECURE_COOKIE=true
OVERLEAF_BEHIND_PROXY=true
```

These variable have been set.


Adding the following variable leads to a '502' message from nginx within the overleaf container:

```
OVERLEAF_TRUSTED_PROXY_IPS=true 
```

I've taken a look at the respective error log within overleaf (/var/log/nginx/error.log), but cannot find anything useful:

```
2024/10/24 07:31:46 [error] 213#213: *1 connect() failed (111: Unknown error) while connecting to upstream, client: <IP_Address>, server: _, request: "GET /login HTTP/1.1", upstream: "http://127.0.0.1:4000/login", host: "<FQDN of overleaf instance>"
```

Could it be that my proxy is not forwarding all required request headers? At the moment, I'm forwarding the Host, X-Real-IP, X-Forwarded-For, X-Forwarded-Port, X-Forwarded-Proto. Have there been some changes with regards to the required headers?

**Comment by mserranom** [comment]
We think the problem is related to IPv6, if the proxy wasn't forwarding the appropriate headers the error would be different.

We've pushed a new version (`5.2.1`), would you mind giving it a try?

**Comment by KKraljic** [comment]
I am able to login. I'll play around with the installation once the full installation completes.

**Comment by KKraljic** [comment]
Accessing and compiling projects works. 5.2.1 fixes the issue, I had not to use the `OVERLEAF_TRUSTED_PROXY_IPS=true ` variable.
