### ISSUE TITLE
Could not load the bindings file

### ISSUE THREAD

**Issue by kontextbewusst** [overleaf/overleaf#129]
Hi all, I just installed sharelatex on a Ubuntu 12.04 LTS server. When I run `grunt run`, I get an exception stating that the bindings file could not be loaded:

```
Exception: Error: Could not load the bindings file. Tried:
 → /var/sharelatex/sharelatex/web/node_modules/bcrypt/build/bcrypt_lib.node
 → /var/sharelatex/sharelatex/web/node_modules/bcrypt/build/Debug/bcrypt_lib.node
 → /var/sharelatex/sharelatex/web/node_modules/bcrypt/build/Release/bcrypt_lib.node
 → /var/sharelatex/sharelatex/web/node_modules/bcrypt/out/Debug/bcrypt_lib.node
 → /var/sharelatex/sharelatex/web/node_modules/bcrypt/Debug/bcrypt_lib.node
 → /var/sharelatex/sharelatex/web/node_modules/bcrypt/out/Release/bcrypt_lib.node
 → /var/sharelatex/sharelatex/web/node_modules/bcrypt/Release/bcrypt_lib.node
 → /var/sharelatex/sharelatex/web/node_modules/bcrypt/build/default/bcrypt_lib.node
 → /var/sharelatex/sharelatex/web/node_modules/bcrypt/compiled/0.10.28/linux/x64/bcrypt_lib.node
    at bindings (/var/sharelatex/sharelatex/web/node_modules/bcrypt/node_modules/bindings/bindings.js:84:13)
    at Object.<anonymous> (/var/sharelatex/sharelatex/web/node_modules/bcrypt/bcrypt.js:1:97)
```

see the full log [here](https://gist.github.com/kontextbewusst/5d8278f18490b3c031f5). I am wondering if this is a bug or if I missed something in the install?

Thanks for your help,

Max.

**Comment by pidupuis** [comment]
I have the same issue for package deasync 0.0.7 with npm 1.4.28 and node v0.13.0-pre.

No full reinstall, no npm rebuild seem to solve this. I can't run any grunt task...

**Comment by JoKeyser** [comment]
With self-compiled node v0.12.0, I encountered a similar problem with the `bcrypt` package during `grunt install:web`. I'm on branch `release`, running Debian wheezy.

npm ERR! Linux 3.2.0-4-686-pae
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.6.0
npm ERR! code ELIFECYCLE
npm ERR! bcrypt@0.7.5 install: `node-gyp rebuild`

A (not recommended) workaround is to locally install version of `bcrypt` in the `web` directory using

`npm install bcrypt@0.8.1`
`npm install v8-profiler@5.2.2`

**Comment by jpallen** [comment]
@JoKeyser Is this a case of needing to update some packages to work with Node 0.12? We've only tested on 0.10 so far.

**Comment by JoKeyser** [comment]
@jpallen Thank you for your quick answer. Recompiling `web` with Node v0.10.9 gets rid of the problem with `bcrypt@0.7.5`, nice! However `v8-profiler@5.2.4` still gives me a `node-pre-gyp ERR! build error`. That's the only module not compiling... While reverting to `v8-profiler@5.2.2` compiles fine. What's the preferred full version for node?

**Comment by henryoswald** [comment]
We are using node 0.10.22 in production at the moment. I am sure we will
move to 0.12 at some point in the next next few months.

On Wed, Feb 25, 2015 at 12:16 PM, Johannes Keyser <notifications@github.com>
wrote:

> @jpallen <https://github.com/jpallen> Thank you for your quick answer.
> Recompiling web with Node v0.10.9 gets rid of the problem with
> bcrypt@0.7.5, nice! However v8-profiler@5.2.4 still gives me a node-pre-gyp
> ERR! build error. That's the only module not compiling... While reverting
> to v8-profiler@5.2.2 compiles fine. What's the preferred full version for
> node?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sharelatex/sharelatex/issues/129#issuecomment-75950439>
> .
>



-- 
Henry Oswald
shareLaTeX.com creator

**Comment by lookingcloudy** [comment]
ARGH - I'm having this exact problem.  With node 0.12.7.

**Comment by blackandcold** [comment]
Well I had the same problem with newer node versions... (LXC  buntu 14.04)

Using n `npm install -g n`
installing older node version `n 0.10.22` linking it to standard `ln -s` etc. "solved" it.

**Comment by phil-oolabs** [comment]
I had this problem with the deasync and Node 5.6.0. Solved it with `node-gyp rebuild` from within the `node_modules/deasync` directory.
