### ISSUE TITLE
feature support for compilation needs with Arara or TrY package

### ISSUE THREAD

**Issue by sharethewisdom** [overleaf/overleaf#142]
hi,
It would be very exciting to allow compilation directives using comments in TeX files. A few months ago when I wanted to use the --shell-escape option for pdfLaTeX, Mr. Oswald kindly answered to my question (if one could allow using compilation options) that "we currently don't allow this for security reasons, it is something we are planning on working on in the future". So what's the current line of thought? I just read this interesting topic, among others:
http://tex.stackexchange.com/questions/119533/how-to-set-a-new-clean-arara-rule-that-circumvents-dropbox-interference-in-windo

Perhaps a package like that could be written for ShareLaTeX to support control over supported features?

**Comment by arjunsuresh** [comment]
I also had this issue. So, these are the steps I did:
login to shell of docker image
went to /var/www/sharelatex and find the file which has pdflatex command being defined. Added "-shell-escape" to it. 
Install imagemagick - sudo apt-get install imagemagick. 
Logout of docker.
Restart docker image
