### ISSUE TITLE
Auto-Indentation Support With latexindent.pl

### ISSUE THREAD

**Issue by manoyes** [overleaf/overleaf#152]
This is an enhancement request. Is there a way to auto-indent `.tex` files in ShareLaTeX to improve code readability like in some IDEs? If not, would the developers be interested if I added a keyboard shortcut which runs `latexindent.pl` on the current TeX file? This perl script comes standard with some TeX distributions (at least MacTex does) and is also [free under the GPL](https://github.com/cmhughes/latexindent.pl).

**Comment by psyyz10** [comment]
vbnm

**Comment by fzimmermann89** [comment]
Any news regarding latexindent.pl?

**Comment by tdegeus** [comment]
It seems that this issue was closed in favour of a PR that never saw the light of day. Maybe this should be reopened ?

**Comment by thesofakillers** [comment]
Would love to hear updates on this :)

**Comment by janpf** [comment]
Same! I believe since the monorepo migration (#923) is going on this would be the perfect opportunity to re-open this issue :)
