### ISSUE TITLE
sharing local files: rstudio -> knitr -> sharelatex

### ISSUE THREAD

**Issue by zeigerpuppy** [overleaf/overleaf#161]
I am trying to share files between sharelatex and rstudio on the same server.
Ideally, it would be useful to have files edited in rstudio (which stores these as normal user files in the user's home directory) and then be able to use these as sources for knitr chunks in sharelatex documents.
Is there any mechanism to access the filesystem in sharelatex (happy to do a symlink or loop mount if necessary but I suspect that sharelatex needs to register the file as its own somehow).
I want to avoid having to re-upload files if there is a change made in the R scripts by the rstudio user.

**Comment by jpallen** [comment]
You will need a custom entry in the your latexmk file. We have the following to run an Rtex file through knitr before compiling the generated main.tex.

```
my $root_file = $ARGV[-1];

add_cus_dep( 'Rtex', 'tex', 0, 'rtex_to_tex');
sub rtex_to_tex {
    do_knitr("$_[0].Rtex");
}

sub do_knitr {
    my $dirname = dirname $_[0];
    my $basename = basename $_[0];
    system("Rscript -e \"library('knitr'); setwd('$dirname'); knit('$basename')\"");
}

my $rtex_file = $root_file =~ s/\.tex$/.Rtex/r;
unless (-e $root_file) {
	if (-e $rtex_file) {
		do_knitr($rtex_file);
	}
}
```

**Comment by zeigerpuppy** [comment]
Thanks @jpallen 
That fixed it, I placed the settings you provided into a .latexmkrc file in the sharelatex user home directory (which I my case is the sharelatex root).
I wonder whether it's worth adding this file to the github repository so that it should work for most users out of the box.

**Comment by jpallen** [comment]
I considered adding it to the repo, but it would be another install step
and only further confuse matters for most people who don't need it. A wiki
page might be a good idea though, with this snippet that people can install
if they want knitr to work.

**Comment by zeigerpuppy** [comment]
I tried to get this working in the latest docker install and it fails to process .Rtex files 

log:
```
This is pdfTeX, Version 3.1415926-2.5-1.40.14 (TeX Live 2013/Debian) (format=pdflatex 2016.10.18)  19 OCT 2016 06:45
entering extended mode
 \write18 enabled.
 %&-line parsing enabled.
**main.tex
! Emergency stop.
<*> main.tex
```
is there a new location for the .latexmkrc file?
