### ISSUE TITLE
Dropbox integration should not request Full Dropbox access.

### ISSUE THREAD

**Issue by ghost** [overleaf/overleaf#169]
As per https://www.dropbox.com/developers/reference/devguide#app-permissions, clients can request permission for an app-specific folder rather than full Dropbox access. Since ShareLaTeX only ever uses one folder for its stuff, this seems far preferable to requesting full access.

**Comment by XaF** [comment]
I think it should be the choice of the user to decide if it wants to share or not that folder with others. In such case, he could give a full access to sharelatex, but in other cases, he could not do it. Forcing everyone to give full access to dropbox seems quite disproportionate, as sharelatex already allows people to share online.

**Comment by John-Jumper** [comment]
It looks like the Dropbox integration has been updated to request limited permissions.  This page still shows up (at least for me) on Google searches; you may want to update the information here.

**Comment by henryoswald** [comment]
Thanks John, I can confirm this has been done now.
