### ISSUE TITLE
Content Length mismatch when compiling

### ISSUE THREAD

**Issue by jamiees2** [overleaf/overleaf#170]
I am trying to compile some latex code. It compiles fine, but i get a content length mismatch for the spellchecker and the pdf document. Any ideas what it could be? Here is the web console output.

```
POST http://<host>/spelling/check net::ERR_CONTENT_LENGTH_MISMATCH jquery.min.js:4
POST http://<host>/spelling/check net::ERR_CONTENT_LENGTH_MISMATCH jquery.min.js:4
GET http://<host>/project/53fbad5e5de3204f067bfe19/output/output.pdf?cache_bust=1409004089380 net::ERR_CONTENT_LENGTH_MISMATCH 53fbad5e5de3204f067bfe19/output/output.pdf?cache_bust=1409004089380:1
GET http://<host>/project/53fbad5e5de3204f067bfe19/output/output.pdf?cache_bust=1409004089380 net::ERR_CONTENT_LENGTH_MISMATCH 
```

**Comment by marcuswestin** [comment]
For anyone else who finds this: I believe that the one line that makes the difference is `proxy_buffering off;`. Adding just that at the top of my `http { ... }` section fixed the issue for me.

**Comment by marcuswestin** [comment]
More info: I believe the real issue was corrupted file entries in `/usr/local/var/run/nginx/*`. The real fix came from http://stackoverflow.com/questions/22889338/javascript-not-loading-due-to-neterr-content-length-mismatch:

```
sudo nginx -s stop
sudo rm -rf /usr/local/var/run/nginx/*
sudo nginx
```

**Comment by g3d** [comment]
@marcuswestin,
Last solution worked for me.

Thank you a lot!

**Comment by lynndylanhurley** [comment]
@marcuswestin - last solution worked for me as well. Thx!!

**Comment by marcuswestin** [comment]
Nice :)
