### ISSUE TITLE
Editor keymapping in Firefox Android appears buggy (arrow keys)

### ISSUE THREAD

**Issue by zeigerpuppy** [overleaf/overleaf#175]
using the latest Android version of firefox beta and an external bluetooth keyboard (or software hackers keyboard app), arrow keys are not working properly in the editor.
Sometimes the editor accepts key input correctly but at other times a right or down key seems to move focus out of the editor. Left and up keys seem to work properly.
This results in menu items being changed (theme for example) but without the onscreen menu shown.
It seems like the down and right are causing the cursor to move to a different element (not the editor).
The behviour appears possible to reset by moving to a textbox in a different tab and then back to the editor.
Also, it is not possible to scroll the editor text using the touchscreen gestures.

**Comment by VerstandInvictus** [comment]
Is there any workaround at all for this? It's infuriating, especially as Firefox is the only Android browser which has a functional debug console (via addon).
