### ISSUE TITLE
Offline support

### ISSUE THREAD

**Issue by jpallen** [overleaf/overleaf#18]
Allow projects to be synced offline (into local storage?), edited in an offline HTML5 app, and then resynced/uploaded when back with an internet connection.

**Comment by tillahoffmann** [comment]
Are there any plans to implement this feature? Overleaf is a great tool, but I do a reasonable amount of writing while travelling where I don't have a reliable internet connection.

**Comment by mserranom** [comment]
@tillahoffmann it's not among our immediate plans I'm afraid. The option that probably suits your use case best would be integrating your projects with git/github/dropbox, checkout before your trip and checkin your updates once you're back online.
