### ISSUE TITLE
nginx proxy can not upload zip file? localhost is ok

### ISSUE THREAD

**Issue by WeiLiPenguin** [overleaf/overleaf#207]
Hi,
When I run on localhost everything fine,
but if I use nginx as proxy, same settings as shown on https://github.com/sharelatex/sharelatex/wiki/Nginx-as-a-Reverse-Proxy  I can not upload zip file, it said "Upload failed. Is it a valid zip file?"

I set the port as 6080.
any ideas? Thanks!

**Comment by jowagner** [comment]
Note that if your sharelatex.conf is included from within an existing http block you need to put the above into your sharelatex.conf without a new http block. Otherwise nginx complains "directive is not allowed here". On my system, everything in conf.d/*.conf is included from within an http block.
