### ISSUE TITLE
Minted shell-escape problem

### ISSUE THREAD

**Issue by ukasiu** [overleaf/overleaf#217]
Hi,
trying to compile the example from CLSI with Sharelatex:

``` latex
\documentclass{article}
\usepackage{minted}
\begin{document}
\begin{minted}{c}
int main() {
    printf("hello, world");
    return 0;
}
\end{minted}
\end{document}
```

I'm getting `! Package minted Error: You must invoke LaTeX with the -shell-escape flag.`. Is something wrong with my installation or is it desired behavior?

**Comment by sunyongke** [comment]
@ukasiu  @jpallen  How to allow -shell-escape  for minted in texmf.cnf exactly?

**Comment by 3nt3** [comment]
@sunyongke add this to your `texmf.cnf`
```
shell_escape = t
```

**Comment by Musicminion** [comment]
Maybe a better way is still use latexmkrc file in project root.
Once I change shell_escape = t in my texmf.cnf, some bug come out continuous,howeve only if I withdraw my change to shell_escape globally, things become normal
