### ISSUE TITLE
Navigation hotkeys in Mac aren't right

### ISSUE THREAD

**Issue by prasincs** [overleaf/overleaf#221]
I noticed that the Navigation hotkey for going to beginning of line is `Cmd+Home` when most of the keyboards for Macs (especially laptops) do not have an explicit `Home` key in them. It should be `Cmd + <-` or `Ctrl+A` and for end of the line - `Cmd+ ->` or `Ctrl+E` (This is emacs mode, for vim they'd be `^` and '$` respectively)
![screen shot 2014-11-12 at 7 18 46 am](https://cloud.githubusercontent.com/assets/40477/5010090/9ea8095a-6a3c-11e4-81b6-4cf2f4d55089.png)

**Comment by aeaton-overleaf** [comment]
These shortcuts appear to be correct, now: 

* Command–Fn–Left Arrow (Cmd + Home) moves the cursor to the beginning of the document
* Command–Fn–Right Arrow (Cmd + End) moves the cursor to the end of the document
