### ISSUE TITLE
Hosted ShareLatex strange compile error - probably libpng fault 

### ISSUE THREAD

**Issue by NikolaTesla80** [overleaf/overleaf#227]
Hello everyone, 
first let me thank you for such a great tool ShareLatex is 
I’m commonly using the hosted version and and recently, working on a project consisting of a paper with about 20 png images, while using pdfLatex compiler I got a totally new error 

> dfTeX error: pdflatex: libpng: internal error ==> Fatal error occurred, no output PDF file produced!

In the last times I have never experienced any problem compiling this project … 

I checked the png files and they look ok (I can see the online preview correctly) so I don’t think this problem can be caused by corrupted image files. 

I tried changing compiler and when using LaTex I can see the compiled paper but again no images inside, for each one I get this kind of error 

> LaTeX Error: File `img/MRF-Img11' not found.
> 
> See the LaTeX manual or LaTeX Companion for explanation.
> Type  H <return>  for immediate help.
>  ...                                              
> 
> l.223 ...phics[width=0.5\textwidth]{img/MRF-Img11}
>                                                   \hfill \
> I could not locate the file with any of these extensions:
> .eps,.ps,.eps.gz,.ps.gz,.eps.Z,.mps
> Try typing  <return>  to proceed.
> If that doesn't work, type  X <return>  to quit.
> 
> [3] [4] [5] [6] [7]

for every png file because this compiler does not look for image files with the png extension (actually I don’t know why) so if I specify this extension in my Latex code I get this error 

> LaTeX Error: Cannot determine size of graphic in img/MRF-Img11.png (no BoundingBox).
> 
> See the LaTeX manual or LaTeX Companion for explanation.
> Type  H <return>  for immediate help.
>  ...                                              
> 
> l.223 ...s[width=0.5\textwidth]{img/MRF-Img11.png}
>                                                   \hfill \
> Try typing  <return>  to proceed.
> If that doesn't work, type  X <return>  to quit.
> 
> File: img/MRF-Img11.png Graphic file (type eps)
> <img/MRF-Img11.png> [3] [4] [5] [6] [7]

I don’t realize the cause of this failure … 

Furthermore I ask if any update have been performed on the hosted version recently : this project always worked well and recently the only modifications I have carried out are just related to text … 

Tnx

**Comment by achimnol** [comment]
I'm seeing the same error on my community edition, but NOT on sharelatex.com website.
Looking at what is happening here...

**Comment by achimnol** [comment]
After investigating inside the docker image, I found that the PNG file used for compilation is completely different from the original one I've uploaded. (md5sum is different and the file size is different! Downloading it again and opening it has errors...)
I'm not sure the upload process has bugs or somewhere else...

**Comment by achimnol** [comment]
Oh, I found that this issue is related to #265 and it's now fixed.
I'll update my image to the latest version!
