### ISSUE TITLE
When pulling from GitHub, editor name is "Anonymous".

### ISSUE THREAD

**Issue by petebachant** [overleaf/overleaf#240]
It would be great if the names were read from the commits.

**Comment by Jim-Vardakis** [comment]
Is there any progress on this matter?

**Comment by dmackinnon1** [comment]
As noted in the [docs](https://www.overleaf.com/learn/how-to/GitHub_Synchronization), when pulling from GitHub the Overleaf history is updated as `Anonymous (via Github)`. There's no guarantee that users on the GitHub side will have an Overleaf identity, and any names in the commits wouldn't be sufficient to make a link between the Github user and the corresponding Overleaf user. Sorry for the limitation.

Note: If you are using www.overleaf.com (the SaaS product) and have a problem, or if you would like to request a new feature or provide other feedback, please contact the support team at support@overleaf.com. 

This form should only be used to report bugs in the Community Edition release of Overleaf.
