### ISSUE TITLE
Server Issue - 

### ISSUE THREAD

**Issue by marc101101** [overleaf/overleaf#241]
Hey guys,

I have just updated to the latest version in the repository (I also tried an installation from scratch) but the server does not start when I try to run it with grunt run ($ grund run:all) the error message I get is the following:

Error: listen EADDRINUSE
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1042:14)
    at listen (net.js:1064:10)
    at net.js:1146:9
    at asyncCallback (dns.js:68:16)
    at Object.onanswer [as oncomplete](dns.js:121:9)
Warning: -> error 8 /home/markus/Dokumente/sharelatex-master/sharelatex/spelling/app.js (8034ms) Use --force to continue.

Aborted due to warnings.
    Warning:  Use --force to continue.

```
    Aborted due to warnings.
```

May someone can help? --force is not a possibilty, isnt it?
with the best wishes marc :)

**Comment by henryoswald** [comment]
it is likely the old process was still running.
