### ISSUE TITLE
Configurable timezone for \today

### ISSUE THREAD

**Issue by fandu** [overleaf/overleaf#269]
The timezone is not configurable in ShareLatex.

I am in US eastern time. The \today command gives the date of the next day.

(This matters. The professor thought I had missed the homework deadline.)

**Comment by jpallen** [comment]
This currently isn't possible (or at least is very hard) because LaTeX takes its time from the server time, and when running multiple compiles on the same server, they can't have different timezones. Sorry about this.

**Comment by tuhoojabotti** [comment]
:+1: for this issue. Maybe it could be achieved using TZ environment variable before the render command? That way it doesn't have to be set globally on the server?

Source: https://tex.stackexchange.com/questions/101101/specify-timezone-for-today-and-currenttime

**Comment by vzaliva** [comment]
Another idea is something similar to Overleaf's solution:

https://www.overleaf.com/help/214-how-do-i-make-slash-today-display-the-date-according-to-my-time-zone#.Vt4dR6grLow

**Comment by henryoswald** [comment]
im going to reopen this as I think it is possible with the solutions you have presented.

**Comment by hrjakobsen** [comment]
The instructions [here](https://www.overleaf.com/learn/latex/Questions/How_do_I_make_%5Ctoday_display_the_date_according_to_my_time_zone%3F#.Vt4dR6grLow) should work for Overleaf Community Edition too.
