### ISSUE TITLE
Merging accounts / defining aliases (Feature request)

### ISSUE THREAD

**Issue by hulk1st** [overleaf/overleaf#274]
Quite often, users have different email addresses and therefore, the chance is high that people will send invitations to different addresses as well. However, you would typically like to have all your projects available in one account. Therefore it would be nice, if you could define kind of an alias or link / merge several accounts or define multiple email addresses for one account.

**Comment by jpallen** [comment]
This is something we would like to improve. There are some subtleties in how to implement it though, and we're still working on a good unified solution to account verification/sharing/multiple email addresses.

**Comment by hulk1st** [comment]
Great, thanks!!

**Comment by somename11111** [comment]
Having this exact problem right now. Please fix this.

**Comment by davidalbertonogueira** [comment]
Still not implemented?

**Comment by ShaneKilkelly** [comment]
We're currently working on a feature that will allow users to transfer ownership of a project to another account. We believe this feature will address most of this problem, at least until we can figure out what an "account merge" feature should look like.

This will become available in an upcoming release of Community Edition and Server Pro.

**Comment by davidalbertonogueira** [comment]
Thanks for your feedback. However, I think that "a feature that will allow users to transfer ownership of a project to another account" is not enough, as we may have lots of projects which we are not owners, and we just want to be able to see/access them with our other accounts.

**Comment by ShaneKilkelly** [comment]
I totally understand :) This is a feature we're considering for the long term development roadmap but at the moment we can't give any exact timeline.
