### ISSUE TITLE
Update task needs to run git fetch first

### ISSUE THREAD

**Issue by oxan** [overleaf/overleaf#322]
The `grunt update:all` task (which calls the `updateGitRepo` helper utility) needs to run `git fetch` before calling `git checkout` and/or `git pull`. The current sequence of commands results in a checkout of a non-existing tag when updating between release versions, which doesn't work.

**Comment by hrjakobsen** [comment]
Hi! The recommended way to run Overleaf Community Edition is now with Docker, using the [Overleaf Toolkit](https://github.com/overleaf/toolkit). I'll close this issue, as it is based on old build instructions, but please open a new issue if you face problems using Overleaf Toolkit.
