### ISSUE TITLE
Ctrl+/ not working on Swedish keyboard layouts

### ISSUE THREAD

**Issue by Micket** [overleaf/overleaf#353]
Unless you have a numpad, there is no primary / key on Swedish keyboard layouts, and even then, using ctrl+/ at the numpad doens't seem to work either.
On swedish layouts, we have / at shift+7, and doing ctrl+shift+7 doesn't work.

I've been trying every ctrl combo i could think of, but I just can't comment anything with this layout.

**Comment by mompes** [comment]
The same is hapenning to me with a spanish dvorak keyboard layout. It would be great if this would work.

**Comment by Micket** [comment]
I discovered that the editor still seems to assume English keyboard layout.
The Ctrl+' shortcut works for commenting under Swedish keyboard layout. The ' key is located next to the Enter key, at the equivalent place that English layouts have a / key, so this workaround will likely work for other layouts as well.
