### ISSUE TITLE
FR: Autocomplete for \ref, \cite, and friends

### ISSUE THREAD

**Issue by Soares** [overleaf/overleaf#354]
When working on large projects, it's really really nice to have autocomplete support for citations (`\cite{...}`, `\citep{...}`, `\citet{...}`, and friends) and for references (`\ref{...}`, `\subref{...}`, and friends) to sections / figures / equations / etc.

This request was already raised in #91, but that was closed (because the feature was mentioned in #49, which tracked linking with online bibtex databases), but then #49 was closed as impractical and (afaict) this feature request fell through the cracks. I'd really like to see it happen, though!

(This is one of the big features that would make it hurt to move my team from overleaf to sharelatex.)

**Comment by zeigerpuppy** [comment]
I agree, this is really an essential feature.  It would be even better if a bibliography could be autogenerated from a zotero library/subfolder/shared group.
It's quite cumbersome for users that aren't familiar with bibtex currently

**Comment by kaqmak** [comment]
I completely agree. For articles with 10 figures or more and 50-100 reference, it is completely impossible having to remember all the labels. Most good LaTeX editors are having this feature (and so does the competing Overleaf).

**Comment by noje** [comment]
+ 1 for autocomplete functionality ! That would be really useful !

**Comment by thinkh** [comment]
I'd also like to use the autocomplete feature. Would be make the whole process much easier.

**Comment by alejpelo** [comment]
+1 for autocomplete functionality on references!!!

**Comment by kvothe** [comment]
+1 
The missing autocomplete for citations is really the one big problem I have with sharelatex at the moment as I often work on papers with 30+ references.

**Comment by msiniscalchi** [comment]
+1 for \ref completion. This is essential IMHO. Love \cite completion, but \ref completion is as important to me. Overleaf has it, too.

**Comment by hanshenrik** [comment]
+1
Would be great to have autocomplete for \ref{fig:oh-shoot-what-was-this-label-agian?}

**Comment by antipa** [comment]
+1 this seems like an essential feature of any LaTeX editor. The \cite autocomplete seems to be working as of Feb 2017, but \ref autocomplete to figure and equation labels appears not to exist.

**Comment by tiagodanielff** [comment]
+1

**Comment by WiktorMadejski** [comment]
\cite completion is great, love how much for better sharelatex is changing!

+1 for \ref{} auto-completion

**Comment by xwjabc** [comment]
+1 for \ref{} auto-completion

**Comment by akuzni2** [comment]
+1 for \ref{} auto-complete. For now I'll be sticking with Overleaf.

**Comment by bwebste** [comment]
One more plea for \ref auto-complete or search.  It's nuts to not have some feature along these lines.  A big minus compared to reftex.

**Comment by antipa** [comment]
This not just a "nice-to-have" this is a basic and necessary function in complex LaTeX documents. It is crazy that this hasn't been implemented.

**Comment by herrwusel** [comment]
\ref is working but it would be nice to have \cite auto completion as well. Especially when you have larger bibliographies!

**Comment by cmcisaac6** [comment]
Closing: Autocomplete is now available for all the commands mentioned.
