### ISSUE TITLE
Hotkeys - custom

### ISSUE THREAD

**Issue by ghost** [overleaf/overleaf#364]
Hi,
Is there a way to add custom hotkeys.

e.g. for \citep when writing an science paper
of \gls when using abbreviations a lot...

I tried using a hotkey manager for my browser, but those don't work inside the text editor but do in e.g. the title text box...

regards,
Pieter

**Comment by apus2016** [comment]
This seems to be what you are looking for:

				# Italicise text on CMD+I
				editor.commands.addCommand
					name: "italics",
					bindKey: win: "Ctrl-I", mac: "Command-I"
					exec: (editor) ->
						selection = editor.getSelection()
						if selection.isEmpty()
							editor.insert("\\textit{}")
							editor.navigateLeft(1)
						else
							text = editor.getCopyText()
							editor.insert("\\textit{" + text + "}")
					readOnly: false

It is part of 

https://github.com/sharelatex/web-sharelatex/blob/83ef761ec9402ac56ada05bfd1abc4460a710340/public/coffee/ide/editor/directives/aceEditor.coffee

Would be great if someone from the sharelatex team could confirm that this is okay to edit at that place without disrupting something else.

Copy/Paste/Edit to your liking and make sure you recompile the web-sharelatex module afterwards.

Warning: I did not test this, but will in the coming days.

**Comment by ilpepe** [comment]
thanks for the followup. keep me posted please!
