### ISSUE TITLE
npm reports security issue with deprecated sequelize 

### ISSUE THREAD

**Issue by jowagner** [overleaf/overleaf#366]
While running grunt install (with node js 0.10.40) for a new sharelatex installation, I spotted the following npm warning in the thousands of lines of output:

```
npm WARN deprecated sequelize@2.1.3: critical security fix in v3.0.0
```

This is under the heading 'Running "install:clsi" task'.

**Comment by das7pad** [comment]
Hello,

We've removed the sqlite database a while ago from the clsi service and with it the dependency on `sequelize`.

Greetings,
Jakob
