### ISSUE TITLE
feature request : zoom compiled preview with mouse and keyboard

### ISSUE THREAD

**Issue by ktzanev** [overleaf/overleaf#371]
If we want to zoom in or zoom out now we have to move the mouse to the upper left corner of the preview window and then click to "+" or "-" button.

It will be nice if we can use for example "Alt + mouse weel" to zoom in/out when we are over the preview window. And why not "Alt + Ctrl + mouse weel" to fit the preview horizontally or vertically.

And heaving also keyboard shortcuts like "Alt+PageUp" and "Alt+PageDown" for zoom in/out could be useful.

**Comment by Babalion** [comment]
I want to push this topic.
Coming from vscode and LaTeX Workshop, I'm absolutely used to using Ctrl+Scroll to zoom in or out the PDF view.
It's so annoying that it doesn't work in Overleaf!

I assume it wouldn't be that complicated to add this shortcut to the built-in overleaf PDF viewer.

One workaround is to change the PDF viewer to the native browser PDF viewer.
A drawback is that double-click to jump to source code doesn't work then anymore.

**Comment by 95A31** [comment]
I made a little [extension](https://github.com/95A31/OverleafWheelZoom) to link _Ctrl + Mouse Wheel_ to the zoom buttons.

**Comment by 95A31** [comment]
It has been natively implemented!
https://github.com/overleaf/overleaf/commit/4fe66c018909dbd5c4d4b63b11e19452a2207186

**Comment by kpym** [comment]
@95A31 is it supposed to be already available on Overleaf.com ? because I don't have this feature available on my account.

**Comment by 95A31** [comment]
@kpym Yes, I am on Chromium and _Ctrl + Mouse Wheel_ works.

**Comment by kpym** [comment]
@95A31 For me it is not working (on Windows/Chrome) : <kbd>Ctrl+Mouse Wheel</kbd> zoom the entire content, not just the pdf preview. And under Windows it should not be <kbd>Ctrl+Mouse Wheel</kbd> (like under Mac it should not be <kbd>Cmd+Mouse Wheel</kbd>).

**Comment by davidmcpowell** [comment]
> @95A31 is it supposed to be already available on Overleaf.com ? because I don't have this feature available on my account.

The feature was released gradually so not all users were able to use it. However, we have just completed the rollout to 100% of users so you should be able to access it. 

I am going to close this issue now that this has been implemented.
