### ISSUE TITLE
Problems setting up sharelatex with apache

### ISSUE THREAD

**Issue by jv-barsuk** [overleaf/overleaf#388]
I used the configuration suggested here: https://github.com/sharelatex/sharelatex/wiki/Apache-as-a-Reverse-Proxy. I can load the project overview, but as soon as I want to open one there is a yellow bar at the top saying "Loading... Lost Connection.Reconnecting in 5 secs.". When I tunnel my connection via SSH onto the server and access it via localhost, it works just fine.

Here is my VHost config. The proxy module is loaded and I of course reloaded apache2. In the logs I can't find any useful information. 

Does anybody have a clue what the issue could be?

`<VirtualHost *:80>
    ServerName sharelatex.MYDOMAIN.at
    ProxyPreserveHost On

```
<LocationMatch "/socket.io">
  ProxyPass http://localhost:3026/socket.io
  ProxyPassReverse http://localhost:3026/socket.io
</LocationMatch>

<LocationMatch "/">
  ProxyPass http://localhost:3000/
  ProxyPassReverse http://localhost:3000/
</LocationMatch>
```

</VirtualHost>
`

In the Firefox Inspector the POST request to:
http://sharelatex.MYDOMAIN.at/socket.io/1/xhr-polling/7-t8qN-fdfd7fHJH?t=1354322652016
is rejected with a 403 Forbidden error.

EDIT: actually there is this error in the log:
`{"message":"invalid csrf token","name":"ForbiddenError","stack":"ForbiddenError: invalid csrf token\n  at verifytoken (/var/www/sharelatex/web/node_modules/csurf/index.js:269:11)\n  at csrf (/var/www/sharelatex/web/node_modules/csurf/index.js:97:7)\n  at Layer.handle [as handle_request] (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:95:5)\n  at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:312:13)\n  at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7\n`

it seems to be related to https://github.com/sharelatex/sharelatex/issues/276 but I can't solve the issue here.

**Comment by Buzzy0815** [comment]
I have a similar issue.

I am hosting sharelatex on a sharedhosting so I don't have access to the apache config. Therefore I am using the .htaccess file for my proxy forwarding.

.htaccess:
```
RewriteEngine On
RewriteRule "^/socket.io/(.*)" "http://localhost:63026/socket.io/$1" [P]
RewriteRule "(.*)" "http://localhost:63000/$1" [P]
```

The interface works like charm but I can't open a project.

The Browser log says: 

> WebSocket connection to 'ws://foo.com/socket.io/1/websocket/easdabw6f1xaPsACSDgyi' failed: Establishing a tunnel via proxy server failed.

> socket.io.js:2 POST http://foo.com/socket.io/1/xhr-polling/eHoWbw6f1xasdaACSDgyi?t=1458123342 403 (Forbidden)

and the output of the server-terminal is

> invalid csrf
ForbiddenError: invalid csrf token

any solutions for this problem?

**Comment by UlyssesZh** [comment]
Ran into the same problem.

**Comment by UlyssesZh** [comment]
A temporary fix to this problem is to comment out `SHARELATEX_SECURE_COOKIE=true` in your env file.

**Comment by das7pad** [comment]
Hello,

I'm afraid we only support nginx for proxying moving forward. The [Overleaf Toolkit](https://github.com/overleaf/toolkit) can manage a [TLS proxy (docs)](https://github.com/overleaf/toolkit/blob/master/doc/tls-proxy.md) for you as well now.

Greetings,
Jakob
