### ISSUE TITLE
`grunt install` does not work properly with git < 1.7.10

### ISSUE THREAD

**Issue by jrandall** [overleaf/overleaf#392]
`grunt install` attempts to check out a tag on the `git clone` command for each of the sharelatex repos. Unfortunately that feature (referring to tags with `-b` instead of just branches) is not supported by git versions prior to 1.7.10 (see http://stackoverflow.com/questions/17216067/git-clone-b-tag-results-in-warning-remote-branch-not-found-in-upstream-origi#17216068).

Rather than failing, the git command simply prints a warning (such as "warning: Remote branch v0.2.0 not found in upstream origin, using HEAD instead") and then goes on to checkout the master branch.

The result is that rather than ending up with a release version of sharelatex, you wind up with the master (development) branch, which is not ideal. 

Perhaps `grunt install` should detect the `git` version and revert to the two-step (`git clone`, `git checkout`) method of checking out a tag for git < 1.7.10?

**Comment by henryoswald** [comment]
Hi,

I would look at using the docker instance of ShareLaTeX.

**Comment by hrjakobsen** [comment]
Hi! The recommended way to run Overleaf Community Edition is now with Docker, using the [Overleaf Toolkit](https://github.com/overleaf/toolkit). I'll close this issue, as it is based on old build instructions, but please open a new issue if you face problems using Overleaf Toolkit.
