### ISSUE TITLE
Package nomencl (for nomenclature) doesn't work

### ISSUE THREAD

**Issue by dpasqualin** [overleaf/overleaf#399]
Hi, I'm using sharelatex from docker (tag 2.0.0, but 0.1.4 doesn't work either) and I can't manage to make the package nomencl work.

I'm using the tutorial from https://pt.sharelatex.com/learn/Nomenclatures and there are no error messages neither in the server logs nor in the client logs. The nomencl package is installed and I can even see that output.nlo is generated, but I get only a blank page as result.

Any ideas? Thank you.

**Comment by featheryjam2** [comment]
I'm having the same issue.  I hope they fix this soon!

**Comment by featheryjam2** [comment]
Doesn't look like this problem will get fixed anytime soon.  I'm guessing they've abandoned the open source version of sharelatex.  The best solution I have found is switching to overleaf.  It's not ideal because I can't have my own server, but nomencl works there and their support has been quite responsive to my questions.  Good luck!

**Comment by dpasqualin** [comment]
Indeed, it seems abandoned :(
Thanks for your reply.

**Comment by henryoswald** [comment]
Hi,

we have not abandoned the open source at all, sorry if we gave that impression. Just the amount of support and tickets we get is more than we can manage as a small company. 

We have actually kicked off a new bit of work yesterday to improve the docker release, with 2 of the main goals being making it easier for us to cut a new release which currently takes a while and improving the latex binaries install path issues like you have with nomencl.

**Comment by dpasqualin** [comment]
Good to hear that @henryoswald  :)

**Comment by nbeyond** [comment]
I have the same issue. Not fixed yet?

**Comment by nbeyond** [comment]
I could resolve the issue by adding the following line just before \documentclass.

\immediate\write18{makeindex -s nomencl.ist -o "\jobname.nls" "\jobname.nlo"}

**Comment by leomaurodesenv** [comment]
> I could resolve the issue by adding the following line just before \documentclass.
> 
> \immediate\write18{makeindex -s nomencl.ist -o "\jobname.nls" "\jobname.nlo"}

Did you used this command in Overleaf or Sharelatex?

**Comment by mserranom** [comment]
Unfortunately the use of Nomenclatures as it's described in https://sharelatex.com/learn/Nomenclatures is valid for [Server Pro](https://www.overleaf.com/for/enterprises) and [overleaf.com](https://www.overleaf.com) only. 

In both these cases we use custom compilation servers  based on TexLive (see our [latest blog entry on the topic](https://www.overleaf.com/blog/tex-live-upgrade-september-2019)). 

Overleaf Community Edition uses instead the latest stable version of TexLive as distributed by CTAN (currently `2019` version), so not all features have a 100% parity.

**Comment by nageshsjagtap** [comment]
> I could resolve the issue by adding the following line just before \documentclass.
> 
> \immediate\write18{makeindex -s nomencl.ist -o "\jobname.nls" "\jobname.nlo"}

Thank you very much. This worked. I was struggling for hours :p!
