### ISSUE TITLE
The sharelatex docker container cannot  run 

### ISSUE THREAD

**Issue by frankchen0130** [overleaf/overleaf#400]
`sudo docker logs sharelatex`
And I get:
`[frankchen@localhost ~]$ sudo docker logs sharelatex 
[sudo] password for frankchen: 
*** Running /etc/my_init.d/00_make_sharelatex_data_dirs.sh...
mkdir: cannot create directory ‘/var/lib/sharelatex/data’: Permission denied
chown: cannot access ‘/var/lib/sharelatex/data’: No such file or directory
mkdir: cannot create directory ‘/var/lib/sharelatex/data’: Permission denied
chown: cannot access ‘/var/lib/sharelatex/data/user_files’: No such file or directory
mkdir: cannot create directory ‘/var/lib/sharelatex/data’: Permission denied
chown: cannot access ‘/var/lib/sharelatex/data/compiles’: No such file or directory
mkdir: cannot create directory ‘/var/lib/sharelatex/data’: Permission denied
chown: cannot access ‘/var/lib/sharelatex/data/cache’: No such file or directory
mkdir: cannot create directory ‘/var/lib/sharelatex/tmp’: Permission denied
chown: cannot access ‘/var/lib/sharelatex/tmp’: No such file or directory
mkdir: cannot create directory ‘/var/lib/sharelatex/tmp’: Permission denied
chown: cannot access ‘/var/lib/sharelatex/tmp/uploads’: No such file or directory
mkdir: cannot create directory ‘/var/lib/sharelatex/tmp’: Permission denied
chown: cannot access ‘/var/lib/sharelatex/tmp/dumpFolder’: No such file or directory
*** /etc/my_init.d/00_make_sharelatex_data_dirs.sh failed with status 1
`
@henryoswald

**Comment by gasse** [comment]
http://stackoverflow.com/questions/35822054/docker-container-cannot-run

**Comment by henryoswald** [comment]
This is a permissions problem as gasse said, look at the permissions of the mounted directory.

**Comment by gasse** [comment]
I had this problem, I guess because I first ran `docker run ...` as a user, and then `sudo docker start sharelatex` as root.

I solved this by running `sudo docker rm sharelatex`, then `sudo docker run ...` and finally `sudo docker start sharelatex`.

**Comment by Akronix** [comment]
I would close this issue...
