### ISSUE TITLE
[feature request] Zotero integration

### ISSUE THREAD

**Issue by Eothred** [overleaf/overleaf#410]
I see this mentioned in other requests, e.g. #354, but I thought it was still worthwile to mention it as a separate request.

I think it would be extremely convenient to have some kind of "insert from zotero" functionality where I could search my library and when selecting an entry that it would be imported to my bib file and the citation inserted to my tex file. There are perhaps other library services than Zotero that should be mentioned in this list. It just happens to be the one I currently use, and it is to my knowledge also open source.

There is also #49 which was closed already and sounds like a similar request, but my expert level is not high enough to understand if this means my request will also automatically be rejected.

**Comment by mizzao** [comment]
Being able to directly link to publicly-accessible Zotero groups would be great. Not sure how one would decide the format of the BibTeX entry though.

**Comment by xlrx** [comment]
I would really appreciate a Zotero Integration as well!

**Comment by ej159** [comment]
This would be a fantastic feature and could be done but require work from Zotero; you can already export from Zotero goups to .bib and you can [use an external bibliography](https://tex.stackexchange.com/questions/201470/remote-bibliography). It's just a matter of getting a "live" bib feed from Zotero, I think. This may already be possible by copying the export link from Zotero.

**Comment by wosen7** [comment]
Very much agreed, a Zotero integration for sharelatex would be amazing and an additional reason for paying the fees! For example Open Science Framework allows for integration of both, Mendeley and Zotero.

**Comment by royerloic** [comment]
+1

**Comment by mdingemanse** [comment]
This actually seems to be done, so can be closed? (Got here because of #1065, a recurrent pet peeve that means Zotero integration is not really functional for group libraries, but that's a different matter)

**Comment by Eothred** [comment]
Indeed, I think this request was made back when overleaf and sharelatex were two different things (and I used the latter).
