### ISSUE TITLE
Feature request: tikzexternalize 

### ISSUE THREAD

**Issue by fernandoandreotti** [overleaf/overleaf#415]
According to [this page](https://www.sharelatex.com/learn/Pgfplots_package), Sharelatex does not yet support `\tikzexternalize`, so I hope I am not creating an existing issue... I believe this feature would make the compilation of papers/thesis which make use of tikz much faster and easier.

Best, Fernando

**Comment by apus2016** [comment]
Let me quote hulk1st:

"Not sure if this helps but you can define options to be passed in /var/www/sharelatex/clsi/app/coffee/LatexRunner.coffee. Make sure to run sudo grunt compile:app and restart the CLSI service afterwards."

He/She wrote this as a comment to another question, asking whether some option could be passed to the latex-command.

I haven't yet used \tikzexternalize, but from what i found online, you would only have to add -shell-escape as an option to the appropriate commands there. Be sure you check for each compiler, if the option exists and is named correctly, since, as I said, I am no expert in this.

The remaining question the sharleatex team has to answer is: Are there problems which would lead to sharelatex not being able to access/manage/delete (upon cleanup) these generated pdf files?

**Comment by fernandoandreotti** [comment]
When I compile my document locally it works fine. I guess for security reasons Sharelatex does not yet widely support -shell-escape commands. For me such feature would be convenient to speed up the compilation process when writing articles with heavier tikz graphs. Here follows a MWE of the problem.

If you create a sharelatex document with the following code...
```
\documentclass{article}
\usepackage{pgfplots}
\usetikzlibrary{external}
\tikzexternalize

\begin{document}
\begin{figure}
  \tikzsetnextfilename{figure}
  \begin{tikzpicture}
      \draw (0,0) -- (10,10); % ...
\end{tikzpicture}
\end{figure}
\end{document}
````

after compiling you get the following error ..

> Package tikz Error: Sorry, the system call 'pdflatex -shell-escape -halt-on-error -interaction=batchmode -jobname "figure" "\def\tikzexternalrealjob{output}\input{output}"' did NOT result in a usable output file 'figure' (expected one of .pdf:.jpg:.jpeg:.png:). Please verify that you have enabled system calls. For pdflatex, this is 'pdflatex -shell-escape'. Sometimes it is also named 'write 18' or something like that. Or maybe the command simply failed? Error messages can be found in 'figure.log'. If you continue now, I'll try to typeset the picture.
> 
> 
> See the tikz package documentation for explanation.
> Type  H <return>  for immediate help.
>  ...                                              
>                                                   
> l.33 \end{tikzpicture}
>                       
> This error message was generated by an \errmessage
> command, so I can't give any explicit help.
> Pretend that you're Hercule Poirot: Examine all clues,
> and deduce the truth by order and method.

**Comment by Eothred** [comment]
Hmm, for me this seemed to work, if I instead of having the tikz code directly in the tex file, put it in a separate file figure.tikz, and used \input:

main.tex:
```
\documentclass{article}
\usepackage{pgfplots}
\usetikzlibrary{external}
\tikzexternalize

\begin{document}
\begin{figure}
 \input{figure.tikz}
\end{figure}
\end{document}
```
figure.tikz:
```
  \begin{tikzpicture}
      \draw (0,0) -- (10,10); % ...
\end{tikzpicture}
```

**Comment by nikolauskrismer** [comment]
Is there any progress regarding this problem??
Right now I am fighting with many tikzpictures and this would save a lot of time during compilation...

**Comment by nikolauskrismer** [comment]
Could this somehow be controlled with changing /usr/local/texlive/2016/texmf.cnf?
I tried to set "shell_escape = t" there, which did not help.

In my case even usetikzlibrary{external} does not seem to work...

**Comment by nikolauskrismer** [comment]
Hmm... according to the log I actually did suceed with the change in the texmf.cnf file.
However, the log generated by tikzexternalize is the following, so obviously something still does not work:

```
This is pdfTeX, Version 3.14159265-2.6-1.40.17 (TeX Live 2016) (preloaded format=pdflatex 2017.2.22)  17 AUG 2017 13:32
entering extended mode
 \write18 enabled.
 %&-line parsing enabled.
**\def\tikzexternalrealjob{output}\input{output}^^M
! Emergency stop.
<read *> 
         
<*> \def\tikzexternalrealjob{output}\input{output}
                                                  ^^M 
Here is how much of TeX's memory you used:
 6 strings out of 494945
 168 string characters out of 6180678
 45269 words of memory out of 5000000
 3401 multiletter control sequences out of 15000+600000
 3640 words of font info for 14 fonts, out of 8000000 for 9000
 14 hyphenation exceptions out of 8191
 4i,0n,3p,1b,8s stack positions out of 5000i,500n,10000p,200000b,80000s

!  ==> Fatal error occurred, no output PDF file produced!
```
The good news is, that write18is enabled, but the rest of the output does not point my anywhere (or at least I do not see it). What is the right log file to view now?

**Comment by jpallen** [comment]
We have fixed this in the latest version of ShareLaTeX (see https://github.com/sharelatex/clsi-sharelatex/blob/08fd440df5b8b07a0f4ed03edfc104854ecc1919/app/coffee/TikzManager.coffee), but it's possible that this hasn't yet made it into the latest release version yet. Which version are you running?

**Comment by fernandoandreotti** [comment]
I can confirm that on ShareLateX's webversion the MWE I originally submitted now runs without outputting any errors.

**Comment by nikolauskrismer** [comment]
An update was performed today (to be sure), but this still does not work.

Is there any place I can see the version number of the current installation??... maybe the update did not work as expected (I used '''docker-compose up''' after removing the sharelatex docker-folder, but not the sharelatex_data folder, so maybe there is still something missing).

**Comment by mserranom** [comment]
Closing, was fixed in https://github.com/sharelatex/clsi-sharelatex/blob/08fd440df5b8b07a0f4ed03edfc104854ecc1919/app/coffee/TikzManager.coffee

**Comment by thebarnable** [comment]
In the [toolkit repo](https://github.com/overleaf/toolkit), this issue seems to persist. The original MWE from Fernando produces the errors he reported in my case.

**Comment by joneuhauser** [comment]
If you hit the error experienced by @nikolauskrismer (and come here searching for it), then a possible cause is that the `\tikzexternalize` command is not in the main file, but hidden in an `\include` statement. At least this fixed the error for me.

**Comment by MayeulC** [comment]
> If you hit the error experienced by @nikolauskrismer (and come here searching for it), then a possible cause is that the `\tikzexternalize` command is not in the main file, but hidden in an `\include` statement. At least this fixed the error for me.

Thank you, that also solved it for me. A possible workaround I haven't tried could be [here](https://tex.stackexchange.com/q/273898). It seems that tikzexternalize doesn't like `-jobname` a lot.

**Comment by jecs** [comment]
> If you hit the error experienced by @nikolauskrismer (and come here searching for it), then a possible cause is that the `\tikzexternalize` command is not in the main file, but hidden in an `\include` statement. At least this fixed the error for me.

This applies to `\input` as well.

**Comment by ibpop** [comment]
I am using Overleaf toolkit community edition and still having this problem.

This is the template I try to compile: https://www.overleaf.com/project/new/template/27519?id=1174669946&templateName=Example+to+externalize+a+TikZ+graphic&latexEngine=pdflatex&texImage=texlive-full%3A2022.1&mainFile=

`
\documentclass{article}
\usepackage{tikz}
\usetikzlibrary{external}
\tikzexternalize[prefix=tikz/]

\begin{document}
% This TikZ figure will be written to
% a file called 'output-figure0.pdf' 
% within the 'tikz' folder
\begin{tikzpicture} 

  \node {root}
    child {node {left}}
    child {node {right}
      child {node {child}}
      child {node {child}}
    };

\end{tikzpicture}

\end{document}
`

And it gives me the same error:
`Package tikz Error: Sorry, the system call 'pdflatex -halt-on-error -interaction=batchmode -jobname "tikz/output-figure0" "\def\tikzexternalrealjob{output}\input{output}"' did NOT result in a usable output file 'tikz/output-figure0' (expected one of .pdf:.jpg:.jpeg:.png:). Please verify that you have enabled system calls. For pdflatex, this is 'pdflatex -shell-escape'. Sometimes it is also named 'write 18' or something like that. Or maybe the command simply failed? Error messages can be found in 'tikz/output-figure0.log'. If you continue now, I'll try to typeset the picture.`

Anyone had this in recent time?

**Comment by mlevans0** [comment]
Hey @ibpop, The `\write18` command is **disabled** by default in the Community Edition due to all compiles happening within the same **sharelatex** container, and all things considered, it is the safer default option for this particular type of installation. 

Should you wish, you can enable this for pdflatex by creating a **latexmkrc** file in the root of your project with the content `$pdflatex = 'pdflatex --shell-escape';` and then try recompiling.

**Comment by ibpop** [comment]
> Hey [@ibpop](https://github.com/ibpop), The `\write18` command is **disabled** by default in the Community Edition due to all compiles happening within the same **sharelatex** container, and all things considered, it is the safer default option for this particular type of installation.
> 
> Should you wish, you can enable this for pdflatex by creating a **latexmkrc** file in the root of your project with the content `$pdflatex = 'pdflatex --shell-escape';` and then try recompiling.

Thanks for the reply!
I did find this solution in some stackoverflow question. I think it should be added to the documentation.
