### ISSUE TITLE
Allow --enable-pipes option

### ISSUE THREAD

**Issue by zeigerpuppy** [overleaf/overleaf#421]
I am trying to do inline word counts in a document, 
and would like to use a command like:

``` latex
\input{|"texcount article.tex"}
```

I believe that this command fails as it needs the `--enable-pipes` option when compiling.
I know that this is a security hole, but may be good to allow it optionally (controlled by admin, perhaps on a per-user basis).

**Comment by hulk1st** [comment]
Hi,

Not sure if this helps but you can pass options to be passed in ```/var/www/sharelatex/clsi/app/coffee/LatexRunner.coffee ```. Make sure to run ```sudo grunt compile:app``` and restart the CLSI service afterwards.

**Comment by zeigerpuppy** [comment]
the following approach works:
ref: https://tex.stackexchange.com/a/117532/29970

add to preamble
```latex
\usepackage{moreverb} % for verbatim ouput
```

```latex
\immediate\write18{texcount -inc -incbib 
-sum article.tex > /tmp/wordcount.tex}
\newcommand\wordcount{
\verbatiminput{/tmp/wordcount.tex}}

\wordcount
```
