### ISSUE TITLE
Feature request: Can't upload folders, only files

### ISSUE THREAD

**Issue by ghost** [overleaf/overleaf#423]
My images/pdf-files are typically in a folder hierarchie. I prepare the images for my chosen size of X inches or centimeter and convert them to pdf. Then I need to upload the files to sharelatex while preserving my folder structure. In order to achieve this I need to manually create each folder on sharelatex first and then select that folder and upload the files into it. Quite the tedious task.

This shouldn't be too hard to accomplish, I hope. Any chance of getting this on the todo list?

**Comment by filipre** [comment]
I also have this issue. I wanted to upload a package with thousands of files inside it. Uploading them in batches of 40 is simply not possible:

<img width="610" alt="screen shot 2018-08-18 at 11 52 39" src="https://user-images.githubusercontent.com/8502198/44298125-b0a6e580-a2dd-11e8-8c34-dc12d7713687.png">

<img width="568" alt="screen shot 2018-08-18 at 11 53 14" src="https://user-images.githubusercontent.com/8502198/44298137-c74d3c80-a2dd-11e8-8738-88fa8ac58ee4.png">

Related: #537

**Comment by windhaunting** [comment]
I have the same issues. uploaded folders with nested folders. All the files uploaded will be put in the same level.

**Comment by pranav-asthana** [comment]
Can we please fix this?

**Comment by StarPrecursor** [comment]
This feature is very useful, please implement. Thanks!

**Comment by RichardLee0211** [comment]
Yes, we need this.

**Comment by GaPhil** [comment]
+1

**Comment by saratrajput** [comment]
+1

**Comment by vedshastry** [comment]
+1, it will be great to have this feature implemented!
Uploading folders is valuable functionality which saves time on large projects (where files are often scattered in subfolders).

**Comment by ssgosh** [comment]
As a workaround, I download the project as a zipped file, unzip it, then add whatever files/folders I need, zip it again, and create a new project with the zipped folder

**Comment by tobiasforest** [comment]
+1. it'll be great to enable the unzip feature on overleaf
