### ISSUE TITLE
Code Folding for \subsubsection doesn't work right

### ISSUE THREAD

**Issue by ghost** [overleaf/overleaf#427]
Unless this is somehow intended, the code folding for \subsubsection only goes to the next latex command, for example a figure or just a label sometimes. I haven't yet seen a consistent behavior. If someone please could have a look?

Note: It works just fine with \subsection and \section. Haven't tested it for \chapter.

**Comment by hrjakobsen** [comment]
This issue was resolved, so I'll close it. If you have any problems, feel free to reopen the issue or create a new one.
