### ISSUE TITLE
Word count issue

### ISSUE THREAD

**Issue by ralotaibi** [overleaf/overleaf#431]
Hi,
Word count was working fine with me. I have my thesis as the main document that includes several files using \input. Since yesterday, word count reports only 2 words with all others zero such as math. Do you know what could the problem? BTW, I tried \include instead of \input, but still no luck.
Reem

**Comment by das7pad** [comment]
Hello,

Thanks for the report. I'm sorry it took so long for us to get back to you! In case you are still having issues with the wordcount feature, please let us know.

Greetings,
Jakob
