### ISSUE TITLE
Linking to github fails

### ISSUE THREAD

**Issue by julianhinz** [overleaf/overleaf#445]
When trying to link to github, i.e. creating new repository, I get this error message:
![screen shot 2016-07-12 at 5 34 35 pm](https://cloud.githubusercontent.com/assets/2875267/16773121/f389324c-4856-11e6-817b-4618b630c697.png)

Any way to get rid of this?

**Comment by davidliu2012** [comment]
I have the same issue. Haven't found any solution yet.

**Comment by das7pad** [comment]
Hello,

Thanks for the report. I'm sorry it took so long for us to get back to you! The GitHub-sync feature is not included in Overleaf Community Edition. Please reach out to the [Overleaf.com support](https://www.overleaf.com/contact) in case you are still having issues linking with GitHub.

Greetings,
Jakob
