### ISSUE TITLE
There is no HostIP for sharelatex Docker

### ISSUE THREAD

**Issue by ZamanOof** [overleaf/overleaf#446]
I try to run sharelatex using this command 
`docker run -d \
  -v ~/sharelatex_data:/var/lib/sharelatex \
  -p 5000:80 \
  --name=sharelatex \
  sharelatex/sharelatex`
I check 
`http://localhost:5000`
 but it was'nt work,and try to change port but still not work 
and try to submit HostIP try using these commands
`docker run -d   -v ~/sharelatex_data:/var/lib/sharelatex  -p 5000:80  --name=sharelatex   sharelatex/sharelatex -e "DOCKER_HOST=$(ip -4 addr show eth0| grep -Po 'inet \K[\d.]+')"
`
and this command 
`docker run -d   -v ~/sharelatex_data:/var/lib/sharelatex  -p 5000:80  --name=sharelatex   sharelatex/sharelatex -it --net="host"
`
and this command 
`docker run -d   -v ~/sharelatex_data:/var/lib/sharelatex  -p 5000:80  --name=sharelatex   sharelatex/sharelatex -e "DOCKER_HOST=$(ip -4 addr show docker0 | grep -Po 'inet \K[\d.]+')"`
and this command
`docker run -d   -v ~/sharelatex_data:/var/lib/sharelatex  -p 5000:80  --name=sharelatex   sharelatex/sharelatex -e "DOCKER_HOST=$(ip -4 addr show enp3s0| grep -Po 'inet \K[\d.]+')"
`
all of commands when run command
`docker inspect sharelatex`
the result was 
`[
    {
        "Id": "a6a43150ba41fe447d7493f925cced17beecbed240c1547ba90f92b3c0f2f334",
        "Created": "2016-07-16T05:32:38.929978205Z",
        "Path": "/sbin/my_init",
        "Args": [
            "-e",
            "DOCKER_HOST="
        ],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 2,
            "Error": "",
            "StartedAt": "2016-07-16T05:32:40.374257282Z",
            "FinishedAt": "2016-07-16T05:32:41.23310693Z"
        },
        "Image": "sha256:8c69309bc22e26728593f65b12425ec3dc34decd4a363a6f5f67ddcf93e4b95a",
        "ResolvConfPath": "/var/lib/docker/containers/a6a43150ba41fe447d7493f925cced17beecbed240c1547ba90f92b3c0f2f334/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/a6a43150ba41fe447d7493f925cced17beecbed240c1547ba90f92b3c0f2f334/hostname",
        "HostsPath": "/var/lib/docker/containers/a6a43150ba41fe447d7493f925cced17beecbed240c1547ba90f92b3c0f2f334/hosts",
        "LogPath": "/var/lib/docker/containers/a6a43150ba41fe447d7493f925cced17beecbed240c1547ba90f92b3c0f2f334/a6a43150ba41fe447d7493f925cced17beecbed240c1547ba90f92b3c0f2f334-json.log",
        "Name": "/sharelatex",
        "RestartCount": 0,
        "Driver": "aufs",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/home/ali/sharelatex_data:/var/lib/sharelatex"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "80/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "5000"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "StorageOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "BlkioIOps": 0,
            "BlkioBps": 0,
            "SandboxSize": 0
        },
        "GraphDriver": {
            "Name": "aufs",
            "Data": null
        },
        "Mounts": [
            {
                "Source": "/home/ali/sharelatex_data",
                "Destination": "/var/lib/sharelatex",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "a6a43150ba41",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "80/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/texlive/2016/bin/x86_64-linux/",
                "HOME=/root",
                "baseDir=.",
                "SHARELATEX_CONFIG=/etc/sharelatex/settings.coffee"
            ],
            "Cmd": [
                "-e",
                "DOCKER_HOST="
            ],
            "Image": "sharelatex/sharelatex",
            "Volumes": null,
            "WorkingDir": "/",
            "Entrypoint": [
                "/sbin/my_init"
            ],
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "db39a4d227e8d7f1b487cce4b8cb22e20cfb7e866531d29b16dace1265f9bc61",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": null,
            "SandboxKey": "/var/run/docker/netns/db39a4d227e8",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "8da96ba5bc9ea47a40ad889bf8222289f748350680de9580eb59dea797b9931d",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": ""
                }
            }
        }
    }
]`
so what i need to do to make HostIP work
Best Regards

**Comment by das7pad** [comment]
Hello,

Thanks for the report. I'm sorry it took so long for us to get back to you! I'm afraid we do not officially support `docker run` based deployments moving forward. We recommend taking a look at our [Overleaf Toolkit](https://github.com/overleaf/toolkit) for deploying new instances of Overleaf Community Edition and [Server Pro](https://www.overleaf.com/for/enterprises).

Greetings,
Jakob
