### ISSUE TITLE
clsi crashes

### ISSUE THREAD

**Issue by quintard** [overleaf/overleaf#447]
sharelatex is installed on a dedicated server(Scientific Linux 7.x) since December 2015.
Now and then, let say after a month of fine running, the clsi service crashes.
clsi.log content : 
{"name":"clsi","hostname":"sharelatex.xxx","pid":11034,"level":40,"msg":"timeouts and sandboxing are not enabled with CommandRunner","time":"2016-07-14T18:07:25.473Z","v":0}
child_process.js:958
    throw errnoException(process._errno, 'spawn');
^
Error: spawn EMFILE

Any idea how to fix it ?
thanks

**Comment by quintard** [comment]
Could not find any idea of the resource values needed for sharelatex services
so I ending up by adding this line :
LimitNOFILE=10240 
in the section [Service]
of the file /etc/systemd/system/sharelatex@.service 
(sharelatex installed on Scientific Linux 7.x with systemd)

I would welcome any feedback.
thanks

**Comment by das7pad** [comment]
Hello,

Thanks for the report. I'm sorry it took so long for us to get back to you! We have not seen any reports for running out of file-handles on our more recent versions of Overleaf Community Edition and [Server Pro](https://www.overleaf.com/for/enterprises). Please let us know if you are still having issues after upgrading.

Greetings,
Jakob
