### ISSUE TITLE
grunt migrate : Warning: stdout maxBuffer exceeded

### ISSUE THREAD

**Issue by msimonin** [overleaf/overleaf#449]
I ran a grunt migrate (v0.2.0 -> v0.3.10) and I hit the max Buffer size for stdout : 

```
Warning: stdout maxBuffer exceeded. Use --force to continue.

Aborted due to warnings.
```

What could be the best way to proceed ? 
- use --force ?
- Increase the max buffer size in the Gruntfile (setting it to infinity for instance) ?
- other solution ?

**Comment by henryoswald** [comment]
hmmm sorry about that, how many docs do you have in your instance?

**Comment by msimonin** [comment]
something like 9000 docs to migrate.
I hit the limits around 8500.

Resuming the migration finished the work.

**Comment by henryoswald** [comment]
ok good to know, I will look into this. Out of interest who is using your instance (trying to get an idea of user base)

**Comment by msimonin** [comment]
I'm maintaining an instance at [Inria](https://www.inria.fr/en/) open to staff members and project partners.

**Comment by das7pad** [comment]
Hello,

Thanks for the additional information. We have not seen any similar reports in big upgrades from our [Server Pro](https://www.overleaf.com/for/enterprises) customers. I suspect either one of the major Node.js version upgrades or MongoDB library upgrades eliminated this limitation.

Greetings,
Jakob
