### ISSUE TITLE
Wiki: Add AdminUser

### ISSUE THREAD

**Issue by PatWie** [overleaf/overleaf#462]
The [wiki](https://github.com/sharelatex/sharelatex/wiki/Creating-and-managing-users) says

`grunt create-admin-user --email joe@example.com`

But this has to be

`grunt user:create-admin --email joe@example.com`

**Comment by Zeawiel** [comment]
This one should work too: 

`grunt create-admin-user --email=joe@example.com`

**Comment by hrjakobsen** [comment]
The wiki was updated, so I'll close this issue.
