### ISSUE TITLE
Feature request: Freeze project

### ISSUE THREAD

**Issue by rahmati** [overleaf/overleaf#463]
It would be great if we can freeze a project so it can not be modified after it is finalized without jumping through a hoop.

**Comment by ShaneKilkelly** [comment]
Hi! that's actually a pretty interesting feature request. This repo is mostly for issues found while running the on-site version of overleaf. Could you relay this feature request to support@overleaf.com please? Then it can be run through our usual feature-request pipeline. Thanks!

**Comment by rahmati** [comment]
Done!
