### ISSUE TITLE
Double filenames are allowed, but should not be.

### ISSUE THREAD

**Issue by duesee** [overleaf/overleaf#466]
See https://www.sharelatex.com/project/57caf608e3e076bd1e80177d

Both files were created via the GUI.

When downloading the whole project as a zip, only one file is contained in the archive. This could possibly lead to data loss. Not sure if this is a security vulnerability also...

**Comment by johannesschweig** [comment]
This also happens when you drag a file into a folder and there is already a file with the same name.

**Comment by mserranom** [comment]
Thanks for the report, this is still happening.

**Comment by ShaneKilkelly** [comment]
I think this has been fixed recently. Will close this ticket. Thanks for bringing it to our attention!
