### ISSUE TITLE
Change project owner

### ISSUE THREAD

**Issue by awasthi** [overleaf/overleaf#469]
Sharelatex is really a good project. I feel there should be owner change feature in case of shared projects.

**Comment by samusangio** [comment]
+1 for this feature 
Perhaps one could consider that the initial owner can grant sharing permissions to other users. It would be an extension of the sharing feature (right now limited to "read only" and "can edit") to include "can edit & share"

**Comment by tiagodanielff** [comment]
+1 for this feature. 
In companies, you don't want to have locked projects with users who have already abandoned the organization.

**Comment by fnoble** [comment]
+1
I have a project that has now been handed off to a different team and I'm slowing them down by having to manage the doc's sharing for them. I really just want to transfer ownership of the doc.

**Comment by usethedata** [comment]
+1.  Anyone know if there's a way to do this under the covers for an on-prem(internally hosted) version?

**Comment by bzduso** [comment]
+1. Any updates on this?

**Comment by NetherGranite** [comment]
Hopefully this will make it into Overleaf 2?

**Comment by jdleesmiller** [comment]
Thanks for the feedback. We definitely plan to add this feature, but we don't have a definite timeline as yet, sorry.

**Comment by computermacgyver** [comment]
Any update on this? I would love to see this in Overleaf 2.

**Comment by rfabbri** [comment]
Need this. The project owner is not an expert and I can't sit next to him.

**Comment by DeltiKron** [comment]
Need this feature as well!

**Comment by a-MyP** [comment]
+1 
It would be really helpful to have this feature.

**Comment by armostafizi** [comment]
+1

**Comment by panholzerp** [comment]
+1

**Comment by meenurajapandian** [comment]
+1 Need this as it is difficult to transfer overleaf projects (especially ones with multiple files) while changing/leaving teams/organizations.

**Comment by lenov** [comment]
This is such a basic feature to have for a collaborative edition tool! I left an employer 6 month ago but I am still owner of a the overleaf projects. The subscription will not be renewed next month. Now what? What happen to those projects? I have to say, this is a very good reason to migrate to other tools that allow to control the "roles" of people involved.

**Comment by jdleesmiller** [comment]
Thanks for the feedback, everyone. We are planning to add this feature soon.

Until then, the best workaround is for the new owner to make a copy of the project from their dashboard and re-invite their remaining collaborators. (We know that's not ideal.)

**Comment by ttsc** [comment]
+1 I absolutely need this feature as well. Do you have any timeline about when this feature will be available? I can see that i has been requested already two and half years ago.

**Comment by JoonasD6** [comment]
+1 again and waiting for roadmap. :)

**Comment by jramiresbrito** [comment]
+1

**Comment by cynosure4sure** [comment]
+1

**Comment by Mrrvm** [comment]
+1

**Comment by scotronq** [comment]
+1

**Comment by knedlyk** [comment]
+1

**Comment by cjwayn** [comment]
+1

**Comment by fkeel** [comment]
Could we also have shared ownership? This would be super valuable.

**Comment by arunpersaud** [comment]
+1 we often have people in our group for a short time and it would be great to keep access to their documents once they are gone and often their email account is gone too

**Comment by jane2L** [comment]
+1 ! And since the feature is supposed to be implemented soon since 2018, I hope it will really come soon!

**Comment by 14shreyasp** [comment]
+1! Would really love an update on when this feature can be made available

**Comment by AnthonyVogliano** [comment]
+1

**Comment by csherstan** [comment]
+1

**Comment by DanielMarcato** [comment]
need this urgently

**Comment by greergo** [comment]
Agree with Daniel Marcato.

**Comment by popoiopo** [comment]
+1

**Comment by mtekman** [comment]
+1

**Comment by jdleesmiller** [comment]
Hi folks, we are working on this now. You can stop with the +1s!

**Comment by DanielMarcato** [comment]
Just to emphasize what I want from a "changing owner" feature @jdleesmiller :
If I am the current owner of a project that I shared with somebody else, then I need to be able to grant them ownership, remove myself from the project, delete it in my projects overview and they still need to be able to keep the project in their workspace to continue the work we initially did together.

**Comment by igorsteinmacher** [comment]
:+1:

**Comment by emcsween** [comment]
This feature was released last month. Please see the [blog post](https://www.overleaf.com/blog/new-feature-transfer-project-ownership-on-overleaf) for details.

**Comment by igorsteinmacher** [comment]
Thanks a lot. This is really useful

**Comment by ttsc** [comment]
Thanks!

**Comment by mukul54** [comment]
I am still unable to transfer the project ownership.
