### ISSUE TITLE
New feature: Vertical split view for editor and PDF

### ISSUE THREAD

**Issue by chuckjia** [overleaf/overleaf#471]
I hope there is a new feature in sharelatex where we can choose to vertical and horizontal split views. When using laptops, since the screens are relatively small, I feel that it's more convenient to use vertical views. In that way, even on a small screen, we can always see whole lines with not too small font size.

**Comment by ermisp** [comment]
That would be very nice if possible. Some people have vertical screens :)

**Comment by 2sls** [comment]
Would love to see this feature...

**Comment by toshi2k2** [comment]
Would be great to have!

**Comment by wiedenhoeft** [comment]
I'm using a pivoting display for all text-related work, which seems to be increasingly common. This feature is a must :-)

**Comment by Joe-annie** [comment]
Use vertical monitor, need this feature

**Comment by praksharma** [comment]
I also need this feature. Editing long documents is a nightmare.

**Comment by mserranom** [comment]
We shipped PDF Detach in Overleaf CE and Server Pro 3.2.0. You should be able to detach the PDF view from the main browser window and place it at your convenience in the screen. I think this covers the user case, I'll close the issue.

 https://github.com/overleaf/overleaf/wiki/Release-Notes-3.x.x#server-pro-320
https://www.overleaf.com/blog/new-feature-ready-set-detach
