### ISSUE TITLE
Problem while typing accents in Chrome 

### ISSUE THREAD

**Issue by caiolopes** [overleaf/overleaf#473]
I am having problem trying to type words with accents just in Chrome (with Safari and Firefox it is fine!)

Basically it is happening is showing in the gif:

![image](https://media.giphy.com/media/26gJyAXd42oHKVnkk/giphy.gif)

While the expected behaviour should be:

![image](https://media.giphy.com/media/l0HlDakpwxgwgMYW4/giphy.gif)

Someone knows how to fix this?? 

Thanks!!

**Comment by ggirotto** [comment]
I'm having the same issue :/

**Comment by victorbluhu** [comment]
I'm having the same issue :/ [2].

**Comment by henryoswald** [comment]
we are planning to look into this.

**Comment by akawano** [comment]
I am also having the same problem. A certain Michael from ShareLaTeX support tried to help me, but we had no success. 
Chrome Versione 53.0.2785.143 (64-bit).
MacOS Yosemite 10.10.5

**Comment by cmcisaac6** [comment]
This should be resolved now. If there are still issues, please re-open or create a new issue (with updated GIFs, as I cannot see them anymore).
