### ISSUE TITLE
docker-compose and SHARELATEX_SECURE_COOKIE=true gives cookie error

### ISSUE THREAD

**Issue by bonanza123** [overleaf/overleaf#476]
I just used the provided docker-compose file to setup a sharelatex instance. 
The only modification I made was to add:

```
SHARELATEX_SECURE_COOKIE: "true"
```

to the `environment:` part of sharelatex, as the docker is running behind a nginx with SSL/TLS on.
Then I used `$ docker exec sharelatex /bin/bash -c "cd /var/www/sharelatex/web; grunt create-admin-user --email joe@example.com"` to create the admin account. When I copied the shown URL to my browser, it showed me the "reset password" field where I entered the same mail address.
Then I got the error message:

```
Session error. Please check you have cookies enabled. If the problem persists, try clearing your cache and cookies.
```

In Firefox and Chromium, also after cleaning caches and cookies.

Edit: With the default docker-compose file it works, but then the cookie directive "secure" is not set (only `httpOnly` is set)

**Comment by tabilzad** [comment]
also experiencing the same issue when running in Unraid docker container

**Comment by mserranom** [comment]
Try setting `SHARELATEX_BEHIND_PROXY=true`, as described in https://github.com/overleaf/overleaf/wiki/HTTPS-reverse-proxy-using-Nginx#configuration-for-overleaf-to-run-with-ssl

**Comment by tabilzad** [comment]
Thanks @mserranom turned out cache/cookies was in fact the problem as I tried in Incognito window

**Comment by mserranom** [comment]
Glad to hear that!
