### ISSUE TITLE
File extensions

### ISSUE THREAD

**Issue by eren-ck** [overleaf/overleaf#478]
Hey, 

what file types do you support in the Online-LaTeX-Editor?

The Online-LaTeX-Editor does not open files with the extension *.inc. Renaming them everytime to *.tex files is not convenient.  Is support for *.inc files planned in further releases? Further it would be nice if you could add a list of supported types to your documentation. 

Thanks, 
Eren

**Comment by henryoswald** [comment]
Hi,

what usage do you have for a inc file?

**Comment by eren-ck** [comment]
Hi, 

there are various conference templates using .inc files. For example this [template](http://eurovis2017.virvig.es/images/site/EuroVis2017FullPapers_latex2e.zip) is using .inc files. 

Thanks,
Eren
