### ISSUE TITLE
link with bibtex database

### ISSUE THREAD

**Issue by andrewfowlie** [overleaf/overleaf#49]
I would like to suggest a new feature; would it be possible to link with on-line databases of `BibTeX` entries?

In physics, if you wish to cite a paper, you have to navigate to its page in the inSPIRE database, copy and paste its BibTeX entry to your BibTeX file, and cite the BibTeX`key in your LaTeX file.

E.g., the `inSPIRE` databaes page http://inspirehep.net/record/687657/export/hx contains

```
 @article{Hawking:2005kf,
  author         = "Hawking, S.W.",
  title          = "{Information loss in black holes}",
  journal        = "Phys.Rev.",
  volume         = "D72",
  pages          = "084013",
  doi            = "10.1103/PhysRevD.72.084013",
  year           = "2005",
  eprint         = "hep-th/0507171",
  archivePrefix  = "arXiv",
  primaryClass   = "hep-th",
  reportNumber   = "DAMTP-2005-66",
  SLACcitation   = "%%CITATION = HEP-TH/0507171;%%",
}
```

All that copying and pasting is quite annoying.  A slight improvement is this https://github.com/rescolo/getinspire package, which were I to `\cite{Hawking:2005kf}` or `\cite{hep-th/0507171}` would automatically scrape the BibTeX entry from the inSPIRE database and put it into my BibTeX file. 

That still requires that you navigate to the inSPIRE webpage to find the BibTeX key, but it is better than having to also copy and paste BibTeX entries.

**Comment by beta2k** [comment]
yes! +1 for autocomplete for \cite{} et al.

**Comment by innisfree** [comment]
+1 from me too, autocomplete \cite{} (as well as autocomplete \ref for labels in the document) would be a great feature. Probably not at all tricky?

**Comment by ceriottm** [comment]
autocomplete \cite is really  a must-have feature. any timeline on the implementation?

**Comment by retorquere** [comment]
@jpallen remote links work for biblatex; it's how many people use the better-bibtex HTTP export. If share latex has an API, better-bibtex can be made to push changes to sharelatex.

**Comment by ebertini** [comment]
+1 for autocomplete, even just for the local bib file. Please add it!!! Thanks.

**Comment by dklesev** [comment]
+1 for autocomplete

**Comment by matthiasnielsen** [comment]
I agree with ebertini - autocomplete from a local .bib file would be a great addition!

Reason: My main annoyance is the focus shift required to go look a specific reference while writing.

**Comment by beta2k** [comment]
local bib file will not be possible due to security restrictions... from the browser you cant access the local file-system. however, there could be a solution with cloud services: you could place your local bib-file in a dropbox folder and share-latex could read it from there. that would work, i guess.

**Comment by matthiasnielsen** [comment]
Yeah, I wasn't clear: I meant project-local .bib file :)
