### ISSUE TITLE
FR: Fix \usepackage autocomplete

### ISSUE THREAD

**Issue by ehknight** [overleaf/overleaf#494]
When I'm typing a `\usepackage` command, I get the following autocomplete options:
`\usepackage[]{}`
`\usepackage{}`

So then when I press `tab`, I get the first one and have to delete the square brackets. AFAIK, the second one is used much more often, so it would make sense to prioritize that first.

**Comment by ShaneKilkelly** [comment]
I think this feature was added in the last year or so. Will close this ticket. Thanks!
