### ISSUE TITLE
Docker image fails to start services (512 Bad Gateway)

### ISSUE THREAD

**Issue by ovm-asharp** [overleaf/overleaf#496]
After running the commands verbatim from the [quickstart]( https://github.com/sharelatex/sharelatex/wiki/Quick-Start-Guide), when i visit the url i get a 512 Bad Gateway. This happens if the ~/sharelatex_data directory exists or not.

The specific docker command was

> docker run -d \
>   -v ~/sharelatex_data:/var/lib/sharelatex \
>   -p 5000:80 \
>   --name=sharelatex \
>   sharelatex/sharelatex
`

The command itself returned successfully, and the container did start, as did nginx, but it looks like something else fails to load.

I thought this was due to lack of an admin user, but when I ran the add admin user command I received 

> Loading "Gruntfile.coffee" tasks...ERROR
> Error: ENOENT, no such file or directory \'user:create-admin\'
>
> Running user:create-admin" task
> {"name":"default-sharelatex","hostname":"b950479f4f19","pid":136,"level":40,"msg":"Email transport > and/or parameters not defined. No emails will be sent.","time":"2016-11-22T19:56:46.584Z","v":0}
> Fatal error: Redis connection to dockerhost:6379 failed - connect ECONNREFUSED

Which also seems to point to something being broken in terms of init.

This is on ubuntu 16.04 with their packaged docker.

**Comment by henryoswald** [comment]
it looks like "Fatal error: Redis connection to dockerhost:6379 failed - connect ECONNREFUSED" is staying the redis connection isn't working, maybe its not mapped correctly.

**Comment by bluebottle2** [comment]
So reading between the lines I take it that 
> This will download the ShareLaTeX image and start it running in the background on port 5000. You should be able to access it at http://localhost:5000/.

Isn't meant to actually give you a working image, like I was expecting.

Would you mind shoving a note on the quick start that it'll fail without bringing up the other services? Maybe "This will start the container, but the application can't start until you bring up redis and mongo?"

Also, the packaged version of docker-compose breaks on the docker-compose.yml. Upstream seems to work though. 

Aside from that, thanks :)

**Comment by henryoswald** [comment]
i've added a note. Which  packaged version of docker-compose are you talking about?

**Comment by yliu-xjtu** [comment]
I have encountered the same problem. After I tried to close my firewall (ufw) temporally, it works. You can have a try.
(1) Close ufw at first:
 `sudo ufw disable`
(2) Try to creating and managing users again:
`$ docker exec sharelatex /bin/bash -c "cd /var/www/sharelatex; grunt user:create-admin --email joe@example.com"
`
After succeed, you can change the password for your created account through provided link:
> http://localhost:5000/user/password/set?passwordResetToken=<your token>
