### ISSUE TITLE
Recompile shortcut not working in full screen mode

### ISSUE THREAD

**Issue by fandu** [overleaf/overleaf#497]
Please tell us the following when opening an issue

- Official Docker version being run: none
- URL to appropriate logs: none

Environment: Mac + safari browser. Official sharelatex.com with subscription.

Issue: at the top right corner you can click to switch between "Split screen" and "Full screen". You can use shortcut cmd + enter to recompile. This shortcut works in split screen mode, but not working in full screen mode.

**Comment by fandu** [comment]
Possible cause: the cursor needs to stay in the editor in order to trigger the shortcut.

**Comment by ShaneKilkelly** [comment]
I think your theory is right, the shortcut is only triggered when the editor is focused. We'll keep this in mind when updating the editor in future.

**Comment by das7pad** [comment]
Hello,

A lot has changed since 2016, Overleaf.com and sharelatex.com have merged now. The latest version of Overleaf.com handles the `cmd + enter` shortcut in the editor-only mode as well for triggering a recompile of your document.

Greetings,
Jakob
