### ISSUE TITLE
Lost connection , Reconnection in 1 secs

### ISSUE THREAD

**Issue by zhonger** [overleaf/overleaf#498]
- Official Docker version being run:1.12.1
- URL to appropriate logs: none

Hi,
When I want to open a latex project, it always prompt me that `Lost connection, Reconnection in 1 secs`. After reconnection, it may be again. Sometimes, it can be the project page completely. Is there some problems in configure ?
The URL to the web is  [http://latex.luish.cc](http://latex.luish.cc)
Thank you !

**Comment by simsong** [comment]
I don't know why this was closed; it is still a problem, even with the production Overleaf.

**Comment by tsbertalan** [comment]
Yeah, poor wifi is a cop-out for overly stringent timeouts. I sometimes get this, and, though no one is doing simultaneous edits, I'm told that the editor is out of sync. It seems that there's a half-baked offline changes resolution mechanism, that doesn't properly realize that that there is no conflict between the unsynced offline edits and the server state, but instead just throws out the offline edits.
