### ISSUE TITLE
Add dot2tex package to CLSI

### ISSUE THREAD

**Issue by jpallen** [overleaf/overleaf#5]

**Comment by carlthome** [comment]
Did this ever get fixed? Noticed that the issue you linked to is gone. 

I'm unable to get `dot2texi` working even with the simplest examples:
>Package dot2texi Warning: Please convert output-dot2tex-fig1.dot manually.

**Comment by joaoquintas** [comment]
I think this is not solved yet.

[output.log.txt](https://github.com/sharelatex/sharelatex/files/952319/output.log.txt)
