### ISSUE TITLE
\cite and \ref autocomplete 

### ISSUE THREAD

**Issue by gianvito** [overleaf/overleaf#502]
Official Docker version being run: 1.12.5 build 7392c3b
URL to appropriate logs: none

Hi all,
I know that the \cite and \ref autocomplete function are now available in ShareLatex, as can be read here:
https://it.sharelatex.com/blog/2016/02/09/autocomplete-of-references-eaiser-citing.html

However, it seems that it does not work in the community edition. Is this function not available here or has it to be somehow activated?

Thank you

**Comment by vladislavivanistsev** [comment]
Docker  version 0.5.10

The autocomplete function does not work. A similar question remains unanswered at https://github.com/sharelatex/sharelatex/issues/452 Is there a way to activate this functions.

Thank you

**Comment by xoxys** [comment]
Is anybody watching and actively maintaining the community version? There seems to some more gaps between community and online version. That's not a big fault but i can find absolutely no documentation of available features for the community version... not very transparen. If you need some help for documentation and cleanup some other things i would like to help you. But therefor we need some more informations about current state of the community version.

**Comment by mserranom** [comment]
This feature is not available in Community Edition, but in [Server Pro](https://www.overleaf.com/for/enterprises) instead.

I agree a finer detailed documentation about differences between Community and Server Pro would be useful. Docs are a bit better now, hopefully that will help.
