### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by TiagoMRodrigues** [overleaf/overleaf#503]
Hello. I need to ask a question. If I am using sharelatex can I define what (crtl + I)  does? because I am using (ctrl + I) in words that are english in my portuguese written repport. and because what I am writting in english is mostly Artificial inteligence jargon that has no easy translation to portuguese I use the italic as it is a foreign word. but for babel is still portuguese and it hyphenate it wrongly. I would prefer something like \textit{\foreignlanguage{english}{Text in another language}} so it would hyphenate it correctly.

**Comment by ShaneKilkelly** [comment]
Hi! This is certainly an interesting case. Unfortunately we don't have control of how the italicisation works at that level of granularity. We'll keep this in mind for future work though, thanks for bringing it to our attention!
