### ISSUE TITLE
Mathematical mode on lstlisting

### ISSUE THREAD

**Issue by toni-1991** [overleaf/overleaf#505]
Hi,

In my projects I use to use the package listings and use enviroments lstlisting to introduce language codes. Lately I'm using R, that have $ as delimiter for elements such as iris$Species.

It don't give log errors or so, but in lstlisting, and I guess in every verbatim, $ is detected as math begining and all the colors functionality is broken with unpaired $ in the same verbatim enviroment.

**Comment by cmcisaac6** [comment]
Closing: This issue has now been resolved.
