### ISSUE TITLE
Raspberry pi

### ISSUE THREAD

**Issue by jucajuca** [overleaf/overleaf#510]
Please tell us the following when opening an issue

Hi, I'm trying to install sharelatex in a raspberry pi. The docker method is not working because the images are for other hardware architecture. 

I already installed all dependencies needed for the non-docker version, but I can't figure out how to install sharelatex without docker. Do you have somewhere the instructions for this?

- Official Docker version being run:
1.13.0
- URL to appropriate logs:
http://pastebin.com/NH3dQNca

**Comment by jucajuca** [comment]
I'm still trying to install sharelatex in my raspberry pi. 
I found the old installation instructions but I can't create the deb package because of [issue 292](https://github.com/sharelatex/sharelatex/issues/292).

As you know docker images can't run in different ***hardware*** architectures, so do you have a solution to install sharelatex in ARM based hardwar?

**Comment by henryoswald** [comment]
we don't sorry. And to be honest you probably don't want ShareLaTeX on a pi, latex will be very slow and ShareLaTeX needs a lot of memory to run.

**Comment by jucajuca** [comment]
@henryoswald good.
Why are you useing the deprecated installation file from nodejs? When I try to install it, it tells that this version is deprecated.

---> https://deb.nodesource.com/setup

Is sharelatex compatible with node 6+?

**Comment by henryoswald** [comment]
no it is not.

**Comment by snajak** [comment]
To Mr. Henry:

I am quite surprised of the politeness of your answer. Good software should be able to run on every system. It is interesting to see that you try to mob someone away. It is not your matter why he wants to run it on it. Maybe he just wants to run a private document to work on with 2 people. I guess sharelatex would be able to do this. To tell someone that you don't want him to run your software on a r-pi is rather ignorant than understanding means of open source. Maybe you should stay at least silent, when you do not want to help.

**Comment by jucajuca** [comment]
no worries, I realized myself that the architecture of sharelatex just needs unusual and unneeded amounts of memory for this kind of application. I can really recommend you to have a look at fiduswriter. it actually runs on a pi and the developers are very engaged in the project

**Comment by mserranom** [comment]
Closing this, as we're only supporting x86 architectures.

**Comment by lpyparmentier** [comment]
Interesting to have arm support in the future ! I don't think it is a good argument to avoid ARM architecture due to the limit hardware of RPI. There are plenty of fast ARM board now (e.g., https://www.picocluster.com/)... (even Mac computer going there). It consumes less which is great for energy, and I'm pretty sure that my rockpi4b (Hexa-Core (6) Rockchip RK3399 1.8GHz with 4GB memory) would be capable to run sharelatex for a small community (2 to 5 users).
