### ISSUE TITLE
Cursor misaligned with text in latest version of Safari

### ISSUE THREAD

**Issue by komodovaran** [overleaf/overleaf#515]
Using Safari 10.1 (12603.1.30.0.33) the cursor is misaligned. Additionally, the interface seems to be unhappy about code that progresses past 70-something characters per line.

For example, I can't fix this, because I can't reach all the way to the right side, and it seems that ShareLatex thinks that it's missing entirely.

<img width="698" alt="screen shot 2017-03-10 at 09 29 22" src="https://cloud.githubusercontent.com/assets/20357875/23787816/1836e3f2-0574-11e7-896c-466de61d738e.png">

Works in Chrome though.

**Comment by meijieru** [comment]
Same thing on linux with chrome

**Comment by thewoz** [comment]
hi I have the seme problem with safari 
Version 13.1 (14609.1.20.111.8)
The problem disappear if I use firefox

**Comment by jdleesmiller** [comment]
We think the latest incarnation of this problem is due to an upstream bug in Ace with non-unit zoom in Safari, which has recently been patched: https://github.com/ajaxorg/ace/issues/4234

We'll work on upgrading in due course.

**Comment by hrjakobsen** [comment]
The patch that @jdleesmiller mentioned was applied, and should have solved this issue. I'll close it for now, but if the issue persists, feel free to reopen it.
