### ISSUE TITLE
Suggestion: Create Electron App?

### ISSUE THREAD

**Issue by nicola** [overleaf/overleaf#518]
I love sharelatex, I started by using the sharelatex.com website, then, since I travel a lot and sometime I have no internet, I decided to run a docker image on my laptop, however, it is quite of annoying to do all of this setup (also, I always try to sync my local sharelatex with google drive)

It would be amazing if there is an electron app that I install on my computer that I can use offline and it will sync online.

Let me know if it is in your roadmap!

**Comment by Monadologie** [comment]
That's a great idea!
It would be very useful. But are you thinking about an electron app that could use local LaTeX version to create PDFs instead of using ShareLaTeX's servers? Or just a simple app which would not provide more features than the actual web does?

**Comment by nicola** [comment]
It should work offline, imho!
It is like hosting sharelatex locally!

**Comment by Monadologie** [comment]
Good luck for creating this electron app xD

**Comment by nicola** [comment]
why so?

**Comment by Monadologie** [comment]
ShareLatex is, for its major part, built on Coffee ...

**Comment by retorquere** [comment]
It's possible to run coffee in electron (atom did in the beginning), either by cross compiling or by including the runtime.

**Comment by seaneberhard** [comment]
I was just looking into a similar idea: running sharelatex locally on a chromebook. The web app is great with the chromebook, but when your internet connection is flakey you basically can't work. I thought it should be possible to run sharelatex locally from crouton and then use the web app from chrome OS (and maybe eventually package this up as a chromebook app), but unfortunately I couldn't get docker to run in crouton.

**Comment by ShaneKilkelly** [comment]
This is a much-requested feature that's been on our radar for a long time (building a fully local app), but because the overleaf system consists of multiple network services, plus a whole backend infrastructure for compiling latex, it's unlikely we'll be able to do this any time soon. Sorry folks!

In the meantime, if you need both the web interface and local editing, we suggest using either the Dropbox sync feature or the Git feature on Overleaf.com
