### ISSUE TITLE
Web client: extremely high memory usage

### ISSUE THREAD

**Issue by mizzao** [overleaf/overleaf#524]
Not sure if this is the right place to post this, but I'm wondering if I can help debug an issue with the web client (hosted on sharelatex.com). Lately I'm editing a document (10 page, normal scientific paper with some figures) and the online editor becomes extremely slow and laggy, sometimes needing seconds to process keystrokes.

When I look at the Chrome task manager I see that ShareLaTeX is using **2.6 GB of RAM**! Is this normal?

![image](https://cloud.githubusercontent.com/assets/2080084/25152127/0eab8508-2456-11e7-8315-02059edf9acb.png)

If I reload the tab the RAM usage goes down to 1.9 GB. Still very high, but also a huge change. Does this suggest a potential memory leak? If so, any way I can help debug? I'm happy to provide the ID of the document in question if anyone is looking to investigate.

![image](https://cloud.githubusercontent.com/assets/2080084/25152180/33b2391e-2456-11e7-92c8-b37de71ac6a6.png)

**EDIT**: A complete restart of the browser gets the document down to 129M:

![image](https://cloud.githubusercontent.com/assets/2080084/25152522/2b7cf468-2457-11e7-9829-4f9fb312bb16.png)

Now I'm very confused.

**Comment by henryoswald** [comment]
Hi Mizzao,

this is very interesting as we have just seen seen an unusual spike in the memory of some of our processes. It is possible something about your document is causing the issue. If you could send support@sharelatex.com the name/url we can look into it. Also please don't open it again until we have chance to look into it please!

**Comment by mizzao** [comment]
Sent you an e-mail. Also, see my last image above: a complete restart shaves a lot off the memory usage.

**Comment by mizzao** [comment]
One hint as to the issues: we are making extensive use of the (recent) track changes and commenting features, and toggling it on and off for various edits, and resolving comments and changes. So maybe processing all these are causing some "unconventional" resource usage server-side.

**Comment by vazeri** [comment]
ok

**Comment by zlepper** [comment]
I have also seen this problem is some of our documents, after having edited for a couple of hours I have to kill the browser and reopen sharelatex, as the editor has practically stopped responding. It's not as a rapid growth as Mizzao is seeing, but it's still there. 

We are not using any of the commenting features, and i doubt we are using track changes either, just normal edit and compile.

**Comment by Nurgy** [comment]
I would also suggest to see if you have too many photos or graphics in your document, this might cause the high usage of memory. This happened to me as I have it on docker and once I opened a document with text it is fine, but if the document contains some Excel sheet or a photo memory usage of Chrome goes to the sky. A complete restart is the only resolution in such cases. Cheers

**Comment by ShaneKilkelly** [comment]
Good points @Nurgy ! 

I'll close this issue as it's quite old and we've not heard much about excessive memory usage lately.

**Comment by vegardjervell** [comment]
I'm having this issue as well, if I've had the browser open for some hours memory usage grows until I have to wait for every other keystroke to register (at around 2.5G). Closing and reopening the tab made overleaf more responsive again, and reduced memory usage to about 700M (still quite high?). 

Just leaving this here in case it comes up again.
