### ISSUE TITLE
docker-compose SMTP settings formaterror

### ISSUE THREAD

**Issue by d0uwe** [overleaf/overleaf#538]
- Official Docker version being run: Docker version 17.05.0-ce, build 89658be
docker-compose version 1.13.0, build 1719ceb

I've tried many configurations for the docker-compose file to get SMTP working but there seems to be something wrong with the formats accepted. Whatever configuration I've tried, this error always shows up in the var/log/sharelatex/web.log file: 

`{"name":"web-sharelatex","hostname":"3b1985dc1d7e","pid":94,"level":50,"err":{"message":"Connection timeout","name":"Error","stack":"Error: Connection timeout\n    at SMTPConnection._formatError (/var/www/sharelatex/web/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/lib/smtp-connection.js:424:15)\n    at SMTPConnection._onError (/var/www/sharelatex/web/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/lib/smtp-connection.js:410:16)\n    at SMTPConnection.<anonymous> (/var/www/sharelatex/web/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/lib/smtp-connection.js:178:14)\n    at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)\n","code":"ETIMEDOUT"},"msg":"error sending message","time":"2017-05-17T17:50:25.260Z","v":0}`

Example given in docker-compose.yml

            `# SHARELATEX_EMAIL_SMTP_HOST: smtp.mydomain.com`
            `# SHARELATEX_EMAIL_SMTP_PORT: 587`
            `# SHARELATEX_EMAIL_SMTP_SECURE: false`
           ` # SHARELATEX_EMAIL_SMTP_USER: `
            `# SHARELATEX_EMAIL_SMTP_PASS: `
           ` # SHARELATEX_EMAIL_SMTP_TLS_REJECT_UNAUTH: true`
           ` # SHARELATEX_EMAIL_SMTP_IGNORE_TLS: false`
            `# SHARELATEX_CUSTOM_EMAIL_FOOTER: "<div>This system is run by department x </div>"`

Whenever i pass booleans like in the example the following error is thrown at me: 

`ERROR: The Compose file './docker-compose.yml' is invalid because:
services.sharelatex.environment.SHARELATEX_EMAIL_SMTP_SECURE contains true, which is an invalid type, it should be a string, number, or a null
`

Currently i have filled in the email settings as following and whenever I uncomment one of the boolean lines they thrown an error.: 
            `SHARELATEX_EMAIL_FROM_ADDRESS: "myemail@gmail.com"`

`            # SHARELATEX_EMAIL_AWS_SES_ACCESS_KEY_ID:`
`            # SHARELATEX_EMAIL_AWS_SES_SECRET_KEY:`

`            SHARELATEX_EMAIL_SMTP_HOST: "smtp.gmail.com"`
`            SHARELATEX_EMAIL_SMTP_PORT: 465`
`           # SHARELATEX_EMAIL_SMTP_SECURE: true`
`            SHARELATEX_EMAIL_SMTP_USER: "myemail@gmail.com"`
`            SHARELATEX_EMAIL_SMTP_PASS: "mypassword"`
`           #SHARELATEX_EMAIL_SMTP_TLS_REJECT_UNAUTH: false`
`           #SHARELATEX_EMAIL_SMTP_IGNORE_TLS: false`
`            SHARELATEX_CUSTOM_EMAIL_FOOTER: "<div>This system is run by department x </div>"`

Even with this configuration an error is thrown. I've tried many things, such as strings in " or not, numbers aswell, or without. Nothing seems to solve the format error.

**Comment by miquelmassot** [comment]
SHARELATEX_EMAIL_FROM_ADDRESS: "team@sharelatex.com"
            SHARELATEX_EMAIL_SMTP_HOST: smtp.gmail.com
            SHARELATEX_EMAIL_SMTP_PORT: 465
            SHARELATEX_EMAIL_SMTP_SECURE: 'true'
            SHARELATEX_EMAIL_SMTP_USER: perfect.email@gmail.com
            SHARELATEX_EMAIL_SMTP_PASS: super_strong_pass
            SHARELATEX_EMAIL_SMTP_TLS_REJECT_UNAUTH: 'true'
            SHARELATEX_EMAIL_SMTP_IGNORE_TLS: 'false'
            SHARELATEX_CUSTOM_EMAIL_FOOTER: "<div>This system is run by me</div>"

**Comment by d0uwe** [comment]
Thanks for your response. I've copied the code you posted into my yml file, but sadly the error does not change. I've attached my .yml file, as .txt.
[docker-compose.txt](https://github.com/sharelatex/sharelatex/files/1150451/docker-compose.txt)

**Comment by rwlaschin** [comment]
Did you try using 1 or 0?
