### ISSUE TITLE
Highlight .Tikz files

### ISSUE THREAD

**Issue by tdehaeze** [overleaf/overleaf#540]
Hi,

Here is my problem, when I edit `.tikz` files inside ShareLaTeX (I love it btw, thank you so much for that!), it does not highlight the file. I have to change the `.tikz` to `.tex`, but then I can't include `.tex` file with `includegraphics`.

So is there a way to treat tikz files as tex files ?

Thank you

**Comment by ShaneKilkelly** [comment]
Hi! I believe this has been fixed in the last year or so :tada: I'll close this issue. Thanks for bringing it to our attention!
