### ISSUE TITLE
Is it possible to use a different user than `www-data` to compile?

### ISSUE THREAD

**Issue by zeigerpuppy** [overleaf/overleaf#544]
- Official Docker version being run: v0.6.3
- added "-shell-escape" to compile commands

I have enabled the `-shell-escape` options in my install (mostly to be able to use `texcount.pl` and `\graphviz{}`).
However, this obviously opens up quite a security hole.  For example:

```latex
\usepackage{alltt}
\title{Shell-escape test}
\begin{document}
\maketitle

Get a listing of root, we can also use rm. \\

  \immediate\write18{ls -al / > getdir.tex}
    \begin{alltt} 
    \input{getdir}
    \end{alltt}
  \immediate\write18{rm getdir.tex}

\end{document}
```

I noticed that all compilation is executed by the `www-data` user.  This user has quite a lot of privileges and could certainly trash the install if a nefarious user wanted to.

Would it be possible to run the compilation commands in a de-privileged user, maybe named `latex-compile`?  This would seem much easier to restrict to a less dangerous set of write permissions.
It would also be easier to set some resource limits on this compile user.

At the moment, we're limited to managing commands via the mechanism of setting allowable commands in `texmf.cnf` using the `shell_escape_commands = ...` syntax.

**Comment by zeigerpuppy** [comment]
I also noticed this older issue along the same lines: https://github.com/sharelatex/sharelatex/issues/321
I'm not expecting the open-source edition to be totally secure.  As was mentioned in that issue, it's not sandboxed per-user and the admin should trust most users.  However, there still seems to be the issue that users could cause inadvertent damage because of their privileges.

**Comment by henp95** [comment]
how do you added the shell-escape flag?

**Comment by mserranom** [comment]
Closing as this won't be actioned. see https://github.com/overleaf/overleaf/issues/321
