### ISSUE TITLE
Collapsing paragraphs into ((sub-)sub-)sections

### ISSUE THREAD

**Issue by jonasrk** [overleaf/overleaf#545]
When I have a paragraph residing in a subsubsection and I collapse this subsubsection, the paragraph stays outside, which appears as a bug to me.

**Comment by jonasrk** [comment]
The same is true for begin tags like \begin{center} or \begin{tabular}.

**Comment by mserranom** [comment]
Haven't been able to reproduce in `v2.0.0`. Feel free to reopen including further information on versions used, screenshots, etc.
