### ISSUE TITLE
"Track changes" hotkey in non-pro version makes the editor buggy

### ISSUE THREAD

**Issue by maahl** [overleaf/overleaf#547]
Hi,

I'm running sharelatex docker image, using the recommended compose file.
I read in issue #533 that the comment and track changes functionality is not available in the self hosted version.

However, the "Show hotkeys" button still shows the hotkeys for comments, toggling the review panel, and activating change tracking:

* the hotkey for creating a comment does nothing
* the hotkey for toggling the review panel works
* the hotkey for activating change tracking makes the editor buggy and sometimes makes the interface lose the connection to the server (seemingly randomly). You can see in the image below how this feature affects the editor: I only typed "test" and I got 4 lines with one more letter every time.
    ![2017-07-18-153756_789x239_scrot](https://user-images.githubusercontent.com/2880719/28321273-249dd84c-6bd3-11e7-9259-6db2af0f16f0.png)
    Reloading the page hasn't fixed the bug, nor has recreating the container: I actually had to recreate the project (fortunately I keep backups of my project in another place).

Steps to reproduce:
* start a docker instance of sharelatex/sharelatex:latest (0.6.3 I assume)
* create a new project and hit the hotkey <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>A</kbd>
* type stuff in your project

I suggest making two changes: 
* making sure the hotkeys do nothing;
* removing these hotkeys from the hotkeys list, or saying somewhere that these features are only for the pro version (it took me some time to figure it out).

Otherwise everything works fine, thanks for the good work! 
I may try to make a pull request myself, but I don't know when I'll have time for it.

Additional info:
```sh
$ docker --version
Docker version 17.05.0-ce, build 89658be
```
```
POST https://domain.tld/project/edited_out/track_changes [HTTP/1.1 404 Not Found 100ms]
```
Let me know if you need more info.

**Comment by jpallen** [comment]
Thanks for reporting this, we'll look into it!

**Comment by mserranom** [comment]
Fixed in https://github.com/overleaf/web/pull/571
