### ISSUE TITLE
Automated dependency management and updates

### ISSUE THREAD

**Issue by elecprog** [overleaf/overleaf#560]
## Problem

It is cumbersome and slow to install LaTeX packages manually, it would be easier if ShareLaTeX automatically installs project dependencies, if the admin allows it (similar to MikTeX).

Also it would be helpful if the was a cronjob that checked for updates, of course this could introduce issues when people require certain versions(?).

Maybe easier to do (or complementing) and solving most issues: having a way to cache the LaTeX install between container recreations.

## Install type

Docker image.

## Version

Latest (v0.6.3)

**Comment by mserranom** [comment]
Sorry, this is not something we plan to support.
