### ISSUE TITLE
Action "Share project" sends an email with different adresses in "from" tag and "reply to" tag which causes some SMTP server refuses to deliver the email

### ISSUE THREAD

**Issue by mazkagaz** [overleaf/overleaf#568]
## Problem

When i invite a collegue to work on my website, no problem, he receives the automatic email, clicks on the link, chooses his password and can connect.

But when i send a "share project" request, depending on the email address i send the request to, it fails on a lot of servers.

What i suspect is : when i invite someone, the "from" tag ang the "reply to" tag in the email header are the same but when i share a project, they contain respectively the webmaster address and my loggin address which are not the same. And for some reason, i think this is why some restricted server won't accept the "share" messages even if they accepted the "invite" email before.

Error with "share" email :
Réponse du serveur distant :
550 5.5.0 Service refuse. Veuillez essayer plus tard. service refused, please try later. LPN007_510 

## Install type

The Docker image

## Version

Which command will show me the version ? (I installed it yesterday...)

## Logs and errors

The SMTP server response on failing share emails (i insist that it is working with other email addresses) :
Réponse du serveur distant :
550 5.5.0 Service refuse. Veuillez essayer plus tard. service refused, please try later. LPN007_510 

## my request 
Is it possible to change the webmaster address with the project creator address in the "from" tag in the email header to avoid this SMTP filtering problem ? Or at less create an environment variable to choose between the two behaviours.

I feel like it has something to deal with /var/www/sharelatex/web/app/coffee/Features/Email/EmailSender.coffee or /var/www/sharelatex/web/app/coffee/Features/Email/EmailBuilder.coffee 
Am i right ?

Thanks a lot

**Comment by ShaneKilkelly** [comment]
Sorry it's taken a while to get around to this! For future reference the email options should be editable in the settings file (under the `email` key), where you can set values for the `fromAddress` and `replyTo` address, although it's not possible to use the project-creator email address in those fields, they are statically set by the server admin.
