### ISSUE TITLE
g-brief.cls in docker

### ISSUE THREAD

**Issue by christianreiss** [overleaf/overleaf#571]
Hey folks,

quick question. I need g-brief.cls (https://ctan.org/tex-archive/macros/latex/contrib/g-brief/). How would I go about adding it to the (current) docker Distribution?

Cheers,
-Chris.

**Comment by das7pad** [comment]
Build a new container with said package on top of it. 

```
FROM sharelatex/sharelatex:2.0.1

RUN tlmgr install g-brief
```
