### ISSUE TITLE
Bad gateway after a fresh install, redis not available.

### ISSUE THREAD

**Issue by Jankoekenpan** [overleaf/overleaf#572]
## Problem

502 Bad Gateway after a fresh install.

## Install type

I ran the docker installation as mentioned in the quick start guide.

## Version

PS C:\Users\Jan> docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true

## Logs and errors

PS C:\Users\Jan> docker logs sharelatex
*** Running /etc/my_init.d/00_make_sharelatex_data_dirs.sh...
*** Running /etc/my_init.d/00_regen_sharelatex_secrets.sh...
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/00_set_docker_host_ipaddress.sh...
*** Running /etc/my_init.d/98_check_db_access.sh...
Checking can connect to mongo and redis
Running "check:redis" task
Checking can connect to redis
>> FAIL.
>> !!!!!!!!!!!!!! REDIS ERROR !!!!!!!!!!!!!!
>>
>> ShareLaTeX can not talk to the redis instance
>>
>> Check the redis instance is running and accessible on env var
>> SHARELATEX_REDIS_HOST
>>
>> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Fatal error: Can not connect to redis
Running "check:mongo" task
Checking can connect to mongoWarning: mongojs.connect is not a function Use --force to continue.

Aborted due to warnings.
All checks passed
*** Running /etc/my_init.d/99_migrate.sh...
/usr/bin/node
/usr/bin/grunt
total 52
drwxr-xr-x 2 root root  4096 Sep  8 12:46 .
drwxr-xr-x 1 root root  4096 Sep  8 12:53 ..
-rw-r--r-- 1 root root  5031 Sep  8 12:46 1_move_doc_lines_to_doc_collection.coffee
-rw-r--r-- 1 root root  5936 Sep  8 12:46 2_doc_lines_delete_from_project.coffee
-rw-r--r-- 1 root root 10627 Sep  8 12:46 3_pack_docHistory_collection.coffee
-rw-r--r-- 1 root root   788 Sep  8 12:46 4_update_user_features.coffee
-rw-r--r-- 1 root root  3526 Sep  8 12:46 5_remove_holding_accounts.coffee
-rw-r--r-- 1 root root   672 Sep  8 12:46 6_add_track_changes_feature.coffee
-rw-r--r-- 1 root root   335 Sep  8 12:46 about_migrations.md
Initializing
Command-line options: --verbose

Reading "Gruntfile.coffee" Gruntfile...OK

Registering Gruntfile tasks.

Registering "grunt-bunyan" local Npm module tasks.
Reading /var/www/sharelatex/node_modules/grunt-bunyan/package.json...OK
Parsing /var/www/sharelatex/node_modules/grunt-bunyan/package.json...OK
Loading "bunyan.js" tasks...OK
+ bunyan

Registering "grunt-execute" local Npm module tasks.
Reading /var/www/sharelatex/node_modules/grunt-execute/package.json...OK
Parsing /var/www/sharelatex/node_modules/grunt-execute/package.json...OK
Loading "execute.js" tasks...OK
+ execute

Registering "grunt-available-tasks" local Npm module tasks.
Reading /var/www/sharelatex/node_modules/grunt-available-tasks/package.json...OK
Parsing /var/www/sharelatex/node_modules/grunt-available-tasks/package.json...OK
Loading "available_tasks.js" tasks...OK
+ availabletasks

Registering "grunt-concurrent" local Npm module tasks.
Reading /var/www/sharelatex/node_modules/grunt-concurrent/package.json...OK
Parsing /var/www/sharelatex/node_modules/grunt-concurrent/package.json...OK
Loading "concurrent.js" tasks...OK
+ concurrent

Registering "grunt-contrib-coffee" local Npm module tasks.
Reading /var/www/sharelatex/node_modules/grunt-contrib-coffee/package.json...OK
Parsing /var/www/sharelatex/node_modules/grunt-contrib-coffee/package.json...OK
Loading "coffee.js" tasks...OK
+ coffee

Registering "grunt-shell" local Npm module tasks.
Reading /var/www/sharelatex/node_modules/grunt-shell/package.json...OK
Parsing /var/www/sharelatex/node_modules/grunt-shell/package.json...OK
Loading "shell.js" tasks...OK
+ shell

Registering "./tasks" tasks.
Loading "CreateAndDestoryUsers.coffee" tasks...OK
+ user:create-admin, user:delete
Loading "ProjectSize.coffee" tasks...OK
>> No tasks were registered or unregistered.
Initializing config...OK
Loading "Gruntfile.coffee" tasks...OK
+ check, check:make, check:mongo, check:redis, default, help, install, install:all, install:chat, install:clsi, install:contacts, install:docstore, install:document-updater, install:filestore, install:notifications, inst
all:real-time, install:spelling, install:tags, install:track-changes, install:web, migrate, postinstall, run, run:all, update, update:all

Running tasks: migrate

Running "migrate" task

Running "coffee:migrate" (coffee) task
Verifying property coffee.migrate exists in config...OK
Files: migrations/1_move_doc_lines_to_doc_collection.coffee -> migrations/1_move_doc_lines_to_doc_collection.js
Files: migrations/2_doc_lines_delete_from_project.coffee -> migrations/2_doc_lines_delete_from_project.js
Files: migrations/3_pack_docHistory_collection.coffee -> migrations/3_pack_docHistory_collection.js
Files: migrations/4_update_user_features.coffee -> migrations/4_update_user_features.js
Files: migrations/5_remove_holding_accounts.coffee -> migrations/5_remove_holding_accounts.js
Files: migrations/6_add_track_changes_feature.coffee -> migrations/6_add_track_changes_feature.js
Options: bare, join=false, sourceMap=false, joinExt=".src.coffee", separator="\n"
Reading migrations/1_move_doc_lines_to_doc_collection.coffee...OK
Writing migrations/1_move_doc_lines_to_doc_collection.js...OK
Reading migrations/2_doc_lines_delete_from_project.coffee...OK
Writing migrations/2_doc_lines_delete_from_project.js...OK
Reading migrations/3_pack_docHistory_collection.coffee...OK
Writing migrations/3_pack_docHistory_collection.js...OK
Reading migrations/4_update_user_features.coffee...OK
Writing migrations/4_update_user_features.js...OK
Reading migrations/5_remove_holding_accounts.coffee...OK
Writing migrations/5_remove_holding_accounts.js...OK
Reading migrations/6_add_track_changes_feature.coffee...OK
Writing migrations/6_add_track_changes_feature.js...OK

Running "shell:migrate" (shell) task
Verifying property shell.migrate exists in config...OK
File: [no files]
Options: stdout, stderr, stdin, failOnError, stdinRawMode=false, preferLocal=false, execOptions={"env":null}
Command: ./node_modules/east/bin/east migrate --adapter east-mongo --url mongodb://dockerhost/sharelatex
/var/www/sharelatex/node_modules/east-mongo/lib/adapter.js:26
        this.db.close(callback);
               ^

TypeError: Cannot read property 'close' of undefined
    at Adapter.disconnect (/var/www/sharelatex/node_modules/east-mongo/lib/adapter.js:26:9)
    at Migrator.disconnect (/var/www/sharelatex/node_modules/east/lib/migrator.js:331:15)
    at /var/www/sharelatex/node_modules/east/bin/commands/base.js:122:18
    at next (/var/www/sharelatex/node_modules/twostep/lib/twoStep.js:148:20)
    at Group.done (/var/www/sharelatex/node_modules/twostep/lib/twoStep.js:30:16)
    at Group.error (/var/www/sharelatex/node_modules/twostep/lib/twoStep.js:34:7)
    at next (/var/www/sharelatex/node_modules/twostep/lib/twoStep.js:155:17)
    at Group.done (/var/www/sharelatex/node_modules/twostep/lib/twoStep.js:30:16)
    at Group.error (/var/www/sharelatex/node_modules/twostep/lib/twoStep.js:34:7)
    at /var/www/sharelatex/node_modules/twostep/lib/twoStep.js:69:17
Warning: Command failed: ./node_modules/east/bin/east migrate --adapter east-mongo --url mongodb://dockerhost/sharelatex
/var/www/sharelatex/node_modules/east-mongo/lib/adapter.js:26
        this.db.close(callback);
               ^

TypeError: Cannot read property 'close' of undefined
    at Adapter.disconnect (/var/www/sharelatex/node_modules/east-mongo/lib/adapter.js:26:9)
    at Migrator.disconnect (/var/www/sharelatex/node_modules/east/lib/migrator.js:331:15)
    at /var/www/sharelatex/node_modules/east/bin/commands/base.js:122:18
    at next (/var/www/sharelatex/node_modules/twostep/lib/twoStep.js:148:20)
    at Group.done (/var/www/sharelatex/node_modules/twostep/lib/twoStep.js:30:16)
    at Group.error (/var/www/sharelatex/node_modules/twostep/lib/twoStep.js:34:7)
    at next (/var/www/sharelatex/node_modules/twostep/lib/twoStep.js:155:17)
    at Group.done (/var/www/sharelatex/node_modules/twostep/lib/twoStep.js:30:16)
    at Group.error (/var/www/sharelatex/node_modules/twostep/lib/twoStep.js:34:7)
    at /var/www/sharelatex/node_modules/twostep/lib/twoStep.js:69:17
 Use --force to continue.

Aborted due to warnings.
All migrations finished
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 90
tail: unrecognized file system type 0x794c7630 for ‘/var/log/syslog’. please report this to bug-coreutils@gnu.org. reverting to polling
tail: unrecognized file system type 0x794c7630 for ‘/var/log/sharelatex/chat.log’. please report this to bug-coreutils@gnu.org. reverting to polling
tail: unrecognized file system type 0x794c7630 for ‘/var/log/sharelatex/clsi.log’. please report this to bug-coreutils@gnu.org. reverting to polling
tail: unrecognized file system type 0x794c7630 for ‘/var/log/sharelatex/docstore.log’. please report this to bug-coreutils@gnu.org. reverting to polling
tail: unrecognized file system type 0x794c7630 for ‘/var/log/sharelatex/document-updater.log’. please report this to bug-coreutils@gnu.org. reverting to polling
tail: unrecognized file system type 0x794c7630 for ‘/var/log/sharelatex/filestore.log’. please report this to bug-coreutils@gnu.org. reverting to polling
tail: unrecognized file system type 0x794c7630 for ‘/var/log/sharelatex/notifications.log’. please report this to bug-coreutils@gnu.org. reverting to polling
tail: unrecognized file system type 0x794c7630 for ‘/var/log/sharelatex/real-time.log’. please report this to bug-coreutils@gnu.org. reverting to polling
tail: unrecognized file system type 0x794c7630 for ‘/var/log/sharelatex/spelling.log’. please report this to bug-coreutils@gnu.org. reverting to polling
tail: unrecognized file system type 0x794c7630 for ‘/var/log/sharelatex/tags.log’. please report this to bug-coreutils@gnu.org. reverting to polling
tail: unrecognized file system type 0x794c7630 for ‘/var/log/sharelatex/track-changes.log’. please report this to bug-coreutils@gnu.org. reverting to polling
tail: unrecognized file system type 0x794c7630 for ‘/var/log/sharelatex/web.log’. please report this to bug-coreutils@gnu.org. reverting to polling

## Screenshots

![bad_gateway](https://user-images.githubusercontent.com/27810652/33168193-640a9048-d040-11e7-91eb-edb82f5b0b63.PNG)

**Comment by elvismt** [comment]
Same happens to me. Is the problem caused by sharelatex not being able to connect to either mongo or redis? if so, at least try adding a better feedback that a "BAD GATEWAY".

**Comment by superobertking** [comment]
This is because the link to mongodb and redis container are not set. For a docker-compose container, you will first need to start up some dependency containers.
In your console:
```
docker run -d --name shareredis redis:latest
docker run -d --name sharemongo mongo:latest
docker run -d \
  -v ~/sharelatex_data:/var/lib/sharelatex \
  -p 5000:80 \
  --env SHARELATEX_MONGO_URL=mongodb://mongo/sharelatex --env SHARELATEX_REDIS_HOST=redis \
  --link sharemongo:mongo --link shareredis:redis \
  --name=sharelatex \
  sharelatex/sharelatex
```
(I would recommend this being added into the wiki.)
(Besides, it is also recommended to mount the data volume of mongodb to your host computer.)
Reference:
https://github.com/sharelatex/sharelatex-docker-image/issues/2
