### ISSUE TITLE
iptables error on initialisation

### ISSUE THREAD

**Issue by klinamen0** [overleaf/overleaf#573]
## Problem

When I run ``sudo docker-compose up`` in the /sharelatex/ directory with the ``docker-compose.yml`` in it I get the following iptables-related error. I'm new to docker so am likely making some schoolkid errors. Any help would very much be appreciated! Thanks in advance.

## Install type

Using the ``docker-compose.yml``.

## Version

sharelatex/sharelatex
Docker 17.09.0-ce
Debian Stretch

## Logs and errors
```
$ sudo docker-compose up
redis is up-to-date
mongo is up-to-date
Starting c14d0ed68dfa_sharelatex

ERROR: for sharelatex  Cannot start service sharelatex: driver failed programming external connectivity on endpoint c14d0ed68dfa_sharelatex (82d14f5b1451161df23ce9cb8e799b5ddb58a78ce6d53052e5831afcd8794e21):  (iptables failed: iptables --wait -t filter -A DOCKER ! -i br-bd557fa535d2 -o br-bd557fa535d2 -p tcp -d 172.18.0.4 --dport 80 -j ACCEPT: iptables: No chain/target/match by that name.
 (exit status 1))
ERROR: Encountered errors while bringing up the project.
```
```
$ sudo docker images
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
hello-world             latest              f2a91732366c        12 days ago         1.85kB
mongo                   latest              d22888af0ce0        4 weeks ago         361MB
redis                   latest              8f2e175b3bd1        4 weeks ago         107MB
sharelatex/sharelatex   latest              bffb5a850d01        2 months ago        2.4GB

```

**Comment by das7pad** [comment]
`Starting c14d0ed68dfa_sharelatex` hints on an already existing sharelatex container, docker failed to remove it and is using a new container (name) now to preserving the last one. The iptables error hints on a slow/failed start of a container: not all of the iptables-rules for the previous container were added, before their removal was requested. Provisioning a new container would require to nuke the rules of the previous one first, but the rules are not there (yet?). There are many reasons for this (concurrent terminal session, previously forcefully cancelled docker command, hardware failure, full disk, ...) - nothing we can really debug via a github issue.

We can probably just close the issue.
