### ISSUE TITLE
ERROR: no matching manifest for linux/arm in the manifest list entries

### ISSUE THREAD

**Issue by godorizzi** [overleaf/overleaf#576]
## Problem

Hello,
I followed the instruction at https://github.com/sharelatex/sharelatex/wiki/Quick-Start-Guide and successfully installed docker on a Raspberry Pi 3 running Ubuntu mate 16.04.

I run $ sudo docker run -d \
  -v ~/sharelatex_data:/var/lib/sharelatex \
  -p 5000:80 \
  --name=sharelatex \
  sharelatex/sharelatex

and no error is given, but still no active server on port 5000.
I downloaded the docker-composer.yml and placed it to the Desktop.
I then ran  sudo docker-compose up and this is what I get:

Pulling mongo (mongo:latest)...
latest: Pulling from library/mongo
ERROR: no matching manifest for linux/arm in the manifest list entries

Could someone please help me out?

Thank you in advance

## Install type

Docker image
## sudo docker-version

Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:13:32 2017
 OS/Arch:	linux/arm

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:09:42 2017
  OS/Arch:	linux/arm
  Experimental:	false

**Comment by mserranom** [comment]
Only x86 architectures are supported sorry.
