### ISSUE TITLE
create new user accounts via grunt

### ISSUE THREAD

**Issue by lucebac** [overleaf/overleaf#581]
## Problem
It would be useful to be able to create new user accounts via grunt during container setup (like it can be done with admin accounts). Is there a way to do this? If not, are there any plans to implement this in the (near) future?

## Install type
official docker image

## Version
v1.2.0

**Comment by Trackhe** [comment]
added but for me not working

**Comment by das7pad** [comment]
Hello,

You can create new users from the command line using the following inside the container:

```bash
source /etc/container_environment.sh
source /etc/overleaf/env.sh
cd /overleaf/services/web
node modules/server-ce-scripts/scripts/create-user --admin --email=user@example.com
node modules/server-ce-scripts/scripts/create-user --admin --email=admin@example.com
```

Greetings,
Jakob
