### ISSUE TITLE
Text files not editable after import

### ISSUE THREAD

**Issue by zeigerpuppy** [overleaf/overleaf#585]
I have some projects that use knitr support.
Sharelatex is implemented using the latest docker release and the patch here: https://github.com/sharelatex/sharelatex/issues/460#issuecomment-283598664.

When I import from an archived project, files that were previously editable no longer open an editor.

I particular, there were files with the `.R` or `.knir` extension.  However, after importing the project, they can only be downloaded, not edited.

Is there a way to force Sharelatex to recognise files with certain endings as editable?
Interestingly, if I create a new `.tex` file, edit it and then rename it to `.R`, it remains editable, so I presume there's some tag in the database attached to the initial file.

**Comment by parmentelat** [comment]
I'd like to +1, it's not uncommon to have source code inserted into a latex document with \lstinputlisting or similar, so editing these text files makes perfect sense

**Comment by ShaneKilkelly** [comment]
Hi! Thanks for the suggestion! We're tracking this in an internal ticket, so I'll close this issue for now, and update it later when the feature lands.

**Comment by sayebms1** [comment]
I am facing the same issue with importing files to a new folder. It seems like the 'create new folder' option only adds a tag and not necessarily make a separate folder, which is a bit misleading.

**Comment by ruffsl** [comment]
@JuneKelly , any update on this feature? It's kind of odd that overleaf can not yet edit `.txt` files, or other text based formats. For example, I'd like to edit source files that are included as code snippet listing in final document, with the common `.py`, `.cpp` or `.rs` file extensions. I recall this being possible back in the day with sharelatex. Could this issue be reopened so it's not forgotten again? I would be best to close tickets once they are resolved or clearly declared as won't fix.

**Comment by logari81** [comment]
Workaround: if you upload the files with ".tex" extension and rename them afterwards to whatever extension you like, they are both browsable and editable. However, I would very much like that this is properly fixed and highlighting for different languages is added.

**Comment by m4lvin** [comment]
I would like to add `.lhs` and `.hs` to the sorts of files that should be editable in the web interface.

For these I can also confirm the workaround given by @logari81. That this works makes me think that Overleaf must be keeping some hidden internal state or marker for each file whether it is "something viewable/editable", in addition to the name suffix and the actual type of content of the file (as shown by `file bla` for example).

**Comment by zzbuzzard** [comment]
Hi @JuneKelly, could this be re-opened given that it's been over 5 years and has not been fixed? Sometimes it's useful to edit `pgf` files.

**Comment by m4lvin** [comment]
I am running into this problem again, as I would like to provide students with an Overleaf template that can also be used for literate programming. The workaround of uploading a `.tex` and then renaming does not solve this use case.

@JuneKelly could you update this issue here and let us know whether this is still tracked in an internal ticket at Overleaf or whether we should assume it will never be changed?

**Comment by BassemMagdi0007** [comment]
Well, I just faced the same problem, I was provided a template from my collage as a link, and wasn't able to modify it. But when I open it, it appears on My Home "All Projects", from there I downloaded it as .zip and re-uploaded it again, and then was able to modify all its content. 
Hope that helps

**Comment by m4lvin** [comment]
I am running into this issue again, after adding some `.lean` files to an Overleaf project via the git interface. It is a bummer that these files can now not even be viewed in Overleaf directly, only downloaded 😿

What would it take to fix/change this matter? Which code is relevant for this?

I assume my new case is more like https://github.com/overleaf/overleaf/issues/1003 and not the issue here which is about imported projects. Both issues are closed without explanation.

**Comment by rebekadekany** [comment]
@m4lvin , The `.lean` file extension is not currently included in the default list of editable text file types.

If you're using Overleaf CE (self-hosted):
You can enable support for `.lean` files by adding the following environment variable to your configuration:
`ADDITIONAL_TEXT_EXTENSIONS=lean`
Add this to your `local.env` file, then restart the services. After this, `.lean` files should be viewable and editable.
Note that `.lhs` is in the default list, but `.hs` is not - you can add it the same way.

If you're using [overleaf.com](https://www.overleaf.com/):
Please send bug reports, feature requests and feedback directly to support@overleaf.com, as the hosted service is managed separately. We'll file an internal ticket right away.
