### ISSUE TITLE
Development Docs missing

### ISSUE THREAD

**Issue by davidmehren** [overleaf/overleaf#587]
https://github.com/sharelatex/sharelatex/blob/master/CONTRIBUTING.md links to https://github.com/sharelatex/sharelatex/wiki/Developer-Guidelines for setting up a dev environment. This document seems to be missing. Have these instructions been moved?

**Comment by blubbsy** [comment]
i'm also missing the documentations, also the quickstart guide lacks of information to get it running without knowing the older versions or to stick your nose into the container.

**Comment by mserranom** [comment]
Broken links are fixed.
