### ISSUE TITLE
Feature Request: GUI for quickly inserting math equations

### ISSUE THREAD

**Issue by dclong** [overleaf/overleaf#588]
I just had a try of ShareLatex. Honestly, its functionality is quite limited compared to traditional desktop software (e.g., TexStudio) for LaTex writing. The key feature missing is GUI for quickly inserting math equations. Users typically don't have good memory about how to typing different types of math equations and they shouldn't spend their precious brain on such things.

**Comment by ShaneKilkelly** [comment]
Hi! This is a suggestion that has been popular enough to make it onto our internal medium/long term road map. I'll close this issue for now. Thanks!
