### ISSUE TITLE
Suggestion: Hotkey to Folding/Collapsing code elements 

### ISSUE THREAD

**Issue by Shriyanshagro** [overleaf/overleaf#593]
## Suggestion

It could be very helpful in large projects to have a hotkey/shortkey to collapse (fold) code fragments such as sections, subsections or tables. 
At present, it can be down using UI but a hotkey will aid users productivity.

By collapsing/folding I mean reducing them to a single visible line. In this way, we can hide the details that, at the moment, seem unimportant. Refer to below screenshot for more clear understanding 

## Screenshots

A table section (which is not important at the moment) was folded using UI.

<img width="632" alt="screen shot 2018-06-29 at 11 20 46 am" src="https://user-images.githubusercontent.com/13868098/42075729-f123a618-7b8f-11e8-8145-aaad884f3d43.png">

**Comment by ShaneKilkelly** [comment]
Hi! This is a suggestion that has been popular enough to make it onto our internal medium/long term road map. I'll close this issue for now. Thanks!
