### ISSUE TITLE
Update TexLive to 2018

### ISSUE THREAD

**Issue by MadMud** [overleaf/overleaf#601]
## Problem

The current docker (v1.2.1) image for sharelatex/sharelatex comunity edition contains only 2017 edition of TexLive. As a consequence tlmgr cannot be used to install additional tex packages.

My current workaround is an additional image installing TexLive 2018 as per their instructions:

```
FROM sharelatex/sharelatex:latest

RUN wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz; \
	mkdir /install-tl-unx; tar -xvf install-tl-unx.tar.gz -C /install-tl-unx --strip-components=1
RUN echo "selected_scheme scheme-full" >> /install-tl-unx/texlive.profile; \
	/install-tl-unx/install-tl -profile /install-tl-unx/texlive.profile; \
	rm -r /install-tl-unx; rm install-tl-unx.tar.gz 
ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/texlive/2018/bin/x86_64-linux/
WORKDIR /usr/local/texlive/2018/bin/x86_64-linux
RUN ./tlmgr install latexmk ; \
    ./tlmgr install texcount
RUN rm -rf /usr/local/texlive/2017
```

This works fine, but an update to the official image would be preferable in my mind.

**Comment by Karamaz0V1** [comment]
Thank you for sharing. Your first `RUN` line seems to be truncated.

**Comment by MadMud** [comment]
ahh, thanks! that is waht I get for copy pasta-ing from the console. I edited in place

BTW: looking at [1] I think this can also be solved by setting DOCKER_RUNNER="true" and TEXLIVE_IMAGE to a custom or more reset official docker images with texlive installed. Anyway this would mean extra rights for the sharelatex container, so I personally did not go that route.

[1]
https://github.com/sharelatex/clsi-sharelatex/blob/master/config/settings.defaults.coffee

**Comment by hippke** [comment]
It also works to point tlmgr to 2017: `docker exec sharelatex tlmgr option repository ftp://tug.org/historic/systems/texlive/2017/tlnet-final`

**Comment by MadMud** [comment]
Heh, you are of course right! Just for others and  context: you will probably want to execute that command while building your container, and pick a mirror near you (well with a decent connection speed).

**Comment by crockeea** [comment]
Also being tracked here: https://github.com/sharelatex/sharelatex-docker-image/issues/90

**Comment by grauschnabel** [comment]
Hi there,
I simply installed 2018 on the server outside the docker, next to `sharelatex_data` into `sharelatex_texlive`, by using the instructions from [tug.org](https://www.tug.org/texlive/quickinstall.html). Simply changing the default pathes on the `install-tl` script from  [here](https://www.tug.org/texlive/acquire-netinstall.html) was all I needed to do.

Adding `- ~/sharelatex_texlive:/usr/local/texlive` to the `volumes` section and `PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/texlive/2018/bin/x86_64-linux/` to the `environment` section did the rest.  Having sharelatex up and running, and I can manage texlive locally.

**Comment by edwardffs** [comment]
> Hi there,
> I simply installed 2018 on the server outside the docker, next to `sharelatex_data` into `sharelatex_texlive`, by using the instructions from [tug.org](https://www.tug.org/texlive/quickinstall.html). Simply changing the default pathes on the `install-tl` script from [here](https://www.tug.org/texlive/acquire-netinstall.html) was all I needed to do.
> 
> Adding `- ~/sharelatex_texlive:/usr/local/texlive` to the `volumes` section and `PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/texlive/2018/bin/x86_64-linux/` to the `environment` section did the rest. Having sharelatex up and running, and I can manage texlive locally.

How do I change the default paths on the install-tl file exactly?

**Comment by grauschnabel** [comment]
@edwardffs  You will be asked during the installation process.

Ok, I'm upgrading to texlive 2019 and logging my steps here:

1. Download install-lt from (here)[http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz]
2. `tar -xzvf install-tl-unx.tar.gz `
3. `./install-tl-20190507/install-tl`
then (ret meand the return key) press `D ret 1 ret ~/sharelatex_texlive/2019 ret R ret I ret`
4. wait for the installation to finish, depends on your internet connection how long it takes.
5. in the `docker-compose.yml`, under _volumes:_, i use `- ~/sharelatex_texlive:/usr/local/texlive` and inside _environment:_ I added: `PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/texlive/2019/bin/x86_64-linux/`
6. `docker-compose down && docker-compose up -d` inside my sharelatex dir where the docker-compose.yml file is.
7. `docker exec sharelatex lualatex --version` to check if it uses the correct version.

I hope that works for you too.

**Comment by markedphillips** [comment]
[docker-compose up -d](https://gist.github.com/markedphillips/3d566d3721f8c80e313d6ce365cd87a0)

**Comment by krswin** [comment]
@grauschnabel Thank you for steps for texlive 2019.
I have followed your steps. But I have problem, Path issue.
`OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"lualatex\": executable file not found in $PATH": unknown`

I am installing on MacOS running with Docker.

**Comment by krswin** [comment]
@grauschnabel Thank you for your explanation to update texlive to 2019 version, this worked on my macbook docker. now i was trying to make it work on synology NAS, but it do not work.  
Can you please tell me what can be specific to synology NAS needs to be done.
basically issue is texlive 2019 do not recognize error is below :

> `OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec format error": unknown`

**Comment by grauschnabel** [comment]
Sorry, I have no idea, maybe someone else? For me this locks like a problem with docker or the container itself. My solultion is just to have latex maintained outside the docker container, which may not be a solution for many people. Nice to know it works on ios too.

**Comment by mserranom** [comment]
Overleaf Community Edition 2.0.0 has been released, including TexLive 2019 by default.
