### ISSUE TITLE
Asymptote support?

### ISSUE THREAD

**Issue by Asuranceturix** [overleaf/overleaf#602]
## Problem

I'm trying to use embedded Asymptote code, such as this example: https://www.overleaf.com/latex/examples/2d-graphics-with-asymptote/zppdrrhdszhr
While this example does work on Overleaf, it fails on my ShareLaTeX installation and no figures are generated.

## Install type

I'm using the Docker image using the compose file.

## Version

Image ID 8e1bae81acac, which is sharelatex:latest as of the time of writing this.

## Logs and errors

Package asymptote Warning: file `output-1.tex' not found on input line 61.

 main.tex, line 85
Package asymptote Warning: file `output-2.tex' not found on input line 85.

**Comment by mserranom** [comment]
Some packages https://sharelatex.com/learn/Nomenclatures are valid for [Server Pro](https://www.overleaf.com/for/enterprises) and [overleaf.com](https://www.overleaf.com) only. In both these cases we use custom compilation servers  based on TexLive (see our [latest blog entry on the topic](https://www.overleaf.com/blog/tex-live-upgrade-september-2019)). 

Overleaf Community Edition uses instead the latest stable version of TexLive as distributed by CTAN (currently `2019` version), so not all features have a 100% parity.
