### ISSUE TITLE
Updated Installation info request

### ISSUE THREAD

**Issue by uwe22** [overleaf/overleaf#604]
First of all thanks everybody for this fantastic piece of software!

The documentation has grown a bit old especially the SSL configuration,
which should be standard now.

Would it be possible to create a docker image or docker-compose file
for that purpose baring in mind already SSL running hosts?

1. sharelatex, with the latest latex
2. sharelatex with ssl configuration, using the keys in a share folder on the host
3. configure shell escape without modification of internal files

the configuration via yml docker-compose is very comfortable.

**Comment by ShaneKilkelly** [comment]
Hi! We've updated the documentation in a few places since this ticket was opened, and we now have internal tickets to further improve the state of the documentation. I'll close this issue for now. If you see any further, specific problems with the docs then please do open another ticket. Thanks!
