### ISSUE TITLE
How to update container after changing the yml file?

### ISSUE THREAD

**Issue by yxnchen** [overleaf/overleaf#608]
Thanks you for the wonderful work of sharelatex open source.

I used the docker-compose.yml file to deploy a perfect service in my server these day with the command "docker-compose up -d". 

Now I would like to make some configuration of the website and change the APP_NAME and  HEADER_IMAGE_URL in the yml file. How to update these changes without destroying the container? I don't want to install the full texlive and the necessary fonts one more time.

**Comment by bauerj** [comment]
The clean solution would probably be to mount the directory that contains the texlive distribution to a Docker volume.

**Comment by mserranom** [comment]
There isn't a supported way to do this. I'd recommend the following:
 - Open a shell to the `sharelatex` container: `docker exec -it <CONTAINER_ID> /bin/bash`
 - Edit the properties you want to change in `/etc/sharelatex/settings.coffee`, they should look like something like this: https://github.com/overleaf/docker-image/blob/master/settings.coffee#L218
 - Find the `node /var/www/sharelatex/web` process using `ps -ef` and kill it - `kill -9 <WEB_PROCESS_ID>`
The service should restart using the updated settings.
