### ISSUE TITLE
How to set up sharelatex

### ISSUE THREAD

**Issue by motermouth15** [overleaf/overleaf#610]
## Problem

Can't get sharelatex up and running on my own server

## Install type

sharelatex docker image

## Version

sharelatex - latest
ubuntu - 18.04 (hosted on kvm host)
docker - latest

## Logs and errors

none

## More Details

This is beyond frustrating. Where is the STEP-BY-STEP guide that actually shows one how to get this running on their own server???

I follow the only command that is stated on the "quick start guide" which is the command that shows you how to pull the docker image to your local server. I get that far, and that's where I am stuck because the guide doesn't show what to do next. 

Where are the guides that explain how to get your docker image up and running?!?! It suggests using the compose file, but fails to explain HOW!

Does anyone have detailed instructions on how to get my docker image of sharelatex up and running? As stated before, the only step I have been successfully able to complete is pulling the docker image with command: docker pull sharelatex/sharelatex. -- I am newer to docker.

Thanks for the help.

**Comment by mandala-mbwa** [comment]
https://www.scaleway.com/docs/installing-sharelatex-ubuntu/

**Comment by moschlar** [comment]
The `docker-compose.yml` is right here in this repository. Either download it or clone the repo (you don't need any of the other files though).

**Comment by mserranom** [comment]
Sorry you've been having trouble running Overleaf CE.

We've released a new version, please checkout this repo and run `docker-compose up`, this should run out of the box with the current [docker-compose.yml](https://github.com/overleaf/overleaf/blob/master/docker-compose.yml) file.
