### ISSUE TITLE
Docker image uses very old Ubuntu version

### ISSUE THREAD

**Issue by VorpalBlade** [overleaf/overleaf#617]
## Problem

The docker image as of writing this is based on Ubuntu 14.04 LTS. Security updates will end in 2019-04 for that according to official documentation. It would be a good idea to update (very soon) to a newer version to ensure secure installations.

It might also be a good idea to ensure that the other images pulled in in the compose file (mongo and redis) are up-to-date. I have not checked this in detail.

## Install type

The official docker image was used.

## Version

Which version of the docker image are you using?

The latest as of writing this, which appears to be v1.2.1.

**Comment by prohde** [comment]
The Ubuntu version comes from the Phusion baseimage. Therefore one has to use a newer Phusion baseimage. But I didn't had time yet to test if everything is working fine with just using a newer image.

**Comment by moschlar** [comment]
I'd say it would be a good idea to have an up-to-date base image!

Mongo and Redis are not tagged, so your initial deployment will fetch the :latest tag.
But docker-compose won't update it automatically.
You could use [v2tec/watchtower](https://hub.docker.com/r/v2tec/watchtower/) for that (although it might not be the wisest idea to always automatically upgrade database containers).

**Comment by AljoschaP** [comment]
I pushed an image with an updated version of the base image using Ubuntu 18.04. Maybe it solves your problem: [Docker Hub](https://cloud.docker.com/repository/docker/aljoshare/sharelatex)

**Comment by mserranom** [comment]
As mentioned before, we're using Phusion Image, which has been updated to its latest release.
