### ISSUE TITLE
Does this ShareLatex support REMOTE_USER ???

### ISSUE THREAD

**Issue by skimmy12** [overleaf/overleaf#618]
(If you have a feature request, or bug with ShareLaTeX, please file an issue at https://github.com/sharelatex/web-sharelatex. This repository should **only be used for installation and maintenance problems** of ShareLaTeX Community Edition)

## Problem

Please describe the problem you are facing

## Install type

Are you using the Docker image (as described at https://github.com/sharelatex/sharelatex/wiki/Quick-Start-Guide), or some other method of installing ShareLaTeX Community Edition?

## Version

Which version of the docker image are you using?

## Logs and errors

Please include any logs and error messages.

## Screenshots

Please provide any screenshots of errors in ShareLaTeX Community Edition.

**Comment by mserranom** [comment]
I'm closing this. @skimmy12 feel free to reopen including further information on the ticket.
