### ISSUE TITLE
Overleaf removes symlink when merging with Github

### ISSUE THREAD

**Issue by NelleV** [overleaf/overleaf#619]
## Problem

Overleaf removes symlinks present in a git repository when merging with a github hosted git repository. 

## Details
I have a project hosted on Github containing a number of symlinks, as well as a latex document. Everytime I sync overleaf with github, it removes all the symilnks. This is problematic as the code doesn't run without those symlinks.

**Comment by mserranom** [comment]
Seems you're experiencing issues with overleaf.com. Sorry about this. I've reported it to be included in the roadmap.

Next time would be better and faster the [contact form](https://www.overleaf.com/contact) for overleaf.com related issues.

**Comment by MayeulC** [comment]
As a workaround, I use the following post-merge hook to run after a git pull.

I use symlinks quite a bit to make `css` directories next to my `svg` figures, where I use an external css sheet with `@import`. Currently that doesn't work on overleaf.com as inkscape is outdated, but I wonder if that will work at all (if my symlinks will be preserved).

Anyway, here's the script:

```bash
#!/bin/bash

# This is currently necessary as overleaf does not support symlinks
# To enable this as a post-merge (post-pull) hook, do:
# ln -s this-script.sh .git/hooks/post-merge
# (don't forget +x permissions)

# The hash can also be obtained by exploring the tree with:
#git cat-file -p master^{tree}

# Find files that were changed from symlinks to regular files

files=$(git show --pretty=%h --compact-summary |grep '(mode -l)' | sed 's/^ \(.\+\) (mode -l)\s\+|.\+$/\1/')

while IFS= read -r file
do
        # Find internal hash
        fhash=$(git rev-parse "HEAD:$file")
        # Change mode to symlink inside the index
        git update-index --add --cacheinfo  120000 $fhash "$file"
        # Restore from the index to the working directory
        git restore "$file"
done <<< "$files"
```
I just made it, not yet sure if it's practical, but at least it should help me not to forget to change those files back to symlinks.
