### ISSUE TITLE
Run on AWS

### ISSUE THREAD

**Issue by corollari** [overleaf/overleaf#620]
Has anyone set up an AWS environment to run sharelatex? Which services are you using?
By digging through git history it seems that sharelatex used to to use S3 to store all the user-provided resources and EC2 to run the containers. Is this still the best course of auction or are some newer services better for this task, such as Fargate & EFS?

**Comment by ShaneKilkelly** [comment]
Hi there! 

We generally recommend sticking to the docker-based way of deploying overleaf, but there's no reason why it wouldn't work with a custom setup on AWS. We just don't offer any support for those kind of custom deployments.

**Comment by corollari** [comment]
@ShaneKilkelly I know, it is just that by reading the code I realised that ShareLatex was running on AWS (there's several mentions of various services it used) but I couldn't find anywhere what was the structure that it used. I'd really appreciate if that info was available because then I would be able to replicate the scalability of sharelatex.

**Comment by nilforooshan** [comment]
What @corollari is asking is very interesting! A documentation on setting up an AWS env to run sharelatex would be very much appreciated. It should be possible with/without docker.
