### ISSUE TITLE
Outdated docker-compose.yml

### ISSUE THREAD

**Issue by pbruneau** [overleaf/overleaf#621]
## Problem

The frontend installed when using docker-compose is outdated: e.g. web/public/js holds recent ace versions in the github "web" repository (1.4.3 to 5), when we get an old ace version with docker-compose (v1.2.5 in /var/www/sharelatex/web/public/js). Generally, it seems that the images on dockerhub are 1 year old: would it be possible to update them plz (or get the procedure to build an updated version locally?)

## Install type

Docker image

## Version

latest/v1.2.1

**Comment by prohde** [comment]
related to #613

**Comment by mserranom** [comment]
COverleaf CE 2.0.0 has been released: https://github.com/overleaf/overleaf/issues/613
