### ISSUE TITLE
rich text not recognising user defined commands

### ISSUE THREAD

**Issue by mattmajic** [overleaf/overleaf#622]
## Problem

User defined shortcuts for use in math mode, e.g. \def\d{\mathrm{d}} do not show in rich text mode, even if they correctly compile in the final pdf. I am aware that \d is a predefined command, but if it displays in the pdf, it makes sense to also display in rich text.

## Install type
not sure, I signed up for the free version of overleaf on 8 July 2019

## Logs and errors

no relevant errors that I can find

## Screenshots

See the integral d's in both the rich text and pdf
![torusTmatOverleaf](https://user-images.githubusercontent.com/52626279/60776197-62613600-a17e-11e9-8147-22b2fd9e100c.PNG)

**Comment by ShaneKilkelly** [comment]
Hi! If this is a bug affecting overleaf.com, please contact support at support@overleaf.com to report the problem.
