### ISSUE TITLE
Any instructions on non-docker installation?

### ISSUE THREAD

**Issue by fangq** [overleaf/overleaf#623]
I am trying to set up a copy of overleaf/sharelatex on my Ubuntu 16.04 sever. Found this page from google, and followed most of the way

https://gist.github.com/gelim/a840a99d15cb765cb7b65105b72f00c4

but still not yet to get it to work. A few things that this instruction fails on my linux box:

1. for nodejs, I need to use 12.x setup script, otherwise, I am getting errors

`curl -sL https://deb.nodesource.com/setup_12.x | sudo bash -
`
2. these two sets of commands did not work, and I still can not figure out how to fix

```
# Minify js assets
pushd /var/www/sharelatex/web
grunt compile:minify
popd

pushd /var/www/sharelatex/clsi
grunt compile:bin
popd
```
I first got an error thta es6-promise was missing, then I installed it manually using the below command

`npm install es6-promise`

I am still getting a bunch of errors, like below:

```
root@taote:/var/www/sharelatex/web# grunt compile:minify
Running "requirejs:compile" (requirejs) task
Error: Error: ERROR: module path does not exist: /var/www/sharelatex/web/public/js/main.js for module named: main. Path is relative to: /var/www/sharelatex/web
    at /var/www/sharelatex/web/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:30214:35

    at /var/www/sharelatex/web/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:30099:19
    at /var/www/sharelatex/web/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:3081:39
    at /var/www/sharelatex/web/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:3021:25
    at Function.prim.nextTick (/var/www/sharelatex/web/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:29929:9)
....
```

for the compile:bin command, I am getting a different error

```
root@taote:/var/www/sharelatex/clsi# grunt compile:bin
No settings or defaults found. I'm flying blind.
Warning: Task "compile:bin" not found. Use --force to continue.

Aborted due to warnings.
```

3. I originally had Apache2 as web sever, but the apache conf file I found via googling did not seem to work (could not connect to localhost:3000 port), then I had to remove apache and installed nginx, but now I am getting a **502 Bad Gateway** error.

in nginx error log, I saw the below message:

> 2019/07/08 23:41:10 [error] 1280#1280: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: "localhost"

I am wondering if some one can provide a more up to date installation guide on ubuntu? would be nice to include this instruction in the release.

thanks

**Comment by fangq** [comment]
another related question, in the above gist link, the author used an offline script to install texlive, I am wondering if I can use apt-get instead? prefer to manage all all packages via apt.

**Comment by mserranom** [comment]
Unfortunately we can't produce such instructions. Among other things, here are some strict needs on Node versioning and we don't contemplate other installations.
