### ISSUE TITLE
Link sharing doesn't work as expected?

### ISSUE THREAD

**Issue by ho1ger** [overleaf/overleaf#628]
I set up a sharelatex server with docker and nginx. The nginx configuration looks like this:

    server {
        server_name xxx.xxx.xxx;

        add_header Strict-Transport-Security "max-age=31536000; includeSubdomains;";
        server_tokens off;
        add_header X-Frame-Options SAMEORIGIN;
        add_header X-Content-Type-Options nosniff;
        client_max_body_size 50M;

        listen 443 ssl; # managed by Certbot
        ssl_certificate /etc/letsencrypt/live/xxx.xxx.xxx/fullchain.pem; # managed by Certbot
        ssl_certificate_key /etc/letsencrypt/live/xxx.xxx.xxx/privkey.pem; # managed by Certbot
        include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

        location / {
            proxy_pass              http://localhost:5180;
            proxy_set_header        X-Forwarded-Proto $scheme;
            proxy_http_version 1.1;        
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_read_timeout 3m;
            proxy_send_timeout 3m;
            access_log      /var/log/nginx/latex.access.log;
            error_log       /var/log/nginx/latex.error.log;    
        }

    }

    server {
        if ($host = xxx.xxx.xxx) {
            return 301 https://$host$request_uri;
        } # managed by Certbot

        server_name xxx.xxx.xxx;
        listen 80;
        return 404; # managed by Certbot
    }

The docker-compose file like this:

    version: '2'
    services:
        sharelatex:
            restart: always
            image: flodointhecloud/sharelatex-texlive2019
            container_name: sharelatex
            depends_on:
                - mongo
                - redis
            privileged: true
            ports:
                - 5180:80
            links:
                - mongo
                - redis
            volumes:
                - /docker/sharelatex_data:/var/lib/sharelatex
                - /var/run/docker.sock:/var/run/docker.sock
            environment:
                SHARELATEX_MONGO_URL: mongodb://mongo/sharelatex
                SHARELATEX_REDIS_HOST: redis
                SHARELATEX_APP_NAME: ShareLaTeX
                SHARELATEX_SITE_URL: https://xxx.xxx.xxx
                SHARELATEX_NAV_TITLE: yyyyy

                SHARELATEX_SECURE_COOKIE: 1
                SHARELATEX_BEHIND_PROXY: 1

                mongo:
                     restart: always
                     image: mongo
                     container_name: mongo
                     expose:
                         - 27017
                     volumes:
                         - /docker/mongo_data:/data/db

                 redis:
                     restart: always
                     image: redis
                     container_name: redis
                     expose:
                         - 6379
                     volumes:
                         - /docker/redis_data:/data

With these settings everything works reasonably well. However, there is a problem with link sharing. When I click on share -> link sharing, the system gives me a share linke list this: https://xxx.xxx.xxx/4557968988kgxccggffcvb.

However, when I open this link, the browser loads the login screen for users. That shouldn't actually happen. How can I fix this problem? Thanks.

**Comment by mserranom** [comment]
Link sharing should be fixed in version `2.0.0`, feel free to reopen the issue if you experience an issue running the latest image. (Note that you need extra environment variables as described in https://github.com/overleaf/overleaf/wiki/Release-Notes-2.0)
