### ISSUE TITLE
Impossible to edit newly created project

### ISSUE THREAD

**Issue by pbruneau** [overleaf/overleaf#630]
## Problem

When opening a blank or example project I just created, the editor displays an error message and freezes (see screenshots). It is impossible to edit the project then.

## Install type

Ubuntu 16.04
Chrome 75

## Version

Generated from the latest overleaf/docker-image,
using `make build-base` and `make build-community`,
Then I run docker-compose using yml in the latest overleaf/overleaf.

## Logs and errors

No error message in the Chrome console,
neither when running `docker logs` on sharelatex, redis and mongo containers.
No error in `/var/log/sharelatex-errors.log` either.

## Screenshots

![screenshots](https://user-images.githubusercontent.com/4252621/63510264-6bb02300-c4de-11e9-8892-24eeced4ffc7.png)

**Comment by danmakarov** [comment]
Seems to work fine on Chrome: https://app.birdeatsbug.com/sessions/XviPgFPqLBJr3dvyPlou1

**Comment by pbruneau** [comment]
OK I just tried right now, build-community does not event build any more...

**Comment by jdleesmiller** [comment]
We are working on a new community edition build now, so things may be in a bit of an inbetween state, sorry. https://github.com/overleaf/overleaf/issues/613

**Comment by mickaelbaron** [comment]
Hi,

Can you check into the document-updater.log file if you have an error related to Redis connection?

I had the same issue. Don't forget to set both environnement variables: REDIS_HOST and SHARELATEX_REDIS_HOST.

Mickael

**Comment by mserranom** [comment]
@pbruneau This should be fixed now, feel free to reopen if you experience the same problem.

**Comment by pbruneau** [comment]
It's fine indeed,
Thanks for the support!
