### ISSUE TITLE
"Delete Forever" has no effect in 2.0.0

### ISSUE THREAD

**Issue by Grumium** [overleaf/overleaf#644]
Related to #613

## Problem
After achiving a project it is not possible to delete it permanently from the deleted projects.

## Screenshots
![Unbenannt-1](https://user-images.githubusercontent.com/47479352/66468645-cbf72600-ea86-11e9-8c21-4c24655c1261.jpg)
Clicking "Confirm" only temporarily removes the project from the list.

**Comment by mserranom** [comment]
Thanks for the report, I'll investigate the problem.
