### ISSUE TITLE
Cite autocomplete not working in 2.0.0

### ISSUE THREAD

**Issue by Arkhaeon** [overleaf/overleaf#646]
Autocompletion for \cite{} does not work and only shows \cite{} as an option, even though the .tex file successfully compiles with references.

Installed using the docker sharelatex/sharelatex:latest image (2.0.0).

**Comment by Grumium** [comment]
I can confirm!
In addition, it would be really neat to get this working with BibTeX files as well, included via `\bibliography{mybib1.bib,mybib2.bib,...}`

**Comment by mserranom** [comment]
I'm afraid this feature is not available in Overleaf Community Edition. Reference autocomplete is only available in Overleaf Server Pro.
