### ISSUE TITLE
Missing toolbar-editor

### ISSUE THREAD

**Issue by erlef10** [overleaf/overleaf#653]
## Problem

Web interface is missing the editor toolbar. Also missing comments.

## Install type
Built containers from master with make base and community running on Docker version 18.09.7, build 2d0083d

## Version

Latest build

## Logs and errors

[logs.tar.gz](https://github.com/overleaf/overleaf/files/3762510/logs.tar.gz)

## Screenshots

![missing-toolbar-editor](https://user-images.githubusercontent.com/52603288/67396674-4906bd00-f5a8-11e9-897d-6a8e97b44a60.png)

**Comment by mserranom** [comment]
Thanks for reporting.  What do you mean by "missing comments" ?

I understand left screenshot is Overleaf CE, while right comes from overleaf.com. Is that correct?

**Comment by erlef10** [comment]
That is correct, the right is overleaf.com.

Sorry, by "missing comment, I meant the "Add comment" function:
![Add comment](https://user-images.githubusercontent.com/52603288/67418314-d8bd6300-f5ca-11e9-8492-1cda58c6d102.png)

It shows up when text is highlighted, but has no function when clicked.

**Comment by das7pad** [comment]
The backend logic for comments are part of the `track-changes` module, which is not open sourced (yet?). It may be part of Server Pro.

**Comment by mserranom** [comment]
That is correct, the scope of this issue is to fix the UI for Overleaf CE where the features are not available.

**Comment by ruezetle** [comment]
I can confirm this issue with the prebuilt docker image `sharelatex/sharelatex:2.0.1`.

**Comment by mserranom** [comment]
Just to clarify: the actual bug in Overleaf Community Edition is cosmetic, it's showing an empty bar. Rich Text editor, Track Changes and comments are features that are not available in Community Edition.

**Comment by ShaneKilkelly** [comment]
As @mserranom says, this is a cosmetic issue that slipped through in the last release. The bar should be removed in CE, as there's nothing for it to display. We do have a plan to fix this in an upcoming release.

**Comment by ShaneKilkelly** [comment]
We're tracking this issue in an internal ticket, so I'll close this ticket for now. Thanks!

**Comment by ocordes** [comment]
Hi, the bar is not useless in CE. It contains the split screen button which is necessary if you activate split screen and move to editor mode. The button is only visible if you move to PDF view ... please add at least the bar with this small button ... everything else maybe a feature of the PRO edition

**Comment by mlevans0** [comment]
Hey @ashwinjosephk which version of CE are you using? Could you also please try the following to see if they help:

- Clear your browser's cookies and cache (especially the cookies)
- Use the Incognito/Private mode of your browser
- Disable all browser extensions/plugins, especially ad-blockers and download managers, or firewalls/proxies, that you may be running
- Upgrade your browser (see also https://www.overleaf.com/learn/how-to/What_browsers_do_you_support)
- Use a different browser or computer, or connect using a different network (home/network/mobile)

Do any of these make a difference? If not, could you provide a screenshot of the editor and the developer console?
