### ISSUE TITLE
How to ensure the security of the article on the overleaf of local version?

### ISSUE THREAD

**Issue by ngl567** [overleaf/overleaf#655]
Thank you for the open-source overleaf, but I have two issues:
1. Why the overleaf runs very slow，it will take a long time to refresh?
2. How to ensure the security of all the articles on overleaf because it connects to network?

**Comment by mserranom** [comment]
1. Overleaf is quite resource intensive, particularly memory, try to increase the resource allocation for your install.
2. That's a question for the community. We also offer a supported on premises version, [Server Pro](https://www.overleaf.com/for/enterprises).

**Comment by ngl567** [comment]
Thank your for your reply and the very useful project.
