### ISSUE TITLE
Cannot sort user list in admin interface

### ISSUE THREAD

**Issue by moschlar** [overleaf/overleaf#657]
## Steps to Reproduce

1. Go to Admin -> "Manage Users"
2. Click on table column header (e.g. "Last logged in")

## Expected Behaviour
The table should be sorted by the selected column.

## Observed Behaviour
Nothing happens.

## Context
I want to be able to quickly determine whether a user is actually using OverLeaf or has just logged in once out of curiosity.

## Technical Info
OverLeaf Server Pro 2.0.1 (but I observed this in earlier versions, too)

* Browser Name and version: Mozilla Firefox 69.0.2
* Operating System and version (desktop or mobile): Debian GNU/Linux 10 (buster)
* Signed in as: Administrator

**Comment by mserranom** [comment]
Thanks for the feature request. Unfortunately sorting is not available for the admin panel.

**Comment by moschlar** [comment]
Thanks for your response!
I would have thought it is actually a bug, because my cursor changes to the one for clickable elements, when I hover over the column header. :wink: 
But anyways - would be a nice feature.
