### ISSUE TITLE
Logs missing

### ISSUE THREAD

**Issue by Jungack** [overleaf/overleaf#658]
Hello,
It might sound stupid but I can't find the logs in the /var/log/sharelatex path. The folder sharelatex even does not exist. How can I enable the logs please ?

**Comment by mserranom** [comment]
Weird, it should exist. can you `ls /var/log` in `sharelatex` container?

**Comment by mserranom** [comment]
> I tried to mount this path as a volume in the docker-compose file but did not work

What was the error?

Try mounting `~/sharelatex_log:/var/log/sharelatex` instead of  `~/sharelatex_log:/var/log`.

**Comment by Jungack** [comment]
Ok figured out the problem was the mounting point : you are right, thank you so much !

**Comment by marcorighi** [comment]
Sorry, can you help me to configure fail2ban? I created /var/log/sharelatex but it is still empty.
