### ISSUE TITLE
Admin access all project

### ISSUE THREAD

**Issue by klebermagno** [overleaf/overleaf#663]
How admin can view or be in shared in all projects?
Sharelatex 2.0.1 ?

**Comment by mserranom** [comment]
I'm sorry, could you elaborate a bit more on what the problem is, perhaps include an example?

**Comment by ShaneKilkelly** [comment]
Admin users do have access to all projects (in the sense that they can load any project in the system), but there is no single list of all projects in the system.

In the Server Pro edition, the closest you can get is to go to the `/admin` section and click through to a particular User, then click on their "Projects" tab, and open the project from there. The Community Edition does not include this admin functionality.
