### ISSUE TITLE
SMTP Email is not working in Overleaf Community

### ISSUE THREAD

**Issue by gleisonsoares** [overleaf/overleaf#665]
Hello! Good night! I am Brazilian and my English is not very good, I am Sorry: this is the first time I ask for help in an English language forum!
I am setting the SMTP email according with the page [https://github.com/overleaf/overleaf/wiki/Configuring-SMTP-Email](https://github.com/overleaf/overleaf/wiki/Configuring-SMTP-Email).
1. I have e-mail server is enabled on your localhost, and it's listening to local connections (through Command Line the mails are send corectly);  
2. When setting the SHARELATEX_EMAIL_FROM_ADDRESS variable I get the following message
ERROR: The Compose file './docker-compose.yml' is invalid because:
**Unsupported config option for services.sharelatex: 'SHARELATEX_EMAIL_FROM_ADDRESS';**
3. Same thing with variables SHARELATEX_EMAIL_SMTP_HOST,    SHARELATEX_EMAIL_SMTP_PORT, SHARELATEX_EMAIL_SMTP_SECURE,       SHARELATEX_EMAIL_SMTP_USER, SHARELATEX_EMAIL_SMTP_PASS,       SHARELATEX_EMAIL_SMTP_TLS_REJECT_UNAUTH, SHARELATEX_EMAIL_SMTP_IGNORE_TLS, SHARELATEX_CUSTOM_EMAIL_FOOTER.
4. It is my docker-compose.yml:
`version: '2.2'
services:
    sharelatex:
        restart: always
        # Server Pro users: 
        # image: quay.io/sharelatex/sharelatex-pro
        image: sharelatex/sharelatex
        container_name: sharelatex
        depends_on:
            mongo:
                condition: service_healthy
            redis:
                condition: service_started
        privileged: true
        ports:
            - 810:80
        links:
            - mongo
            - redis
        volumes:
            - ~/sharelatex_data:/var/lib/sharelatex
            - /var/run/docker.sock:/var/run/docker.sock
        environment:

            SHARELATEX_APP_NAME: Overleaf Community Edition

            SHARELATEX_MONGO_URL: mongodb://mongo/sharelatex
            #SHARELATEX_SITE_LANGUAGE: 'pt'
            # Same property, unfortunately with different names in
            # different locations
            SHARELATEX_REDIS_HOST: redis
            REDIS_HOST: redis

            ENABLED_LINKED_FILE_TYPES: 'url,project_file'

            # Enables Thumbnail generation using ImageMagick
            ENABLE_CONVERSIONS: 'true'

            ## Set for SSL via nginx-proxy
            #VIRTUAL_HOST: 103.112.212.22

            # SHARELATEX_SITE_URL: http://sharelatex.mydomain.com
            # SHARELATEX_NAV_TITLE: Our ShareLaTeX Instance
            # SHARELATEX_HEADER_IMAGE_URL: http://somewhere.com/mylogo.png
            SHARELATEX_ADMIN_EMAIL: gleisomoura@gmail.com

             #SHARELATEX_LEFT_FOOTER: '[{"text": "Powered by <a href=\"https://www.sharelatex.com\">ShareLaTeX</a> 2016"},{"text": "Another page I want to link to can be found <a href=\"here\">here</a>"} ]'
            # SHARELATEX_RIGHT_FOOTER: '[{"text": "Hello I am on the Right"} ]'

            # SHARELATEX_EMAIL_AWS_SES_ACCESS_KEY_ID:
            # SHARELATEX_EMAIL_AWS_SES_SECRET_KEY:

        #SHARELATEX_EMAIL_FROM_ADDRESS: "gleisomoura@gmail.com"
        #SHARELATEX_EMAIL_SMTP_HOST: smtp.gmail.com
        #SHARELATEX_EMAIL_SMTP_PORT: 587
        #SHARELATEX_EMAIL_SMTP_SECURE: 'true'
        #SHARELATEX_EMAIL_SMTP_USER: gleisomoura@gmail.com
        #SHARELATEX_EMAIL_SMTP_PASS: mypassword
        #SHARELATEX_EMAIL_SMTP_TLS_REJECT_UNAUTH: 'true'
        #SHARELATEX_EMAIL_SMTP_IGNORE_TLS: 'false'
        #SHARELATEX_CUSTOM_EMAIL_FOOTER: "<div>This system is run by me</div>"

            ################
            ## Server Pro ##
            ################

            # SANDBOXED_COMPILES: 'true'

            # SANDBOXED_COMPILES_SIBLING_CONTAINERS: 'true'
            # SANDBOXED_COMPILES_HOST_DIR: '/var/clsi/compiles'

            # DOCKER_RUNNER: 'false'

            ## Works with test LDAP server shown at bottom of docker compose
            # SHARELATEX_LDAP_URL: 'ldap://ldap:389'
            # SHARELATEX_LDAP_SEARCH_BASE: 'ou=people,dc=planetexpress,dc=com'
            # SHARELATEX_LDAP_SEARCH_FILTER: '(uid={{username}})'
            # SHARELATEX_LDAP_BIND_DN: 'cn=admin,dc=planetexpress,dc=com'
            # SHARELATEX_LDAP_BIND_CREDENTIALS: 'GoodNewsEveryone'
            # SHARELATEX_LDAP_EMAIL_ATT: 'mail'
            # SHARELATEX_LDAP_NAME_ATT: 'cn'
            # SHARELATEX_LDAP_LAST_NAME_ATT: 'sn'
            # SHARELATEX_LDAP_UPDATE_USER_DETAILS_ON_LOGIN: 'true'

            # SHARELATEX_TEMPLATES_USER_ID: "578773160210479700917ee5"
            # SHARELATEX_NEW_PROJECT_TEMPLATE_LINKS: '[ {"name":"All Templates","url":"/templates/all"}]'
            # SHARELATEX_PROXY_LEARN: "true"`

`
    mongo:
        restart: always
        image: mongo
        container_name: mongo
        expose:
            - 27017
        volumes:
            - ~/mongo_data:/data/db
        healthcheck:
            test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
            interval: 10s
            timeout: 10s
            retries: 5

    redis:
        restart: always
        image: redis
        container_name: redis
        expose:
            - 6379
        volumes:
            - ~/redis_data:/data

    # ldap:
    #    restart: always
    #    image: rroemhild/test-openldap
    #    container_name: ldap
    #    expose:
    #        - 389
# nginx-proxy:
#     image: jwilder/nginx-proxy
#     container_name: nginx-proxy
#     ports:
#       #- "80:80"
#       - "443:443"
#     volumes:
#       - /var/run/docker.sock:/tmp/docker.sock:ro
#       - /home/sharelatex/tmp:/etc/nginx/certs`
5. When registering a user the system does not send the activation link. The send SMTP Email is only available in the version Pro?

**Comment by lovestat** [comment]
I am stuck in the same issue.

According to the log (/var/log/sharelatex/web.log in docker), it says:

```
{"name":"web","hostname":"private","pid":135,"level":30,"receiver":"private@example.com","subject":"Confirm Email","msg":"sending email","time":"2019-11-14T09:30:37.346Z","v":0}
{"name":"web","hostname":"private","pid":135,"level":40,"err":{"message":"getaddrinfo ENOTFOUND smtp.google.com smtp.google.com:465","name":"Error","stack":"Error: getaddrinfo ENOTFOUND smtp.google.com smtp.google.com:465\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)\n","info":{},"code":"ENOTFOUND"},"msg":"error sending message","time":"2019-11-14T09:30:37.484Z","v":0}
{"name":"web","hostname":"private","pid":135,"level":50,"err":{"message":"Cannot send email","name":"Error","stack":"Error: Cannot send email\n    at /var/www/sharelatex/web/app/src/Features/Email/EmailSender.js:148:17\n    at Nodemailer.<anonymous> (/var/www/sharelatex/web/node_modules/nodemailer/lib/nodemailer.js:213:26)\n    at SMTPConnection.<anonymous> (/var/www/sharelatex/web/node_modules/nodemailer-smtp-transport/lib/smtp-transport.js:80:16)\n    at Object.onceWrapper (events.js:286:20)\n    at SMTPConnection.emit (events.js:198:13)\n    at SMTPConnection.EventEmitter.emit (domain.js:448:20)\n    at SMTPConnection._onError (/var/www/sharelatex/web/node_modules/smtp-connection/lib/smtp-connection.js:414:10)\n    at TLSSocket.emit (events.js:198:13)\n    at TLSSocket.EventEmitter.emit (domain.js:448:20)\n    at emitErrorNT (internal/streams/destroy.js:91:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n","info":{}},"url":"/user/emails/resend_confirmation","method":"POST","user":{"id":"private","email":"private@example.com"},"msg":"error passed to top level next middleware","time":"2019-11-14T09:30:37.493Z","v":0}
{"name":"web","hostname":"private","pid":135,"level":30,"req":{"url":"/user/emails/resend_confirmation","method":"POST","referrer":"private","remote-addr":"127.0.0.1","user-agent":"private","content-length":"75"},"res":{"statusCode":500},"response-time":201,"msg":"http request","time":"2019-11-14T09:30:37.534Z","v":0}
```

It seems that `nodemailer.js` fails to lookup the name server and get ip address.

**Comment by ShaneKilkelly** [comment]
Hi @gleisonsoares , I've taken a look at the docker-compose text you've included in your comment, and I think this might be an indentation issue. I think that docker-compose is confused because the `SHARELATEX_EMAIL_*` keys are not indented in line with the other config keys. Because they are indented to the wrong level, docker-compose thinks that they are a sibling of the `environment` section, whereas they should really be inside the `environment` section.

See this image:

![image](https://user-images.githubusercontent.com/1540054/68846479-13478680-06c5-11ea-8da8-82e5eda45384.png)

The purple section should align with its siblings marked in red, not with the section marked in green.

I hope that helps!
