### ISSUE TITLE
Track Changes to Community Edition

### ISSUE THREAD

**Issue by wixaw** [overleaf/overleaf#666]
## Steps to Reproduce
1. Use track changes 

## Expected Behaviour
Find functionnality in show hotkeys list

## Observed Behaviour
Nothing

## Technical Info
* URL: private
* Overleaf 2.0.1 Community edition

Hello 
Will we find this feature on the community edition soon?
Thank you in advance
William

**Comment by mserranom** [comment]
We have no plans to include the feature on the Community Edition, sorry.
