### ISSUE TITLE
Is it possible to export into .docx from LaTex file

### ISSUE THREAD

**Issue by narendra36** [overleaf/overleaf#668]
I was looking for an option to export a latex file (that includes some diagrams and tables) as .docx but it seems that there is only option to export as PDF. 
Please Let me know if there is one?

**Comment by ShaneKilkelly** [comment]
We don't have anything like this in Overleaf, but I know that [Pandoc](https://pandoc.org/) can convert latex to docx.

**Comment by LindaLuck** [comment]
I found best way is to download as pdf, then convert in Adobe Acrobat (not the reader). Keeps the formatting and even line numbers if using

**Comment by JHarrisonEcoEvo** [comment]
I second the motion that incorporating a Pandoc conversion into overleaf could be handy

**Comment by adam2392** [comment]
^ I third the motion if it is possible to incorporate it natively into overleaf.

**Comment by sgirardin** [comment]
I just tried, and you can open the PDF with word and the output is really good (not perfect but it's "free").
