### ISSUE TITLE
Bug when typing backslash command + Korean on the same line

### ISSUE THREAD

**Issue by lovestat** [overleaf/overleaf#672]
## Steps to Reproduce

When I type any backslash command and some Korean words on the same line, the former texts are all deleted while typing. Please refer to the following screen capture. Everything is fine when I only type English or there is no backslash command.

![issue](https://user-images.githubusercontent.com/17664107/70504586-5af8eb00-1b69-11ea-9013-ae742803a3c9.gif) 

## Technical Info

* URL: NA
* Browser Name and version: Firefox 71.0
* Operating System and version (desktop or mobile): Windows 10
* Signed in as: NA
* Project and/or file: NA
* I am running the latest docker images on Ubuntu 18.04.

**Comment by ShaneKilkelly** [comment]
Hi there!

Would you mind sending an email to support@overleaf.com, with the details of this bug? The issue tracker on this repo is mostly for issues which specifically affect the on-site installations of overleaf, while we tend to handle these general bugs through the usual support channels.

Thanks!
