### ISSUE TITLE
"Add comment" button is visible in Community Edition

### ISSUE THREAD

**Issue by clemoan** [overleaf/overleaf#678]
I deployed sharelatex community edition using docker. The review panel is hidden. I see the «add comment» button which is ineffective. 
 Is this a bug due to bad configuration or a limitation ? 

Thanks in advance

**Comment by mserranom** [comment]
Track Changes is available in our Server Pro offering only.
https://www.overleaf.com/for/enterprises

**Comment by mserranom** [comment]
Would you mind providing a screenshot of the "Add Comment" button? You shouldn't see anything like that in Community Edition. Thanks!

**Comment by clemoan** [comment]
Bad news for us.
It appears when you select a text.
![Capture du 2020-01-08 14-39-00](https://user-images.githubusercontent.com/4123413/71982397-a95edf80-3224-11ea-9d13-ee2b7049acbd.png)

**Comment by mserranom** [comment]
Thanks! I updated the title to reflect the actual problem

**Comment by ShaneKilkelly** [comment]
Hi @clemoan, we're tracking this issue in an internal ticket, and will update this issue when the problem is solved. Thanks for bringing this to our attention!

**Comment by cryptoluks** [comment]
Still visible.

**Comment by cryptoluks** [comment]
Fixed for me in latest version. Can probably be closed.

**Comment by mserranom** [comment]
Closing, thanks!

**Comment by KiralyCraft** [comment]
Sorry to bump this after all these years, but it seems the problem is back. I'm running `sharelatex/sharelatex:5.4.1-with-texlive-full` in the Docker variant (installed all textlive-full as per the instructions) and the button is visible again, resulting in an error:

![Image](https://github.com/user-attachments/assets/1447349e-161d-4f03-b75b-8b5a860efd95)

**Comment by mlevans0** [comment]
Hi @KiralyCraft, thank you for reaching out. This is something we are currently aware of and are working on a fix. We hope to have it released soon.

**Comment by lugetego** [comment]
> Sorry to bump this after all these years, but it seems the problem is back. I'm running `sharelatex/sharelatex:5.4.1-with-texlive-full` in the Docker variant (installed all textlive-full as per the instructions) and the button is visible again, resulting in an error:
> 
> ![Image](https://github.com/user-attachments/assets/1447349e-161d-4f03-b75b-8b5a860efd95)

I'm in the same situation using:
sharelatex/sharelatex:5.5.0-with-texlive-full

Thanks!

**Comment by mlevans0** [comment]
Hi @lugetego, this issue has now been resolved. Please, can you try upgrading to 5.5.4 and retry?
