### ISSUE TITLE
"Unable to connect" message - but it connects

### ISSUE THREAD

**Issue by luspi** [overleaf/overleaf#681]
## Steps to Reproduce

1. Installed Overleaf using docker
2. Open any project or create a new one

## Expected Behaviour

Everything should load without showing any "Unable to connect" message.

## Observed Behaviour

The "Unable to connect" message is shown but after a few seconds (typically ~10) everything loads just fine.

## Context

It is not a huge issue but requires me to point this out to every user/collaborator to ignore that message at startup and just be patient. It also renders the message useless when there really is a problem connecting.

Note: If I first SSH onto the server and then do the same steps from within the server network the message does not appear and everything loads just fine (using the same browsers).

## Technical Info

* Browser Name and version: Firefox 72, Chromium 79
* Operating System and version (desktop or mobile): I'm running Arch Linux (desktop), the server runs Ubuntu 18.04. Overleaf is the latest docker image pulled yesterday.

## Analysis

I can't find anything out of the ordinary in any of the log files, but would be happy to provide any if helpful.

**Comment by Zeawiel** [comment]
Hello,
I had also this issue, it was related to websocket.
If you open the network dev tool of your navigator you'll see that there is some request that gets 404.

Do you enable websocket in your (reverse) proxy ? You need to add this to the config:
```
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
```
See : https://github.com/overleaf/overleaf/wiki/HTTPS-reverse-proxy-using-Nginx

**Comment by ShaneKilkelly** [comment]
Hi, thanks for bringing this to our attention. Given @Zeawiel 's comment, I suspect this has something to do with the local network, especially as a direct connection works fine. 

Can you try adding the configuration @Zeawiel posted? If this fixes the problem we can add this to th e general documentation.

**Comment by luspi** [comment]
Sorry for the delay, yes, this does indeed solve the issue! Thanks @Zeawiel!

**Comment by ShaneKilkelly** [comment]
Excellent!

**Comment by asvattha** [comment]
Hello, I am getting the exact same problem, and the above fix didn't work in my case.  I have installed it on synology nas, with reverse proxy. I can access it over https. 

In addition, in nginx.conf file in the line proxy_pass, if i set the port number to my sharelatex port number says, 8070 (which is set in the overleaf.rc file) then it gives 502 bad gateway error. however, when change it to 80 then it works correctly.
