### ISSUE TITLE
Support for LanguageTool

### ISSUE THREAD

**Issue by beevelop** [overleaf/overleaf#682]
## Steps to Reproduce
1. Install LanguageTool Chrome Plugin
2. Navigate to Overleaf
3. Open a document

## Expected Behaviour
LanguageTool should be able to check my document.

## Observed Behaviour
LanguageTool complains with the following message:
> Sorry, this site uses a technology for its text editing that we cannot support. Please contact the site owners and ask them to integrate LanguageTool

## Context
LanguageTool is a proofreading software that supports multiple languages (better than Grammarly).

## Technical Info
Integrating LanguageTool is pretty straight-forward: http://wiki.languagetool.org/integration-on-websites

- Chrome: `v80.0.3987.16`
- LanguageTool Chrome Plugin: `v3.0.4`

**Comment by ShaneKilkelly** [comment]
Hi @beevelop, thanks for bringing this to our attention. Unfortunately, as the LanguageTool says, our editor is built in a way that makes this difficult to support. We are planning to replace the entire editor with something more modern in the near future, and when we do so we'll definitely keep this use-case in mind.

**Comment by beevelop** [comment]
Thank you for the response. Is there an issue to track for the new editor?

**Comment by danielnaber** [comment]
The [LanguageTool add-on](https://languagetool.org/addon-redirect) now supports Overleaf.com. If you find bugs with the support, please report them at https://forum.languagetool.org.

**Comment by JohnHammersley** [comment]
Thanks Daniel -- yes, this was great to see :) 

For anyone finding this thread, there's a short (updated) blog post with details [here](https://www.overleaf.com/blog/635-languagetool-a-free-browser-add-on-to-check-your-grammar-and-spelling).

**Comment by LukasBec** [comment]
LanguageTool does not seem to work for me on a self-hosted overleaf but works fine on overleaf.com
Is this normal behavior, or am I missing something?

**Comment by danielnaber** [comment]
> LanguageTool does not seem to work for me on a self-hosted overleaf but works fine on overleaf.com

It's a known issue but should be fixed with the next update (might take 2-3 weeks).
