### ISSUE TITLE
Suggestion: locking files (making files read-only) by project owner

### ISSUE THREAD

**Issue by ivankokan** [overleaf/overleaf#685]
## Suggestion
Considering the multi-user project for which some editable files (custom classes, packages etc.) must not be changed by regular project members (due to their inexperience or clumsiness), I suggest that file access attributes can be set by the project owner, in the following fashion:
- editable only by owner
- editable (by every user).

**Comment by ShaneKilkelly** [comment]
Hi! Thanks for this suggestion. This repository is mostly used for reporting issues specific to the open-source release of Overleaf. Could you email this feature request to support@overleaf.com please? From there it can be routed to the right people.

Thanks!

**Comment by ivankokan** [comment]
Hi @ShaneKilkelly.

What I really thought was "the users the project is shared with and have Edit rights" (even for the free version of Overleaf). In such case, the owner might permit editing for specific files within the project due to already mentioned reasons.

Did I misuse the syntagm "regular project members"?
