### ISSUE TITLE
Full-scheme TexLive install update

### ISSUE THREAD

**Issue by 2014CAIS01** [overleaf/overleaf#687]
## Steps to Reproduce

1. Install full-scheme TexLive in the container.
2. Update docker container from `2.1.0` to `2.1.1-beta-1`

## Expected Behaviour

The new container have full-scheme install of TexLive.

## Observed Behaviour

The new containner have a minimal install of TeXLive. 

## Context

Can I update the containner without reinstall full-scheme TexLive?

## Technical Info

* URL:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Signed in as:
* Project and/or file:

**Comment by ahmedmagdiosman** [comment]
I found a way that's a bit hacky but doesn't require re-building the docker container. Basically you copy the installed texlive into a mountable volume, such that when you update texlive, your updates are persistent.

1. Mount a new directory with any name:  texlive-copy:/texlive-copy
2. Shell into the container
3. Copy /usr/local/texlive to /texlive-copy
4. Close the container and mount the texlive-copy dir as the original texlive:
    texlive-copy:/usr/local/texlive

**Comment by ShaneKilkelly** [comment]
Unfortunately the texlive install is local to the container, so it doesn't survive version upgrades. @ahmedmagdiosman 's solution is a decent stop-gap until we re-assess how we handle this.
