### ISSUE TITLE
Open source `sharelatex-dev-environment`

### ISSUE THREAD

**Issue by andreiborisov** [overleaf/overleaf#700]
A lot of dev project files are generated with https://github.com/sharelatex/sharelatex-dev-environment (here is an example https://github.com/overleaf/clsi/blob/master/Dockerfile), however, it's not open-sourced, which is making project setup for the development quite hard.

It would be nice to have access to the full dev pipeline to better understand what's going on and contribute more easily.

**Comment by mserranom** [comment]
We have launched a new development environment for Overleaf CE, please check it out. Any feedback is appreaciated!

https://github.com/overleaf/overleaf/tree/main/develop
