### ISSUE TITLE
tlmgr verify checksum error

### ISSUE THREAD

**Issue by vinaysb** [overleaf/overleaf#716]
Hello, I am running an instance of sharelatex/overleaf on my system via docker. When I try to run `docker exec sharelatex tlmgr install scheme-full` I get the following error, 
```
/usr/local/texlive/2019/bin/x86_64-linux/tlmgr: unexpected return value from verify_checksum: -5
```

I even tried to add the tlcontrib & its verification, I still got the same error

**Comment by jdleesmiller** [comment]
This seems to be a problem in TeX Live at the moment, based on [mailing list](https://www.tug.org/texlive/lists.html) traffic. Karl Berry says:

> Indeed, the gpg key for the main TL19 repository expired yesterday :(. The TL20 release will have an updated key.

> There have been no updates to TL19 for some weeks, and won't be any in the future.  If you want/need to run tlmgr from TL19 anyway, e.g., because there are some older updates you didn't previously get, you can tell it to skip verification with tlmgr --verify-repo=none.

**Comment by Turakar** [comment]
TL20 seems to be released now, so a new image on docker hub would be helpful.

**Comment by Pingger** [comment]
So... when will this be fixed? Looks to me like a simple change of a 2 characters somewhere

**Comment by AdriBloober** [comment]
But how can i run overleaf with the sharelatex image with TL20?

**Comment by Turakar** [comment]
You can do a manual upgrade. You actually only need steps 8 and 10. On my instance, 10 errors, but a `tlmgr install scheme-full` afterwards fixes all problems :smile: 

https://tug.org/texlive/upgrade.html

**Comment by Keridos** [comment]
Why is this closed? This is a valid bug report and probably affects many users.

**Comment by AgentOak** [comment]
@Keridos That's what I've been doing too. I have turned it into a permanent (but not quite proper) solution with docker-compose by adding a bind-mount volume like this:
`- /var/opt/overleaf/sharelatex_texlive:/usr/local/texlive/2020`,
then installing TeXLive 2020 inside the running container and finally added the following to the `environment`:
`PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/texlive/2020/bin/x86_64-linux/'`

**Comment by jdleesmiller** [comment]
> Would be great to see an update to the official sharelatex-base image.

The CE 2.3.x images from June should be using TL 2020:
https://github.com/overleaf/overleaf/blob/02098ca23b2f4301f737296bb73652c7cf207730/Dockerfile-base#L49
