### ISSUE TITLE
Is it possible to push the compiled PDF to Github too?

### ISSUE THREAD

**Issue by JangoCG** [overleaf/overleaf#721]
Is it possible to push the compiled PDF to Github too?

**Comment by mserranom** [comment]
Github integration is not available in Overleaf Community Edition. For overleaf.com questions it's better to use the contact form: https://www.overleaf.com/contact.

Pushing the compiled PDF is not available in overleaf.com, sorry.

**Comment by 4ndre4s** [comment]
Would it not be possible to add a custom / modify existing .gitignore?

**Comment by daviddoji** [comment]
I'm also interested in this feature. Any updates on this @mserranom??

**Comment by rafisics** [comment]
+1 for enabling gitignore functionality on Overleaf.

**Comment by 4ndre4s** [comment]
Any updates here?
