### ISSUE TITLE
Cannot Enter the "Project" When I make an update, Mongo keeps restarting.

### ISSUE THREAD

**Issue by muguruzawang** [overleaf/overleaf#728]
## Steps to Reproduce

I am very stupid that I have made an update of the container sharelatex without back up. At very beginning, everything goes well. But after several days, even though I can log in the website, I cannot enter the Project, the following error appears:
![image](https://user-images.githubusercontent.com/48216295/80349415-cdacfd80-88a1-11ea-8988-10161638b766.png)

1.  update sharelatex container without back up
2.  log in the website with my account
3.  click "project" button.

## Expected Behaviour

Get into "Project" and my several projects can be viewed and edited. 

## Observed Behaviour

![image](https://user-images.githubusercontent.com/48216295/80349781-53c94400-88a2-11ea-8e39-6abb65c73eab.png)

## Context

I tried to addd SHARELATEX_REDIS_PORT: 6379    REDIS_PORT: 6379  as someone suggested into docker-compose.yml, but the problem still exists.
## Technical Info

* URL:
* Browser Name and version:
* Operating System and version (desktop or mobile): Red Hat
* Signed in as:
* Project and/or file:

## Analysis

I don't know whether the question is caused by the fact that I didn't have a backup when updating container. Actually, the newest version worked well for a certain period of time. It's when more people log in the website that the problem arose. 

What's worse, yesterday, When I tried to back up Mongodb, I killed it. Then the container mongo restarts again and again. Is there some solution to the above problems? @

**Comment by mserranom** [comment]
Is there any error message in the container logs `/var/log/sharelatex/web.log` or `/var/log/sharelatex/clsi.log` ?

**Comment by muguruzawang** [comment]
> Is there any error message in the container logs `/var/log/sharelatex/web.log` or `/var/log/sharelatex/clsi.log` ?

please check the web.log. I don't find obvious error message there.
[web.log](https://github.com/overleaf/overleaf/files/4540362/web.log)

**Comment by muguruzawang** [comment]
> Is there any error message in the container logs `/var/log/sharelatex/web.log` or `/var/log/sharelatex/clsi.log` ?

The error message in clsi.log is:
Unhandled rejection SequelizeDatabaseError: SQLITE_IOERR: disk I/O error
    at Query.formatError (/var/www/sharelatex/clsi/node_modules/sequelize/lib/dialects/sqlite/query.js:423:16)
    at afterExecute (/var/www/sharelatex/clsi/node_modules/sequelize/lib/dialects/sqlite/query.js:119:32)
    at replacement (/var/www/sharelatex/clsi/node_modules/sqlite3/lib/trace.js:19:31)
    at Statement.errBack (/var/www/sharelatex/clsi/node_modules/sqlite3/lib/sqlite3.js:16:21)
{ SequelizeDatabaseError: SQLITE_IOERR: disk I/O error
    at Query.formatError (/var/www/sharelatex/clsi/node_modules/sequelize/lib/dialects/sqlite/query.js:423:16)
    at afterExecute (/var/www/sharelatex/clsi/node_modules/sequelize/lib/dialects/sqlite/query.js:119:32)
