### ISSUE TITLE
unexpected return value from verify_checksum

### ISSUE THREAD

**Issue by jucajuca** [overleaf/overleaf#730]
hello the following command 
**docker exec sharelatex tlmgr install scheme-full**
returns the following error message. any ideas?
**/usr/local/texlive/2019/bin/x86_64-linux/tlmgr: unexpected return value from verify_checksum: -5**

## Steps to Reproduce

1. Installed sharelatex using the docker-compose file
2. ran docker exec sharelatex tlmgr install scheme-full

## Expected Behaviour
The container should have installed texlive. "To upgrade to a complete TeXLive installation, run the installation script in the Overleaf container with the following command:"

## Observed Behaviour

error meessage:
/usr/local/texlive/2019/bin/x86_64-linux/tlmgr: unexpected return value from verify_checksum: -5

## Context

install a full version of textlive
## Technical Info

docker
debian

**Comment by jdleesmiller** [comment]
Please see https://github.com/overleaf/overleaf/issues/716.
