### ISSUE TITLE
ShareLaTeX can not talk to the redis instance.

### ISSUE THREAD

**Issue by Soptq** [overleaf/overleaf#734]
## Steps to Reproduce

1. ShareLaTeX fails to connect to Redis after Redis started

![](https://user-images.githubusercontent.com/32592090/81277105-82a39f00-9086-11ea-98cc-aceb71f7d801.png)

## Expected Behaviour

ShareLaTex successfully connect to the Redis

## Observed Behaviour

1. Redis can be connect through netcat or redis-cli in sharelatex
2. Error reported that it might be because of the new safe strategy of Redis 6.0
![](https://user-images.githubusercontent.com/32592090/81277396-f180f800-9086-11ea-8afd-d6af59583980.png)

## Analysis

I fixed this issue by initiating a default password for Redis's default user. I will make a PR later.

**Comment by Lyken17** [comment]
Same here. Fresh (locally) built docker images and fresh install. When trying to laucn with `docker-compose up -d`, `Fatal error: cannot talk to redis` shows up.

**Comment by Lyken17** [comment]
and forcing the version to 5.0 works for me

**Comment by mserranom** [comment]
Using redis v5 should should fixed it. `docker-compose` has been updated in https://github.com/overleaf/overleaf/pull/737

**Comment by mrtntome** [comment]
This issue still persist with the provided docker-compose.yml.

**Comment by bububox** [comment]
still not working....

**Comment by hxhue** [comment]
Setting `SHARELATEX_REDIS_HOST` instead of `OVERLEAF_REDIS_HOST` worked for me. Mongo has the same problem.
