### ISSUE TITLE
how can i change the 'localhost' in the signup link to my server's ip?

### ISSUE THREAD

**Issue by zhengyima** [overleaf/overleaf#741]
how can i change the 'localhost' in the signup link to the ip of my server? 

![微信图片_20200520204403](https://user-images.githubusercontent.com/19338129/82447286-a8935f80-9ada-11ea-8cac-4e068e666ab8.png)

**Comment by das7pad** [comment]
Hi @zhengyima!

You can adjust the URL via the environment variable `SHARELATEX_SITE_URL`, e.g. from the docker-compose config: https://github.com/overleaf/overleaf/blob/e2f6f670ef5abd44706e411df276d0d41cbdebe6/docker-compose.yml#L53
