### ISSUE TITLE
lmgr: unexpected return value from verify_checksum: -5

### ISSUE THREAD

**Issue by AdriBloober** [overleaf/overleaf#742]
## Steps to Reproduce

1. Install overleaf in a docker container
2. Go with ``docker exec -it sharelatex /bin/bash`` in the docker container
3. Run ``tlmgr search --file ecrm1000.tfm --global``

## Expected Behaviour
I dont know, but i think that the command should tell me, there the file ``ecrm1000.tfm`` is.

## Observed Behaviour
I get the following error:
```
/usr/local/texlive/2019/bin/x86_64-linux/tlmgr: unexpected return value from verify_checksum: -5
```
I get this error if i run any tlmgr command.

## Technical Info

I use docker with the sharelatex package.

**Comment by jdleesmiller** [comment]
Please see https://github.com/overleaf/overleaf/issues/716 .
