### ISSUE TITLE
nginx errors with a fresh install

### ISSUE THREAD

**Issue by zhuoyw** [overleaf/overleaf#743]
## Steps to Reproduce

1. git clone https://github.com/overleaf/overleaf.git
2. sudo docker-compose up

## Expected Behaviour

Sharelatex service should be up.

## Observed Behaviour

Errors output when executing "sudo docker-compose up":

```
mongo         | 2020-05-24T00:55:43.998+0000 I  NETWORK  [listener] connection accepted from 127.0.0.1:47436 #23 (2 connections now open)
mongo         | 2020-05-24T00:55:43.998+0000 I  NETWORK  [conn23] received client metadata from 127.0.0.1:47436 conn23: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "4.2.6" }, os: { type: "Linux", name: "Ubuntu", architecture: "x86_64", version: "18.04" } }
mongo         | 2020-05-24T00:55:44.012+0000 I  NETWORK  [conn23] end connection 127.0.0.1:47436 (1 connection now open)
sharelatex    | nginx: [emerg] open() "/etc/nginx/sites-enabled/default" failed (2: No such file or directory) in /etc/nginx/nginx.conf:75
sharelatex    | nginx: [emerg] open() "/etc/nginx/sites-enabled/default" failed (2: No such file or directory) in /etc/nginx/nginx.conf:75
sharelatex    | nginx: [emerg] open() "/etc/nginx/sites-enabled/default" failed (2: No such file or directory) in /etc/nginx/nginx.conf:75
sharelatex    | nginx: [emerg] open() "/etc/nginx/sites-enabled/default" failed (2: No such file or directory) in /etc/nginx/nginx.conf:75
sharelatex    | nginx: [emerg] open() "/etc/nginx/sites-enabled/default" failed (2: No such file or directory) in /etc/nginx/nginx.conf:75
sharelatex    | nginx: [emerg] open() "/etc/nginx/sites-enabled/default" failed (2: No such file or directory) in /etc/nginx/nginx.conf:75
sharelatex    | nginx: [emerg] open() "/etc/nginx/sites-enabled/default" failed (2: No such file or directory) in /etc/nginx/nginx.conf:75
sharelatex    | nginx: [emerg] open() "/etc/nginx/sites-enabled/default" failed (2: No such file or directory) in /etc/nginx/nginx.conf:75
sharelatex    | nginx: [emerg] open() "/etc/nginx/sites-enabled/default" failed (2: No such file or directory) in /etc/nginx/nginx.conf:75
```

## Technical Info

When I logon the container, there is no "/etc/nginx/sites-enabled/default" file. But why nginx searches it???

* URL:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Signed in as:
* Project and/or file:

**Comment by mserranom** [comment]
Are you using `sudo` for any particular reason?

Could you provide more info about your host OS, docker version etc?

**Comment by zhuoyw** [comment]
OS: CentOS 7.4 
Docker: 1.13.1

Can I install with a non-root environment?

**Comment by minchnew** [comment]
You can execute Docker commands without sudo. Follow the instructions [here](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-18-04#step-2-%E2%80%94-executing-the-docker-command-without-sudo-(optional)).

**Comment by zhuoyw** [comment]
> 
> 
> You can execute Docker commands without sudo. Follow the instructions [here](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-18-04#step-2-%E2%80%94-executing-the-docker-command-without-sudo-(optional)).

Thanks. I will try. 

I resolved this issue by touching a "default" and then remove it. Hope it helps if anyone else found the same errors.

**Comment by mserranom** [comment]
> Docker: 1.13.1

You're using an outdated version of Docker, there's a change you find other issues during the setup.
