### ISSUE TITLE
Confirmation mail is not being sent, ssl3_get_record:wrong version number

### ISSUE THREAD

**Issue by FunnyPocketBook** [overleaf/overleaf#750]
## Steps to Reproduce

1. Create user account from web interface as admin
2. Visit the generated link to set password
3. Login as that user and click on "resend confirmation mail"

## Expected Behaviour

1. The user should receive an email when the admin creates the account 
2. The user should receive an email when the user clicks on "resend confirmation mail"
## Observed Behaviour

1. The admin UI shows "We've sent out welcome emails to the registered users." but the mail is not being sent
2. After clicking on "resend confirmation mail", "Resending confirmation mail..." comes up and the spinner keeps spinning. The mail is not sent
## Technical Info

* Host System: Unraid 6.8.3
* Sharelatex Container Version: 2.2.0 (https://hub.docker.com/r/sharelatex/sharelatex)
* Redis Version: 5.0
* MongoDB Version: 3.6

### Important container env variables
![env_var_settings](https://user-images.githubusercontent.com/30187411/83792779-d14f5380-a69b-11ea-905f-8470a2a27324.png)

### Description
Overleaf is running via HTTPS on a reverse proxy with websockets enabled. Loading the page, logging in, managing users and the likes works without issues. 
The mail provider uses SMTP with STARTTLS on port 587 with authentication required. The credentials and settings that are set in this container have been successfully used in other containers.

### web.log, creating user account
```json
{
    "name": "web",
    "hostname": "bfe6958d9f0b",
    "pid": 116,
    "level": 40,
    "err": {
        "message": "error sending message: 22608863790912:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n",
        "name": "OError",
        "stack": "OError: error sending message: 22608863790912:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n\n    at Object.sendEmail (/var/www/sharelatex/web/app/src/Features/Email/EmailSender.js:104:11)\n    at process._tickCallback (internal/process/next_tick.js:68:7)\n\ncaused by: Error: 22608863790912:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n\n\n",
        "info": {}
    },
    "msg": "failed to send activation email",
    "time": "2020-06-04T17:35:56.206Z",
    "v": 0
}
```

### web.log, user resends confirmation mail
```json
{
    "name": "web",
    "hostname": "bfe6958d9f0b",
    "pid": 116,
    "level": 50,
    "err": {
        "message": "error sending message: 22608863790912:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n",
        "name": "OError",
        "stack": "OError: error sending message: 22608863790912:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n\n    at Object.sendEmail (/var/www/sharelatex/web/app/src/Features/Email/EmailSender.js:104:11)\n    at process._tickCallback (internal/process/next_tick.js:68:7)\n\ncaused by: Error: 22608863790912:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n\n\n",
        "info": {}
    },
    "url": "/user/emails/resend_confirmation",
    "method": "POST",
    "user": {
        "id": "5ed7c3ea60cdbc008c1d5405",
        "email": "email@email.com"
    },
    "msg": "error passed to top level next middleware",
    "time": "2020-06-04T17:28:19.516Z",
    "v": 0
}
{
    "name": "web",
    "hostname": "bfe6958d9f0b",
    "pid": 116,
    "level": 30,
    "req": {
        "url": "/user/emails/resend_confirmation",
        "method": "POST",
        "referrer": "https://subdomain.domain.org/project",
        "remote-addr": "203.0.113.3",
        "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0",
        "content-length": "81"
    },
    "res": {
        "statusCode": 500
    },
    "response-time": 5242,
    "msg": "http request",
    "time": "2020-06-04T17:28:19.545Z",
    "v": 0
}
```

## Screenshots
![resend_confirmation_mail](https://user-images.githubusercontent.com/30187411/83793876-73237000-a69d-11ea-9d69-90c9c8fe9ecf.png)
![resending_confirmation_mail](https://user-images.githubusercontent.com/30187411/83793882-7585ca00-a69d-11ea-9904-ae5140e59614.png)

**Comment by FunnyPocketBook** [comment]
Apparently STARTTLS doesn't work. I have also tried using STARTTLS for SMTP with Outlook, which gave me the same error message. However, switching to SSL/TLS works flawlessly.

**Comment by MayeulC** [comment]
I have exactly the same issue. The same config works for me under thunderbird.

```json
"name":"web","hostname":"8dca9dc06b59","pid":128,"level":50,"err":{"message":"error sending message","name":"OError","stack":"OError: error sending message\n  at Object.sendEmail (/var/www/sharelatex/web/app/src/Features/Email/EmailSender.js:98:11)\n  at process._tickCallback (internal/process/next_tick.js:68:7)\n\n[object Object]\n  at Object.<anonymous> (/var/www/sharelatex/web/modules/launchpad/app/src/LaunchpadController.js:109:16)\n  at cb (util.js:353:39)\n  at callbackifyOnRejected (util.js:337:10)\n  at process._tickCallback (internal/process/next_tick.js:63:19)\n\ncaused by:\n    Error: 140345495566144:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n    \n    \n    ","info":{"email":"mayeul@xxx"}},"url":"/launchpad/send_test_email","method":"POST","user":{"id":"60059ba0ef33170094f6fa3c","email":"mayeul@xxx"},"msg":"error passed to top level next middleware","time":"2021-01-18T16:08:54.523Z","v":0}
{"name":"web","hostname":"8dca9dc06b59","pid":128,"level":50,"req":{"url":"/launchpad/send_test_email","method":"POST","referrer":"https://latex.xxx.example.com/launchpad","remote-addr":"10.xxx.xxx.xxx","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0","content-length":"75"},"res":{"statusCode":500},"response-time":43891,"msg":"POST /launchpad/send_test_email","time":"2021-01-18T16:08:54.551Z","v":0}
```

Note: technically the SMTP server is on the same host, but outside of docker. I only have STARTTLS enabled for now, so this is less than ideal :/

**Comment by meglio** [comment]
@MayeulC could you please explain in a bit more detail? Did you have to expose any specific ports from your Docker container to make SMTP work? Or was the issue something else?

**Comment by MayeulC** [comment]
> @MayeulC could you please explain in a bit more detail? Did you have to expose any specific ports from your Docker container to make SMTP work? Or was the issue something else?

It's just a matter of configuring overleaf correctly, in a way that is compatible with the SMTP server. No ports to expose.

IIRC, The issue here is that my SMTP server doesn't accept starting a connection with SSL/TLS. It has to start a plaintext session, then upgrade it (STARTTLS).

The configuration to do this is a bit cryptic and counter-intuitive, I wrote it above: disable `SMTP_SECURE` and disable `SMTP_IGNORE_TLS`. This way the connection starts in plaintext, and is then upgraded to TLS.
