### ISSUE TITLE
Docker latest tag image outdated 

### ISSUE THREAD

**Issue by Fuzzer11** [overleaf/overleaf#753]
Running the application using docker as is indicated in the [wiki](https://github.com/overleaf/overleaf/wiki/Quick-Start-Guide) pulls an old docker image, making `tlmgr` not able to install any package because the TexLive version is from 2019 and is unable to update itself through the CLI.

**Comment by mserranom** [comment]
`sharelatex/sharelatex:latest` has been updated  to `v2.3.0`, which should be using TexLive 2020.

https://hub.docker.com/layers/sharelatex/sharelatex/latest/images/sha256-cd39d3f39223684cadb172fb7dabe1266100a2e00517348ea42953b3f2934395?context=explore

**Comment by WangBRen** [comment]
I change some code from overleaf/web, I want to build my own image, but It can't connect to Redis, I use the Dockerfiles from master branch, and change the web service url from service.js.
Did I do something wrong?

**Comment by mserranom** [comment]
@WangBRen I answered in the other ticket you created, closing this, as the image has been updated.
