### ISSUE TITLE
I build share latex Image by myself, than can not connect to Redis

### ISSUE THREAD

**Issue by WangBRen** [overleaf/overleaf#755]
1.I changed some web code to show the page on my way
2.Then I changed service.js to download code from my url
3.Change the docker-compose.yml, build image by myself instead of pulling from docker.hub, but when I run image, I can't connect to Redis, I didn't change any config

I want to know how  I can solve this problem

**Comment by mserranom** [comment]
Could you provide error messages, logs, etc?

**Comment by WangBRen** [comment]
@mserranom Now I can use docker-compose up to run Containers，but when I access the web，show "Welcome to nginx!"

no error log 

sharelatex    |
sharelatex    | Done, without errors.
sharelatex    | All migrations finished
sharelatex    | *** Booting runit daemon...
sharelatex    | *** Runit started as PID 116
sharelatex    | Jun 24 03:29:38 957f71c6c3d1 cron[143]: (CRON) INFO (pidfile fd = 3)
sharelatex    | Jun 24 03:29:38 957f71c6c3d1 cron[143]: (CRON) INFO (Running @reboot jobs)
sharelatex    | nginx: [warn] conflicting server name "_" on 0.0.0.0:80, ignored

These are what I changed
docker-compose.yml
`       # image: quay.io/sharelatex/sharelatex-pro
        build:
            context: .
            dockerfile: Dockerfile
        image: sharelatex/sharelatex
        container_name: sharelatex
`
service.js
`{
	name: "web",
	repo: "https://github.com/WangBRen/web.git",
	version: "master"
}`

**Comment by WangBRen** [comment]
when I use official web repo,the same problem show

**Comment by WangBRen** [comment]
> Could you provide error messages, logs, etc?

@mserranom  When I when I access the web , show Welcome to nginx! Can u help me ?

**Comment by mserranom** [comment]
Can you share:
- Details of the host machine (OS, version, docker version)
- logs of `docker-compose up` when running it on a fresh checkout of this repo
- `web.log` as described in https://github.com/overleaf/overleaf/wiki/Log-files
