### ISSUE TITLE
Jump to code/PDF location non functional

### ISSUE THREAD

**Issue by cryptoluks** [overleaf/overleaf#756]
Hi,

using the latest overleaf/sharelatex community docker image in a docker-compose setup similar to the example one.

```
> docker image ls | grep sharelatex
sharelatex/sharelatex             latest              843316001077        3 weeks ago         3.59GB
```

Since the new update to version 2.3 the jump to code and jump to PDF location buttons are non functional. Double clicking the PDF also doesn't work. This was working for me fine before the update.
![image](https://user-images.githubusercontent.com/9020527/85689304-cd2eb880-b6d2-11ea-8087-0c6a62850747.png)

I observed the request to the server:

![image](https://user-images.githubusercontent.com/9020527/85688657-3b26b000-b6d2-11ea-9c24-be6c221f894c.png)

The requests are probably fine, but there is no response (timeout).

Tested this with latest Firefox and Chromium on Arch Linux.

Is anyone experiencing similar issues?

Thanks.

**Comment by mserranom** [comment]
Thanks for the report, having a look.

**Comment by bowesj** [comment]
It looks like this issue is back.

**Comment by cryptoluks** [comment]
Can confirm, but only Code-to-PDF does not work for me, PDF-to-Code is functional. Also, the response when clicking the Code-to-PDF button is simply empty, no timeout this time.

Using the latest docker image v. 2.6.1.

@mserranom can you reproduce it? :-)
