### ISSUE TITLE
Outdated tlmgr repository

### ISSUE THREAD

**Issue by PatrickGoettsch** [overleaf/overleaf#762]
## Steps to Reproduce

1. When you run docker exec sharelatex tlmgr install scheme-full you get the error that the repository http://ctan.altspu.ru/systems/texlive/tlnet cannot be connected to (I cannot connect with browser as well)

## Expected Behaviour

Updates docker image to textlive 2019 scheme full

## Observed Behaviour

does not work

## Technical Info

* URL:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Signed in as:
* Project and/or file:

**Comment by PatrickGoettsch** [comment]
if you change the repository to https://ctan.kako-dev.de/systems/texlive/tlnet/ with the following steps it seems to work
1. docker exec -it sharelatex bash
1. tlmgr option repository https://ctan.kako-dev.de/systems/texlive/tlnet/
1. tlmgr update --self --all
1. luaotfload-tool -fu
1. tlmgr install scheme-full
1. exit
1. docker restart sharelatex

**Comment by philmarion** [comment]
Hi, 

Same issue for me: update to texlive-full following the https://github.com/overleaf/overleaf/wiki/Quick-Start-Guide instructions doesn't work.

solved:  remove texlive2019 and install texlive2020 according: https://github.com/overleaf/overleaf/issues/601 
Phil.

**Comment by PatrickGoettsch** [comment]
It already uses TexLive 2020 right. For me it worked I only had to solve the changes in the docker with a docker commit

**Comment by das7pad** [comment]
Hello,

I'm afraid this will be a re-occuring issue around the time of the new TeXLive release and before we had a chance to ship another release of Overleaf Community Edition using the new TeXLive release.

Our Server Pro offering provides you with access to the same optimized TeXLive-full LaTeX environment as used for overleaf.com. We run [extensive tests with the overleaf.com gallery templates](https://www.overleaf.com/learn/latex/Overleaf_and_TeX_Live) with new TeXLive releases and generally make sure that they compile with new versions or leave them at their previous TeXLive release. Server Pro customers get access to our historic TeXLive releases (all the way back to 2014) as well to ensure older projects continue to work.
You can find more information on Server Pro here: https://www.overleaf.com/for/enterprises

Greetings,
Jakob
