### ISSUE TITLE
Dependencies of sharelatex/real-time don't get installed

### ISSUE THREAD

**Issue by zauguin** [overleaf/overleaf#764]
## Steps to Reproduce

1. Run `docker image build --no-cache -t sharelatex .` in the repo
2. In docker-compose.yml set `image: sharelatex`
3. Run `docker-compose up`
4. Run `docker container exec -t sharelatex sh -c "tail -f /var/log/sharelatex/*.log"` and/or open a webbrowser

## Expected Behaviour
Overleaf Community Edition starts and outputs lots of non-error log output

## Observed Behaviour
The log is filled with loading errors from `real-time` because `metrics-sharelatex` is missing.

## Context
I tried to experiment with the setup and apply a change to `overleaf-web`, therefore I had to rebuild the container.

## Technical Info
n/a

## Analysis
The issue was introduced by https://github.com/overleaf/real-time/commit/94d7d6679e8a989d4a798867e778b6fd6b805049: `real-time` now has a `.npmrc` with the content:

```
# block local, outside docker invocations of $ npm install
dry-run=true
```
This turns the instructions to install the dependencies in the Dockerfile into no-ops. Therefore the dependencies don't get installed. The issue disappeared after applying

```diff
diff --git a/Dockerfile b/Dockerfile
index dce3f6d..5d0de69 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -42,7 +42,11 @@ RUN cd /var/www/sharelatex \
   \
 # Cleanup the git history
 # -------------------
-&&  rm -rf $(find /var/www/sharelatex -name .git)
+&&  rm -rf $(find /var/www/sharelatex -name .git) \
+  \
+# Ensure that dependency installation isn't suppressed
+# -------------------
+&&  rm -f $(find /var/www/sharelatex -name .npmrc)
 
 # Install npm dependencies
 # ------------------------
```
but that feels a bit too hacky for a PR.

(OT, but not really worth a separate issue: There is another problem with the `sharelatex-base` issue on Docker Hub currently. The file `/etc/nginx/sites-enabled/default` exists and overwrites the Overleaf nginx configuration because both provide `server_name _`. The same issue does not appear when building a `sharelatex-base` version from Dockerfile-base.)

**Comment by jdleesmiller** [comment]
Thanks for the detailed report. I think this was an unintended consequence of another change. We're looking into it.

**Comment by das7pad** [comment]
Hello @zauguin,

Thanks again for your report and sorry for the inconveniences this has caused! Can you confirm that https://github.com/overleaf/real-time/pull/175 restored the ability to install dependencies for you?

**Comment by zauguin** [comment]
@das7pad Yes, the dependencies get installed correctly again. Thank you for the quick fix!
