### ISSUE TITLE
Sections' Navigation List

### ISSUE THREAD

**Issue by anderflash** [overleaf/overleaf#77]
Could we develop a navigation list for sections to list all `/(sub)*sections/`? I think this feature would be a great improvement. I think the left list could be used to show the sections below the file name. By clicking on them, the editor would scroll down to that line.

Thanks

**Comment by cmcisaac6** [comment]
Closing: This is now available in the file outline

<img width="313" alt="image" src="https://user-images.githubusercontent.com/81039188/179005030-41ff2b95-5251-43ff-9bd2-f90a22b785c6.png">
