### ISSUE TITLE
Separate texlive for fastest updating

### ISSUE THREAD

**Issue by wixaw** [overleaf/overleaf#772]
Hello
At each update adding texlive is very slow, would it be possible to have it in a separate container, or on the host machine via a volume like /local/texlive:/xxxx/texlive/ ?
Thanks you in advance
William

**Comment by qupfer** [comment]
you find a solution somewhere in the issue list.
The basic concept was:
- deploy it
- copy /local/textlive to some external place
- destroy container
- deploy it with mount of the copied folder
- use it
- use internal tlmgr to update texlive packages
- after a while...
- destroy it
- update it
- deploy it with mount of the copied folder
-

**Comment by wixaw** [comment]
I'm sorry I hadn't seen #706 
Thank you, I'll do it like this
