### ISSUE TITLE
How to confirm email (supress warning) without any mailing?

### ISSUE THREAD

**Issue by qupfer** [overleaf/overleaf#773]
## Steps to Reproduce
1. create new user
2. login 
3. see yellow warning,  that the mail address is not confirmed

## Expected Behaviour
As an admin, I want to "validate" users mail (or may own) without any sending of any mails

## Technical Info
Using the actual docker-compose.yml from the gitlab repo

* URL: local IP
* Browser Name and version: Firefox 80
* Operating System and version (desktop or mobile): Arch Linux 

Did anybody know, how/there I have to modify the database or anything else to get accounts validated without any mailing?

Side question: Did anybody know, how to auto-login to a single account (aka no login required)

Thanks
qupfer

**Comment by mserranom** [comment]
https://github.com/overleaf/overleaf/wiki/Configuring-Overleaf

The only option is to disable entirely email confirmation with `EMAIL_CONFIRMATION_DISABLED: 'true'`

> Did anybody know, how to auto-login to a single accoun

That's not possible without rewriting the authentication middleware.

**Comment by qupfer** [comment]
thanks, thats helped
