### ISSUE TITLE
tlmgr installation not persistent

### ISSUE THREAD

**Issue by YanB25** [overleaf/overleaf#774]
What `tlmgr` installed is not persisted into the disk if the container is destroyed. It's inconvenient to me.

`tlmgr install scheme-full` installs all the packages under `/usr/local/texlive`, which is not mounted to the volume/fs. After `docker-compose down` and destroy the containers, any installed packages are lost.

I tried to mount `/usr/local/texlive` to the local filesystem by modifying `docker-compose.yml`. However, the directory becomes empty after mounted.

So, I finally come to this solution:

1. run `docker-compose up -d` first.
2. cp the `texlive` directory to my filesystem. `docker cp <container>:/usr/local/texlive /data/sharelatex/`
3. run `docker-compose down`
4. modify the `docker-compose.yaml` and mount `/data/sharelatex/texlive` to `/usr/local/texlive`
5. finally run `docker-compose up -d`

It works but is tedious and ugly.

My question is, is there any better way to persist `/usr/local/texlive` to my local filesystem or the docker volume, so that all my installed packages are not volatile?

**Comment by Craskermasker** [comment]
Maybe try using `docker commit` as in this guide:
https://medium.com/@shuangzizuobh2/host-your-own-latex-server-a-docker-example-2787531bf93b

**Comment by jdleesmiller** [comment]
The `docker commit` approach is the best one I know of, as well. I've updated the docs to mention this:
https://github.com/overleaf/overleaf/wiki/Quick-Start-Guide#latex-environment

(Note that this does not apply if using sandboxed compiles on Server Pro --- in that case there is a separate tex live image.)
