### ISSUE TITLE
Question regarding hardware scaling

### ISSUE THREAD

**Issue by synergiator** [overleaf/overleaf#784]
Hi there,

from the[ hardware requirements](https://github.com/overleaf/overleaf/wiki/Hardware-Requirements) article it's not quite clear how does the architecture scale for more users, that is can be all parameters extrapolated linearly from the given setup for 30 users?

That is (for concurrent users!):
* 30 users need 8 GB RAM and 7 CPU cores
* would 5000 concurrent users need accordingly 1335 GB RAM and 1750 CPUs?

Is there something to consider regarding storage beyond the correlation with the document volume?

**Comment by mserranom** [comment]
The hardware requirements are a recommendation for an initial provisioning. We do a customer-taylored capacity planning as part of our [Enterprise Solution, Overleaf Server Pro](https://www.overleaf.com/for/enterprises/).
