### ISSUE TITLE
Question about dependencies in term of their EOL

### ISSUE THREAD

**Issue by synergiator** [overleaf/overleaf#785]
Hi there,

as far as I can see, Overleaf depends on these components:

* Redis 5.0
* Mongo DB 3.6

According to the following sources, these versions have the following EOL (End of Life) dates, which possibly means there will be no more security updates. This could become a security problem.

* Redis 5.0: EOL since May 31, 2019
* Mongo 3.6: upcoming EOL due April 2021

What are current migration plans?

https://docs.redislabs.com/latest/rs/administering/product-lifecycle/
https://www.mongodb.com/support-policy

**Comment by mserranom** [comment]
I've updated the [documentation](https://github.com/overleaf/overleaf/wiki/Dependencies) to reflect Overleaf depends on Redis 5.x (which is not EOL), as defined in the [compose file](https://github.com/overleaf/overleaf/blob/28f326fd980216b82a815b2ad5366b01e2a9ff71/docker-compose.yml#L119).

**Comment by d1nuc0m** [comment]
@mserranom Again the same problem:
* MongoDB 4.2 is going EOL in April 2023 (one month left) [[source](https://www.mongodb.com/support-policy/lifecycles)]
* Redis 5.x is EOL as of 31 October 2021, more than a year ago [[source](https://docs.redis.com/latest/rs/installing-upgrading/product-lifecycle/)]

**Comment by d1nuc0m** [comment]
Also pinging @aeaton-overleaf @timothee-alby @emcsween

**Comment by emcsween** [comment]
Hi @d1nuc0m. Thanks for the heads up! The latest version of Overleaf actually runs on MongoDB 4.4, as you can see in the [docker-compose file](https://github.com/overleaf/overleaf/blob/main/docker-compose.yml#L107). We'll update the documentation to clarify that fact.

You're right that the same docker-compose file pulls Redis 5.x. Overleaf should run fine on Redis 6.x. We'll look at making that upgrade.

**Comment by d1nuc0m** [comment]
> Overleaf should run fine on Redis 6.x. We'll look at making that upgrade.
Thank you, I'll wait for a confirmation

**Comment by das7pad** [comment]
Hello,

The docker-compose file references `redis:6.2` now, which is the latest version on the `6.x` release line, which is still supported by Redis until the release of redis `8.x`.

Greetings,
Jakob
