### ISSUE TITLE
Installing additional packages

### ISSUE THREAD

**Issue by eeriksp** [overleaf/overleaf#789]
It seems that the Community edition uses a LaTeX distribution, where the `beamer` class is not available.

How can I install additional packages or another LaTeX distribution which would have the necessary packages installed already?

My self-hosted version is installed using the Overleaf Toolkit.

**Comment by tramir** [comment]
You can enter the container:

`docker exec -it sharelatex /bin/bash`

Once there, you can use `tlmgr` to install any package you want. If you have the space, you can also just install the full TeXLive distribution:

`tlmgr install beamer
tlmgr install scheme-full`

Note that all this will be lost if you update your image and installation. There's a discussion in the issues on how to move the `/usr/local/texlive` folder onto the host and then mount it back into the sharelatex container. That way it persists across updates.

**Comment by eeriksp** [comment]
I got a quick reply from the Overleaf stuff: the result is actually really simple as described [here](https://github.com/overleaf/overleaf/wiki/Quick-Start-Guide#latex-environment).

The only thing to not is that I had to run
