### ISSUE TITLE
Bibtex failed, biber work.

### ISSUE THREAD

**Issue by SizheRee** [overleaf/overleaf#794]
## Steps to Reproduce

1.  use docker with the latest sharelatex image on ubuntu18.04.
2. build the example project failed.
```
\usepackage{natbib}
...
\bibliographystyle{plain}
\bibliography{references}
```

## Expected Behaviour

expect build with cites completed.

## Observed Behaviour

> Set environment variable BIBINPUTS='/var/lib/sharelatex/data/compiles/5f76a6f24db11c007a238c87-5f6ef7488b59ba008cccdbb5:'
Set environment variable TEXINPUTS='/var/lib/sharelatex/data/compiles/5f76a6f24db11c007a238c87-5f6ef7488b59ba008cccdbb5:'
Latexmk: applying rule 'pdflatex'...
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
Latexmk: Examining '/var/lib/sharelatex/data/compiles/5f76a6f24db11c007a238c87-5f6ef7488b59ba008cccdbb5/output.log'
=== TeX engine is 'pdfTeX'
Latexmk: applying rule 'bibtex /var/lib/sharelatex/data/compiles/5f76a6f24db11c007a238c87-5f6ef7488b59ba008cccdbb5/output'...
For rule 'bibtex /var/lib/sharelatex/data/compiles/5f76a6f24db11c007a238c87-5f6ef7488b59ba008cccdbb5/output', running '&run_bibtex(  )' ...
I couldn't open file name `/var/lib/sharelatex/data/compiles/5f76a6f24db11c007a238c87-5f6ef7488b59ba008cccdbb5/output.blg'
Latexmk: applying rule 'pdflatex'...
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
Latexmk: Examining '/var/lib/sharelatex/data/compiles/5f76a6f24db11c007a238c87-5f6ef7488b59ba008cccdbb5/output.log'
=== TeX engine is 'pdfTeX'
Latexmk: All targets (/var/lib/sharelatex/data/compiles/5f76a6f24db11c007a238c87-5f6ef7488b59ba008cccdbb5/output.pdf) are up-to-date

![image](https://user-images.githubusercontent.com/23694675/94893257-5404e580-04b9-11eb-9dfb-7082677f8660.png)

## TechInfo

> root@7e18a4f88867:~# whereis bibtex
bibtex: /usr/local/texlive/2020/bin/x86_64-linux/bibtex

> root@7e18a4f88867:~# bibtex --version
BibTeX 0.99d (TeX Live 2020)
kpathsea version 6.3.2
Copyright 2020 Oren Patashnik.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the BibTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the BibTeX source.
Primary author of BibTeX: Oren Patashnik.

## Analysis

I try and found the bibtex not functioning.

> root@7e18a4f88867:~# bibtex /var/lib/sharelatex/data/compiles/5f76a6f24db11c007a238c87-5f6ef7488b59ba008cccdbb5/output 
bibtex: Not writing to /var/lib/sharelatex/data/compiles/5f76a6f24db11c007a238c87-5f6ef7488b59ba008cccdbb5/output.blg (openout_any = p). 
I couldn't open file name `/var/lib/sharelatex/data/compiles/5f76a6f24db11c007a238c87-5f6ef7488b59ba008cccdbb5/output.blg'

however the biber works fine.
> root@7e18a4f88867:~# biber /var/lib/sharelatex/data/compiles/5f76a6f24db11c007a238c87-5f6ef7488b59ba008cccdbb5/output
INFO - This is Biber 2.15
INFO - Logfile is '/var/lib/sharelatex/data/compiles/5f76a6f24db11c007a238c87-5f6ef7488b59ba008cccdbb5/output.blg'
INFO - Reading '/var/lib/sharelatex/data/compiles/5f76a6f24db11c007a238c87-5f6ef7488b59ba008cccdbb5/output.bcf'
INFO - Found 1 citekeys in bib section 0
INFO - Processing section 0
INFO - Looking for bibtex format file 'references.bib' for section 0
INFO - LaTeX decoding ...
INFO - Found BibTeX data source '/var/lib/sharelatex/data/compiles/5f76a6f24db11c007a238c87-5f6ef7488b59ba008cccdbb5/references.bib'
INFO - Overriding locale 'en-US' defaults 'variable = shifted' with 'variable = non-ignorable'
INFO - Overriding locale 'en-US' defaults 'normalization = NFD' with 'normalization = prenormalized'
INFO - Sorting list 'nty/global//global/global' of type 'entry' with template 'nty' and locale 'en-US'
INFO - No sort tailoring available for locale 'en-US'
INFO - Writing '/var/lib/sharelatex/data/compiles/5f76a6f24db11c007a238c87-5f6ef7488b59ba008cccdbb5/output.bbl' with encoding 'UTF-8'
INFO - Output to /var/lib/sharelatex/data/compiles/5f76a6f24db11c007a238c87-5f6ef7488b59ba008cccdbb5/output.bbl

so I change tex code into
```
% \usepackage[
%     backend=biber,
%     style=numeric,
%   ]{biblatex}
...
\bibliography{references.bib}
```
finally this works out.

**Comment by tramir** [comment]
Had the same issue, which seems to be related to the security settings in TeXLive and how it's set up in Overleaf. If you're ok with the security risk that someone might upload a bib file that runs arbitrary code (which I personally think is low as long as you control access to the instance and given that everything is run in docker), you can solve it following the suggestion from the bibtex error message. Enter the container, edit the file `/usr/local/texlive/2020/texmf.cnf` and add:

`openout_any = a`

After that, bibtex should work.

**Comment by SizheRee** [comment]
Thanks, this solved my problem.

**Comment by SizheRee** [comment]
> Had the same issue, which seems to be related to the security settings in TeXLive and how it's set up in Overleaf: latexmk is instructed to put all the intermediate files in a separate folder, but bibtex is not allowed by default to write in a different folder than where the project is located. Hence the error.
> 
> If you're ok with the security risk that someone might upload a bib file that runs arbitrary code (which I personally think is low as long as you control access to the instance and given that everything is run in docker), you can solve it following the suggestion from the bibtex error message. Enter the container, edit the file `/usr/local/texlive/2020/texmf.cnf` and add:
> 
> `openout_any = a`
> 
> After that, bibtex should work.

Thanks, this solved my problem.
