### ISSUE TITLE
Add tag or releases

### ISSUE THREAD

**Issue by Chostakovitch** [overleaf/overleaf#795]
I would like to install Overleaf without using Docker (example use case : propose a package in YunoHost). 

From what I found, the Docker images are built from `master` at a certain point, tagged with the release number and pushed on the Docker Hub.

However, there is no way to find from which commit the images have been built, neither in this repository or in the fetched repositories (which I believed are defined in [services.js](https://github.com/overleaf/overleaf/blob/master/services.js)).

The Changelog only references image id.

I know that you do not support installing outside Docker nor plan to support it, but would it be possible to at least add a Git tag, so we can find which commit (in each repository) is associated with which release ?

It would be also useful to check for modifications between versions, for example.

Thanks in advance :)

**Comment by mserranom** [comment]
You can find the commit has for each repository inside a container in `/var/www/revisions.txt`:

https://github.com/overleaf/overleaf/blob/master/Dockerfile#L40-L41
