### ISSUE TITLE
Create First User Cannot read property 'findOne' of undefined Use

### ISSUE THREAD

**Issue by Trackhe** [overleaf/overleaf#796]
I have a K8s bare metal Cluster. arm64.
for there i build all in arm64 and it seems working. i have the login page and if i start it. it connect to redis. that by the way reqirement is version 5. maybe you can write system requirements. and it can connect to mongodb. at the start he migrates to there collection.

now if i want to create a user i get 
Warning: Cannot read property 'findOne' of undefined Use --force to continue.
and in the db nothing changes.

## Expected Behaviour
Create a User

## Observed Behaviour
I realy dont now. i test around with the javascript file but it comes over and over.

https://hub.docker.com/repository/docker/trackhe/sharelatex arm64 version.
https://hub.docker.com/repository/docker/trackhe/sharelatex-base arm64 version.

![Bildschirmfoto 2020-10-04 um 12 10 16](https://user-images.githubusercontent.com/1494328/95012644-93a70b00-063a-11eb-9b2f-14fb2487e659.png)

![Bildschirmfoto 2020-10-04 um 12 11 40](https://user-images.githubusercontent.com/1494328/95012668-c3eea980-063a-11eb-9422-a8521fac943e.png)

exist a way to trigger the mongodb setup? because it only migrates at start. also at first start

**Comment by das7pad** [comment]
Hi!

Thank you for the report. https://github.com/overleaf/overleaf/pull/797 may get you back on track. It is generally advised to use the official releases which are tested before they are cut. You may be able to extract the git-shas of an official release, they are stored in `/var/www/sharelatex/revisions.txt`; building with pinned repositories should then work without https://github.com/overleaf/overleaf/pull/797.

**Comment by Trackhe** [comment]
Thank you for the fast fix and response. I had later created a user over `url/launchpad` this was working for me but. I had errors and errors. The Login was okey but if i create i projekt i get error 500 and if i want to edit a file i get only 500 errors and the full-livetex installation is failing over and over. That is why i dont try to port at arm anymore. But this is another problem. Thank you. I use it later on amd64 ^^
