### ISSUE TITLE
How to find out the reason when "Something went wrong talking to the server :(. Please try again" occurs.

### ISSUE THREAD

**Issue by muguruzawang** [overleaf/overleaf#799]
I have installed overleaf locally for over 10 month, but in the last month, overleaf crashes frequently. The reasons are diverse as below:
1. cannot log in
![image](https://user-images.githubusercontent.com/48216295/95804136-6e01bc00-0d34-11eb-9bde-b8c3cbcefe46.png)
2. Failed to compile when entering the project successfully.

So I wonder,  how could I find out the reason for these failures, for example, logs at somewhere?

**Comment by mserranom** [comment]
Please check the logging information in the wiki: https://github.com/overleaf/overleaf/wiki/Log-files
