### ISSUE TITLE
Gruntfile Update

### ISSUE THREAD

**Issue by philipempl** [overleaf/overleaf#801]
## Steps to Reproduce
1. git clone https://github.com/overleaf/overleaf.git
2. cd overleaf
3. grunt install

## Expected Behaviour
I tried to install overleaf locally with grunt install.

## Observed Behaviour
Cannot find ./config/services

## Context
Installation of overleaf

## Analysis
Grunt is referring to a older structure within this project. The services.js file is currently inside the main github repo. Just delete "config" from path (--> ./services) within the Gruntfile.

**Comment by mpsdskd** [comment]
Thanks, that solved my problem.

Additional info: To build docker after _grunt install_ worked, I had to revert this change in the Gruntfile.

**Comment by hrjakobsen** [comment]
Hi! The recommended way to run Overleaf Community Edition is now with Docker, using the [Overleaf Toolkit](https://github.com/overleaf/toolkit). I'll close this issue, as it is based on old build instructions, but please open a new issue if you face problems using Overleaf Toolkit.
