### ISSUE TITLE
Link sharing not working

### ISSUE THREAD

**Issue by Liane-Y** [overleaf/overleaf#804]
## Steps to Reproduce

After the link sharing is turned on, I got two links. The link for anyone to view this project works well. 

However, the link for anyone to edit this project doesn't work well. If I open this link, the browser loads the project for a few seconds, and redirects to the login screen for users.

## Expected Behaviour

Expected to see the edit windows without login screen.

## Observed Behaviour
Redirects to the login screen after a few seconds.

## Analysis
Maybe due to some javascript errors. If I stop js after the content is loaded, I can view and edit this project.

**Comment by mserranom** [comment]
This should have been fixed in version 2.4.2, please give it a try.
