### ISSUE TITLE
Is there a visual editor?

### ISSUE THREAD

**Issue by ORESoftware** [overleaf/overleaf#808]
Sorry I am trying to find a visual editor - don't really want to edit the latex by hand if I can avoid it. Is there one?

**Comment by mserranom** [comment]
[Rich Text Editor](https://www.overleaf.com/blog/new-overleaf-v2-features-rich-text-and-adding-linked-files) is not available in the Community Edition. Our [commercial Offering, Server Pro](https://www.overleaf.com/for/enterprises/features) does include it.

You can also create an account in https://www.overleaf.com and give it a try.
