### ISSUE TITLE
Add option to specify the git branch to sync with

### ISSUE THREAD

**Issue by nkakouros** [overleaf/overleaf#820]
Syncing with git is great. An option to set the branch to sync against is missing though. Such an option would allow a pull-request flow. As it stands now, everything is committed to the default branch.

**Comment by xaverbrems** [comment]
Is there any news on this issue ?

**Comment by mserranom** [comment]
Hi! git syncing feature is not available in Overleaf Community Edition. I'm closing this issue, for questions/suggestions regarding our SaaS offering please refer to https://www.overleaf.com/contact
