### ISSUE TITLE
Kubernetes support

### ISSUE THREAD

**Issue by StackKorora** [overleaf/overleaf#825]
Greetings,
I've been asked to setup a community version of overleaf as a trial before we buy. I don't have docker, but I do have a namespace on a Kubernetes cluster. But I'm still trying to wrap my head around all of this and don't do anything with docker outside of the kubernetes scripts. It looks like [Kubernetes support has been in trial](https://www.overleaf.com/blog/637-happy-birthday-5-years-of-docker-at-overleaf) for nearly two years but I don't see anything about it working yet.

I attempted to convert the docker-compose with kompose but that was a mess. Fixing one error in the yaml just produced another. Tried something I found online for making `docker stack deploy` talk to kubernetes and that didn't work. I can take the raw docker image and get it working, but obviously it's broken without all the other pieces.

Is there an "easy" way to test overleaf on a kubernetes cluster? Or am I just going to have to manually convert the docker-compose into a kubernetes file?

Thanks!

**Comment by jdleesmiller** [comment]
Thanks for getting in touch. Currently the single Docker container (like the [CE Docker container](https://hub.docker.com/r/sharelatex/sharelatex)) is the only supported way to run Server Pro. Kubernetes is not yet supported for Server Pro, but this is a feature request we are tracking.
