### ISSUE TITLE
Something went wrong connecting to your project.

### ISSUE THREAD

**Issue by saroberts** [overleaf/overleaf#829]
## Steps to Reproduce
1.  Was successfully running overleaf on a RHEL7 server, running a version build around 6 months ago. 
2.  Upgraded today following the instructions at https://github.com/overleaf/overleaf/wiki/Upgrading-Containers to version 2.5.1

## Expected Behaviour
1. Upgrade proceeded normally

## Observed Behaviour
1. Main UI works fine.  But when trying to open a project, get an error "Something went wrong connecting.  Something went wrong connecting to your project.  Please refresh if this continues to happen.
2. There are also errors when creating new project.

## Context
1. Server is completely unusable.

## Technical Info

* URL:  Not publicly accessible
* Browser Name and version:  Chrome
* Operating System and version (desktop or mobile):  N/A
* Signed in as:  N/A
* Project and/or file:  N/A

## Analysis

Project fails to load when triggering the websocket connection.  Contents of real-time.log:
```
{"name":"real-time","hostname":"######","pid":137,"level":50,"project_id":"######","user_id":"######","client_id":"_6N_IqhqbBtsov_oLKxD","err":{"message":"non-success status code from web","name":"WebApiRequestFailedError","stack":"WebApiRequestFailedError: non-success status code from web\n  at Request._callback (/var/www/sharelatex/real-time/app/js/WebApiManager.js:64:20)\n  at Request.self.callback (/var/www/sharelatex/real-time/node_modules/request/request.js:185:22)\n  at Request.emit (events.js:198:13)\n  at Request.<anonymous> (/var/www/sharelatex/real-time/node_modules/request/request.js:1154:10)\n  at Request.emit (events.js:198:13)\n  at IncomingMessage.<anonymous> (/var/www/sharelatex/real-time/node_modules/request/request.js:1076:12)\n  at Object.onceWrapper (events.js:286:20)\n  at IncomingMessage.emit (events.js:203:15)\n  at endReadableNT (_stream_readable.js:1145:12)\n  at process._tickCallback (internal/process/next_tick.js:63:19)\n","info":{"statusCode":301}},"method":"joinProject","msg":"server side error in joinProject","time":"2021-01-15T18:41:16.754Z","v":0}
```

Rolling back to the previous images does not work, suggesting the upgrade changed something in the persistent files.

**Comment by saroberts** [comment]
I believe this issue was related to me accidently upgrading mongodb too many versions, and without the appropriate conversion steps.  Would be nice for a better warning, but this is all my fault.

**Comment by MohamedElashri** [comment]
> I believe this issue was related to me accidently upgrading mongodb too many versions, and without the appropriate conversion steps. Would be nice for a better warning, but this is all my fault.

I have the same problem, can you tell me how did you solve that?

**Comment by saroberts** [comment]
I wasn't able to recover; had to roll back to my backup.

**Comment by MohamedElashri** [comment]
> I wasn't able to recover; had to roll back to my backup.

The problem is that it occurs to me even with fresh installation and cannot have a working setup.
