### ISSUE TITLE
behind apache

### ISSUE THREAD

**Issue by fcarlier** [overleaf/overleaf#83]
Hello,

My sharelatex is behind apache server.

I put in my configuration : 
""" 
    ProxyPreserveHost On
    ProxyRequests Off
    ProxyPass /sharelatex http://127.0.0.1:3000
    ProxyPassReverse /sharelatex http://127.0.0.1:3000
"""
and http://toto.univXXX.fr/sharelatex redirect to http://toto.univXXX.fr:3000
It's correct for the first page but no /template for example 

Maybe put in header : 
base href="http://toto.univXXX.fr/sharelatex"  ????
or configuration in settings.development.coffee file ??
THX

**Comment by asedeno** [comment]
I'm actively working on this at https://github.com/asedeno/web-sharelatex/tree/rebase and so far it's working pretty well for me.

For anyone else who decides to look at it, be aware that I may rewrite history without notice until I open a pull request. With that warning, I'm also accepting feedback.

**Comment by asedeno** [comment]
I'm no longer working on this, having received no feedback and lost interest in running my own sharelatex instance. The branch will stick around in case anyone else wants to look at it.

**Comment by jdleesmiller** [comment]
Thanks for the update and sorry for the silence. Unfortunately, we still don't have much experience with Apache, and as several have pointed out above there would be a lot of changes required to get Overleaf/ShareLaTeX to comfortably run under a subpath.

The best alternative approach is to run on a subdomain.

I will close this ticket, but hopefully your branch and this thread will continue to be useful to anyone who wants to pursue this.

**Comment by asedeno** [comment]
@jdleesmiller, I had already made many of those changes and was using sharelatex behind a subpath for over a year. Running on a subdomain isn't really an option when you have one server and no access to DNS. If there is interest at overleaf, look over the commits in my branch and ask me questions. I think they were reasonably bite-sized, and mostly distill down to:

1. Set up a base path for relative urls
2. Honor the `X-Script-Name` header
3. Use relative urls instead of absolute urls

**Comment by knedlyk** [comment]
@jdleesmiller Please take a look on these changes, it is worth to commit them. Running sharelatex/overleafe behind subpath by means of the apache or nginx proxy pass is a very useful option for people who have several subpath projects on a one serve. I personally looked for this solution several years ago and found this discussion and Alejandro's project.
