### ISSUE TITLE
Docs: How to add latex dependencies to sharelatex/sharelatex image

### ISSUE THREAD

**Issue by christian-steinmeyer** [overleaf/overleaf#830]
I am trying to figure out how to properly extend the default set of latex packages provided in the [official sharelatex/sharelatex image](https://hub.docker.com/r/sharelatex/sharelatex).

I can't find any documentation for this use case that might happen to other users. I'm afraid, that it might too obvious for advanced users.

When I try to `\usepackage{datetime}` or some other package that seems to not be part of the default set of packages provided with overleaf, I get a LaTeX Error: "File `datetime.sty' not found.". If it really is not installed, that shouldn't be surprising. I have the following questions:

1.) Where is the package list defined that is installed with the community edition?
2.) How can I extend this list? Ideally, I would like to do this through another docker image that is based on sharelatex/sharelatex and extends it by some additional packages, I define in some config file. Would that be possible? 

Thanks for the great work!

**Comment by mserranom** [comment]
You can use use `tlmgr` to customise your Latex environment as described in https://github.com/overleaf/overleaf/wiki/Quick-Start-Guide#latex-environment.

**Comment by christian-steinmeyer** [comment]
Thanks for the quick reply, I must have missed that bit, sorry. Could I also use that to create a "wrapper-image" (an image that behaves exactly like the original but has the full installation)? Something along the lines of 
```dockerfile
FROM sharelatex/sharelatex:2.5.1

RUN tlmgr install scheme-full

ENTRYPOINT ["/sbin/my_init"]
```

**Comment by mserranom** [comment]
I don't see why not, but more often I see people doing the `tlmgr` updates inside the container, then committing the changes: https://docs.docker.com/engine/reference/commandline/commit/

**Comment by christian-steinmeyer** [comment]
Thanks for getting back. The above solution seems to do what I want. We want to roll out the overleaf instance with ansible without the changes being overwritten on the next deployment. That's why we prefer the packages already loaded in the image.
