### ISSUE TITLE
Incorrect capture of section/paragraph title in File outline

### ISSUE THREAD

**Issue by Xiphoseer** [overleaf/overleaf#832]
## Steps to Reproduce

1. Enable the "beta" feature "File outline"
2. Create a blank project
3. Enter `\section{Introduction} \textit{a} \textit{b}` somewhere

## Expected Behaviour
The *File outline* panel on the bottom left should display `Introduction`

## Observed Behaviour
The *File outline* panel displays `Introduction} \textit{a} \textit{b`

## Context
It's a minor bug that doesn't cause any problems but seems worth reporting. It seems to happen at all outline levels.

## Technical Info

* URL: https://sharelatex01.ca.hrz.tu-darmstadt.de/project/{ID}
* Browser Name and version: Firefox 78.6.1esr (64bit)
* Operating System and version (desktop or mobile): Debian Buster (desktop)
* Signed in as: LDAP user
* Project and/or file: LaTeX source file

## Analysis
Unfortunately I don't have the time to look into that right now. I would like to come back to that though.

it also happens in MS Edge (89.0.767.0) i.e. Chromium, so it's unlikely that it is a browser compatibility issue.

**Comment by NilsEnevoldsen** [comment]
Another one that I've encountered is `\section{foo\@. bar \textit{baz} qux}` as `foobaz qux` instead of the preferable `foo. bar baz qux` or `foo\@. bar baz qux`. Not sure if this is the same root issue, but similar enough that I'll put it here.

**Comment by mserranom** [comment]
The File outline is design to track a specific set of commands, described in:

https://www.overleaf.com/learn/how-to/Using_the_File_Outline_in_Overleaf#Supported_heading_commands

I'm afraid we don't plan to extend it anytime soon.

**Comment by Xiphoseer** [comment]
Thanks for the heads up! I must admit that I didn't find that docs page when googleing whether this issue was known. Three questions:

I originally encountered the bug when using a `\textit` on the same line as a `\paragraph` which does not feel "non-standard" given that its on the same line in the output. Would you be open to updating the docs to list supported expansions (e.g. single label ?) instead of declaring anything that's not explicitly handled "other non-standard usages"?

The observable behavior seems very much like a regex that looks somewhat like `\\(chapter|section|…)\{[^\n]*\}`. The bug I reported is essentially about this regex being too greedy so that it doesn't stop at the matching closing brace. Is the assumption correct that this was a deliberate decision to disallow newlines instead so that it would capture nested macros?

If I were to dig into the implementation and provide a PR that scans each match to find the first position where all opened braces are closed again and split the string there, is there a reasonable chance that you would merge that?

**Comment by Xiphoseer** [comment]
For reference: The relevant parser code lives (at least at the moment) in [overleaf/web](https://github.com/overleaf/web), specifically in [/frontend/js/features/outline/outline-parser.js](https://github.com/overleaf/web/blob/babec42d80272757d00b5fe4fa4012f5fb26c43b/frontend/js/features/outline/outline-parser.js). Would it make sense to move this issue there, even if closed?

**Comment by Xiphoseer** [comment]
> Another one that I've encountered is `\section{foo\@. bar \textit{baz} qux}` as `foobaz qux` instead of the preferable `foo. bar baz qux` or `foo\@. bar baz qux`. Not sure if this is the same root issue, but similar enough that I'll put it here.
> 
> Another example is `\section{\textit{foo} \textit{bar}}` becomes `foo \textit{bar}`.

So the explanation for this is that it only ever "hides" a single command and that it accepts any letter but an opening brace (i.e. `[^{]`) as the name of a macro, which should really just be `[A-Za-z]` according to <https://en.wikibooks.org/wiki/TeX/catcode>.
