### ISSUE TITLE
Overleaf https Nginx does not work with subpath other than "/"

### ISSUE THREAD

**Issue by nicolasgoudard** [overleaf/overleaf#834]
Hello.
I have multiple location entries in my Nginx  : /zabbix  /jupyterhub /grafana /    I want to use /overleaf or /sharelatex location 
I cannot use subpath with  overleaf But it does not work . I see this "bug" was related already in 2016 : https://github.com/overleaf/docker-image/issues/44
Only this configuration works : If I change the path location in Nginx  it does not work. I have tried many combinations for SHARELATEX_SITE_URL in docker-compose.yml,  and  "proxy_pass" in nginx.conf but it does not work 

In my docker-compose.yml : 
```
      environment:
             SHARELATEX_SITE_URL: https://myoverleaf.localdomain
```
In my nginx.conf configuration : 
```
	      location / {
		proxy_pass  http://localhost:8090; 
```

Is there a workaround to fix this bug ?   
Thanks. Best regards.

**Comment by das7pad** [comment]
> Is there a workaround to fix this bug ?

No. There is no logic in place for looking at the path of the provided site URL and composing relative paths to that. You could use a subdomain instead.

**Comment by massih10** [comment]
Any plan to fix this? The containers are useless without this feature ...

**Comment by Chritzel** [comment]
I am experiencing the same problem. I looked around a bit, and there has been a thread on this (https://github.com/overleaf/overleaf/issues/83) and even a PR (https://github.com/overleaf/web/pull/653), which unfortunately did not get any attention. I would also very much appreciate these changes to run overleaf on a subpath.
