### ISSUE TITLE
How to install texlive full for overleaf ?

### ISSUE THREAD

**Issue by OrnithOrtion** [overleaf/overleaf#835]
## Steps to Reproduce

1. Install Overleaf Community edition using toolkit
2. Install texlive-full metapackage using `sudo apt install texlive-full`
3.Try to use a tex package such as `lipsum` in a overleaf latex document

## Expected Behaviour

I expected that after I installed texlive-full package, the ctan tex package included will be usable in overleaf.
## Observed Behaviour

I could not use tex package such as lipsum, the pdf compilation stopped.
## Analysis

May be there is an other way to install texlive full directly using overleaf's docker, I do not know.

**Comment by jasek5** [comment]
`docker exec sharelatex tlmgr install scheme-full`

**Comment by goofus** [comment]
Always good to read at least the quick start guide. https://github.com/overleaf/overleaf/wiki/Quick-Start-Guide
