### ISSUE TITLE
XeLaTeX not available on Clean Install

### ISSUE THREAD

**Issue by cmprmsd** [overleaf/overleaf#837]
## Steps to Reproduce
1. Install with overleaf toolkit (it installs v2.5.0)
2. Create a sample minimal document or open the example.
2. Change the compiler to xelatex
3. Compile and the error message will appear (without details or any logs in the log div)
4. ![image](https://user-images.githubusercontent.com/73472903/107649599-e98d5e80-6c7d-11eb-800e-04fb131a830c.png)

## Expected Behaviour

The file should compile in XeLaTeX.

## Observed Behaviour

The file does not compile in XeLaTeX. It does compile in pdfLaTeX
## Context

No output :(
## Technical Info

N/A

* URL:
* Browser Name and version: Firefox 85
* Operating System and version (desktop or mobile): Arch Linux Desktop
* Signed in as: Admin
* Project and/or file: Example File

Thanks in advance for your help!
Btw, how can I compile the sharelatex/sharelatex docker container myself? I can't find the source for it.
The dockerfile in this repo shows sharelatex/sharelatex as base (from the Docker hub, but no source definition file)

**Comment by Raymo111** [comment]
Same issue with PDFLaTeX. Any fix?
![image](https://user-images.githubusercontent.com/34818275/108005276-3f3b7100-6fc6-11eb-9103-2d5160c456ba.png)
It just hangs like that for 2 minutes and then becomes:
![image](https://user-images.githubusercontent.com/34818275/108010382-be36a680-6fd2-11eb-915b-6b33a993cdd0.png)

**Comment by Raymo111** [comment]
So it just worked. Turns out the sqlite database was set to readonly. Running `sudo chown www-data:www-data -R <data-dir>` worked.

**Comment by cmprmsd** [comment]
![image](https://user-images.githubusercontent.com/73472903/108036877-17d1bc00-7039-11eb-8aac-bc2371ba1124.png)
On my container the folder is already owned by www-data. I also tried to chown again and the data folder itself in order to own files, that do not belong to www-data, but no change.
Did you try something else, that fixed the issue but became effective only after a restart?

**Comment by cmprmsd** [comment]
I looked a bit deeper into the issue..
1. sudo docker exec -it sharelatex bash
2. ll /usr/local/texlive/2020/bin/x86_64-linux/

You will see there is latexmk, lualatex but no xelatex.

Also compiling from the cli with `/usr/local/texlive/2020/bin/x86_64-linux/latexmk -xelatex main.tex` from your compile folder `root@c44a552b20c8:/var/lib/sharelatex/data/compiles/<hashhere>#` will result in the output:

```
Latexmk: This is Latexmk, John Collins, 29 September 2020, version: 4.70b.
Latexmk: applying rule 'xelatex'...                                       
Rule 'xelatex': The following rules & subrules became out-of-date:        
      'xelatex'                                                           
------------                                                              
Run number 1 of rule 'xelatex'                                            
------------                                                              
------------                                                              
Running 'xelatex -no-pdf -recorder  "main.tex"'                           
------------                                                              
sh: 1: xelatex: not found                                                 
Latexmk: fls file doesn't appear to have been made.                       
Latexmk: Examining 'main.log'                                             
=== TeX engine is 'LuaHBTeX'                                              
Latexmk: Index file 'main.idx' was written                                
Latexmk: Errors, so I did not complete making targets                     
Collected error summary (may duplicate other messages):                   
  xelatex: Command for 'xelatex' gave return code 127                     
      Refer to 'main.log' for details                                     
----------------------                                                    
This message may duplicate earlier message.                               
Latexmk: Failure in processing file 'main.tex':                           
   *LaTeX didn't generate the expected log file 'main.log'                

```

Obviously the binary is not bundle in this release of texlive 2020 :cry: 
Interesting is also the "became out of date" for xelatex.

**Comment by mbedded** [comment]
Thank you for investigation. I am using XeLaTeX, too and wonderd why it doesn't work on a clean install

**Comment by wolfbolin** [comment]
It is the same for me 

When I'm using `latexmk`, `latexmk -xelatex` is not available at all

I had to use the apt command to install it and its dependencies
```
apt-get update
apt-get install texlive-xetex texlive-latex-extra texlive-science
```
Error log
```
# latexmk -pvc -xelatex -gg -silent csuthesis_main                                                            Rc files read:
  NONE
======= Need to update make_preview_continuous for target files
Viewing pdf
Latexmk: Run number 1 of rule 'xelatex'
sh: 1: xelatex: not found
Latexmk: fls file doesn't appear to have been made.
Latexmk: Getting log file 'csuthesis_main.log'
Latexmk: Couldn't read log file 'csuthesis_main.log':
  No such file or directory
Latexmk: *LaTeX didn't generate the expected log file 'csuthesis_main.log'
    ==> You will need to change a source file before I do another run <==
Collected error summary (may duplicate other messages):
  xelatex: Run of rule 'xelatex' gave a non-zero error code

=== Watching for updated files. Use ctrl/C to stop ...
```

**Comment by cmprmsd** [comment]
Will this be added to the packages some day? :sweat_smile:

**Comment by das7pad** [comment]
Thanks for the ping. I've created an internal ticket for this. Unfortunately, I cannot give any estimate if or when this gets included in a release.

**Comment by jimohuaxue** [comment]
现在这个问题还存在吗，我似乎也遇到了这样的问题

**Comment by das7pad** [comment]
> 现在这个问题还存在吗，我似乎也遇到了这样的问题

Which version of Server CE are you using?

We are installing the `xetex` package explicitly since version 4.2.

https://github.com/overleaf/overleaf/blob/48337b2e2ca84da0cdf675ada0e8e945fbe64a10/server-ce/Dockerfile-base#L78

**Comment by jimohuaxue** [comment]
docker显示的sharelaetx版本是5.5.0，这是我之前的报错

![Image](https://github.com/user-attachments/assets/8fea0ccb-ba78-45d6-8e91-b9bfb38076f7)
![Image](https://github.com/user-attachments/assets/f44c0926-54e6-4e8a-a662-5b7306abcc87)

**Comment by das7pad** [comment]
Does the project compile in version 5.4? Can you try compiling it on overleaf.com? (provided this is acceptable)

> P.S. Would you mind replying in English?

**Comment by mserranom** [comment]
I can compile the Example Project using `xelatex` in 5.5.0. 

<img width="829" alt="Image" src="https://github.com/user-attachments/assets/6a644b06-8335-4f9d-a45d-4f4f5be3f639"/>

**Comment by jimohuaxue** [comment]
> Does the project compile in version 5.4? Can you try compiling it on overleaf.com? (provided this is acceptable)
> 
> > P.S. Would you mind replying in English?

I can compiling it on overleaf.com
Now that I've entered Docker and reinstalled the full version of the TeX Live image, compilation works successfully.
Question: If a document compiles on Overleaf.com, does that mean this minimal installation supports all packages?

**Comment by das7pad** [comment]
> > Does the project compile in version 5.4? Can you try compiling it on overleaf.com? (provided this is acceptable)
> > > P.S. Would you mind replying in English?
> 
> I can compiling it on overleaf.com Now that I've entered Docker and reinstalled the full version of the TeX Live image, compilation works successfully. Question: If a document compiles on Overleaf.com, does that mean this minimal installation supports all packages?

I'm glad to hear that you got it working. Perhaps you missed to install missing packages again after upgrading the image?

If you cannot compile on overleaf.com that usually indicates something is wrong with your projects LaTeX source.
