### ISSUE TITLE
Two versions of Textlife in version Community

### ISSUE THREAD

**Issue by gleisonsoares** [overleaf/overleaf#838]
## Expected Behaviour

Good afternoon people. Is there any way to have two versions of TexLive in the community version (same as the official portal version)?

**Comment by mserranom** [comment]
I'm afraid is not possible in Community Edition. It is possible in Server Pro, our commercial version, since compilations [are performed in separate containers](https://github.com/overleaf/overleaf/wiki/Server-Pro:-sandboxed-compiles).
