### ISSUE TITLE
How to Add Custom Snippets to Overleaf Community Edition

### ISSUE THREAD

**Issue by cmprmsd** [overleaf/overleaf#839]
## Steps to Reproduce

Hey all,

I looked into Overleaf's container in order to extend the snippets of the "ACE editor" with custom snippets, that we want to used for reporting.

Does anyone have an idea how to do it properly?

If found several occurrences of snippets but it seems Overleaf is not using these places, or I'd have to recompile all minified JavaScript somehow.

It tried to recompile with grunt as it is discussed in the readme of /web/ but grunt does not compile anything.

Thanks in advance I love the editor!

**Comment by blepabyte** [comment]
Not sure if you've already solved this but one way is to modify the web repo link in `overleaf/overleaf/services.js` to point to your own fork of `overleaf/web` and then rebuilding the docker image. Changes made to, say, `web/frontend/js/ide/editor/directives/aceEditor/auto-complete/snippets/TopHundredSnippets.js` via Git should be reflected after the build (unfortunately each docker build took around 10 minutes for me, so this is not very practical for development). 

Another way I just found that works inside a running container: 
- Modify files under `/var/www/sharelatex/web`, e.g. that same snippets file
- Running `npm run-script webpack:production` to build the minified JS
- `pkill -9 node` to force the new changes to be served

(these are probably not the 'proper' ways to do it but just what I managed to figure out by digging through the code, hopefully this is somewhat helpful to someone)

**Comment by cmprmsd** [comment]
Thank you @blepabyte! That's nearly the way I also solved it. I added my snippets to the EnvironmentManager.js as I first did not fully understand the way the webserver worked :D 


You can even change the priority and sorting with `Score:`

Do you know, if there is a difference between the npm way to compile the server and:
`webpack --target=web --config webpack.config.prod.js` ? That was the way I used to recompile the server.

Also `webpack --target=web --config webpack.config.dev.js` came in handy in order to debug [Overleaf Image Helper](https://github.com/cmprmsd/Overleaf-Image-Helper) that I now integrated in the web application itself. At least for our server :)

**Comment by blepabyte** [comment]
No difference it seems, looking at `package.json[scripts]`, other than not requiring webpack to be installed globally. There's also `npm run-script webpack` which runs `webpack-dev-server` for faster builds and live-reload. 

Your image helper looks great! Working with images in latex is always a pain and I can never remember the proper syntax. Would be awesome if the functionality got merged into overleaf :D. A drag-and-drop image feature could also be convenient - which I'd be happy to try and work on.
