### ISSUE TITLE
Uploaded PDF: Sorry, no preview is available.

### ISSUE THREAD

**Issue by axkibe** [overleaf/overleaf#844]
## Steps to Reproduce

1. Upload a PDF. 
2. Try to view it. 
3. Get "Sorry, no preview is available"

## Expected Behaviour
Be able to view the PDF just as with generated PDFs

## Observed Behaviour
That error message instead.

## Context

This would be very useful to collect the PDFs of cited literature directly with the project, shared with all participants and quickly view them without downloading, or using yet another Filesharing service

## Technical Info

I read on a Twitter reply, this has been disabled on purpose due to a security issue. 
  https://twitter.com/overleaf/status/1217900796668456966?lang=en

That's all I could find about this.

I don't know what the issue is and what it entails, but I'd really like to be able to turn this on again on a local site installation. I'd willingly accept a slight mishap for this to work, it are all to be trusted users on this server...

**Comment by JonathanTreffler** [comment]
Self Hosted Server Admins should really have the option to enable this :/

**Comment by axkibe** [comment]
I looked into the source code of CE. It's not as simple as flipping a flag there somewhere, since as far I can see the code to view PDFs isn't there at the place where it would be needed, there is only textview and imageview. So if it was doable previously before they disabled it, they removed the respective code. However, I think it wouldn't be that hard to add a PDF viewer at this place also, since basically it's already in the source (just at some different place to view compilation results). Currently don't have much time for this tough and the pressure in my case to get this working isn't there at the moment (as projects come and go). Still think it would be nice for collaboration tough as it would require one tool less for collaborators when this can be done in Overleaf right away.

**Comment by das7pad** [comment]
Hello,

Thanks for raising this feature request. I'm glad to let you know that we have implemented it at the end of last year :tada: Overleaf Community Edition and [Server Pro](https://www.overleaf.com/for/enterprises) version 4.2.x and 5.x include it.

![image](https://github.com/user-attachments/assets/2660739b-ac44-468b-b5b6-b897a5261857)

Greetings,
Jakob

**Comment by bryan-ilman-on-github** [comment]
but it fails to compile on first error. how to make it more forgiving like in the browser version?

**Comment by das7pad** [comment]
> but it fails to compile on first error. how to make it more forgiving like in the browser version?

Hi @bryan-ilman-on-github! Please open a new ticket and include which version/deployment method your are using. Thanks.
