### ISSUE TITLE
I can't create admin user

### ISSUE THREAD

**Issue by alikej** [overleaf/overleaf#846]
## Steps to Reproduce

1. I try to deploy a new docker installation
2. On fresh install I go to: ... /launchpad and put an admin mail + pass = Created admin user, Log in here to continue
3. Following link - I put my admin credentials on webssite ... /login?redir=%2Flaunchpad
4. or over grunt when I follow the link - Successfully created ...@... admin user.
5. When I follow in the link I see this: Reset your password - I do

## Expected Behaviour

Create a admin account

## Observed Behaviour

I CANNOT CREATE A FIRST ADMIN USER on a fresh installation
I see an error message: "Your password reset token has expired. Please request a new password reset email and follow the link there." or "Your email or password is incorrect."

When I try to log with admin credentials error message is: this email is not registered 

What can I do?

## Technical Info

* Browser Name and version: Firefox 81
* Operating System and version (desktop or mobile): unraid 6.9.0 - docker and overleaf image LATEST

**Comment by cmprmsd** [comment]
Did your enter your email with capital case letters?
The was a bug in the last versions and the workaround was to use only non capital letters for the email address on creation.

**Comment by das7pad** [comment]
Hello,

Thanks for the report. Creating users, including admin users, is now part of our automated tests and working for the latest versions of Overleaf Community Edition and [Server Pro](https://www.overleaf.com/for/enterprises).
Let us know if you are still having issues after upgrading to 5.1.1 or later.

Greetings,
Jakob
