### ISSUE TITLE
How to Install pygmentize (pip package) for overleaf

### ISSUE THREAD

**Issue by UncleSamulus** [overleaf/overleaf#851]
## Steps to Reproduce

1. Install overleaf CE
2. Load minted package in tex file '\usepackage{minted}'

## Expected Behaviour

Overleaf should compile latex without trouble

## Observed Behaviour

```bash 
! Package minted Error: You must have `pygmentize' installed to use this packag
e.
```
```bash
! Package minted Error: You must invoke LaTeX with the -shell-escape flag.
```

**Comment by cryptoluks** [comment]
As the errors indicates, you need both the pygmentize package in your environment and execute for example `pdflatex` with the shell-escape flag.

For the default overleaf/sharelatex docker setup, install pygmentize as follows:

- find name of docker container with `docker ps -a`
- enter container with `docker exec -it <name> sh`
- install pygmentize with `apt update; apt install python-pygments`
- to run `pdflatex` with shell-escape flag, insert this in you `latexmkrc` file in project root, create if not exist:

```
# latexmkrc
$pdflatex = 'pdflatex --shell-escape';
```

Make sure you actually using `pdflatex` for compilation. Might work with other compilers as well, but did not test it.

**Comment by Kinsteen** [comment]
Quick question, is it possible to enable shell-escape globally, and not on a project-basis? It is sort of annoying... Thanks for the answer still!

**Comment by RainshawGao** [comment]
@Kinsteen  In /usr/local/texlive/2021/texmf.cnf add this line
```
shell_escape = t
```

**Comment by rickycraft** [comment]
> As the errors indicates, you need both the pygmentize package in your environment and execute for example `pdflatex` with the shell-escape flag.
> 
> For the default overleaf/sharelatex docker setup, install pygmentize as follows:
> 
> * find name of docker container with `docker ps -a`
> * enter container with `docker exec -it <name> sh`
> * install pygmentize with `apt update; apt install python-pygments`
> * to run `pdflatex` with shell-escape flag, insert this in you `latexmkrc` file in project root, create if not exist:
> 
> ```
> # latexmkrc
> $pdflatex = 'pdflatex --shell-escape';
> ```
> 
> Make sure you actually using `pdflatex` for compilation. Might work with other compilers as well, but did not test it.

With this steps i was not able to install correctly pygments, i had to install it from pip like this:

1.  `apt update`
2.  `apt install python3-pip`
3.  `pip3 install Pygments`
4.  `apt clean`
