### ISSUE TITLE
\href to URL with custom scheme doesn't render as clickable link

### ISSUE THREAD

**Issue by nobodyinperson** [overleaf/overleaf#852]
## Steps to Reproduce

1. Create a blank project 
2. Copy-Paste this into the LaTeX file:

```latex
\documentclass{article}
\usepackage{hyperref}
\begin{document}
\href{https://wikipedia.org}{\texttt{https} link is clickable}, 
\href{myscheme://link/is/not/clickable}{\texttt{myscheme} link isn't}
\end{document}
```

2. Recompile

## Expected Behaviour

The link with the custom `myscheme` link is rendered as a clickable link, instructing the PDF application/browser to handle opening it. 

This is the case when compiling the above LaTeX document locally with `pdflatex` and opening it with a PDF viewer.

## Observed Behaviour

Only the `https` link is clickable, the `myscheme` link isn't. When downloading the PDF and opening with a PDF viewer, the link ~~isn't clickable either.~~ is indeed clickable, it seems to be a browser thing. Opening the PDF seperately in ~~the browser~~ Firefox also doesn't show the link as clickable. In the PDF opened separately in Chromium (89.0.4389.82 Arch Linux) the link is clickable. But not in the `built-in` Overleaf PDF viewer, only when selecting `native` PDF viewer.

## Context

I implemented a new URL scheme handler and wanted to insert such a clickable link into an Overleaf LaTeX document.

## Technical Info

* URL: custom instance
* Browser Name and version: Mozilla Firefox 86.0
* Operating System and version (desktop or mobile): up-to-date Manjaro Linux
* Signed in as:
* Project and/or file:

## Analysis

I suppose this might be some kind of a security feature? However, I'd like to turn that off then. Where would I look for that?

**Comment by nobodyinperson** [comment]
Ah, it seems to be a ”security feature” of PDF.js, Mozilla's in-browser PDF viewer: https://github.com/mozilla/pdf.js/pull/1326 which obviously can't be disabled easily: https://github.com/mozilla/pdf.js/issues/10057 

Chromium obviously doesn't use PDF.js as built-in PDF viewer.

However, as [Overleaf seems to use a fork of PDF.js](https://www.overleaf.com/blog/sharelatex-and-pdfjs-2013-03-22), it should be possible to override this on a custom instance.

**Comment by das7pad** [comment]
Hello,

Thanks for raising this issue. We have since moved back to the upstream version of pdf.js. It's unlikely that we will override a security feature.

Out of curiousity, what kinds of links do you need clickable inside the Overleaf PDF Preview?

Greetings,
Jakob

**Comment by nobodyinperson** [comment]
Just some custom schemes to internal resources we use, which would be very convenient to have in our overleaf documents. But I understand the security concerns.
