### ISSUE TITLE
can't create admin

### ISSUE THREAD

**Issue by ghost** [overleaf/overleaf#864]
Hi
It is like the same issue: https://github.com/overleaf/overleaf/issues/647
But the Timezone is right. I use the latest version and I can't find something in the logs.

`Command: ./node_modules/east/bin/east migrate --adapter east-mongo --url mongodb://192.168.65.45:27017
nothing to migrate

[32mDone, without errors.[39m
All migrations finished`

**Comment by Maximilian-tek** [comment]
Same here
