### ISSUE TITLE
tlmgr install scheme-full demands Tex 2021

### ISSUE THREAD

**Issue by julsal** [overleaf/overleaf#873]
An attempt to run

`docker exec sharelatex tlmgr install scheme-full`

Gives an error:

```tlmgr: Local TeX Live (2020) is older than remote repository (2021).
Cross release updates are only supported with
  update-tlmgr-latest(.sh/.exe) --update
See https://tug.org/texlive/upgrade.html for details.```

**Comment by dvmc** [comment]
Until TeX Live 2021 is shipped with the official Overleaf image, one of the following workarounds is possible (adjust years where applicable):

* Override the PATH variable in docker-compose.yml with the updated year and upgrade TeX Live (see https://github.com/overleaf/docker-image/issues/90#issuecomment-392588774 or https://github.com/overleaf/overleaf/issues/601#issuecomment-480504415)
* Create a custom image which takes Overleaf as base and installs TeX Live (see https://github.com/overleaf/overleaf/issues/601)
* Switch to the historic 2020 repository and try again (see https://github.com/overleaf/toolkit/issues/50).

I went with the last one. Note that for the historic repositories there are fewer mirrors available. Pick a near one from the [TUG historic README](https://tug.org/historic/README).

Pre-emptively, if you don't want to upgrade Overleaf and just re-create the container with other settings, use [`docker commit` as outlined in the Toolkit docs](https://github.com/overleaf/toolkit/blob/3b5fbcf1d5a4a8a4751e1f90e8e709f15b1a4c18/doc/ce-upgrading-texlive.md).

**Comment by mserranom** [comment]
We have published `sharelatex/sharelatex:2.6.1` containing TexLive 2021, please check it out :)

**Comment by julsal** [comment]
Thanks a lot!

**Comment by hrvylein** [comment]
Sorry to reopen but $PATH still points to 2020 installation.

**Comment by ehfd** [comment]
Issue is back in 2023.

```
FROM sharelatex/sharelatex:latest

RUN export TEXLIVE_PATH=/usr/local/texlive && \
    ls -la "${TEXLIVE_PATH}" && \
    export TEXLIVE_VERSION="$(find ${TEXLIVE_PATH} -type d -name "2*" -printf "%f\n" | tail -1)" && \
    export PATH="${PATH}:${TEXLIVE_PATH}/${TEXLIVE_VERSION}/bin/x86_64-linux" && \
    echo ${PATH} && \
    tlmgr path add && \
    (tlmgr update --self --all || (tlmgr option repository "https://ftp.math.utah.edu/pub/tex/historic/systems/texlive/${TEXLIVE_VERSION}/tlnet-final" && tlmgr update --self --all)) && \
    tlmgr path add && \
    tlmgr install scheme-full && \
    tlmgr path add
```

**Comment by 9Mad-Max5** [comment]
Seems to be reoccurring all the time
