### ISSUE TITLE
Still problems with sending emails

### ISSUE THREAD

**Issue by johwoesten** [overleaf/overleaf#874]
## Steps to Reproduce

1. Installed (described in startup-guide)
2. Edited variables (described in Configuring SMTP Email)
3. Got error in Launchpad when sending test email

## Technical Info

* URL:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Signed in as:
* Project and/or file:

**Comment by julsal** [comment]
I also faced problems configuring the SMPT email service.
I got it working only after setting `SHARELATEX_EMAIL_SMTP_SECURE`  to `false`.

I hope it helps.

**Comment by mserranom** [comment]
@johwoesten I'm closing the issue, feel free to reopen if you can provide a the complete set of details requested by the template.
