### ISSUE TITLE
LaTeX Error: File `scrartcl.cls' not found.

### ISSUE THREAD

**Issue by hammermannman** [overleaf/overleaf#876]
## Steps to Reproduce
If I use:
`\LoadClass[a4paper,oneside,12pt, enabledeprecatedfontcommands, bibliography=totocnumbered]{scrartcl}
`
or
`\documentclass[a4paper,oneside,12pt, toc=listof, toc=bib]{scrartcl} `

it shows this error:
![grafik](https://user-images.githubusercontent.com/44962130/115715396-5e64cf00-a378-11eb-9177-d5c56c84f368.png)

Same sourcecode has no problem in the online-version from overleaf or in a local app like texstudio.

I can't compile

## Technical Info
I am using the latest unRAID version and the Docker from the Appstore (https://hub.docker.com/r/sharelatex/sharelatex)

* Browser Name and version: latest Firefox and google chrome
* Operating System and version (desktop or mobile): windows 10
* Signed in as: admin
* Project and/or file:

**Comment by Spiritreader** [comment]
Have you correctly installed all required texlive packages for this to compile?
This is an extra step, the overleaf container only comes with a barebone texlive installation.
If not, try running

```
tlmgr update --self
tlmgr install scheme-full
```
inside the container

Note: This will download **all** available packages (about 4000) and could take a while. Also make sure you have enough storage space (~4GB)

**Comment by hammermannman** [comment]
I will try it
where will the container save this files? In the mongoDB?

**Comment by hrjakobsen** [comment]
I hope upgrading TexLive resolved the issue. For reference, the upgrade process (along with persisting the changes to the image) is documented here https://github.com/overleaf/toolkit/blob/master/doc/ce-upgrading-texlive.md. I'll close this issue, but feel free to reopen it if you encounter it again.
