### ISSUE TITLE
Is there speech-to-text/dictating functionality available?

### ISSUE THREAD

**Issue by Nestak2** [overleaf/overleaf#877]
Hi,
I wonder if overleaf includes some speech-to-text functionality, so I can dictate text? Or can I somehow "hack" overleaf to import a library that does this, or something like that. If this isn't availble for overleaf can you recommend me a similar free service that would allow this?
Thanks!

**Comment by mserranom** [comment]
No, nothing is included, but we try to make the application as accessible as possible, any browser-specific speech-to-text solution should work reasonably well.
