### ISSUE TITLE
Incorrect entries in spellcheck dictionary can not be erased by user

### ISSUE THREAD

**Issue by ruffsl** [overleaf/overleaf#882]
## Steps to Reproduce

1. Open a new project and type out an erroneous misspelling into a .tex file.
2. Right click the underlined miss spelled word and then click  `Add to Dictionally`
3. Try and remove erroneous misspelling from dictionally without contacting support

![image](https://user-images.githubusercontent.com/2293573/116731716-ea8d7c80-a99e-11eb-8c00-f2f6e225e9bd.png)

## Expected Behavior
Users can remove as well as add custom words into the project's spellcheck dictionary.

## Observed Behavior
Users can only add custom words into the project's spellcheck dictionary.

## Context
When correcting for spellcheck errors and right clicking highlighted miss spelled words, it s rather easy miss click the `Add to Dictionally` option within the popup menu, either from unfortunate placement of the popup given the right click location in the current page layout or accidental double click. Thus, erroneous miss spelling are often accidently included into the project's spellcheck dictionary. Unfortunately, users have no means on their side to correct this mistake and must instead contact the system admistrator to erase incorrect entries in spell-checker.

## Analysis
Related:
 * https://tex.stackexchange.com/questions/360481/erasing-incorrect-entries-in-overleaf-spell-checker

**Comment by thefeinkoster** [comment]
Are there at least any plans to adapt this?

**Comment by 00santiagob** [comment]
It has been 4 years since the publication of this issue, have you thought about applying it?

**Comment by douira** [comment]
There was a lot of discussion of the feature allowing users to selectively remove their dictionary words in this issue: https://github.com/overleaf/web/issues/673 from the archived Overleaf Web repository. I'm linking it here so that the fact that there were at least 68 votes (+ much more indirect) on the issue there isn't lost. This is obviously a highly requested feature.

**Comment by thesethtruth** [comment]
Bumping this. Dear god, how can this not be a feature already? Please be so kind to reply.

**Comment by kennethchiu** [comment]
Agree, this is a critical feature, and doesn't seem like it would be superhard to add. Even something crude, like allowing users to download their dictionary and upload a dictionary would be better than nothing. I could download my dictionary, correct it, then upload it.

**Comment by jxu** [comment]
https://github.com/overleaf/web/issues/673#issuecomment-772391472 Supposedly it's on this year's roadmap.

**Comment by primepeter** [comment]
@gh2k 
Any updates on this issue?

**Comment by timothee-alby** [comment]
We've just released this today. _(The feature is currently in beta; you can join the beta program [here](https://www.overleaf.com/beta/participate))_

From the editor menu (top-left button) in the settings section, click on the "Dictionary -- Edit" button. You will be able to remove words from your custom dictionary.
Hope that helps!

**Comment by cmcisaac6** [comment]
This has now been rolled out to all users, and is also available in the Community Edition and Server Pro! I will close this issue now.

![image](https://user-images.githubusercontent.com/81039188/188597543-e7978ed1-bb0f-40a6-baa3-d8a5d0769f35.png)
