### ISSUE TITLE
Share pdf result, not overleaf project ?

### ISSUE THREAD

**Issue by kpym** [overleaf/overleaf#883]
## Steps to Reproduce

1. Click the Share button.
2. Search for PDF share.

## Expected Behaviour

I expect to find a link to a resulting pdf. Let say that the read only url is something like `https://www.overleaf.com/read/xxxxxx`, I expect to be able to use a link like `https://www.overleaf.com/read/xxxxxx/folder/file.pdf` to the last compiled version of `https://www.overleaf.com/read/xxxxxx/folder/file.tex`.

## Observed Behaviour

Nothing is mentioned about how to share resulting pdf file.

## Context

I would like to make a script that recover the last version of `pdf` produced by Overleaf.
I would like to publish a link on a web page to the last version of `pdf` produced by Overleaf.

**Comment by mserranom** [comment]
PDFs are not persistent, so no script can be written to fetch the last PDF version of the project. 

Providing an option to share the latest PDF is in our roadmap, but no delivery date can be confirmed yet.
