### ISSUE TITLE
Comment Feature Misleading Readme

### ISSUE THREAD

**Issue by RapIt** [overleaf/overleaf#884]
Hi,
Overleaf is great work but apparently the Pro Server has the entire dev focus these days. Of course commercialization and promoting is fine but it would be great if you would state the differences clearly in the readme.

Now I spent an hour setting up an instance only to find out that the basic comment feature is not supported in the free version. I am wondering about that as it is available using the free plan on overleaf.com and the first screenshot on the readme also suggests its being available. An early clarification / screenshot replacemant would be great to avoid further confusion.

If you plan to support commenting in the future, I would appreciate a comment.

Thanks!

**Comment by jdleesmiller** [comment]
Thanks for pointing this out. I've tried to clarify this in the README with https://github.com/overleaf/overleaf/commit/0cb9e530519b9499d0622d46107894fcdc463c2b .
