### ISSUE TITLE
Cannot see the list of registered users

### ISSUE THREAD

**Issue by julsal** [overleaf/overleaf#885]
## Steps to Reproduce

When clicking in Admin/Manage Users, the form only shows the option to register new users. One cannot see the list of already existing users.

## Expected Behaviour

In addition to the option to register new users, it should show the current list of registered users.

## Technical Info

* URL: localhost/admin/register
* Browser Name and version: Chrome 90.0.4430.93
* Operating System and version (desktop or mobile): Windows 10 Desktop
* Signed in as:
* Project and/or file:

**Comment by mserranom** [comment]
This is a feature available only in [Overleaf Server Pro, our enterprise offering](https://www.overleaf.com/for/enterprises).

You can obtain the list of registered users querying the database:

```
docker-compose exec mongo bash
mongo
> use sharelatex
> db.users.find({}, {"email": 1})
```
