### ISSUE TITLE
Can not use link to set password when register a user that existed .

### ISSUE THREAD

**Issue by cubercsl** [overleaf/overleaf#886]
## Steps to Reproduce

1. Register a user and tell him to set a password.
2. He forget his password, and ask me to register a "new" account with the original email.
3. He received an email and try to set the password, but redirected to login page.

## Expected Behaviour

- When register in step 2, tell admin this account has already registered. or
- When he received an email and try to set the password, redirect to a page to reset password.

**Comment by das7pad** [comment]
Hello,

Users can click on "Forgot your password?" on the login page or navigate to `https://my-domain/user/password/reset` directly to request a password reset link. Creating new users with the same email to reset the user password is not a supported procedure.

Greetings,
Jakob
