### ISSUE TITLE
Can university use Overleaf Server Pro free of charge?

### ISSUE THREAD

**Issue by leemgs** [overleaf/overleaf#893]
> * https://github.com/overleaf/overleaf#key-features
> 
> If you want help installing and maintaining Overleaf at your university or workplace, we offer an officially 
> supported version called Overleaf Server Pro. It also comes with extra security and admin features. Click here to find out more!
> 

When I press the link (e.g., https://www.overleaf.com/university/onsite.html), I could not visit the webpage because the webpage is automatically redirected to https://www.overleaf.com/for/enterprises.  So, I wonder about the Overleaf Server Pro's selling policy for university. In case of universities. Can they install and use Overleaf Server Pro free of charge? 

BRs, 
Geunsik Lim.

**Comment by JohnHammersley** [comment]
Thanks for your feedback on that, we've [updated](https://github.com/overleaf/overleaf/commit/4a8f88c4a834261189c091da369e0c4e398f206b) that link and text to make it clearer -- Server Pro is a paid product, and is generally aimed at companies or labs.

For universities, we generally recommend Overleaf Commons -- please see this page for more details: https://www.overleaf.com/for/universities

If you'd like to keep using Overleaf for free, you can do so with free accounts on the main website, or via the Community Edition.
