### ISSUE TITLE
Which of the directories under `SHARELATEX_DATA_PATH` can be safely deleted (or emptied)?

### ISSUE THREAD

**Issue by moschlar** [overleaf/overleaf#897]
Which of the directories under `SHARELATEX_DATA_PATH` can be safely deleted (or emptied)?

- `cache`
- `compiles`
- `output`
- `user_files`

**Comment by das7pad** [comment]
Hello,

You can find a description of the folders in the data folder in the wiki here: https://github.com/overleaf/overleaf/wiki/Data-and-Backups#folders-in-detail

Greetings,
Jakob
