### ISSUE TITLE
changing to mounted volume in docker container causes web ui to fail and other issues 

### ISSUE THREAD

**Issue by BretG137** [overleaf/overleaf#898]
The documentation for overleaf says that 

    Mongodb
    Overleaf Filesystem data
    Redis

need to be backed up but I cannot accomplish this currently

## Expected Behaviour

1. Using dockercompose I attempt the following change:
        volumes:
            - ~/sharelatex:/var/lib/sharelatex
to:
        volumes:
            - ~/mnt/sharelatex:/var/lib/sharelatex
 
this should allow the sharelatex folder to be accessible through a mounted nfs share directory.  

2.
also I expect rsync to backup the mongo_data with the following command
          sudo rsync -a /mongo_data /mnt/sharelatex/mongo_data 
 
## Observed Behaviour
1. 
the container loads fine but the webui is inaccessible. I have tried mounting many different ways and I can see that it copies the folders on to the mounted directory but it still causes the webui to fail (the webui won't load)  

2.
attempting to rsync the mongo_data folder gives all kinds of permission failures.  even after chown -R 777 /mongo_data

## Context
I only want to make sure that my tex files are stored on my NAS so that they are routinely backed up with rest of my data.  I don't understand why there isn't just a folder with all the texfiles that can just easily be changed to a mounted directory.  I'm confused by the folder structure and why this is so complicated.  Thanks!

**Comment by das7pad** [comment]
Hello,

Thanks for opening this issue. We've got some documentation on migrating data between servers, which could be relevant here: https://github.com/overleaf/overleaf/wiki/Data-and-Backups#migrating-data-between-servers

Notably all containers must be stopped and special care must be taken to copy/restore the folders with the original permissions. Some NFS shares do not support custom permissions. We recommend against running Overleaf Community Edition and [Server Pro](https://www.overleaf.com/for/enterprises) off of NFS and advise on using local disks instead. You can store backups on NFS instead, see the above link for taking consistent backups -- tar-balls/rsync the sharelatex container data, use `mongodump` for mongo data and copy the redis rdb file.

Greetings,
Jakob
