### ISSUE TITLE
PDF Rendering Error Something went wrong while rendering this PDF.

### ISSUE THREAD

**Issue by HansYeoh** [overleaf/overleaf#914]
## Steps to Reproduce
1.This restriction will appear after an ordinary user compiles several times in a short time, but I haven't found a description of this restriction in Wiki.
![image](https://user-images.githubusercontent.com/23377286/125628223-31c39aa0-8e02-4c6c-8f88-51237084293b.png)
![image](https://user-images.githubusercontent.com/23377286/125628459-a1f70146-1aa5-45cb-aac2-c951004518d6.png)

## Expected Behaviour
PDF can be compiled normally

## Observed Behaviour
The screenshots are above

## Context
Is there any parameter to remove this limitation?

## Technical Info
Docker Image ID is 2d8a8b6d1930

* URL:
* Browser Name and version:Chrome
* Operating System and version (desktop or mobile):macOS
* Signed in as:Ordinary users

**Comment by darkphoenix** [comment]
I have now also run into this issue, and have not succeeded in fixing it, even restarting the server does not seem to help.

**Comment by rockmagma02** [comment]
I have the same problem as you, but I solve this problem by copying my project. I don't know the reason, maybe it is a bad bug they can't solve

**Comment by moein1924** [comment]
I  deactivated Internet Download Manager (IDM) plugin in Chrome and now it works. If you don't have IDM, try to see which plugin causes this issue. Alternatively, you can use another browser.

**Comment by Mehwish722** [comment]
> I deactivated Internet Download Manager (IDM) plugin in Chrome and now it works. If you don't have IDM, try to see which plugin causes this issue. Alternatively, you can use another browser.

Yeah, IDM plugin is creating the issue for me as well. Thanks!

**Comment by shazib2022skipq** [comment]
Removing IDM extension solved the issue for me too

**Comment by SMzubairshah** [comment]
disable the IDM make things good

**Comment by mserranom** [comment]
Closing as this was already resolved.
