### ISSUE TITLE
go to code location in pdf is not working

### ISSUE THREAD

**Issue by CymaticsCC** [overleaf/overleaf#919]
Hi, 

There is a close issue in https://github.com/overleaf/web/issues/626

I come across the same problem like described in the site above.

The "go to code location in pdf" cannot work even in a example project created by system itself.
In this project, only three files "main.tex, xx.jpg, xx.bib". This means there is no problems like "file folders" mentioned in the above issue.

I am using a overleaf community edition installed by docker images  sharelatex  2.7.0.

This feature is important to manipulate some big pdf file.

**Comment by dongwoo21** [comment]
I'm still suffer from this issue under the latest version 3.0.1.

Following the temporary fix in https://github.com/overleaf/clsi/pull/261#issuecomment-903693127, I added the following environmental variable, but it still doesn't work.

```
environment:
  TEXINPUTS='/compile:'
  BIBINPUTS='/compile:'
  ...
```

Is there any other solution?

**Comment by jamessud** [comment]
\synctex=1 in the preamble fixed this for me
