### ISSUE TITLE
New release when new docker image created

### ISSUE THREAD

**Issue by RainshawGao** [overleaf/overleaf#921]
I notice that we release 2.7.0 on July 7th, but there is no way to get heard from this project, I must to take a look at hub.docker.com everyday.

It may be nice if we make a new release in this project when new docker image created. We can `watch` this project and receive the news from github.

Thank you!

**Comment by jdleesmiller** [comment]
Thanks for the feedback. We may indeed start using GitHub releases again in the future. In the meantime, we do have a mailing list: https://mailchi.mp/overleaf.com/community-edition-and-server-pro .

**Comment by RainshawGao** [comment]
thanks for your reply, maybe this could be close.
