### ISSUE TITLE
Ability to remove words from dictionary

### ISSUE THREAD

**Issue by douira** [overleaf/overleaf#932]
See issue from before migration: https://github.com/overleaf/web/issues/673. Nothing about this issue has changed, unless this feature has been implemented but nobody's been told about it.

**Comment by JR-Morgan** [comment]
Potential duplicate of https://github.com/overleaf/overleaf/issues/882

**Comment by douira** [comment]
Yes this is a duplicate. I didn't check for duplicates as I only made this to reference the issue of the archived repo. I'll close this and reference the archived issue in the earlier issue here.
