### ISSUE TITLE
[Feature] Git version control for comments

### ISSUE THREAD

**Issue by tvercaut** [overleaf/overleaf#934]
This is a copy-paste from a feature request in the the old repo:
https://github.com/overleaf/web/issues/686

The "Add comment" feature of overleaf is great for collaborative work. It would be even better if one had access to the comments history when pulling the project through git. I currently couldn't find it, so let me know if I misunderstood.

This feature probably relates to the issue documented in https://github.com/overleaf/overleaf/issues/552

**Comment by selffoe** [comment]
You can specify that it is a version control for the review-comments and review track change history, not the in-line %comment history

**Comment by mserranom** [comment]
Hi! Git syncing is not available in Overleaf Community Edition. For feedback on overleaf.com, please visit https://www.overleaf.com/contact.
