### ISSUE TITLE
[BUG] :s/.../.../c broken (vim mode)

### ISSUE THREAD

**Issue by gustaphe** [overleaf/overleaf#938]
## Steps to Reproduce

1. In vim-mode (in a file containing pattern), write `:s/pattern/subtsitution/gc` (followed by enter).
1. Press one of the offered options (like y).

## Expected Behaviour

It should replace the found instance of pattern by substitution.

## Observed Behaviour

It finds an instance of pattern, a bar shows up saying "Replace with substitution (y/n/a/q/l)". However, I am in normal mode (so pressing y, for instance, only starts a yank). The bar doesn't disappear until I close or reload the tab.

## Context

Just trying to edit files.

## Technical Info

* URL: any overleaf.com/project/
* Browser Name and version: Brave V1.27.111 (have also previously observed this bug in chromium)
* Operating System and version (desktop or mobile): Arch Linux / desktop
* Signed in as:
* Project and/or file: any of the ones I've tried

## Migration

Migrated this issue from [the multirepo](https://github.com/overleaf/web/issues/743), but I tested specifically and the issue remains. Updated the browser version number.

**Comment by jorsn** [comment]
For me: I had then to click on the bar so that it is focused, and then I could type y/n/q/…

In the new editor, it seems to be fixed, i.e. the bar is focused automatically. Can you confirm this and if successful close the issue, @gustaphe ?

**Comment by gustaphe** [comment]
Yep, it works perfectly now!
