### ISSUE TITLE
Overleaf Community Edition | How to read the changed LaTex file from disk?

### ISSUE THREAD

**Issue by yoursbh** [overleaf/overleaf#949]
Dear all,

I've installed [Overleaf](https://github.com/overleaf/overleaf) on my personal server (Ubuntu 20.04.2 LTS). After the installation, I figured out that Overleaf save the LaTex files (.tex, .bib, ...) and the compiled file (.pdf) in `INSTALL_PATH/data/sharelatex/data/compiles/*project_folder*`. Each time, if I make some modifications from my browser and recompile the project, the above folder (i.e., `*project_folder*`) will be automatically updated.

However, if I change directly the .tex file in a texteditor (not in the browser), then I reopen the project in the browser, the LaTex file on the left panel is not updated. But if I check the .tex file in the above folder, it is truly changed and saved.

So how can I make this to be possible?

Here is an illustration of what I expect:
[![Expected result][1]][1]

  [1]: https://i.stack.imgur.com/ePAu9.png

Thanks in advance

**Comment by axkibe** [comment]
It should be obvious, but you really shouldn't change the data folder yourself. It might put your instance in an inconsistent state. Overleaf keeps the data internally in a database format and also has some operation transformation engine for multi-user editing. If you want to edit the file offline, you should to download and upload it again using the web interface (or use some tool that in effect does the same only automatically)

**Comment by das7pad** [comment]
Hello,

Thanks for raising this ticket. As @axkibe mentioned, the files in the compiles folder are not meant to be edited externally. There are a copy of the project source in Overleaf Community Edition's data stores (redis and mongo).

As part of our [Server Pro offering](https://www.overleaf.com/for/enterprises) for enterprises and large on-premises instances we are also including the [Git-Integration](https://www.overleaf.com/learn/how-to/Git_integration) feature. Users can then utilize `git` for syncing Overleaf projects to their local disk and edit the content there.

Greetings,
Jakob
