### ISSUE TITLE
Consider Monaco as Web Editor

### ISSUE THREAD

**Issue by kalaschnik** [overleaf/overleaf#953]
I have found nothing in the repo regarding the editor that is being used in overleaf (CE). Anyway, I was playing recently with the Monaco editor for a web project and it feels much better than the editor being used in overleaf. Yes, I am biased as I use VS Code as my daily driver, but I think that it should be considered at some point in time.

- https://github.com/microsoft/monaco-editor
- https://www.npmjs.com/package/monaco-editor

**Comment by Adam-Antios** [comment]
Is there any update regarding this? Are there any plans for the future? This would be a huge improvement. At the moment, I work locally and sync with Overleaf through git.

**Comment by das7pad** [comment]
Hello,

Thanks for the suggestion. We've build the new Overleaf Source and Visual editor using CodeMirror 6 and you can read more about it [on our blog](https://www.overleaf.com/blog/towards-the-future-a-new-source-editor). A large number of features were unlocked by this migration and there are no plans to start another editor migration :wink: 

Greetings,
Jakob
