### ISSUE TITLE
Increase compile timeout for self-hosted/on-premise solutions

### ISSUE THREAD

**Issue by JohannLange** [overleaf/overleaf#955]
While I understand the compile timeouts for the cloud version of Overleaf, I think for an on-premise solution, everyone should be able to increase the compile timeout at will.
I'd opt to be even able to set the limit to infinity, aka no limit.

**Comment by moschlar** [comment]
I'd still like that feature, too.

**Comment by das7pad** [comment]
Hi! You should be able to increase the timeout using the environment variable `COMPILE_TIMEOUT` (this in seconds; default is `180` aka 3min). It might not work in retrospect for existing users, for which you may need to update the entries in the db.

Tip: Be sure to re-create the docker-container after making the change to the docker-compose file.

**Comment by JohannLange** [comment]
@das7pad,
thank you! That solves my problem!
Thus, I‘ll close the issue.

Nevertheless, is there a list of some sort with all those environmental variables I can set?
I can’t seem to find anything :/

**Comment by vankxr** [comment]
Hello,
I can't seem to make `COMPILE_TIMEOUT` work. I have set it to 1200 (20 minutes), and confirmed it applies to the docker container with `docker inspect sharelatex`. I have also confirmed that the setting applied to my user in mongodb, as it states `"compileTimeout" : 1200` for my user.

However, I have a big project that just times out on the website. I can confirm that the compiler is still running on `htop`, but the website shows the usual timed out message and I have no clue how to fix it.

Can someone with internal knowledge please advise?

Thanks
