### ISSUE TITLE
Overleaf register new user email not sent...

### ISSUE THREAD

**Issue by davetengineer** [overleaf/overleaf#956]
## Steps to Reproduce

1.
2.
3.

## Technical Info

* URL:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Signed in as:
* Project and/or file:

**Comment by das7pad** [comment]
Hi there! Are you having troubles registering on www.overleaf.com or using a self-hosted instance? In case of the later, can you provide more information on your setup and the steps taken to create a new user?

**Comment by das7pad** [comment]
Hello,

We've fixed a bug in the `create-user` script that caused the script to exit too early, before sending the email. The fix has been released with Overleaf Community Editition and [Server Pro](https://www.overleaf.com/for/enterprises) version 5.1.1.

Greetings,
Jakob
