### ISSUE TITLE
Update Ace to version 1.4.13

### ISSUE THREAD

**Issue by psvenk** [overleaf/overleaf#970]
Is there any chance that the version of Ace used in Overleaf could be updated to [1.4.13](https://github.com/ajaxorg/ace/releases/tag/v1.4.13), which contains (among other features) [support for wrapping text in Vim mode](https://github.com/ajaxorg/ace/pull/4545)?

I apologize if I opened this issue on the wrong repository; while I understand that the ace-builds repository is used for updating Ace, issues seem to be disabled on that repository, and I am not yet knowledgeable enough about the process to open a pull request directly.

**Comment by das7pad** [comment]
Hello,

We've migrated away from Ace and onto Code Mirror 6 now.

Greetings,
Jakob
