### ISSUE TITLE
Overleaf is down

### ISSUE THREAD

**Issue by ritwik12** [overleaf/overleaf#977]
Overleaf seems down!

<img width="688" alt="Screen Shot 2021-11-16 at 9 55 26 AM" src="https://user-images.githubusercontent.com/20038775/142039500-b383a95f-e5c6-4560-8580-188b26cc2c4e.png">

**Comment by JohannesThoren** [comment]
I have the same problem

**Comment by ritwik12** [comment]
Yeah, seems like a DNS issue.

**Comment by ritwik12** [comment]
https://status.overleaf.com/

Please stop using whatever service you are using for status tracking, it ain't showing correct status. Overleaf is down but it shows it online

**Comment by matthewa26** [comment]
I have the same issue. I think their status tracking has to be manually updated (I believe there's a 10-15 minute delay for companies that do it manually).

**Comment by matthewa26** [comment]
Looks like it's back up!

**Comment by ritwik12** [comment]
yeah its back up

**Comment by ritwik12** [comment]
Will keep this issue open for RCA if they are going to give 😅

**Comment by jdleesmiller** [comment]
It looks like it was a google-wide issue, e.g. https://news.ycombinator.com/item?id=29243617 . https://status.overleaf.com/ is now updated (it is indeed mainly manual).

**Comment by ritwik12** [comment]
Thanks for the info @jdleesmiller :)
