### ISSUE TITLE
LaTeX Error: File `cite.sty' not found.

### ISSUE THREAD

**Issue by slacklife** [overleaf/overleaf#978]
Hello, I encountered the following problems when compiling in local version overleaf (with docker) on mac.
I configured it according to [this](https://github.com/overleaf/toolkit/blob/master/doc/quick-start-guide.md)
I'm sure there are no grammatical errors because I can compile it on the online version overleaf.

```
Compile Error. Sorry, your LaTeX code couldn’t compile for some reason. 
Please check the errors below for details, or view the raw log.
LaTeX Error: File `cite.sty' not found.

The compiler cannot find the file you want to include. 
Make sure that you have uploaded the file and specified the file location correctly.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.93 \RequirePackage
                    {xspace}^^M
*** (cannot \read from terminal in nonstop modes)
```

docker images version information
redis                   5.0 
sharelatex/sharelatex   3.0.1 
mongo                   4.0

If it is a docker image problem, how to upgrade it.

**Comment by YinAoXiong** [comment]
@slacklife 
follow https://github.com/overleaf/toolkit/blob/master/doc/ce-upgrading-texlive.md

upgrade textlive may fix this problem

**Comment by slacklife** [comment]
Many thanks to you.
It works!

**Comment by hrjakobsen** [comment]
This issue seems to have been fixed by upgrading TexLive , so I'll close this issue. Please reopen it if you still are having issues.
