### ISSUE TITLE
How should I reset password as admin?

### ISSUE THREAD

**Issue by tankgit** [overleaf/overleaf#980]
Due to some proxy policy restrictions, I cannot enable email service for sharelatex server, well how can I reset password from command line for a user as an admin?

Thx

**Comment by wongsingfo** [comment]
I had the same problem and found a workaround:

1. Open "Admin -> Manage Users"
2. Register again the user who forgets its password, and we will get a link `http://localhost/user/activate?token=<token>&user_id=<id>`. Copy the `token`.
3. Construct a new ur `http://localhost/user/password/set?passwordResetToken=<token>`, where `<token>` is the string in step 2. Send this new url to the user and they should be able to reset their password.

This method will not remove any exsiting projects owned by the user.

**Comment by tankgit** [comment]
> I had the same problem and found a workaround:
> 
> 1. Open "Admin -> Manage Users"
> 2. Register again the user who forgets his/her password, and we will get a link `http://localhost/user/activate?token=<token>&user_id=<id>`. Copy the `token`.
> 3. Construct a new URL `http://localhost/user/password/set?passwordResetToken=<token>`, where `<token>` is the string in step 2. Send this new URL to the user and he/she should be able to reset the password.
> 
> This method will not remove any exsiting projects owned by the user.

Great solution!
BTW, how did you find the request key `passwordResetToken` since nothing similar mentioned in official docs, and I wonder if there's more APIs like it?

**Comment by wongsingfo** [comment]
> > I had the same problem and found a workaround:
> > 
> > 1. Open "Admin -> Manage Users"
> > 2. Register again the user who forgets his/her password, and we will get a link `http://localhost/user/activate?token=<token>&user_id=<id>`. Copy the `token`.
> > 3. Construct a new URL `http://localhost/user/password/set?passwordResetToken=<token>`, where `<token>` is the string in step 2. Send this new URL to the user and he/she should be able to reset the password.
> > 
> > This method will not remove any exsiting projects owned by the user.
> 
> Great solution!
> 
> I achieve this by overriding the hashcode with the one of known password in mongoDB directly... which is super dumb.
> 
> BTW, how did you find the request key `passwordResetToken` since nothing similar mentioned in official docs, and I wonder if there's more APIs like it?

I found the password reset URL at issue #674 and gave it a try. Fortunately it works :) I am also wondering if there exist similar management APIs.

**Comment by heartofrain** [comment]
> I had the same problem and found a workaround:
> 
> 1. Open "Admin -> Manage Users"
> 2. Register again the user who forgets his/her password, and we will get a link `http://localhost/user/activate?token=<token>&user_id=<id>`. Copy the `token`.
> 3. Construct a new URL `http://localhost/user/password/set?passwordResetToken=<token>`, where `<token>` is the string in step 2. Send this new URL to the user and he/she should be able to reset the password.
> 
> This method will not remove any exsiting projects owned by the user.

Dear @wongsingfo , I have tried your instructions in the latest Overleaf. However, I came across an error:
```
{"statusCode":400,"error":"Bad Request","message":"child \"email\" fails because [\"email\" is required]","validation":{"source":"query","keys":["email"]}}
```
I assumed that the Overleaf API had been updated. So, I added a field named `email` to the URL, like this:
```
http://localhost/user/password/set?passwordResetToken=<token>&email=<email>
```
Then, I successfully changed my password!
Anyway, thank you for letting me know about this API.

**Comment by hkn-uestc** [comment]
> > I had the same problem and found a workaround:
> > 
> > 1. Open "Admin -> Manage Users"
> > 2. Register again the user who forgets his/her password, and we will get a link `http://localhost/user/activate?token=<token>&user_id=<id>`. Copy the `token`.
> > 3. Construct a new URL `http://localhost/user/password/set?passwordResetToken=<token>`, where `<token>` is the string in step 2. Send this new URL to the user and he/she should be able to reset the password.
> > 
> > This method will not remove any exsiting projects owned by the user.
> 
> Dear @wongsingfo , I have tried your instructions in the latest Overleaf. However, I came across an error:
> 
> ```
> {"statusCode":400,"error":"Bad Request","message":"child \"email\" fails because [\"email\" is required]","validation":{"source":"query","keys":["email"]}}
> ```
> 
> I assumed that the Overleaf API had been updated. So, I added a field named `email` to the URL, like this:
> 
> ```
> http://localhost/user/password/set?passwordResetToken=<token>&email=<email>
> ```
> 
> Then, I successfully changed my password! Anyway, thank you for letting me know about this API.

Great！Thanks

**Comment by qianchd** [comment]
> > I had the same problem and found a workaround:
> > 
> > 1. Open "Admin -> Manage Users"
> > 2. Register again the user who forgets his/her password, and we will get a link `http://localhost/user/activate?token=<token>&user_id=<id>`. Copy the `token`.
> > 3. Construct a new URL `http://localhost/user/password/set?passwordResetToken=<token>`, where `<token>` is the string in step 2. Send this new URL to the user and he/she should be able to reset the password.
> > 
> > This method will not remove any exsiting projects owned by the user.
> 
> Dear @wongsingfo , I have tried your instructions in the latest Overleaf. However, I came across an error:
> 
> ```
> {"statusCode":400,"error":"Bad Request","message":"child \"email\" fails because [\"email\" is required]","validation":{"source":"query","keys":["email"]}}
> ```
> 
> I assumed that the Overleaf API had been updated. So, I added a field named `email` to the URL, like this:
> 
> ```
> http://localhost/user/password/set?passwordResetToken=<token>&email=<email>
> ```
> 
> Then, I successfully changed my password! Anyway, thank you for letting me know about this API.

It solves my problem. Thanks.
