### ISSUE TITLE
Failed to get image: quay.io/sharelatex/texlive-full:2017.1

### ISSUE THREAD

**Issue by SaoXiaoPiZhuPi** [overleaf/overleaf#983]
When I run the acceptance test under sharelatex-3.0/clsi directory(by command "make test_acceptance"), it reports the under error.
~~~
"message":"(HTTP code 404) no such container - No such image: quay.io/sharelatex/texlive-full:2017.1 "
~~~
The result is similar when I set the TEXLIVE_IMAGE as 'gcr.io/overleaf-ops/texlive-full:2017.1'.
Should I choose another docker image? Or have I made some mistake before test?

**Comment by Benjamin-Loison** [comment]
May you precise how you setup your Overleaf instance and provide the associated configuration files (if any)?

**Comment by das7pad** [comment]
Hello,

I'm afraid these texlive-full images are proprietary and we cannot grant you access to them for running tests in Overleaf Community Edition. I'll have a look at exlcuding these tests from the open source sync. Sorry for this limitation.

Greetings,
Jakob

**Comment by wzqvip** [comment]
Still occurs.

docker:
`
services:
    sharelatex:
        restart: always
        # Server Pro users:
        # image: quay.io/sharelatex/sharelatex-pro
        image: sharelatex/sharelatex
        container_name: sharelatex
        depends_on:
            mongo:
                condition: service_healthy
            redis:
                condition: service_started`

`Using default settings from /overleaf/services/clsi/config/settings.defaults.js
Using settings from /etc/overleaf/settings.js
{"name":"clsi","hostname":"1d6beffdd9ad","pid":194,"level":30,"target":"2025-05-17T19:30:38.541Z","msg":"Lifespan limited","time":"2025-05-15T22:35:43.038Z","v":0}
{"name":"clsi","hostname":"1d6beffdd9ad","pid":194,"level":50,"err":{"message":"(HTTP code 404) no such container - No such image: quay.io/sharelatex/texlive-full:2017.1 ","name":"Error","stack":"Error: (HTTP code 404) no such container - No such image: quay.io/sharelatex/texlive-full:2017.1 \n    at /overleaf/services/clsi/node_modules/docker-modem/lib/modem.js:383:17\n    at getCause (/overleaf/services/clsi/node_modules/docker-modem/lib/modem.js:418:7)\n    at Modem.buildPayload (/overleaf/services/clsi/node_modules/docker-modem/lib/modem.js:379:5)\n    at IncomingMessage.<anonymous> (/overleaf/services/clsi/node_modules/docker-modem/lib/modem.js:347:16)\n    at IncomingMessage.emit (node:events:536:35)\n    at endReadableNT (node:internal/streams/readable:1698:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","info":{}},"projectId":"68266858f0fa09d9c667d27c","msg":"error running compile","time":"2025-05-15T22:36:48.021Z","v":0}`

**Comment by mlevans0** [comment]
Hey @wzqvip, the **texlive-full** images are proprietary and unavailable for use in the Community Edition. Sorry for this limitation. I've checked our internal backlog, and we still have an open issue to clean up the Sandboxed Compiles code to address this. 

Please see the updated [docker-compose.yml](https://github.com/overleaf/overleaf/blob/main/docker-compose.yml) configuration (specifically [this](https://github.com/overleaf/overleaf/blob/main/docker-compose.yml#L76) section) on disabling Sandboxed Compiles when deploying CE.
