### ISSUE TITLE
Unable to connect. Websocket connection failed in Overleaf Community Edition docker installation

### ISSUE THREAD

**Issue by asvattha** [overleaf/overleaf#984]
I followed the [quick-start-guide](https://github.com/overleaf/toolkit/blob/master/doc/quick-start-guide.md)  and [HTTPS-reverse-proxy-using-Nginx](https://github.com/overleaf/overleaf/wiki/HTTPS-reverse-proxy-using-Nginx) to setup overleaf community edition in synology nas. I was able to install it successfully. However, when I try to click on any of the project to open it, it throws an error "**Unable to connect, please view the connection problems guide to fix the issue**", then it waits for ~10s before the project loads correctly. On checking the browser console, I see 4 messages as follows:
WebSocket connection to 'wss://<host-name>/socket.io/1/websocket/Xu3LxZh_GmqwVMy' failed: 

My config/overleaf.rc config looks like the following:
#### Overleaf RC ####

PROJECT_NAME=overleaf

##### Sharelatex container
SHARELATEX_DATA_PATH=data/sharelatex
SERVER_PRO=false
SHARELATEX_LISTEN_IP=127.0.0.1
SHARELATEX_PORT=8070

###### Sibling Containers
SIBLING_CONTAINERS_ENABLED=false
DOCKER_SOCKET_PATH=/var/run/docker.sock

####### Mongo configuration
MONGO_ENABLED=true
MONGO_DATA_PATH=data/mongo

####### Redis configuration
REDIS_ENABLED=true
REDIS_DATA_PATH=data/redis

####### See documentation in doc/tls-proxy.md
NGINX_ENABLED=true
NGINX_CONFIG_PATH=config/nginx/nginx.conf
NGINX_HTTP_PORT=8888
###### Replace these IP addresses with the external IP address of your host
NGINX_HTTP_LISTEN_IP=192.168.0.16
NGINX_TLS_LISTEN_IP=192.168.0.16
######TLS_PRIVATE_KEY_PATH=config/nginx/certs/overleaf_key.pem
TLS_PRIVATE_KEY_PATH=config/nginx/certs/RSA-privkey.pem
#######TLS_CERTIFICATE_PATH=config/nginx/certs/overleaf_certificate.pem
TLS_CERTIFICATE_PATH=config/nginx/certs/RSA-cert.pem
TLS_PORT=8443

The nginx configuration looks like the following:

events {}

http {

    server {
        listen 80 default_server;
        server_name _;
        return 301 https://$host$request_uri;
    }

    server {

        listen 443 ssl;
        server_name _;

        ssl_certificate      /certs/nginx_certificate.pem;
        ssl_certificate_key  /certs/nginx_key.pem;

        ssl_protocols               TLSv1 TLSv1.1 TLSv1.2;
        ssl_prefer_server_ciphers   on;

        # used cloudflares ciphers https://github.com/cloudflare/sslconfig/blob/master/conf
        ssl_ciphers                 EECDH+CHACHA20:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5;

        # config to enable HSTS(HTTP Strict Transport Security) https://developer.mozilla.org/en-US/docs/Security/HTTP_Strict_Transport_Security
        # to avoid ssl stripping https://en.wikipedia.org/wiki/SSL_stripping#SSL_stripping  
        add_header Strict-Transport-Security "max-age=31536000; includeSubdomains;";

        server_tokens off;

        add_header X-Frame-Options SAMEORIGIN;
        add_header X-Content-Type-Options nosniff;

        client_max_body_size 50M;

        location / {
            proxy_pass http://sharelatex:80; # The port must match the value of SHARELATEX_PORT.
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_read_timeout 3m;
            proxy_send_timeout 3m;
        }

    }

}

Please note: if i change the port number in proxy_pass to match the SHARELATEX_PORT then I am getting 502 Bad gateway error. It only works when I set it to 80.  Even though the config file says that it should match with SHARELATEX_PORT.

I have also set up reverse proxy on my nas which directs the 443 https traffic to my sharelatex 192.168.0.16:8443 port. 

I have also set the two lines to true in the variables.env file. 

I am new to nginx and docker, and can't figure out the issue.

Thanks.

**Comment by axkibe** [comment]
snip
```SHARELATEX_PORT=8070```
snip
```
 proxy_pass http://sharelatex:80; # The port must match the value of SHARELATEX_PORT.
```
Do you see what is wrong here? It doesn't match

**Comment by asvattha** [comment]
@axkibe Thank you for your response. 
If sharelatex is the problem then why it would work at the first place? I mean i shouldn't be able to set up overleaf or create projects at the first place. 
Second, I do not have any firewall setup. I simply followed the overleaf quick start guide to it up. I configured the overleaf.rc and nginx.conf files,  along with two lines uncommented from variables.env file, and ran bin/up script as given in the tutorial. I don't know what is misconfigured. I have already shared my entire methodology for this setup. 
Third, I tried to change it to localhost:8070 and it gives 502 bad gateway error. It only works when i set up localhost:80, even though the SHARELATEX_PORT is set as 8070 in the overleaf.rc file.

**Comment by axkibe** [comment]
Okay, well to be honest I don't fully understand how your setup works.
 
Maybe a hit "then it waits for ~10s before the project loads correctly" is often a IPv6 vs IPv4 issue (the underlaying layers first try to connect via IPv6 when this fails, it tries with IPv4 after a timeout which then work).

Especially I noted:
```SHARELATEX_LISTEN_IP=127.0.0.1```
in your setup, which means it binds to the loopback interface only and on v4 only. I didn't find this line in the guidelines you mentioned. So unless your nginx runs on the same host, it shouldn't be able to connect.

I can only say, in my setup, I have an external nginx instance running on the same machine sharelatex runs with 
```
    [SSL config snipped]
    location / {
        proxy_pass http://localhost:5000;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_read_timeout 3m;
        proxy_send_timeout 3m;
    }
```
Where port 5000 does match the default port for Sharelatex.

I mean I realized now there is another nginx instance running within sharelatex container, which can be optimized to take the SSL configuration directly, but okay.

**Comment by asvattha** [comment]
@axkibe 
Let me simplify my setup so that you can help me better. 

I have a synology nas and currently i am connected to it within local network using 192.168.0.16:5001 (https)

After that, I followed the overleaf-quick-start-guide to fetch the git repo.
Ran the following commands: 
1. bin/init 
2. bin/init --tls
3. Uncommented two lines from variables.env file
4. Changed the SHARELATEX_PORT AND SHARELATEX_LISTEN_IP variable to 8080 and 127.0.1.1 respectively.
5. Changed the NGINX_ENABLED to true
6. Changed the NGINX_HTTP_PORT and NGINX_HTTP_LISTEN_IP to 80 and 192.16.0.16
7. Changed the NGINX_TLS_PORT and NGINX_TLS_LISTEN_IP to 8443 and 192.16.0.16
8. Changed the nginx/nginx.conf file, to set proxy_pass to http://localhost:8080

After that I ran the command bin/up which starts mongo, redis, sharelatex and nginx. 

However, in the browser when I am typing https://192.168.0.16:8443, it directs me to https://127.0.1.1 and says safari can't connect to the server. 

Can you help me with this simple setup and explain what I am doing wrong? 
Thank you again!

**Comment by asvattha** [comment]
I fixed it. It looks like I had two reverse proxies running, and one of them didn't had the websocket configured. Doing it fixed the problem, and now I can run overleaf on my synology nas without any issue.

**Comment by axkibe** [comment]
Congrats, sorry I wasn't able to help you.
