### ISSUE TITLE
Just to confirm, server CE/Pro is not affected by log4shell? 

### ISSUE THREAD

**Issue by axkibe** [overleaf/overleaf#985]
I'm asking because there is Redis in it and it was listed as affected, I looked in the respective docker container but it isn't there. So I guess not. Made an apt update/install anyway to get some security updates. BTW, I guess in the containers automatic debian security updates (package unattended-upgrades ) aren't active by default. Wouldn't this be a good idea?

[the default git bridge is written in Java so it could have been affected, but it isn't active anyway.. so]

**Comment by jdleesmiller** [comment]
We are continuing to monitor the situation, but we don't believe CE or Server Pro (or overleaf.com) are affected, no.

I have also read that redis is affected, but I have not been able to work out why or how. I did find that a Java redis client (which we don't use) used log4j in its test framework (https://github.com/redis/jedis/issues/2726), but that's the closest thing I've found so far. Thanks for looking into it!

**Comment by axkibe** [comment]
Thank you for your response. In the long run, you think it would be a good idea to enable unattended security updates from the debian security team in the docker containers by default? I mean I can do this myself without much issues, just thinking it might be a good practice.

**Comment by jdleesmiller** [comment]
> unattended security updates

This is an interesting one. On the one hand, it doesn't feel very "containery" --- generally speaking, the trend is toward immutable infrastructure that is built and tested, remains read-only for its entire working life, and is then thrown away and replaced when a newer version is available. On the other hand, we already have several aspects of the CE/SP container that are not very consistent with that, e.g. installing TeX Live in the container post-install, and generally running a lot of processes in that container. My longer term goal is to make the distribution more "containery", so my preference is not to enable the unattended upgrades by default (but users who want to enable them can do so).

**Comment by axkibe** [comment]
I see, yes this is understandable. I have a similar trade off, on the one hand I don't like the idea of unattended upgrades breaking stuff over night by itself (nothing is perfect) on the other hand of course security. There might be a middle ground of unattended security container replacement..  (which would break post install Tex Lives over night.)
