### ISSUE TITLE
[Wiki] Incorrected language option on wiki page

### ISSUE THREAD

**Issue by atxy-blip** [overleaf/overleaf#986]
The language option for Simplified Chinese should be `zh-CN` instead of `cn` on https://github.com/overleaf/overleaf/wiki/i18n-Languages, and I am pretty sure there are more languages available while not listed. Maybe it is time to update this wiki page?

Since the bug is nowhere related to the functioning of sharelatex, I decided not to use the issue template anyway.

**Comment by hrjakobsen** [comment]
Thanks for reporting this @atxy-blip, I've updated the wiki.
