### ISSUE TITLE
No E-Mail sent when creating user with "node create-user"

### ISSUE THREAD

**Issue by chschenk** [overleaf/overleaf#988]
## Steps to Reproduce

1. Run `./bin/shell sharelatex`
2. Change into the script directory `cd /var/www/sharelatex/web/modules/server-ce-scripts/scripts`
3. Create user with node command `node create-user --email=email@example.com`

## Expected Behaviour
A User should be created and a mail with an activation URL should be sent to email@example.com

## Observed Behaviour
There is no email sent. When using the web interface to create a user e-mails are working perfectly fine.

## Technical Info
N/A

**Comment by MartinJindra** [comment]
Set the environment variable `SHARELATEX_EMAIL_SMTP_LOGGER` to `true`. It will print the logs into the file. I have the same problem and saw that the authentication did not work. 

To read the output: use 

```
docker exec sharelatex cat /var/log/sharelatex/web.log
```

**Comment by senk** [comment]
Can confirm the issue. 
Looks like the script is not processing the mail, maybe the node runtime dies before mail is sent?

**Comment by senk** [comment]
Last line for this event in log is:
```
{"name":"default-sharelatex","hostname":"ccf2265a411e","pid":2621,"level":30,"email":"email@example.de","msg":"user already exists, resending welcome email","time":"2022-03-05T07:43:35.987Z","v":0}
[2022-03-05 07:43:35] INFO: Sending mail using SMTP/2.0.1[client:2.0.1]

Successfully created email@example.de as a user.

Please visit the following URL to set a password for email@example.de and log in:

  https://overleaf.example.de/user/activate?token=174112ca8b01855ff3fb7e7cf96934e878d3501faee509a404966e6ebf15f912&user_id=622311765b1c6d0a0c4bd9f1


Done.
```
