### ISSUE TITLE
Installed TeX Live version does not match UI list

### ISSUE THREAD

**Issue by homocomputeris** [overleaf/overleaf#989]
## Steps to Reproduce

1. Install Overleaf
2. Update Overleaf
3. Install TexLive full and update

## Expected Behaviour

TeX Live 2021 in the UI

## Observed Behaviour

```
tlmgr revision 60693 (2021-10-04 04:24:25 +0200)
tlmgr using installation: /usr/local/texlive/2021
TeX Live (https://tug.org/texlive) version 2021
```

No TeX live 2021 in the UI
![2022-01-26 01 46 06](https://user-images.githubusercontent.com/7422433/151072661-5d6572b1-1fd8-4671-818c-38c58c1f6477.jpg)

## Context

Use latest version

## Technical Info

* URL: N/A
* Browser Name and version: Firefox 96.0.2
* Operating System and version (desktop or mobile): desktop
* Signed in as: N/A
* Project and/or file: N/A

**Comment by das7pad** [comment]
> * Install Overleaf
> * Update Overleaf
> * Install TexLive full and update

Can you extend on your setup (toolkit/docker-compose/other), Server CE/Server PRO, commands used for updating Overleaf/Texlive?

**Comment by homocomputeris** [comment]
I used the toolkit for the CE and literally followed the guides:
- this https://github.com/overleaf/toolkit/blob/master/doc/quick-start-guide.md
- this https://github.com/overleaf/toolkit/blob/master/doc/upgrading.md
- and this https://github.com/overleaf/toolkit/blob/master/doc/ce-upgrading-texlive.md

**Comment by das7pad** [comment]
Thanks for providing the steps!
We've identified a bad default value as the cause for seeing the list with mismatching TeXLive versions. Server CE does not support multiple TeXLive versions, so this list should not be shown to you.
Could you comment out `TEX_LIVE_DOCKER_IMAGE` and `ALL_TEX_LIVE_DOCKER_IMAGES` in your `config/variables.env` file (similar to https://github.com/overleaf/toolkit/pull/89) and run `bin/up`?
