### ISSUE TITLE
fileupload broken? filestore moving files, corrupt project?

### ISSUE THREAD

**Issue by pablomendes** [overleaf/overleaf#99]
Hi all,
I have a local installation using filestore.  I tried moving a file (model.pdf) with drag-and-drop and since then I have been experiencing weird errors (potentially EBKAC). My project won't compile. The log shows:

```
 "! Package pdftex.def Error: File `images/model.pdf' not found."
```

So I deleted the model.pdf via the Web UI and recompiled. The output.pdf is generated successfully (an empty frame is shown where the image would be), and the log shows an error: 

```
Error in /var/www/sharelatex/compiles/533b2998feb7db9a33000006/model.tex (line 26): Package pdftex.def Error: File `model.pdf' not found.
```

Now I reupload model.pdf via the Web UI, and the project won't recompile.

> Compile Error: Sorry, something went wrong and the project could not be compiled. This may be due to our compiler being overloaded or an incompatibility with the project. Please try again in a few moments and if the problem continues let us know via the feedback tab at the top.

If I click "Show Raw Logs", it seems to show the logs for the previous (successful) run:

```
...
! Package pdftex.def Error: File `model.pdf' not found.
...
Output written on /var/www/sharelatex/compiles/533b2998feb7db9a33000006/output.
pdf (6 pages, 184975 bytes).
```

And now, no output.pdf is found there.

Also, if I copy the file via SSH to `/var/www/sharelatex/compiles/533b2998feb7db9a33000006/images/model.pdf` it does not help, as the system seems to wipe it out at each recompile.

```
$ latexmk --version
Latexmk, John Collins, 15 Jan 2014. Version 4.40
```

Any pointers on where to keep looking would be much appreciated!

EDIT: figured out that the logs shown were from earlier run. I suspect there is something wrong with my file upload.

**Comment by Chupaflo** [comment]
Hello, 

I installed sharelatex on my server and it is running fine exept that I have the same issue as you. I made the directoty writable for the sharelatex user but I am still getting the same error when I try to print an image using the figure environment 

  >  \begin{figure}
        \centering
        \includegraphics[width=0.5\columnwidth]{avatar.jpeg}
        \caption{Caption}
        \label{fig:my_label}
    \end{figure}

and i get the following error 

> LaTeX Warning: File `avatar.jpeg' not found on input line 44.
> ! Package pdftex.def Error: File `avatar.jpeg' not found.
> See the pdftex.def package documentation for explanation.
> Type  H <return>  for immediate help.
>  ...                                                                         
> l.44 ...aphics[width=0.5\columnwidth]{avatar.jpeg}                                      
> Using draft setting for this image.
> Try typing  <return>  to proceed.
> If that doesn't work, type  X <return>  to quit.

But when I try to download the file from sharelatex interface it does not give me a "File not found" error.

Does anybody has any suggestion ?

Thank you in advance ! =)

**Comment by Chupaflo** [comment]
It's ok ! I used the thread https://github.com/sharelatex/clsi-sharelatex/issues/15 and created the folder missing, for me it was : /var/www/sharelatex/clsi/cache/
