### ISSUE TITLE
Changing docker-compose.yml after tlmgr install scheme-full

### ISSUE THREAD

**Issue by michaelvanhorn** [overleaf/overleaf#998]
I've followed the instructions here 

`https://github.com/overleaf/overleaf/wiki/Quick-Start-Guide`

for installing a full version of TeXLive into overleaf. After having done 

`docker commit sharelatex sharelatex/sharelatex:with-texlive-full`

you supposed to "edit your docker-compose.yml to use that image". Where do I do that? I found several docker-compose-*.yml files in /usr/local/overleaf/lib, and docker-compose.base.yml looks like the most likely place. However, the "image:" line there references a variable ( ${IMAGE} ), so maybe that isn't where you're supposed to change it. 

How do you tell docker to use a different share-latex container when starting overleaf?

**Comment by rezass** [comment]
The docker-compose.yml in the root directory of overleaf should be changed.

**Comment by QwertyJack** [comment]
If you go to the very beginning of the doc, [overleaf-toolkit](https://github.com/overleaf/overleaf/wiki/Quick-Start-Guide#-announcing-the-overleaf-toolkit-) is recommended. It shows [here](https://github.com/overleaf/toolkit/blob/master/doc/ce-upgrading-texlive.md#saving-your-changes) how to override the default docker-compose file.
