### ISSUE TITLE
Query Regarding Analytics

### ISSUE THREAD

**Issue by VivekB7** [overleaf/overleaf#999]
I found Google Tracking  scripts in multiple pug files. I have added one example below. 
[https://github.com/overleaf/overleaf/blob/main/services/web/app/views/layout.pug#L34](https://github.com/overleaf/overleaf/blob/main/services/web/app/views/layout.pug#L34)
I would like to know, if any analytics data is sent outside the company premise by default?  Is there a easy way to disable all analytics easily?

**Comment by jdleesmiller** [comment]
Thanks for getting in touch. The code is included conditionally --- if you don't set a Google Analytics token in your settings (and I don't think there is actually a way to set one via env var, at the moment...), the script will not be included in the page.
